// Code generated by cljgo build. DO NOT EDIT.

package cljzip

import (
	rt "github.com/muthuishere/cljgo/pkg/emit/rt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_changed_QMARK_                = lang.InternKeywordString("changed?")
	kw_column                        = lang.InternKeywordString("column")
	kw_content                       = lang.InternKeywordString("content")
	kw_doc                           = lang.InternKeywordString("doc")
	kw_end                           = lang.InternKeywordString("end")
	kw_end_column                    = lang.InternKeywordString("end-column")
	kw_end_line                      = lang.InternKeywordString("end-line")
	kw_exclude                       = lang.InternKeywordString("exclude")
	kw_file                          = lang.InternKeywordString("file")
	kw_l                             = lang.InternKeywordString("l")
	kw_line                          = lang.InternKeywordString("line")
	kw_pnodes                        = lang.InternKeywordString("pnodes")
	kw_ppath                         = lang.InternKeywordString("ppath")
	kw_r                             = lang.InternKeywordString("r")
	kw_zip_SLASH_branch_QMARK_       = lang.InternKeywordString("zip/branch?")
	kw_zip_SLASH_children            = lang.InternKeywordString("zip/children")
	kw_zip_SLASH_make_node           = lang.InternKeywordString("zip/make-node")
	sym_clojure_DOT_core             = lang.NewSymbol("clojure.core")
	sym_clojure_DOT_zip              = lang.NewSymbol("clojure.zip")
	sym_next                         = lang.NewSymbol("next")
	sym_remove                       = lang.NewSymbol("remove")
	sym_replace                      = lang.NewSymbol("replace")
	v_clojure_DOT_core_X_EQ_         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("="))
	v_clojure_DOT_core_apply         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("apply"))
	v_clojure_DOT_core_assoc         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("assoc"))
	v_clojure_DOT_core_butlast       = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("butlast"))
	v_clojure_DOT_core_comp          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("comp"))
	v_clojure_DOT_core_complement    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("complement"))
	v_clojure_DOT_core_concat        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("concat"))
	v_clojure_DOT_core_conj          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("conj"))
	v_clojure_DOT_core_cons          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("cons"))
	v_clojure_DOT_core_count         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("count"))
	v_clojure_DOT_core_ex_info       = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("ex-info"))
	v_clojure_DOT_core_first         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("first"))
	v_clojure_DOT_core_get           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("get"))
	v_clojure_DOT_core_identity      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("identity"))
	v_clojure_DOT_core_in_ns         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_last          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("last"))
	v_clojure_DOT_core_meta          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("meta"))
	v_clojure_DOT_core_next          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("next"))
	v_clojure_DOT_core_nil_QMARK_    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("nil?"))
	v_clojure_DOT_core_nth           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("nth"))
	v_clojure_DOT_core_peek          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("peek"))
	v_clojure_DOT_core_pop           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("pop"))
	v_clojure_DOT_core_pos_QMARK_    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("pos?"))
	v_clojure_DOT_core_refer         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
	v_clojure_DOT_core_rest          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("rest"))
	v_clojure_DOT_core_seq           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("seq"))
	v_clojure_DOT_core_seq_QMARK_    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("seq?"))
	v_clojure_DOT_core_string_QMARK_ = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("string?"))
	v_clojure_DOT_core_vec           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("vec"))
	v_clojure_DOT_core_vector        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("vector"))
	v_clojure_DOT_core_vector_QMARK_ = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("vector?"))
	v_clojure_DOT_core_with_meta     = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("with-meta"))
	v_clojure_DOT_zip_append_child   = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("append-child"))
	v_clojure_DOT_zip_branch_QMARK_  = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("branch?"))
	v_clojure_DOT_zip_children       = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("children"))
	v_clojure_DOT_zip_down           = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("down"))
	v_clojure_DOT_zip_edit           = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("edit"))
	v_clojure_DOT_zip_end_QMARK_     = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("end?"))
	v_clojure_DOT_zip_insert_child   = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("insert-child"))
	v_clojure_DOT_zip_insert_left    = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("insert-left"))
	v_clojure_DOT_zip_insert_right   = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("insert-right"))
	v_clojure_DOT_zip_left           = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("left"))
	v_clojure_DOT_zip_leftmost       = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("leftmost"))
	v_clojure_DOT_zip_lefts          = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("lefts"))
	v_clojure_DOT_zip_make_node      = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("make-node"))
	v_clojure_DOT_zip_next           = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("next"))
	v_clojure_DOT_zip_node           = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("node"))
	v_clojure_DOT_zip_path           = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("path"))
	v_clojure_DOT_zip_prev           = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("prev"))
	v_clojure_DOT_zip_remove         = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("remove"))
	v_clojure_DOT_zip_replace        = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("replace"))
	v_clojure_DOT_zip_right          = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("right"))
	v_clojure_DOT_zip_rightmost      = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("rightmost"))
	v_clojure_DOT_zip_rights         = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("rights"))
	v_clojure_DOT_zip_root           = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("root"))
	v_clojure_DOT_zip_seq_zip        = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("seq-zip"))
	v_clojure_DOT_zip_up             = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("up"))
	v_clojure_DOT_zip_vector_zip     = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("vector-zip"))
	v_clojure_DOT_zip_xml_zip        = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("xml-zip"))
	v_clojure_DOT_zip_zipper         = lang.InternVarName(lang.NewSymbol("clojure.zip"), lang.NewSymbol("zipper"))
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("clojure.zip")), lang.VarFile, "zip.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote clojure.zip))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_clojure_DOT_zip)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core) :exclude (quote [replace remove next]))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply3(tmp3, sym_clojure_DOT_core, kw_exclude, lang.NewVector(sym_replace, sym_remove, sym_next))
	_ = tmp4
	// (def zipper "Creates a new zipper structure.\n\n  branch? is a fn that, given a node, retu…
	v_clojure_DOT_zip_zipper.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(28), kw_column, int64(7), kw_end_line, int64(28), kw_end_column, int64(13), kw_doc, "Creates a new zipper structure.\n\n  branch? is a fn that, given a node, returns true if can have\n  children, even if it currently doesn't.\n\n  children is a fn that, given a branch node, returns a seq of its\n  children.\n\n  make-node is a fn that, given an existing node and a seq of\n  children, returns a new branch node with the supplied children.\n  root is the root node."))
	tmp5 := lang.FnFunc4(func(branch_QMARK_6, children7, make_node8, root9 any) any {
		tmp10 := v_clojure_DOT_core_with_meta.Get()
		tmp11 := lang.NewVector(root9, nil)
		tmp12 := lang.NewMap(kw_zip_SLASH_branch_QMARK_, branch_QMARK_6, kw_zip_SLASH_children, children7, kw_zip_SLASH_make_node, make_node8)
		tmp13 := lang.Apply2(tmp10, tmp11, tmp12)
		return tmp13
	})
	tmp14 := &lang.NamedFn4{Name: "clojure.zip/zipper", Expects: "4: [branch? children make-node root]", F: tmp5}
	v_clojure_DOT_zip_zipper.BindRoot(tmp14)
	_ = v_clojure_DOT_zip_zipper
	// (def seq-zip "Returns a zipper for nested sequences, given a root sequence" (clojure.core/…
	v_clojure_DOT_zip_seq_zip.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(45), kw_column, int64(7), kw_end_line, int64(45), kw_end_column, int64(14), kw_doc, "Returns a zipper for nested sequences, given a root sequence"))
	tmp15 := lang.FnFunc1(func(root16 any) any {
		tmp17 := v_clojure_DOT_zip_zipper.Get()
		tmp18 := v_clojure_DOT_core_seq_QMARK_.Get()
		tmp19 := v_clojure_DOT_core_identity.Get()
		tmp20 := lang.FnFunc2(func(node21, children22 any) any {
			tmp23 := v_clojure_DOT_core_with_meta.Get()
			tmp24 := v_clojure_DOT_core_meta.Get()
			tmp25 := lang.Apply1(tmp24, node21)
			tmp26 := lang.Apply2(tmp23, children22, tmp25)
			return tmp26
		})
		tmp27 := &lang.NamedFn2{Name: "fn", Expects: "2: [node children]", F: tmp20}
		tmp28 := lang.Apply4(tmp17, tmp18, tmp19, tmp27, root16)
		return tmp28
	})
	tmp29 := &lang.NamedFn1{Name: "clojure.zip/seq-zip", Expects: "1: [root]", F: tmp15}
	v_clojure_DOT_zip_seq_zip.BindRoot(tmp29)
	_ = v_clojure_DOT_zip_seq_zip
	// (def vector-zip "Returns a zipper for nested vectors, given a root vector" (clojure.core/f…
	v_clojure_DOT_zip_vector_zip.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(54), kw_column, int64(7), kw_end_line, int64(54), kw_end_column, int64(17), kw_doc, "Returns a zipper for nested vectors, given a root vector"))
	tmp30 := lang.FnFunc1(func(root31 any) any {
		tmp32 := v_clojure_DOT_zip_zipper.Get()
		tmp33 := v_clojure_DOT_core_vector_QMARK_.Get()
		tmp34 := v_clojure_DOT_core_seq.Get()
		tmp35 := lang.FnFunc2(func(node36, children37 any) any {
			tmp38 := v_clojure_DOT_core_with_meta.Get()
			tmp39 := v_clojure_DOT_core_vec.Get()
			tmp40 := lang.Apply1(tmp39, children37)
			tmp41 := v_clojure_DOT_core_meta.Get()
			tmp42 := lang.Apply1(tmp41, node36)
			tmp43 := lang.Apply2(tmp38, tmp40, tmp42)
			return tmp43
		})
		tmp44 := &lang.NamedFn2{Name: "fn", Expects: "2: [node children]", F: tmp35}
		tmp45 := lang.Apply4(tmp32, tmp33, tmp34, tmp44, root31)
		return tmp45
	})
	tmp46 := &lang.NamedFn1{Name: "clojure.zip/vector-zip", Expects: "1: [root]", F: tmp30}
	v_clojure_DOT_zip_vector_zip.BindRoot(tmp46)
	_ = v_clojure_DOT_zip_vector_zip
	// (def xml-zip "Returns a zipper for xml elements (as from xml/parse),\n  given a root eleme…
	v_clojure_DOT_zip_xml_zip.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(64), kw_column, int64(7), kw_end_line, int64(64), kw_end_column, int64(14), kw_doc, "Returns a zipper for xml elements (as from xml/parse),\n  given a root element"))
	tmp47 := lang.FnFunc1(func(root48 any) any {
		tmp49 := v_clojure_DOT_zip_zipper.Get()
		tmp50 := v_clojure_DOT_core_complement.Get()
		tmp51 := v_clojure_DOT_core_string_QMARK_.Get()
		tmp52 := lang.Apply1(tmp50, tmp51)
		tmp53 := v_clojure_DOT_core_comp.Get()
		tmp54 := v_clojure_DOT_core_seq.Get()
		tmp55 := lang.Apply2(tmp53, tmp54, kw_content)
		tmp56 := lang.FnFunc2(func(node57, children58 any) any {
			tmp59 := v_clojure_DOT_core_assoc.Get()
			var tmp60 any
			_ = tmp60
			{
				var and__1__auto__61 any = children58
				_ = and__1__auto__61
				var tmp62 any
				_ = tmp62
				if lang.IsTruthy(and__1__auto__61) {
					tmp63 := v_clojure_DOT_core_apply.Get()
					tmp64 := v_clojure_DOT_core_vector.Get()
					tmp65 := lang.Apply2(tmp63, tmp64, children58)
					tmp62 = tmp65
				} else {
					tmp62 = and__1__auto__61
				}
				tmp60 = tmp62
			}
			tmp66 := lang.Apply3(tmp59, node57, kw_content, tmp60)
			return tmp66
		})
		tmp67 := &lang.NamedFn2{Name: "fn", Expects: "2: [node children]", F: tmp56}
		tmp68 := lang.Apply4(tmp49, tmp52, tmp55, tmp67, root48)
		return tmp68
	})
	tmp69 := &lang.NamedFn1{Name: "clojure.zip/xml-zip", Expects: "1: [root]", F: tmp47}
	v_clojure_DOT_zip_xml_zip.BindRoot(tmp69)
	_ = v_clojure_DOT_zip_xml_zip
	// (def node "Returns the node at loc" (clojure.core/fn [loc] (loc 0)))
	v_clojure_DOT_zip_node.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(75), kw_column, int64(7), kw_end_line, int64(75), kw_end_column, int64(11), kw_doc, "Returns the node at loc"))
	tmp70 := lang.FnFunc1(func(loc71 any) any {
		tmp72 := lang.Apply1(loc71, int64(0))
		return tmp72
	})
	tmp73 := &lang.NamedFn1{Name: "clojure.zip/node", Expects: "1: [loc]", F: tmp70}
	v_clojure_DOT_zip_node.BindRoot(tmp73)
	_ = v_clojure_DOT_zip_node
	// (def branch? "Returns true if the node at loc is a branch" (clojure.core/fn [loc] ((:zip/b…
	v_clojure_DOT_zip_branch_QMARK_.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(81), kw_column, int64(7), kw_end_line, int64(81), kw_end_column, int64(14), kw_doc, "Returns true if the node at loc is a branch"))
	tmp74 := lang.FnFunc1(func(loc75 any) any {
		tmp76 := v_clojure_DOT_core_meta.Get()
		tmp77 := lang.Apply1(tmp76, loc75)
		tmp78 := lang.Apply1(kw_zip_SLASH_branch_QMARK_, tmp77)
		tmp79 := v_clojure_DOT_zip_node.Get()
		tmp80 := lang.Apply1(tmp79, loc75)
		tmp81 := lang.Apply1(tmp78, tmp80)
		return tmp81
	})
	tmp82 := &lang.NamedFn1{Name: "clojure.zip/branch?", Expects: "1: [loc]", F: tmp74}
	v_clojure_DOT_zip_branch_QMARK_.BindRoot(tmp82)
	_ = v_clojure_DOT_zip_branch_QMARK_
	// (def children "Returns a seq of the children of node at loc, which must be a branch" (cloj…
	v_clojure_DOT_zip_children.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(88), kw_column, int64(7), kw_end_line, int64(88), kw_end_column, int64(15), kw_doc, "Returns a seq of the children of node at loc, which must be a branch"))
	tmp83 := lang.FnFunc1(func(loc84 any) any {
		tmp85 := v_clojure_DOT_zip_branch_QMARK_.Get()
		tmp86 := lang.Apply1(tmp85, loc84)
		var tmp87 any
		_ = tmp87
		if lang.IsTruthy(tmp86) {
			tmp88 := v_clojure_DOT_core_meta.Get()
			tmp89 := lang.Apply1(tmp88, loc84)
			tmp90 := lang.Apply1(kw_zip_SLASH_children, tmp89)
			tmp91 := v_clojure_DOT_zip_node.Get()
			tmp92 := lang.Apply1(tmp91, loc84)
			tmp93 := lang.Apply1(tmp90, tmp92)
			tmp87 = tmp93
		} else {
			tmp94 := v_clojure_DOT_core_ex_info.Get()
			tmp95 := lang.NewMap()
			tmp96 := lang.Apply2(tmp94, "called children on a leaf node", tmp95)
			panic(rt.Throw(tmp96))
		}
		return tmp87
	})
	tmp97 := &lang.NamedFn1{Name: "clojure.zip/children", Expects: "1: [loc]", F: tmp83}
	v_clojure_DOT_zip_children.BindRoot(tmp97)
	_ = v_clojure_DOT_zip_children
	// (def make-node "Returns a new branch node, given an existing node and new\n  children. The…
	v_clojure_DOT_zip_make_node.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(96), kw_column, int64(7), kw_end_line, int64(96), kw_end_column, int64(16), kw_doc, "Returns a new branch node, given an existing node and new\n  children. The loc is only used to supply the constructor."))
	tmp98 := lang.FnFunc3(func(loc99, node100, children101 any) any {
		tmp102 := v_clojure_DOT_core_meta.Get()
		tmp103 := lang.Apply1(tmp102, loc99)
		tmp104 := lang.Apply1(kw_zip_SLASH_make_node, tmp103)
		tmp105 := lang.Apply2(tmp104, node100, children101)
		return tmp105
	})
	tmp106 := &lang.NamedFn3{Name: "clojure.zip/make-node", Expects: "3: [loc node children]", F: tmp98}
	v_clojure_DOT_zip_make_node.BindRoot(tmp106)
	_ = v_clojure_DOT_zip_make_node
	// (def path "Returns a seq of nodes leading to this loc" (clojure.core/fn [loc] (:pnodes (lo…
	v_clojure_DOT_zip_path.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(103), kw_column, int64(7), kw_end_line, int64(103), kw_end_column, int64(11), kw_doc, "Returns a seq of nodes leading to this loc"))
	tmp107 := lang.FnFunc1(func(loc108 any) any {
		tmp109 := lang.Apply1(loc108, int64(1))
		tmp110 := lang.Apply1(kw_pnodes, tmp109)
		return tmp110
	})
	tmp111 := &lang.NamedFn1{Name: "clojure.zip/path", Expects: "1: [loc]", F: tmp107}
	v_clojure_DOT_zip_path.BindRoot(tmp111)
	_ = v_clojure_DOT_zip_path
	// (def lefts "Returns a seq of the left siblings of this loc" (clojure.core/fn [loc] (seq (:…
	v_clojure_DOT_zip_lefts.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(109), kw_column, int64(7), kw_end_line, int64(109), kw_end_column, int64(12), kw_doc, "Returns a seq of the left siblings of this loc"))
	tmp112 := lang.FnFunc1(func(loc113 any) any {
		tmp114 := v_clojure_DOT_core_seq.Get()
		tmp115 := lang.Apply1(loc113, int64(1))
		tmp116 := lang.Apply1(kw_l, tmp115)
		tmp117 := lang.Apply1(tmp114, tmp116)
		return tmp117
	})
	tmp118 := &lang.NamedFn1{Name: "clojure.zip/lefts", Expects: "1: [loc]", F: tmp112}
	v_clojure_DOT_zip_lefts.BindRoot(tmp118)
	_ = v_clojure_DOT_zip_lefts
	// (def rights "Returns a seq of the right siblings of this loc" (clojure.core/fn [loc] (:r (…
	v_clojure_DOT_zip_rights.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(115), kw_column, int64(7), kw_end_line, int64(115), kw_end_column, int64(13), kw_doc, "Returns a seq of the right siblings of this loc"))
	tmp119 := lang.FnFunc1(func(loc120 any) any {
		tmp121 := lang.Apply1(loc120, int64(1))
		tmp122 := lang.Apply1(kw_r, tmp121)
		return tmp122
	})
	tmp123 := &lang.NamedFn1{Name: "clojure.zip/rights", Expects: "1: [loc]", F: tmp119}
	v_clojure_DOT_zip_rights.BindRoot(tmp123)
	_ = v_clojure_DOT_zip_rights
	// (def down "Returns the loc of the leftmost child of the node at this loc, or\n  nil if no …
	v_clojure_DOT_zip_down.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(122), kw_column, int64(7), kw_end_line, int64(122), kw_end_column, int64(11), kw_doc, "Returns the loc of the leftmost child of the node at this loc, or\n  nil if no children"))
	tmp124 := lang.FnFunc1(func(loc125 any) any {
		tmp126 := v_clojure_DOT_zip_branch_QMARK_.Get()
		tmp127 := lang.Apply1(tmp126, loc125)
		var tmp128 any
		_ = tmp128
		if lang.IsTruthy(tmp127) {
			var tmp129 any
			_ = tmp129
			{
				var vec__38130 any = loc125
				_ = vec__38130
				tmp131 := v_clojure_DOT_core_nth.Get()
				tmp132 := lang.Apply3(tmp131, vec__38130, int64(0), nil)
				var node133 any = tmp132
				_ = node133
				tmp134 := v_clojure_DOT_core_nth.Get()
				tmp135 := lang.Apply3(tmp134, vec__38130, int64(1), nil)
				var path136 any = tmp135
				_ = path136
				tmp137 := v_clojure_DOT_zip_children.Get()
				tmp138 := lang.Apply1(tmp137, loc125)
				var vec__41139 any = tmp138
				_ = vec__41139
				tmp140 := v_clojure_DOT_core_seq.Get()
				tmp141 := lang.Apply1(tmp140, vec__41139)
				var seq__42142 any = tmp141
				_ = seq__42142
				tmp143 := v_clojure_DOT_core_first.Get()
				tmp144 := lang.Apply1(tmp143, seq__42142)
				var first__43145 any = tmp144
				_ = first__43145
				tmp146 := v_clojure_DOT_core_next.Get()
				tmp147 := lang.Apply1(tmp146, seq__42142)
				var seq__42148 any = tmp147
				_ = seq__42148
				var c149 any = first__43145
				_ = c149
				var cnext150 any = seq__42148
				_ = cnext150
				var cs151 any = vec__41139
				_ = cs151
				var tmp152 any
				_ = tmp152
				if lang.IsTruthy(cs151) {
					tmp153 := v_clojure_DOT_core_with_meta.Get()
					tmp154 := lang.NewVector()
					var tmp155 any
					_ = tmp155
					if lang.IsTruthy(path136) {
						tmp156 := v_clojure_DOT_core_conj.Get()
						tmp157 := lang.Apply1(kw_pnodes, path136)
						tmp158 := lang.Apply2(tmp156, tmp157, node133)
						tmp155 = tmp158
					} else {
						tmp159 := lang.NewVector(node133)
						tmp155 = tmp159
					}
					tmp160 := lang.NewMap(kw_l, tmp154, kw_pnodes, tmp155, kw_ppath, path136, kw_r, cnext150)
					tmp161 := lang.NewVector(c149, tmp160)
					tmp162 := v_clojure_DOT_core_meta.Get()
					tmp163 := lang.Apply1(tmp162, loc125)
					tmp164 := lang.Apply2(tmp153, tmp161, tmp163)
					tmp152 = tmp164
				} else {
					tmp152 = nil
				}
				tmp129 = tmp152
			}
			tmp128 = tmp129
		} else {
			tmp128 = nil
		}
		return tmp128
	})
	tmp165 := &lang.NamedFn1{Name: "clojure.zip/down", Expects: "1: [loc]", F: tmp124}
	v_clojure_DOT_zip_down.BindRoot(tmp165)
	_ = v_clojure_DOT_zip_down
	// (def up "Returns the loc of the parent of the node at this loc, or nil if at\n  the top" (…
	v_clojure_DOT_zip_up.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(137), kw_column, int64(7), kw_end_line, int64(137), kw_end_column, int64(9), kw_doc, "Returns the loc of the parent of the node at this loc, or nil if at\n  the top"))
	tmp166 := lang.FnFunc1(func(loc167 any) any {
		var tmp168 any
		_ = tmp168
		{
			var vec__44169 any = loc167
			_ = vec__44169
			tmp170 := v_clojure_DOT_core_nth.Get()
			tmp171 := lang.Apply3(tmp170, vec__44169, int64(0), nil)
			var node172 any = tmp171
			_ = node172
			tmp173 := v_clojure_DOT_core_nth.Get()
			tmp174 := lang.Apply3(tmp173, vec__44169, int64(1), nil)
			var map__47175 any = tmp174
			_ = map__47175
			var path176 any = map__47175
			_ = path176
			tmp177 := v_clojure_DOT_core_get.Get()
			tmp178 := lang.Apply2(tmp177, map__47175, kw_l)
			var l179 any = tmp178
			_ = l179
			tmp180 := v_clojure_DOT_core_get.Get()
			tmp181 := lang.Apply2(tmp180, map__47175, kw_ppath)
			var ppath182 any = tmp181
			_ = ppath182
			tmp183 := v_clojure_DOT_core_get.Get()
			tmp184 := lang.Apply2(tmp183, map__47175, kw_pnodes)
			var pnodes185 any = tmp184
			_ = pnodes185
			tmp186 := v_clojure_DOT_core_get.Get()
			tmp187 := lang.Apply2(tmp186, map__47175, kw_r)
			var r188 any = tmp187
			_ = r188
			tmp189 := v_clojure_DOT_core_get.Get()
			tmp190 := lang.Apply2(tmp189, map__47175, kw_changed_QMARK_)
			var changed_QMARK_191 any = tmp190
			_ = changed_QMARK_191
			var tmp192 any
			_ = tmp192
			if lang.IsTruthy(pnodes185) {
				var tmp193 any
				_ = tmp193
				{
					tmp194 := v_clojure_DOT_core_peek.Get()
					tmp195 := lang.Apply1(tmp194, pnodes185)
					var pnode196 any = tmp195
					_ = pnode196
					tmp197 := v_clojure_DOT_core_with_meta.Get()
					var tmp198 any
					_ = tmp198
					if lang.IsTruthy(changed_QMARK_191) {
						tmp199 := v_clojure_DOT_zip_make_node.Get()
						tmp200 := v_clojure_DOT_core_concat.Get()
						tmp201 := v_clojure_DOT_core_cons.Get()
						tmp202 := lang.Apply2(tmp201, node172, r188)
						tmp203 := lang.Apply2(tmp200, l179, tmp202)
						tmp204 := lang.Apply3(tmp199, loc167, pnode196, tmp203)
						var tmp205 any
						_ = tmp205
						{
							var and__1__auto__206 any = ppath182
							_ = and__1__auto__206
							var tmp207 any
							_ = tmp207
							if lang.IsTruthy(and__1__auto__206) {
								tmp208 := v_clojure_DOT_core_assoc.Get()
								tmp209 := lang.Apply3(tmp208, ppath182, kw_changed_QMARK_, true)
								tmp207 = tmp209
							} else {
								tmp207 = and__1__auto__206
							}
							tmp205 = tmp207
						}
						tmp210 := lang.NewVector(tmp204, tmp205)
						tmp198 = tmp210
					} else {
						tmp211 := lang.NewVector(pnode196, ppath182)
						tmp198 = tmp211
					}
					tmp212 := v_clojure_DOT_core_meta.Get()
					tmp213 := lang.Apply1(tmp212, loc167)
					tmp214 := lang.Apply2(tmp197, tmp198, tmp213)
					tmp193 = tmp214
				}
				tmp192 = tmp193
			} else {
				tmp192 = nil
			}
			tmp168 = tmp192
		}
		return tmp168
	})
	tmp215 := &lang.NamedFn1{Name: "clojure.zip/up", Expects: "1: [loc]", F: tmp166}
	v_clojure_DOT_zip_up.BindRoot(tmp215)
	_ = v_clojure_DOT_zip_up
	// (def root "zips all the way up and returns the root node, reflecting any\n changes." (cloj…
	v_clojure_DOT_zip_root.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(152), kw_column, int64(7), kw_end_line, int64(152), kw_end_column, int64(11), kw_doc, "zips all the way up and returns the root node, reflecting any\n changes."))
	tmp216 := lang.FnFunc1(func(loc217 any) any {
	fnloop218:
		for {
			tmp219 := lang.Apply1(loc217, int64(1))
			tmp220 := rt.EQBool(v_clojure_DOT_core_X_EQ_, kw_end, tmp219)
			var tmp221 any
			_ = tmp221
			if tmp220 {
				tmp222 := v_clojure_DOT_zip_node.Get()
				tmp223 := lang.Apply1(tmp222, loc217)
				tmp221 = tmp223
			} else {
				var tmp224 any
				_ = tmp224
				{
					tmp225 := v_clojure_DOT_zip_up.Get()
					tmp226 := lang.Apply1(tmp225, loc217)
					var p227 any = tmp226
					_ = p227
					var tmp228 any
					_ = tmp228
					if lang.IsTruthy(p227) {
						var tmp229 any = p227
						loc217 = tmp229
						continue fnloop218
					} else {
						tmp230 := v_clojure_DOT_zip_node.Get()
						tmp231 := lang.Apply1(tmp230, loc217)
						tmp228 = tmp231
					}
					tmp224 = tmp228
				}
				tmp221 = tmp224
			}
			return tmp221
		}
	})
	tmp232 := &lang.NamedFn1{Name: "clojure.zip/root", Expects: "1: [loc]", F: tmp216}
	v_clojure_DOT_zip_root.BindRoot(tmp232)
	_ = v_clojure_DOT_zip_root
	// (def right "Returns the loc of the right sibling of the node at this loc, or nil" (clojure…
	v_clojure_DOT_zip_right.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(165), kw_column, int64(7), kw_end_line, int64(165), kw_end_column, int64(12), kw_doc, "Returns the loc of the right sibling of the node at this loc, or nil"))
	tmp233 := lang.FnFunc1(func(loc234 any) any {
		var tmp235 any
		_ = tmp235
		{
			var vec__48236 any = loc234
			_ = vec__48236
			tmp237 := v_clojure_DOT_core_nth.Get()
			tmp238 := lang.Apply3(tmp237, vec__48236, int64(0), nil)
			var node239 any = tmp238
			_ = node239
			tmp240 := v_clojure_DOT_core_nth.Get()
			tmp241 := lang.Apply3(tmp240, vec__48236, int64(1), nil)
			var map__51242 any = tmp241
			_ = map__51242
			var path243 any = map__51242
			_ = path243
			tmp244 := v_clojure_DOT_core_get.Get()
			tmp245 := lang.Apply2(tmp244, map__51242, kw_l)
			var l246 any = tmp245
			_ = l246
			tmp247 := v_clojure_DOT_core_get.Get()
			tmp248 := lang.Apply2(tmp247, map__51242, kw_r)
			var vec__52249 any = tmp248
			_ = vec__52249
			tmp250 := v_clojure_DOT_core_seq.Get()
			tmp251 := lang.Apply1(tmp250, vec__52249)
			var seq__53252 any = tmp251
			_ = seq__53252
			tmp253 := v_clojure_DOT_core_first.Get()
			tmp254 := lang.Apply1(tmp253, seq__53252)
			var first__54255 any = tmp254
			_ = first__54255
			tmp256 := v_clojure_DOT_core_next.Get()
			tmp257 := lang.Apply1(tmp256, seq__53252)
			var seq__53258 any = tmp257
			_ = seq__53258
			var r259 any = first__54255
			_ = r259
			var rnext260 any = seq__53258
			_ = rnext260
			var rs261 any = vec__52249
			_ = rs261
			var tmp262 any
			_ = tmp262
			{
				var and__1__auto__263 any = path243
				_ = and__1__auto__263
				var tmp264 any
				_ = tmp264
				if lang.IsTruthy(and__1__auto__263) {
					tmp264 = rs261
				} else {
					tmp264 = and__1__auto__263
				}
				tmp262 = tmp264
			}
			var tmp265 any
			_ = tmp265
			if lang.IsTruthy(tmp262) {
				tmp266 := v_clojure_DOT_core_with_meta.Get()
				tmp267 := v_clojure_DOT_core_assoc.Get()
				tmp268 := v_clojure_DOT_core_conj.Get()
				tmp269 := lang.Apply2(tmp268, l246, node239)
				tmp270 := lang.Apply(tmp267, []any{path243, kw_l, tmp269, kw_r, rnext260})
				tmp271 := lang.NewVector(r259, tmp270)
				tmp272 := v_clojure_DOT_core_meta.Get()
				tmp273 := lang.Apply1(tmp272, loc234)
				tmp274 := lang.Apply2(tmp266, tmp271, tmp273)
				tmp265 = tmp274
			} else {
				tmp265 = nil
			}
			tmp235 = tmp265
		}
		return tmp235
	})
	tmp275 := &lang.NamedFn1{Name: "clojure.zip/right", Expects: "1: [loc]", F: tmp233}
	v_clojure_DOT_zip_right.BindRoot(tmp275)
	_ = v_clojure_DOT_zip_right
	// (def rightmost "Returns the loc of the rightmost sibling of the node at this loc, or self"…
	v_clojure_DOT_zip_rightmost.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(173), kw_column, int64(7), kw_end_line, int64(173), kw_end_column, int64(16), kw_doc, "Returns the loc of the rightmost sibling of the node at this loc, or self"))
	tmp276 := lang.FnFunc1(func(loc277 any) any {
		var tmp278 any
		_ = tmp278
		{
			var vec__55279 any = loc277
			_ = vec__55279
			tmp280 := v_clojure_DOT_core_nth.Get()
			tmp281 := lang.Apply3(tmp280, vec__55279, int64(0), nil)
			var node282 any = tmp281
			_ = node282
			tmp283 := v_clojure_DOT_core_nth.Get()
			tmp284 := lang.Apply3(tmp283, vec__55279, int64(1), nil)
			var map__58285 any = tmp284
			_ = map__58285
			var path286 any = map__58285
			_ = path286
			tmp287 := v_clojure_DOT_core_get.Get()
			tmp288 := lang.Apply2(tmp287, map__58285, kw_l)
			var l289 any = tmp288
			_ = l289
			tmp290 := v_clojure_DOT_core_get.Get()
			tmp291 := lang.Apply2(tmp290, map__58285, kw_r)
			var r292 any = tmp291
			_ = r292
			var tmp293 any
			_ = tmp293
			{
				var and__1__auto__294 any = path286
				_ = and__1__auto__294
				var tmp295 any
				_ = tmp295
				if lang.IsTruthy(and__1__auto__294) {
					tmp295 = r292
				} else {
					tmp295 = and__1__auto__294
				}
				tmp293 = tmp295
			}
			var tmp296 any
			_ = tmp296
			if lang.IsTruthy(tmp293) {
				tmp297 := v_clojure_DOT_core_with_meta.Get()
				tmp298 := v_clojure_DOT_core_last.Get()
				tmp299 := lang.Apply1(tmp298, r292)
				tmp300 := v_clojure_DOT_core_assoc.Get()
				tmp301 := v_clojure_DOT_core_apply.Get()
				tmp302 := v_clojure_DOT_core_conj.Get()
				tmp303 := v_clojure_DOT_core_butlast.Get()
				tmp304 := lang.Apply1(tmp303, r292)
				tmp305 := lang.Apply4(tmp301, tmp302, l289, node282, tmp304)
				tmp306 := lang.Apply(tmp300, []any{path286, kw_l, tmp305, kw_r, nil})
				tmp307 := lang.NewVector(tmp299, tmp306)
				tmp308 := v_clojure_DOT_core_meta.Get()
				tmp309 := lang.Apply1(tmp308, loc277)
				tmp310 := lang.Apply2(tmp297, tmp307, tmp309)
				tmp296 = tmp310
			} else {
				tmp296 = loc277
			}
			tmp278 = tmp296
		}
		return tmp278
	})
	tmp311 := &lang.NamedFn1{Name: "clojure.zip/rightmost", Expects: "1: [loc]", F: tmp276}
	v_clojure_DOT_zip_rightmost.BindRoot(tmp311)
	_ = v_clojure_DOT_zip_rightmost
	// (def left "Returns the loc of the left sibling of the node at this loc, or nil" (clojure.c…
	v_clojure_DOT_zip_left.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(183), kw_column, int64(7), kw_end_line, int64(183), kw_end_column, int64(11), kw_doc, "Returns the loc of the left sibling of the node at this loc, or nil"))
	tmp312 := lang.FnFunc1(func(loc313 any) any {
		var tmp314 any
		_ = tmp314
		{
			var vec__59315 any = loc313
			_ = vec__59315
			tmp316 := v_clojure_DOT_core_nth.Get()
			tmp317 := lang.Apply3(tmp316, vec__59315, int64(0), nil)
			var node318 any = tmp317
			_ = node318
			tmp319 := v_clojure_DOT_core_nth.Get()
			tmp320 := lang.Apply3(tmp319, vec__59315, int64(1), nil)
			var map__62321 any = tmp320
			_ = map__62321
			var path322 any = map__62321
			_ = path322
			tmp323 := v_clojure_DOT_core_get.Get()
			tmp324 := lang.Apply2(tmp323, map__62321, kw_l)
			var l325 any = tmp324
			_ = l325
			tmp326 := v_clojure_DOT_core_get.Get()
			tmp327 := lang.Apply2(tmp326, map__62321, kw_r)
			var r328 any = tmp327
			_ = r328
			var tmp329 any
			_ = tmp329
			{
				var and__1__auto__330 any = path322
				_ = and__1__auto__330
				var tmp331 any
				_ = tmp331
				if lang.IsTruthy(and__1__auto__330) {
					tmp332 := v_clojure_DOT_core_seq.Get()
					tmp333 := lang.Apply1(tmp332, l325)
					tmp331 = tmp333
				} else {
					tmp331 = and__1__auto__330
				}
				tmp329 = tmp331
			}
			var tmp334 any
			_ = tmp334
			if lang.IsTruthy(tmp329) {
				tmp335 := v_clojure_DOT_core_with_meta.Get()
				tmp336 := v_clojure_DOT_core_peek.Get()
				tmp337 := lang.Apply1(tmp336, l325)
				tmp338 := v_clojure_DOT_core_assoc.Get()
				tmp339 := v_clojure_DOT_core_pop.Get()
				tmp340 := lang.Apply1(tmp339, l325)
				tmp341 := v_clojure_DOT_core_cons.Get()
				tmp342 := lang.Apply2(tmp341, node318, r328)
				tmp343 := lang.Apply(tmp338, []any{path322, kw_l, tmp340, kw_r, tmp342})
				tmp344 := lang.NewVector(tmp337, tmp343)
				tmp345 := v_clojure_DOT_core_meta.Get()
				tmp346 := lang.Apply1(tmp345, loc313)
				tmp347 := lang.Apply2(tmp335, tmp344, tmp346)
				tmp334 = tmp347
			} else {
				tmp334 = nil
			}
			tmp314 = tmp334
		}
		return tmp314
	})
	tmp348 := &lang.NamedFn1{Name: "clojure.zip/left", Expects: "1: [loc]", F: tmp312}
	v_clojure_DOT_zip_left.BindRoot(tmp348)
	_ = v_clojure_DOT_zip_left
	// (def leftmost "Returns the loc of the leftmost sibling of the node at this loc, or self" (…
	v_clojure_DOT_zip_leftmost.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(191), kw_column, int64(7), kw_end_line, int64(191), kw_end_column, int64(15), kw_doc, "Returns the loc of the leftmost sibling of the node at this loc, or self"))
	tmp349 := lang.FnFunc1(func(loc350 any) any {
		var tmp351 any
		_ = tmp351
		{
			var vec__63352 any = loc350
			_ = vec__63352
			tmp353 := v_clojure_DOT_core_nth.Get()
			tmp354 := lang.Apply3(tmp353, vec__63352, int64(0), nil)
			var node355 any = tmp354
			_ = node355
			tmp356 := v_clojure_DOT_core_nth.Get()
			tmp357 := lang.Apply3(tmp356, vec__63352, int64(1), nil)
			var map__66358 any = tmp357
			_ = map__66358
			var path359 any = map__66358
			_ = path359
			tmp360 := v_clojure_DOT_core_get.Get()
			tmp361 := lang.Apply2(tmp360, map__66358, kw_l)
			var l362 any = tmp361
			_ = l362
			tmp363 := v_clojure_DOT_core_get.Get()
			tmp364 := lang.Apply2(tmp363, map__66358, kw_r)
			var r365 any = tmp364
			_ = r365
			var tmp366 any
			_ = tmp366
			{
				var and__1__auto__367 any = path359
				_ = and__1__auto__367
				var tmp368 any
				_ = tmp368
				if lang.IsTruthy(and__1__auto__367) {
					tmp369 := v_clojure_DOT_core_seq.Get()
					tmp370 := lang.Apply1(tmp369, l362)
					tmp368 = tmp370
				} else {
					tmp368 = and__1__auto__367
				}
				tmp366 = tmp368
			}
			var tmp371 any
			_ = tmp371
			if lang.IsTruthy(tmp366) {
				tmp372 := v_clojure_DOT_core_with_meta.Get()
				tmp373 := v_clojure_DOT_core_first.Get()
				tmp374 := lang.Apply1(tmp373, l362)
				tmp375 := v_clojure_DOT_core_assoc.Get()
				tmp376 := lang.NewVector()
				tmp377 := v_clojure_DOT_core_concat.Get()
				tmp378 := v_clojure_DOT_core_rest.Get()
				tmp379 := lang.Apply1(tmp378, l362)
				tmp380 := lang.NewVector(node355)
				tmp381 := lang.Apply3(tmp377, tmp379, tmp380, r365)
				tmp382 := lang.Apply(tmp375, []any{path359, kw_l, tmp376, kw_r, tmp381})
				tmp383 := lang.NewVector(tmp374, tmp382)
				tmp384 := v_clojure_DOT_core_meta.Get()
				tmp385 := lang.Apply1(tmp384, loc350)
				tmp386 := lang.Apply2(tmp372, tmp383, tmp385)
				tmp371 = tmp386
			} else {
				tmp371 = loc350
			}
			tmp351 = tmp371
		}
		return tmp351
	})
	tmp387 := &lang.NamedFn1{Name: "clojure.zip/leftmost", Expects: "1: [loc]", F: tmp349}
	v_clojure_DOT_zip_leftmost.BindRoot(tmp387)
	_ = v_clojure_DOT_zip_leftmost
	// (def insert-left "Inserts the item as the left sibling of the node at this loc,\n without …
	v_clojure_DOT_zip_insert_left.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(201), kw_column, int64(7), kw_end_line, int64(201), kw_end_column, int64(18), kw_doc, "Inserts the item as the left sibling of the node at this loc,\n without moving"))
	tmp388 := lang.FnFunc2(func(loc389, item390 any) any {
		var tmp391 any
		_ = tmp391
		{
			var vec__67392 any = loc389
			_ = vec__67392
			tmp393 := v_clojure_DOT_core_nth.Get()
			tmp394 := lang.Apply3(tmp393, vec__67392, int64(0), nil)
			var node395 any = tmp394
			_ = node395
			tmp396 := v_clojure_DOT_core_nth.Get()
			tmp397 := lang.Apply3(tmp396, vec__67392, int64(1), nil)
			var map__70398 any = tmp397
			_ = map__70398
			var path399 any = map__70398
			_ = path399
			tmp400 := v_clojure_DOT_core_get.Get()
			tmp401 := lang.Apply2(tmp400, map__70398, kw_l)
			var l402 any = tmp401
			_ = l402
			tmp403 := v_clojure_DOT_core_nil_QMARK_.Get()
			tmp404 := lang.Apply1(tmp403, path399)
			var tmp405 any
			_ = tmp405
			if lang.IsTruthy(tmp404) {
				tmp406 := v_clojure_DOT_core_ex_info.Get()
				tmp407 := lang.NewMap()
				tmp408 := lang.Apply2(tmp406, "Insert at top", tmp407)
				panic(rt.Throw(tmp408))
			} else {
				tmp409 := v_clojure_DOT_core_with_meta.Get()
				tmp410 := v_clojure_DOT_core_assoc.Get()
				tmp411 := v_clojure_DOT_core_conj.Get()
				tmp412 := lang.Apply2(tmp411, l402, item390)
				tmp413 := lang.Apply(tmp410, []any{path399, kw_l, tmp412, kw_changed_QMARK_, true})
				tmp414 := lang.NewVector(node395, tmp413)
				tmp415 := v_clojure_DOT_core_meta.Get()
				tmp416 := lang.Apply1(tmp415, loc389)
				tmp417 := lang.Apply2(tmp409, tmp414, tmp416)
				tmp405 = tmp417
			}
			tmp391 = tmp405
		}
		return tmp391
	})
	tmp418 := &lang.NamedFn2{Name: "clojure.zip/insert-left", Expects: "2: [loc item]", F: tmp388}
	v_clojure_DOT_zip_insert_left.BindRoot(tmp418)
	_ = v_clojure_DOT_zip_insert_left
	// (def insert-right "Inserts the item as the right sibling of the node at this loc,\n  witho…
	v_clojure_DOT_zip_insert_right.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(212), kw_column, int64(7), kw_end_line, int64(212), kw_end_column, int64(19), kw_doc, "Inserts the item as the right sibling of the node at this loc,\n  without moving"))
	tmp419 := lang.FnFunc2(func(loc420, item421 any) any {
		var tmp422 any
		_ = tmp422
		{
			var vec__71423 any = loc420
			_ = vec__71423
			tmp424 := v_clojure_DOT_core_nth.Get()
			tmp425 := lang.Apply3(tmp424, vec__71423, int64(0), nil)
			var node426 any = tmp425
			_ = node426
			tmp427 := v_clojure_DOT_core_nth.Get()
			tmp428 := lang.Apply3(tmp427, vec__71423, int64(1), nil)
			var map__74429 any = tmp428
			_ = map__74429
			var path430 any = map__74429
			_ = path430
			tmp431 := v_clojure_DOT_core_get.Get()
			tmp432 := lang.Apply2(tmp431, map__74429, kw_r)
			var r433 any = tmp432
			_ = r433
			tmp434 := v_clojure_DOT_core_nil_QMARK_.Get()
			tmp435 := lang.Apply1(tmp434, path430)
			var tmp436 any
			_ = tmp436
			if lang.IsTruthy(tmp435) {
				tmp437 := v_clojure_DOT_core_ex_info.Get()
				tmp438 := lang.NewMap()
				tmp439 := lang.Apply2(tmp437, "Insert at top", tmp438)
				panic(rt.Throw(tmp439))
			} else {
				tmp440 := v_clojure_DOT_core_with_meta.Get()
				tmp441 := v_clojure_DOT_core_assoc.Get()
				tmp442 := v_clojure_DOT_core_cons.Get()
				tmp443 := lang.Apply2(tmp442, item421, r433)
				tmp444 := lang.Apply(tmp441, []any{path430, kw_r, tmp443, kw_changed_QMARK_, true})
				tmp445 := lang.NewVector(node426, tmp444)
				tmp446 := v_clojure_DOT_core_meta.Get()
				tmp447 := lang.Apply1(tmp446, loc420)
				tmp448 := lang.Apply2(tmp440, tmp445, tmp447)
				tmp436 = tmp448
			}
			tmp422 = tmp436
		}
		return tmp422
	})
	tmp449 := &lang.NamedFn2{Name: "clojure.zip/insert-right", Expects: "2: [loc item]", F: tmp419}
	v_clojure_DOT_zip_insert_right.BindRoot(tmp449)
	_ = v_clojure_DOT_zip_insert_right
	// (def replace "Replaces the node at this loc, without moving" (clojure.core/fn [loc node] (…
	v_clojure_DOT_zip_replace.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(222), kw_column, int64(7), kw_end_line, int64(222), kw_end_column, int64(14), kw_doc, "Replaces the node at this loc, without moving"))
	tmp450 := lang.FnFunc2(func(loc451, node452 any) any {
		var tmp453 any
		_ = tmp453
		{
			var vec__75454 any = loc451
			_ = vec__75454
			tmp455 := v_clojure_DOT_core_nth.Get()
			tmp456 := lang.Apply3(tmp455, vec__75454, int64(0), nil)
			var X_457 any = tmp456
			_ = X_457
			tmp458 := v_clojure_DOT_core_nth.Get()
			tmp459 := lang.Apply3(tmp458, vec__75454, int64(1), nil)
			var path460 any = tmp459
			_ = path460
			tmp461 := v_clojure_DOT_core_with_meta.Get()
			tmp462 := v_clojure_DOT_core_assoc.Get()
			tmp463 := lang.Apply3(tmp462, path460, kw_changed_QMARK_, true)
			tmp464 := lang.NewVector(node452, tmp463)
			tmp465 := v_clojure_DOT_core_meta.Get()
			tmp466 := lang.Apply1(tmp465, loc451)
			tmp467 := lang.Apply2(tmp461, tmp464, tmp466)
			tmp453 = tmp467
		}
		return tmp453
	})
	tmp468 := &lang.NamedFn2{Name: "clojure.zip/replace", Expects: "2: [loc node]", F: tmp450}
	v_clojure_DOT_zip_replace.BindRoot(tmp468)
	_ = v_clojure_DOT_zip_replace
	// (def edit "Replaces the node at this loc with the value of (f node args)" (clojure.core/fn…
	v_clojure_DOT_zip_edit.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(229), kw_column, int64(7), kw_end_line, int64(229), kw_end_column, int64(11), kw_doc, "Replaces the node at this loc with the value of (f node args)"))
	tmp469 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		default:
			if len(args) < 2 {
				panic(lang.NewArityError(len(args), "clojure.zip/edit", "2+: [loc f args & more]"))
			}
			loc470 := args[0]
			_ = loc470
			f471 := args[1]
			_ = f471
			var args472 any
			if len(args) > 2 {
				args472 = lang.NewList(args[2:]...)
			}
			_ = args472
			tmp473 := v_clojure_DOT_zip_replace.Get()
			tmp474 := v_clojure_DOT_core_apply.Get()
			tmp475 := v_clojure_DOT_zip_node.Get()
			tmp476 := lang.Apply1(tmp475, loc470)
			tmp477 := lang.Apply3(tmp474, f471, tmp476, args472)
			tmp478 := lang.Apply2(tmp473, loc470, tmp477)
			return tmp478
		}
	})
	v_clojure_DOT_zip_edit.BindRoot(tmp469)
	_ = v_clojure_DOT_zip_edit
	// (def insert-child "Inserts the item as the leftmost child of the node at this loc,\n  with…
	v_clojure_DOT_zip_insert_child.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(235), kw_column, int64(7), kw_end_line, int64(235), kw_end_column, int64(19), kw_doc, "Inserts the item as the leftmost child of the node at this loc,\n  without moving"))
	tmp479 := lang.FnFunc2(func(loc480, item481 any) any {
		tmp482 := v_clojure_DOT_zip_replace.Get()
		tmp483 := v_clojure_DOT_zip_make_node.Get()
		tmp484 := v_clojure_DOT_zip_node.Get()
		tmp485 := lang.Apply1(tmp484, loc480)
		tmp486 := v_clojure_DOT_core_cons.Get()
		tmp487 := v_clojure_DOT_zip_children.Get()
		tmp488 := lang.Apply1(tmp487, loc480)
		tmp489 := lang.Apply2(tmp486, item481, tmp488)
		tmp490 := lang.Apply3(tmp483, loc480, tmp485, tmp489)
		tmp491 := lang.Apply2(tmp482, loc480, tmp490)
		return tmp491
	})
	tmp492 := &lang.NamedFn2{Name: "clojure.zip/insert-child", Expects: "2: [loc item]", F: tmp479}
	v_clojure_DOT_zip_insert_child.BindRoot(tmp492)
	_ = v_clojure_DOT_zip_insert_child
	// (def append-child "Inserts the item as the rightmost child of the node at this loc,\n  wit…
	v_clojure_DOT_zip_append_child.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(242), kw_column, int64(7), kw_end_line, int64(242), kw_end_column, int64(19), kw_doc, "Inserts the item as the rightmost child of the node at this loc,\n  without moving"))
	tmp493 := lang.FnFunc2(func(loc494, item495 any) any {
		tmp496 := v_clojure_DOT_zip_replace.Get()
		tmp497 := v_clojure_DOT_zip_make_node.Get()
		tmp498 := v_clojure_DOT_zip_node.Get()
		tmp499 := lang.Apply1(tmp498, loc494)
		tmp500 := v_clojure_DOT_core_concat.Get()
		tmp501 := v_clojure_DOT_zip_children.Get()
		tmp502 := lang.Apply1(tmp501, loc494)
		tmp503 := lang.NewVector(item495)
		tmp504 := lang.Apply2(tmp500, tmp502, tmp503)
		tmp505 := lang.Apply3(tmp497, loc494, tmp499, tmp504)
		tmp506 := lang.Apply2(tmp496, loc494, tmp505)
		return tmp506
	})
	tmp507 := &lang.NamedFn2{Name: "clojure.zip/append-child", Expects: "2: [loc item]", F: tmp493}
	v_clojure_DOT_zip_append_child.BindRoot(tmp507)
	_ = v_clojure_DOT_zip_append_child
	// (def next "Moves to the next loc in the hierarchy, depth-first. When reaching\n  the end, …
	v_clojure_DOT_zip_next.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(250), kw_column, int64(7), kw_end_line, int64(250), kw_end_column, int64(11), kw_doc, "Moves to the next loc in the hierarchy, depth-first. When reaching\n  the end, returns a distinguished loc detectable via end?. If already\n  at the end, stays there."))
	tmp508 := lang.FnFunc1(func(loc509 any) any {
		tmp510 := lang.Apply1(loc509, int64(1))
		tmp511 := rt.EQBool(v_clojure_DOT_core_X_EQ_, kw_end, tmp510)
		var tmp512 any
		_ = tmp512
		if tmp511 {
			tmp512 = loc509
		} else {
			var tmp513 any
			_ = tmp513
			{
				var tmp514 any
				_ = tmp514
				{
					tmp515 := v_clojure_DOT_zip_branch_QMARK_.Get()
					tmp516 := lang.Apply1(tmp515, loc509)
					var and__1__auto__517 any = tmp516
					_ = and__1__auto__517
					var tmp518 any
					_ = tmp518
					if lang.IsTruthy(and__1__auto__517) {
						tmp519 := v_clojure_DOT_zip_down.Get()
						tmp520 := lang.Apply1(tmp519, loc509)
						tmp518 = tmp520
					} else {
						tmp518 = and__1__auto__517
					}
					tmp514 = tmp518
				}
				var or__2__auto__521 any = tmp514
				_ = or__2__auto__521
				var tmp522 any
				_ = tmp522
				if lang.IsTruthy(or__2__auto__521) {
					tmp522 = or__2__auto__521
				} else {
					var tmp523 any
					_ = tmp523
					{
						tmp524 := v_clojure_DOT_zip_right.Get()
						tmp525 := lang.Apply1(tmp524, loc509)
						var or__2__auto__526 any = tmp525
						_ = or__2__auto__526
						var tmp527 any
						_ = tmp527
						if lang.IsTruthy(or__2__auto__526) {
							tmp527 = or__2__auto__526
						} else {
							var tmp528 any
							_ = tmp528
							{
								var p529 any = loc509
								_ = p529
							loop530:
								for {
									tmp531 := v_clojure_DOT_zip_up.Get()
									tmp532 := lang.Apply1(tmp531, p529)
									var tmp533 any
									_ = tmp533
									if lang.IsTruthy(tmp532) {
										var tmp534 any
										_ = tmp534
										{
											tmp535 := v_clojure_DOT_zip_right.Get()
											tmp536 := v_clojure_DOT_zip_up.Get()
											tmp537 := lang.Apply1(tmp536, p529)
											tmp538 := lang.Apply1(tmp535, tmp537)
											var or__2__auto__539 any = tmp538
											_ = or__2__auto__539
											var tmp540 any
											_ = tmp540
											if lang.IsTruthy(or__2__auto__539) {
												tmp540 = or__2__auto__539
											} else {
												tmp541 := v_clojure_DOT_zip_up.Get()
												tmp542 := lang.Apply1(tmp541, p529)
												var tmp543 any = tmp542
												p529 = tmp543
												continue loop530
											}
											tmp534 = tmp540
										}
										tmp533 = tmp534
									} else {
										tmp544 := v_clojure_DOT_zip_node.Get()
										tmp545 := lang.Apply1(tmp544, p529)
										tmp546 := lang.NewVector(tmp545, kw_end)
										tmp533 = tmp546
									}
									tmp528 = tmp533
									break loop530
								}
							}
							tmp527 = tmp528
						}
						tmp523 = tmp527
					}
					tmp522 = tmp523
				}
				tmp513 = tmp522
			}
			tmp512 = tmp513
		}
		return tmp512
	})
	tmp547 := &lang.NamedFn1{Name: "clojure.zip/next", Expects: "1: [loc]", F: tmp508}
	v_clojure_DOT_zip_next.BindRoot(tmp547)
	_ = v_clojure_DOT_zip_next
	// (def prev "Moves to the previous loc in the hierarchy, depth-first. If already\n  at the r…
	v_clojure_DOT_zip_prev.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(267), kw_column, int64(7), kw_end_line, int64(267), kw_end_column, int64(11), kw_doc, "Moves to the previous loc in the hierarchy, depth-first. If already\n  at the root, returns nil."))
	tmp548 := lang.FnFunc1(func(loc549 any) any {
		var tmp550 any
		_ = tmp550
		{
			tmp551 := v_clojure_DOT_zip_left.Get()
			tmp552 := lang.Apply1(tmp551, loc549)
			var temp__4__auto__553 any = tmp552
			_ = temp__4__auto__553
			var tmp554 any
			_ = tmp554
			if lang.IsTruthy(temp__4__auto__553) {
				var tmp555 any
				_ = tmp555
				{
					var lloc556 any = temp__4__auto__553
					_ = lloc556
					var tmp557 any
					_ = tmp557
					{
						var loc558 any = lloc556
						_ = loc558
					loop559:
						for {
							var tmp560 any
							_ = tmp560
							{
								var tmp561 any
								_ = tmp561
								{
									tmp562 := v_clojure_DOT_zip_branch_QMARK_.Get()
									tmp563 := lang.Apply1(tmp562, loc558)
									var and__1__auto__564 any = tmp563
									_ = and__1__auto__564
									var tmp565 any
									_ = tmp565
									if lang.IsTruthy(and__1__auto__564) {
										tmp566 := v_clojure_DOT_zip_down.Get()
										tmp567 := lang.Apply1(tmp566, loc558)
										tmp565 = tmp567
									} else {
										tmp565 = and__1__auto__564
									}
									tmp561 = tmp565
								}
								var temp__4__auto__568 any = tmp561
								_ = temp__4__auto__568
								var tmp569 any
								_ = tmp569
								if lang.IsTruthy(temp__4__auto__568) {
									var tmp570 any
									_ = tmp570
									{
										var child571 any = temp__4__auto__568
										_ = child571
										tmp572 := v_clojure_DOT_zip_rightmost.Get()
										tmp573 := lang.Apply1(tmp572, child571)
										var tmp574 any = tmp573
										loc558 = tmp574
										continue loop559
									}
								} else {
									tmp569 = loc558
								}
								tmp560 = tmp569
							}
							tmp557 = tmp560
							break loop559
						}
					}
					tmp555 = tmp557
				}
				tmp554 = tmp555
			} else {
				tmp575 := v_clojure_DOT_zip_up.Get()
				tmp576 := lang.Apply1(tmp575, loc549)
				tmp554 = tmp576
			}
			tmp550 = tmp554
		}
		return tmp550
	})
	tmp577 := &lang.NamedFn1{Name: "clojure.zip/prev", Expects: "1: [loc]", F: tmp548}
	v_clojure_DOT_zip_prev.BindRoot(tmp577)
	_ = v_clojure_DOT_zip_prev
	// (def end? "Returns true if loc represents the end of a depth-first walk" (clojure.core/fn …
	v_clojure_DOT_zip_end_QMARK_.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(280), kw_column, int64(7), kw_end_line, int64(280), kw_end_column, int64(11), kw_doc, "Returns true if loc represents the end of a depth-first walk"))
	tmp578 := lang.FnFunc1(func(loc579 any) any {
		tmp580 := lang.Apply1(loc579, int64(1))
		tmp581 := rt.EQ2(v_clojure_DOT_core_X_EQ_, kw_end, tmp580)
		return tmp581
	})
	tmp582 := &lang.NamedFn1{Name: "clojure.zip/end?", Expects: "1: [loc]", F: tmp578}
	v_clojure_DOT_zip_end_QMARK_.BindRoot(tmp582)
	_ = v_clojure_DOT_zip_end_QMARK_
	// (def remove "Removes the node at loc, returning the loc that would have preceded\n  it in …
	v_clojure_DOT_zip_remove.SetMeta(lang.NewMap(kw_file, "zip.cljg", kw_line, int64(287), kw_column, int64(7), kw_end_line, int64(287), kw_end_column, int64(13), kw_doc, "Removes the node at loc, returning the loc that would have preceded\n  it in a depth-first walk."))
	tmp583 := lang.FnFunc1(func(loc584 any) any {
		var tmp585 any
		_ = tmp585
		{
			var vec__78586 any = loc584
			_ = vec__78586
			tmp587 := v_clojure_DOT_core_nth.Get()
			tmp588 := lang.Apply3(tmp587, vec__78586, int64(0), nil)
			var node589 any = tmp588
			_ = node589
			tmp590 := v_clojure_DOT_core_nth.Get()
			tmp591 := lang.Apply3(tmp590, vec__78586, int64(1), nil)
			var map__81592 any = tmp591
			_ = map__81592
			var path593 any = map__81592
			_ = path593
			tmp594 := v_clojure_DOT_core_get.Get()
			tmp595 := lang.Apply2(tmp594, map__81592, kw_l)
			var l596 any = tmp595
			_ = l596
			tmp597 := v_clojure_DOT_core_get.Get()
			tmp598 := lang.Apply2(tmp597, map__81592, kw_ppath)
			var ppath599 any = tmp598
			_ = ppath599
			tmp600 := v_clojure_DOT_core_get.Get()
			tmp601 := lang.Apply2(tmp600, map__81592, kw_pnodes)
			var pnodes602 any = tmp601
			_ = pnodes602
			tmp603 := v_clojure_DOT_core_get.Get()
			tmp604 := lang.Apply2(tmp603, map__81592, kw_r)
			var rs605 any = tmp604
			_ = rs605
			tmp606 := v_clojure_DOT_core_nil_QMARK_.Get()
			tmp607 := lang.Apply1(tmp606, path593)
			var tmp608 any
			_ = tmp608
			if lang.IsTruthy(tmp607) {
				tmp609 := v_clojure_DOT_core_ex_info.Get()
				tmp610 := lang.NewMap()
				tmp611 := lang.Apply2(tmp609, "Remove at top", tmp610)
				panic(rt.Throw(tmp611))
			} else {
				tmp612 := v_clojure_DOT_core_pos_QMARK_.Get()
				tmp613 := v_clojure_DOT_core_count.Get()
				tmp614 := lang.Apply1(tmp613, l596)
				tmp615 := lang.Apply1(tmp612, tmp614)
				var tmp616 any
				_ = tmp616
				if lang.IsTruthy(tmp615) {
					var tmp617 any
					_ = tmp617
					{
						tmp618 := v_clojure_DOT_core_with_meta.Get()
						tmp619 := v_clojure_DOT_core_peek.Get()
						tmp620 := lang.Apply1(tmp619, l596)
						tmp621 := v_clojure_DOT_core_assoc.Get()
						tmp622 := v_clojure_DOT_core_pop.Get()
						tmp623 := lang.Apply1(tmp622, l596)
						tmp624 := lang.Apply(tmp621, []any{path593, kw_l, tmp623, kw_changed_QMARK_, true})
						tmp625 := lang.NewVector(tmp620, tmp624)
						tmp626 := v_clojure_DOT_core_meta.Get()
						tmp627 := lang.Apply1(tmp626, loc584)
						tmp628 := lang.Apply2(tmp618, tmp625, tmp627)
						var loc629 any = tmp628
						_ = loc629
					loop630:
						for {
							var tmp631 any
							_ = tmp631
							{
								var tmp632 any
								_ = tmp632
								{
									tmp633 := v_clojure_DOT_zip_branch_QMARK_.Get()
									tmp634 := lang.Apply1(tmp633, loc629)
									var and__1__auto__635 any = tmp634
									_ = and__1__auto__635
									var tmp636 any
									_ = tmp636
									if lang.IsTruthy(and__1__auto__635) {
										tmp637 := v_clojure_DOT_zip_down.Get()
										tmp638 := lang.Apply1(tmp637, loc629)
										tmp636 = tmp638
									} else {
										tmp636 = and__1__auto__635
									}
									tmp632 = tmp636
								}
								var temp__4__auto__639 any = tmp632
								_ = temp__4__auto__639
								var tmp640 any
								_ = tmp640
								if lang.IsTruthy(temp__4__auto__639) {
									var tmp641 any
									_ = tmp641
									{
										var child642 any = temp__4__auto__639
										_ = child642
										tmp643 := v_clojure_DOT_zip_rightmost.Get()
										tmp644 := lang.Apply1(tmp643, child642)
										var tmp645 any = tmp644
										loc629 = tmp645
										continue loop630
									}
								} else {
									tmp640 = loc629
								}
								tmp631 = tmp640
							}
							tmp617 = tmp631
							break loop630
						}
					}
					tmp616 = tmp617
				} else {
					tmp646 := v_clojure_DOT_core_with_meta.Get()
					tmp647 := v_clojure_DOT_zip_make_node.Get()
					tmp648 := v_clojure_DOT_core_peek.Get()
					tmp649 := lang.Apply1(tmp648, pnodes602)
					tmp650 := lang.Apply3(tmp647, loc584, tmp649, rs605)
					var tmp651 any
					_ = tmp651
					{
						var and__1__auto__652 any = ppath599
						_ = and__1__auto__652
						var tmp653 any
						_ = tmp653
						if lang.IsTruthy(and__1__auto__652) {
							tmp654 := v_clojure_DOT_core_assoc.Get()
							tmp655 := lang.Apply3(tmp654, ppath599, kw_changed_QMARK_, true)
							tmp653 = tmp655
						} else {
							tmp653 = and__1__auto__652
						}
						tmp651 = tmp653
					}
					tmp656 := lang.NewVector(tmp650, tmp651)
					tmp657 := v_clojure_DOT_core_meta.Get()
					tmp658 := lang.Apply1(tmp657, loc584)
					tmp659 := lang.Apply2(tmp646, tmp656, tmp658)
					tmp616 = tmp659
				}
				tmp608 = tmp616
			}
			tmp585 = tmp608
		}
		return tmp585
	})
	tmp660 := &lang.NamedFn1{Name: "clojure.zip/remove", Expects: "1: [loc]", F: tmp583}
	v_clojure_DOT_zip_remove.BindRoot(tmp660)
	_ = v_clojure_DOT_zip_remove
}
