// Code generated by cljgo build. DO NOT EDIT.

package cljedn

import (
	"fmt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	sym_clojure_DOT_core                      = lang.NewSymbol("clojure.core")
	sym_clojure_DOT_edn                       = lang.NewSymbol("clojure.edn")
	v_clojure_DOT_core_X_edn_read_string      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("-edn-read-string"))
	v_clojure_DOT_core_X_edn_read_string_opts = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("-edn-read-string-opts"))
	v_clojure_DOT_core_in_ns                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_refer                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
	v_clojure_DOT_edn_read_string             = lang.InternVarName(lang.NewSymbol("clojure.edn"), lang.NewSymbol("read-string"))
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("clojure.edn")), lang.VarFile, "edn.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote clojure.edn))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_clojure_DOT_edn)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply1(tmp3, sym_clojure_DOT_core)
	_ = tmp4
	// (def read-string "Reads one object from the string s. Returns nil when s has nothing but\n…
	tmp5 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			s6 := args[0]
			_ = s6
			tmp7 := v_clojure_DOT_core_X_edn_read_string.Get()
			tmp8 := lang.Apply1(tmp7, s6)
			return tmp8
		case 2:
			opts9 := args[0]
			_ = opts9
			s10 := args[1]
			_ = s10
			tmp11 := v_clojure_DOT_core_X_edn_read_string_opts.Get()
			tmp12 := lang.Apply2(tmp11, opts9, s10)
			return tmp12
		default:
			panic(fmt.Errorf("wrong number of args (%d) passed to: %s", len(args), "fn"))
		}
	})
	v_clojure_DOT_edn_read_string.BindRoot(tmp5)
	_ = v_clojure_DOT_edn_read_string
}
