// Code generated by cljgo build. DO NOT EDIT.

package cljghttp

import (
	rt "github.com/muthuishere/cljgo/pkg/emit/rt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_addr                       = lang.InternKeywordString("addr")
	kw_column                     = lang.InternKeywordString("column")
	kw_doc                        = lang.InternKeywordString("doc")
	kw_end_column                 = lang.InternKeywordString("end-column")
	kw_end_line                   = lang.InternKeywordString("end-line")
	kw_file                       = lang.InternKeywordString("file")
	kw_handler                    = lang.InternKeywordString("handler")
	kw_line                       = lang.InternKeywordString("line")
	kw_opts                       = lang.InternKeywordString("opts")
	kw_stop                       = lang.InternKeywordString("stop")
	sym_cljg_DOT_http             = lang.NewSymbol("cljg.http")
	sym_clojure_DOT_core          = lang.NewSymbol("clojure.core")
	v_cljg_DOT_http_X_http_serve  = lang.InternVarName(lang.NewSymbol("cljg.http"), lang.NewSymbol("-http-serve")).SetPrivate()
	v_cljg_DOT_http_addr          = lang.InternVarName(lang.NewSymbol("cljg.http"), lang.NewSymbol("addr"))
	v_cljg_DOT_http_serve         = lang.InternVarName(lang.NewSymbol("cljg.http"), lang.NewSymbol("serve"))
	v_cljg_DOT_http_stop          = lang.InternVarName(lang.NewSymbol("cljg.http"), lang.NewSymbol("stop"))
	v_clojure_DOT_core_dissoc     = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("dissoc"))
	v_clojure_DOT_core_ex_info    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("ex-info"))
	v_clojure_DOT_core_ifn_QMARK_ = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("ifn?"))
	v_clojure_DOT_core_in_ns      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_pr_str     = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("pr-str"))
	v_clojure_DOT_core_refer      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
	v_clojure_DOT_core_str        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("str"))
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("cljg.http")), lang.VarFile, "cljg/http.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote cljg.http))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_cljg_DOT_http)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply1(tmp3, sym_clojure_DOT_core)
	_ = tmp4
	// (def serve "Start the raw HTTP server: {:port p :host h :handler f :tls {…}} → a\n  se…
	v_cljg_DOT_http_serve.SetMeta(lang.NewMap(kw_file, "cljg/http.cljg", kw_line, int64(34), kw_column, int64(7), kw_end_line, int64(34), kw_end_column, int64(12), kw_doc, "Start the raw HTTP server: {:port p :host h :handler f :tls {…}} → a\n  server handle {:port :addr :stop}. `f` is (fn [request-map] response-map)\n  — the Ring-shaped contract above. Never blocks; :port 0 binds a free\n  port (read it back with `addr`). Stop gracefully with `stop`."))
	tmp5 := lang.FnFunc1(func(opts6 any) any {
		var tmp7 any
		_ = tmp7
		{
			tmp8 := lang.Apply1(kw_handler, opts6)
			var handler9 any = tmp8
			_ = handler9
			tmp10 := v_clojure_DOT_core_ifn_QMARK_.Get()
			tmp11 := lang.Apply1(tmp10, handler9)
			var tmp12 any
			_ = tmp12
			if lang.IsTruthy(tmp11) {
				tmp12 = nil
			} else {
				tmp13 := v_clojure_DOT_core_ex_info.Get()
				tmp14 := v_clojure_DOT_core_str.Get()
				tmp15 := v_clojure_DOT_core_pr_str.Get()
				tmp16 := lang.Apply1(tmp15, handler9)
				tmp17 := lang.Apply3(tmp14, "cljg.http/serve: :handler must be a function ", "(request-map -> response-map), got: ", tmp16)
				tmp18 := v_clojure_DOT_core_dissoc.Get()
				tmp19 := lang.Apply2(tmp18, opts6, kw_handler)
				tmp20 := lang.NewMap(kw_opts, tmp19)
				tmp21 := lang.Apply2(tmp13, tmp17, tmp20)
				panic(rt.Throw(tmp21))
			}
			_ = tmp12
			tmp22 := v_cljg_DOT_http_X_http_serve.Get()
			tmp23 := v_clojure_DOT_core_dissoc.Get()
			tmp24 := lang.Apply2(tmp23, opts6, kw_handler)
			tmp25 := lang.Apply2(tmp22, handler9, tmp24)
			tmp7 = tmp25
		}
		return tmp7
	})
	tmp26 := &lang.NamedFn1{Name: "cljg.http/serve", Expects: "1: [opts]", F: tmp5}
	v_cljg_DOT_http_serve.BindRoot(tmp26)
	_ = v_cljg_DOT_http_serve
	// (def addr "The bound \"host:port\" of a server handle — with {:port 0} this is how\n  yo…
	v_cljg_DOT_http_addr.SetMeta(lang.NewMap(kw_file, "cljg/http.cljg", kw_line, int64(47), kw_column, int64(7), kw_end_line, int64(47), kw_end_column, int64(11), kw_doc, "The bound \"host:port\" of a server handle — with {:port 0} this is how\n  you learn the actual port."))
	tmp27 := lang.FnFunc1(func(server28 any) any {
		tmp29 := lang.Apply1(kw_addr, server28)
		return tmp29
	})
	tmp30 := &lang.NamedFn1{Name: "cljg.http/addr", Expects: "1: [server]", F: tmp27}
	v_cljg_DOT_http_addr.BindRoot(tmp30)
	_ = v_cljg_DOT_http_addr
	// (def stop "Gracefully stop a server handle: the listener closes, in-flight requests\n  fin…
	v_cljg_DOT_http_stop.SetMeta(lang.NewMap(kw_file, "cljg/http.cljg", kw_line, int64(53), kw_column, int64(7), kw_end_line, int64(53), kw_end_column, int64(11), kw_doc, "Gracefully stop a server handle: the listener closes, in-flight requests\n  finish (deadline), then the server is down. Returns nil."))
	tmp31 := lang.FnFunc1(func(server32 any) any {
		tmp33 := lang.Apply1(kw_stop, server32)
		tmp34 := lang.Apply0(tmp33)
		_ = tmp34
		return nil
	})
	tmp35 := &lang.NamedFn1{Name: "cljg.http/stop", Expects: "1: [server]", F: tmp31}
	v_cljg_DOT_http_stop.BindRoot(tmp35)
	_ = v_cljg_DOT_http_stop
}
