// Code generated by cljgo build. DO NOT EDIT.

package cljgos

import (
	rt "github.com/muthuishere/cljgo/pkg/emit/rt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_arglists                         = lang.InternKeywordString("arglists")
	kw_cljg_DOT_os_SLASH_job            = lang.InternKeywordString("cljg.os/job")
	kw_cljg_DOT_os_SLASH_service        = lang.InternKeywordString("cljg.os/service")
	kw_column                           = lang.InternKeywordString("column")
	kw_cron                             = lang.InternKeywordString("cron")
	kw_doc                              = lang.InternKeywordString("doc")
	kw_end_column                       = lang.InternKeywordString("end-column")
	kw_end_line                         = lang.InternKeywordString("end-line")
	kw_file                             = lang.InternKeywordString("file")
	kw_fn                               = lang.InternKeywordString("fn")
	kw_line                             = lang.InternKeywordString("line")
	kw_max_ticks                        = lang.InternKeywordString("max-ticks")
	kw_name                             = lang.InternKeywordString("name")
	kw_private                          = lang.InternKeywordString("private")
	kw_scope                            = lang.InternKeywordString("scope")
	kw_user                             = lang.InternKeywordString("user")
	sym_cljg_DOT_os                     = lang.NewSymbol("cljg.os")
	sym_clojure_DOT_core                = lang.NewSymbol("clojure.core")
	sym_expr                            = lang.NewSymbol("expr")
	sym_f                               = lang.NewSymbol("f")
	sym_from                            = lang.NewSymbol("from")
	sym_j                               = lang.NewSymbol("j")
	sym_jobs                            = lang.NewSymbol("jobs")
	sym_m                               = lang.NewSymbol("m")
	sym_name                            = lang.NewSymbol("name")
	sym_opts                            = lang.NewSymbol("opts")
	sym_os                              = lang.NewSymbol("os")
	sym_spec                            = lang.NewSymbol("spec")
	v_cljg_DOT_os_X_check_opts          = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("-check-opts")).SetPrivate()
	v_cljg_DOT_os_X_cron_next           = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("-cron-next")).SetPrivate()
	v_cljg_DOT_os_X_now_millis          = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("-now-millis")).SetPrivate()
	v_cljg_DOT_os_X_service_install     = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("-service-install")).SetPrivate()
	v_cljg_DOT_os_X_service_op          = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("-service-op")).SetPrivate()
	v_cljg_DOT_os_X_service_render      = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("-service-render")).SetPrivate()
	v_cljg_DOT_os_X_sleep_millis        = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("-sleep-millis")).SetPrivate()
	v_cljg_DOT_os_cron_next             = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("cron-next"))
	v_cljg_DOT_os_job                   = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("job"))
	v_cljg_DOT_os_now                   = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("now"))
	v_cljg_DOT_os_run                   = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("run"))
	v_cljg_DOT_os_run_job               = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("run-job")).SetPrivate()
	v_cljg_DOT_os_service               = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("service"))
	v_cljg_DOT_os_service_install       = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("service-install"))
	v_cljg_DOT_os_service_start         = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("service-start"))
	v_cljg_DOT_os_service_status        = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("service-status"))
	v_cljg_DOT_os_service_stop          = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("service-stop"))
	v_cljg_DOT_os_service_uninstall     = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("service-uninstall"))
	v_cljg_DOT_os_service_unit          = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("service-unit"))
	v_cljg_DOT_os_soonest               = lang.InternVarName(lang.NewSymbol("cljg.os"), lang.NewSymbol("soonest")).SetPrivate()
	v_clojure_DOT_core_X_               = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("-"))
	v_clojure_DOT_core_X_EQ_            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("="))
	v_clojure_DOT_core_X_GT__EQ_        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol(">="))
	v_clojure_DOT_core_X_STAR_err_STAR_ = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("*err*"))
	v_clojure_DOT_core_X_STAR_out_STAR_ = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("*out*"))
	v_clojure_DOT_core_ex_message       = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("ex-message"))
	v_clojure_DOT_core_first            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("first"))
	v_clojure_DOT_core_in_ns            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_inc              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("inc"))
	v_clojure_DOT_core_map_             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("map"))
	v_clojure_DOT_core_max_             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("max"))
	v_clojure_DOT_core_merge            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("merge"))
	v_clojure_DOT_core_next             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("next"))
	v_clojure_DOT_core_nth              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("nth"))
	v_clojure_DOT_core_println_         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("println"))
	v_clojure_DOT_core_refer            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
	v_clojure_DOT_core_second           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("second"))
	v_clojure_DOT_core_seq              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("seq"))
	v_clojure_DOT_core_sort_by          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("sort-by"))
	v_clojure_DOT_core_str              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("str"))
)

var (
	fnD_cljg_DOT_os_now               lang.FnFunc0
	fnD_cljg_DOT_os_cron_next         lang.FnFunc2
	fnD_cljg_DOT_os_soonest           lang.FnFunc2
	fnD_cljg_DOT_os_run_job           lang.FnFunc1
	fnD_cljg_DOT_os_service           lang.FnFunc1
	fnD_cljg_DOT_os_service_install   lang.FnFunc1
	fnD_cljg_DOT_os_service_start     lang.FnFunc1
	fnD_cljg_DOT_os_service_stop      lang.FnFunc1
	fnD_cljg_DOT_os_service_uninstall lang.FnFunc1
	fnD_cljg_DOT_os_service_status    lang.FnFunc1
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("cljg.os")), lang.VarFile, "cljg/os.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote cljg.os))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_cljg_DOT_os)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply1(tmp3, sym_clojure_DOT_core)
	_ = tmp4
	// (def now (clojure.core/fn ([] (-now-millis))))
	v_cljg_DOT_os_now.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(22), kw_column, int64(7), kw_end_line, int64(22), kw_end_column, int64(10), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "Current time as epoch milliseconds."))
	tmp5 := lang.FnFunc0(func() any {
		tmp6 := v_cljg_DOT_os_X_now_millis.Get()
		tmp7 := lang.Apply0(tmp6)
		return tmp7
	})
	tmp8 := &lang.NamedFn0{Name: "cljg.os/now", Expects: "0: []", F: tmp5}
	v_cljg_DOT_os_now.BindRoot(tmp8)
	fnD_cljg_DOT_os_now = tmp8.F
	v_cljg_DOT_os_now.SealDirect()
	_ = v_cljg_DOT_os_now
	// (def cron-next (clojure.core/fn ([expr from] (-cron-next expr from))))
	v_cljg_DOT_os_cron_next.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(27), kw_column, int64(7), kw_end_line, int64(27), kw_end_column, int64(16), kw_arglists, lang.NewList(lang.NewVector(sym_expr, sym_from)), kw_doc, "The next fire time (epoch ms) STRICTLY after `from` (epoch ms) for a 5-field\n  cron `expr`. Pure/deterministic — throws on a malformed expression."))
	tmp9 := lang.FnFunc2(func(expr10, from11 any) any {
		tmp12 := v_cljg_DOT_os_X_cron_next.Get()
		tmp13 := lang.Apply2(tmp12, expr10, from11)
		return tmp13
	})
	tmp14 := &lang.NamedFn2{Name: "cljg.os/cron-next", Expects: "2: [expr from]", F: tmp9}
	v_cljg_DOT_os_cron_next.BindRoot(tmp14)
	fnD_cljg_DOT_os_cron_next = tmp14.F
	v_cljg_DOT_os_cron_next.SealDirect()
	_ = v_cljg_DOT_os_cron_next
	// (def job (clojure.core/fn ([expr f] (job expr f {})) ([expr f opts] (merge {:cljg.os/job t…
	v_cljg_DOT_os_job.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(33), kw_column, int64(7), kw_end_line, int64(33), kw_end_column, int64(10), kw_arglists, lang.NewList(lang.NewVector(sym_expr, sym_f), lang.NewVector(sym_expr, sym_f, sym_opts)), kw_doc, "A scheduled job: a cron expression + a 0-arg fn to run each fire. opts may\n  carry :name (for errors). Usually passed to `run`."))
	tmp15 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 2:
			expr16 := args[0]
			_ = expr16
			f17 := args[1]
			_ = f17
			tmp18 := v_cljg_DOT_os_job.Get()
			tmp19 := lang.NewMap()
			tmp20 := lang.Apply3(tmp18, expr16, f17, tmp19)
			return tmp20
		case 3:
			expr21 := args[0]
			_ = expr21
			f22 := args[1]
			_ = f22
			opts23 := args[2]
			_ = opts23
			tmp24 := v_clojure_DOT_core_merge.Get()
			tmp25 := lang.NewMap(kw_cljg_DOT_os_SLASH_job, true, kw_cron, expr21, kw_fn, f22)
			tmp26 := lang.Apply2(tmp24, tmp25, opts23)
			return tmp26
		default:
			panic(lang.NewArityError(len(args), "cljg.os/job", "2: [expr f] or 3: [expr f opts]"))
		}
	})
	v_cljg_DOT_os_job.BindRoot(tmp15)
	_ = v_cljg_DOT_os_job
	// (def soonest (clojure.core/fn ([jobs from] (->> jobs (map (fn [j] [j (cron-next (:cron j) …
	v_cljg_DOT_os_soonest.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(40), kw_column, int64(8), kw_end_line, int64(40), kw_end_column, int64(15), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_jobs, sym_from)), kw_doc, "The [job next-ms] pair due first, given `from`."))
	tmp27 := lang.FnFunc2(func(jobs28, from29 any) any {
		tmp30 := v_clojure_DOT_core_first.Get()
		tmp31 := v_clojure_DOT_core_sort_by.Get()
		tmp32 := v_clojure_DOT_core_second.Get()
		tmp33 := v_clojure_DOT_core_map_.Get()
		tmp34 := lang.FnFunc1(func(j35 any) any {
			tmp36 := v_cljg_DOT_os_cron_next.Direct()
			var tmp37 any
			if !tmp36 {
				tmp37 = v_cljg_DOT_os_cron_next.Get()
			}
			tmp38 := lang.Apply1(kw_cron, j35)
			var tmp39 any
			if tmp36 {
				tmp39 = fnD_cljg_DOT_os_cron_next(tmp38, from29)
			} else {
				tmp39 = lang.Apply2(tmp37, tmp38, from29)
			}
			tmp40 := lang.NewVector(j35, tmp39)
			return tmp40
		})
		tmp41 := &lang.NamedFn1{Name: "fn", Expects: "1: [j]", F: tmp34}
		tmp42 := lang.Apply2(tmp33, tmp41, jobs28)
		tmp43 := lang.Apply2(tmp31, tmp32, tmp42)
		tmp44 := lang.Apply1(tmp30, tmp43)
		return tmp44
	})
	tmp45 := &lang.NamedFn2{Name: "cljg.os/soonest", Expects: "2: [jobs from]", F: tmp27}
	v_cljg_DOT_os_soonest.BindRoot(tmp45)
	fnD_cljg_DOT_os_soonest = tmp45.F
	v_cljg_DOT_os_soonest.SealDirect()
	_ = v_cljg_DOT_os_soonest
	// (def run-job (clojure.core/fn ([j] (try ((:fn j)) (catch Throwable e (binding [*out* *err*…
	v_cljg_DOT_os_run_job.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(48), kw_column, int64(8), kw_end_line, int64(48), kw_end_column, int64(15), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_j)), kw_doc, "Run one job's fn, converting a thrown error into a printed warning so one\n  bad tick never kills the scheduler."))
	tmp46 := lang.FnFunc1(func(j47 any) any {
		var tmp48 any
		_ = tmp48
		func() {
			defer func() {
				if r := recover(); r != nil {
					thrown := rt.Recover(r)
					if rt.CatchMatches("Throwable", thrown) {
						var e49 any = thrown
						_ = e49
						tmp50 := v_clojure_DOT_core_X_STAR_err_STAR_.Get()
						lang.PushThreadBindings(lang.NewMap(v_clojure_DOT_core_X_STAR_out_STAR_, tmp50))
						tmp51 := v_clojure_DOT_core_println_.Get()
						tmp52 := v_clojure_DOT_core_str.Get()
						var tmp53 any
						_ = tmp53
						{
							tmp54 := lang.Apply1(kw_name, j47)
							var or__2__auto__55 any = tmp54
							_ = or__2__auto__55
							var tmp56 any
							_ = tmp56
							if lang.IsTruthy(or__2__auto__55) {
								tmp56 = or__2__auto__55
							} else {
								tmp57 := lang.Apply1(kw_cron, j47)
								tmp56 = tmp57
							}
							tmp53 = tmp56
						}
						tmp58 := v_clojure_DOT_core_ex_message.Get()
						tmp59 := lang.Apply1(tmp58, e49)
						tmp60 := lang.Apply4(tmp52, "cljg.os: job ", tmp53, " failed: ", tmp59)
						tmp61 := lang.Apply1(tmp51, tmp60)
						var tmp62 any = tmp61
						lang.PopThreadBindings()
						tmp48 = tmp62
						return
					}
					panic(r)
				}
			}()
			tmp63 := lang.Apply1(kw_fn, j47)
			tmp64 := lang.Apply0(tmp63)
			tmp48 = tmp64
		}()
		return tmp48
	})
	tmp65 := &lang.NamedFn1{Name: "cljg.os/run-job", Expects: "1: [j]", F: tmp46}
	v_cljg_DOT_os_run_job.BindRoot(tmp65)
	fnD_cljg_DOT_os_run_job = tmp65.F
	v_cljg_DOT_os_run_job.SealDirect()
	_ = v_cljg_DOT_os_run_job
	// (def run (clojure.core/fn ([jobs] (run jobs {})) ([jobs opts] (-check-opts "cljg.os/run" o…
	v_cljg_DOT_os_run.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(57), kw_column, int64(7), kw_end_line, int64(57), kw_end_column, int64(10), kw_arglists, lang.NewList(lang.NewVector(sym_jobs), lang.NewVector(sym_jobs, sym_opts)), kw_doc, "Run the scheduler over `jobs` (job values), sleeping until the soonest due\n  fire, running every job due at that minute, and repeating. Blocking — a\n  daemon's main loop. opts:\n    :max-ticks n  stop after n fires (default: run forever; use for tests/one-shots)\n  Returns the number of ticks run."))
	tmp66 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			jobs67 := args[0]
			_ = jobs67
			tmp68 := v_cljg_DOT_os_run.Get()
			tmp69 := lang.NewMap()
			tmp70 := lang.Apply2(tmp68, jobs67, tmp69)
			return tmp70
		case 2:
			jobs71 := args[0]
			_ = jobs71
			opts72 := args[1]
			_ = opts72
			tmp73 := v_cljg_DOT_os_X_check_opts.Get()
			tmp74 := lang.NewVector(kw_max_ticks)
			tmp75 := lang.Apply3(tmp73, "cljg.os/run", opts72, tmp74)
			_ = tmp75
			var tmp76 any
			_ = tmp76
			{
				tmp77 := lang.Apply1(kw_max_ticks, opts72)
				var maxt78 any = tmp77
				_ = maxt78
				var tmp79 any
				_ = tmp79
				if !rt.CoreDirty() {
					var tmp80 int64
					_ = tmp80
					{
						var ticks81 int64 = int64(0)
						_ = ticks81
					loop82:
						for {
							var tmp83 any
							_ = tmp83
							{
								var and__1__auto__84 any = maxt78
								_ = and__1__auto__84
								var tmp85 any
								_ = tmp85
								if lang.IsTruthy(and__1__auto__84) {
									tmp86 := rt.GE2(v_clojure_DOT_core_X_GT__EQ_, ticks81, maxt78)
									tmp85 = tmp86
								} else {
									tmp85 = and__1__auto__84
								}
								tmp83 = tmp85
							}
							var tmp87 int64
							_ = tmp87
							if lang.IsTruthy(tmp83) {
								tmp87 = ticks81
							} else {
								var tmp88 any
								_ = tmp88
								{
									tmp89 := v_cljg_DOT_os_now.Direct()
									var tmp90 any
									if !tmp89 {
										tmp90 = v_cljg_DOT_os_now.Get()
									}
									var tmp91 any
									if tmp89 {
										tmp91 = fnD_cljg_DOT_os_now()
									} else {
										tmp91 = lang.Apply0(tmp90)
									}
									var from92 any = tmp91
									_ = from92
									tmp93 := v_cljg_DOT_os_soonest.Direct()
									var tmp94 any
									if !tmp93 {
										tmp94 = v_cljg_DOT_os_soonest.Get()
									}
									var tmp95 any
									if tmp93 {
										tmp95 = fnD_cljg_DOT_os_soonest(jobs71, from92)
									} else {
										tmp95 = lang.Apply2(tmp94, jobs71, from92)
									}
									var vec__16496 any = tmp95
									_ = vec__16496
									tmp97 := v_clojure_DOT_core_nth.Get()
									tmp98 := lang.Apply3(tmp97, vec__16496, int64(0), nil)
									var X_99 any = tmp98
									_ = X_99
									tmp100 := v_clojure_DOT_core_nth.Get()
									tmp101 := lang.Apply3(tmp100, vec__16496, int64(1), nil)
									var due_ms102 any = tmp101
									_ = due_ms102
									tmp103 := v_clojure_DOT_core_max_.Get()
									tmp104 := rt.Sub2(v_clojure_DOT_core_X_, due_ms102, from92)
									tmp105 := lang.Apply2(tmp103, int64(0), tmp104)
									var wait106 any = tmp105
									_ = wait106
									tmp107 := v_cljg_DOT_os_X_sleep_millis.Get()
									tmp108 := lang.Apply1(tmp107, wait106)
									_ = tmp108
									var tmp109 any
									_ = tmp109
									{
										tmp110 := v_clojure_DOT_core_seq.Get()
										tmp111 := lang.Apply1(tmp110, jobs71)
										var s__9__auto__112 any = tmp111
										_ = s__9__auto__112
									loop113:
										for {
											var tmp114 any
											_ = tmp114
											if lang.IsTruthy(s__9__auto__112) {
												var tmp115 any
												_ = tmp115
												{
													tmp116 := v_clojure_DOT_core_first.Get()
													tmp117 := lang.Apply1(tmp116, s__9__auto__112)
													var j118 any = tmp117
													_ = j118
													tmp119 := v_cljg_DOT_os_cron_next.Direct()
													var tmp120 any
													if !tmp119 {
														tmp120 = v_cljg_DOT_os_cron_next.Get()
													}
													tmp121 := lang.Apply1(kw_cron, j118)
													var tmp122 any
													if tmp119 {
														tmp122 = fnD_cljg_DOT_os_cron_next(tmp121, from92)
													} else {
														tmp122 = lang.Apply2(tmp120, tmp121, from92)
													}
													tmp123 := rt.EQBool(v_clojure_DOT_core_X_EQ_, due_ms102, tmp122)
													var tmp124 any
													_ = tmp124
													if tmp123 {
														tmp125 := v_cljg_DOT_os_run_job.Direct()
														var tmp126 any
														if !tmp125 {
															tmp126 = v_cljg_DOT_os_run_job.Get()
														}
														var tmp127 any
														if tmp125 {
															tmp127 = fnD_cljg_DOT_os_run_job(j118)
														} else {
															tmp127 = lang.Apply1(tmp126, j118)
														}
														tmp124 = tmp127
													} else {
														tmp124 = nil
													}
													_ = tmp124
													var tmp128 any
													_ = tmp128
													if lang.IsTruthy(true) {
														tmp129 := v_clojure_DOT_core_next.Get()
														tmp130 := lang.Apply1(tmp129, s__9__auto__112)
														var tmp131 any = tmp130
														s__9__auto__112 = tmp131
														continue loop113
													} else {
														tmp128 = nil
													}
													tmp115 = tmp128
												}
												tmp114 = tmp115
											} else {
												tmp114 = nil
											}
											tmp109 = tmp114
											break loop113
										}
									}
									_ = tmp109
									var tmp132 int64 = rt.IInc(ticks81)
									var tmp133 int64 = tmp132
									ticks81 = tmp133
									continue loop82
								}
							}
							tmp80 = tmp87
							break loop82
						}
					}
					tmp79 = tmp80
				} else {
					var tmp134 any
					_ = tmp134
					{
						var ticks135 any = int64(0)
						_ = ticks135
					loop136:
						for {
							var tmp137 any
							_ = tmp137
							{
								var and__1__auto__138 any = maxt78
								_ = and__1__auto__138
								var tmp139 any
								_ = tmp139
								if lang.IsTruthy(and__1__auto__138) {
									tmp140 := rt.GE2(v_clojure_DOT_core_X_GT__EQ_, ticks135, maxt78)
									tmp139 = tmp140
								} else {
									tmp139 = and__1__auto__138
								}
								tmp137 = tmp139
							}
							var tmp141 any
							_ = tmp141
							if lang.IsTruthy(tmp137) {
								tmp141 = ticks135
							} else {
								var tmp142 any
								_ = tmp142
								{
									tmp143 := v_cljg_DOT_os_now.Direct()
									var tmp144 any
									if !tmp143 {
										tmp144 = v_cljg_DOT_os_now.Get()
									}
									var tmp145 any
									if tmp143 {
										tmp145 = fnD_cljg_DOT_os_now()
									} else {
										tmp145 = lang.Apply0(tmp144)
									}
									var from146 any = tmp145
									_ = from146
									tmp147 := v_cljg_DOT_os_soonest.Direct()
									var tmp148 any
									if !tmp147 {
										tmp148 = v_cljg_DOT_os_soonest.Get()
									}
									var tmp149 any
									if tmp147 {
										tmp149 = fnD_cljg_DOT_os_soonest(jobs71, from146)
									} else {
										tmp149 = lang.Apply2(tmp148, jobs71, from146)
									}
									var vec__164150 any = tmp149
									_ = vec__164150
									tmp151 := v_clojure_DOT_core_nth.Get()
									tmp152 := lang.Apply3(tmp151, vec__164150, int64(0), nil)
									var X_153 any = tmp152
									_ = X_153
									tmp154 := v_clojure_DOT_core_nth.Get()
									tmp155 := lang.Apply3(tmp154, vec__164150, int64(1), nil)
									var due_ms156 any = tmp155
									_ = due_ms156
									tmp157 := v_clojure_DOT_core_max_.Get()
									tmp158 := rt.Sub2(v_clojure_DOT_core_X_, due_ms156, from146)
									tmp159 := lang.Apply2(tmp157, int64(0), tmp158)
									var wait160 any = tmp159
									_ = wait160
									tmp161 := v_cljg_DOT_os_X_sleep_millis.Get()
									tmp162 := lang.Apply1(tmp161, wait160)
									_ = tmp162
									var tmp163 any
									_ = tmp163
									{
										tmp164 := v_clojure_DOT_core_seq.Get()
										tmp165 := lang.Apply1(tmp164, jobs71)
										var s__9__auto__166 any = tmp165
										_ = s__9__auto__166
									loop167:
										for {
											var tmp168 any
											_ = tmp168
											if lang.IsTruthy(s__9__auto__166) {
												var tmp169 any
												_ = tmp169
												{
													tmp170 := v_clojure_DOT_core_first.Get()
													tmp171 := lang.Apply1(tmp170, s__9__auto__166)
													var j172 any = tmp171
													_ = j172
													tmp173 := v_cljg_DOT_os_cron_next.Direct()
													var tmp174 any
													if !tmp173 {
														tmp174 = v_cljg_DOT_os_cron_next.Get()
													}
													tmp175 := lang.Apply1(kw_cron, j172)
													var tmp176 any
													if tmp173 {
														tmp176 = fnD_cljg_DOT_os_cron_next(tmp175, from146)
													} else {
														tmp176 = lang.Apply2(tmp174, tmp175, from146)
													}
													tmp177 := rt.EQBool(v_clojure_DOT_core_X_EQ_, due_ms156, tmp176)
													var tmp178 any
													_ = tmp178
													if tmp177 {
														tmp179 := v_cljg_DOT_os_run_job.Direct()
														var tmp180 any
														if !tmp179 {
															tmp180 = v_cljg_DOT_os_run_job.Get()
														}
														var tmp181 any
														if tmp179 {
															tmp181 = fnD_cljg_DOT_os_run_job(j172)
														} else {
															tmp181 = lang.Apply1(tmp180, j172)
														}
														tmp178 = tmp181
													} else {
														tmp178 = nil
													}
													_ = tmp178
													var tmp182 any
													_ = tmp182
													if lang.IsTruthy(true) {
														tmp183 := v_clojure_DOT_core_next.Get()
														tmp184 := lang.Apply1(tmp183, s__9__auto__166)
														var tmp185 any = tmp184
														s__9__auto__166 = tmp185
														continue loop167
													} else {
														tmp182 = nil
													}
													tmp169 = tmp182
												}
												tmp168 = tmp169
											} else {
												tmp168 = nil
											}
											tmp163 = tmp168
											break loop167
										}
									}
									_ = tmp163
									tmp186 := v_clojure_DOT_core_inc.Get()
									tmp187 := lang.Apply1(tmp186, ticks135)
									var tmp188 any = tmp187
									ticks135 = tmp188
									continue loop136
								}
							}
							tmp134 = tmp141
							break loop136
						}
					}
					tmp79 = tmp134
				}
				tmp76 = tmp79
			}
			return tmp76
		default:
			panic(lang.NewArityError(len(args), "cljg.os/run", "1: [jobs] or 2: [jobs opts]"))
		}
	})
	v_cljg_DOT_os_run.BindRoot(tmp66)
	_ = v_cljg_DOT_os_run
	// (def service (clojure.core/fn ([m] (merge {:cljg.os/service true, :scope :user} m))))
	v_cljg_DOT_os_service.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(86), kw_column, int64(7), kw_end_line, int64(86), kw_end_column, int64(14), kw_arglists, lang.NewList(lang.NewVector(sym_m)), kw_doc, "A service spec. Keys: :name (required), :exec (binary path, required),\n  :args [..], :description, :env {..}, :working-dir, :scope (:user default |\n  :system — :system needs root on Linux)."))
	tmp189 := lang.FnFunc1(func(m190 any) any {
		tmp191 := v_clojure_DOT_core_merge.Get()
		tmp192 := lang.NewMap(kw_cljg_DOT_os_SLASH_service, true, kw_scope, kw_user)
		tmp193 := lang.Apply2(tmp191, tmp192, m190)
		return tmp193
	})
	tmp194 := &lang.NamedFn1{Name: "cljg.os/service", Expects: "1: [m]", F: tmp189}
	v_cljg_DOT_os_service.BindRoot(tmp194)
	fnD_cljg_DOT_os_service = tmp194.F
	v_cljg_DOT_os_service.SealDirect()
	_ = v_cljg_DOT_os_service
	// (def service-unit (clojure.core/fn ([spec] (-service-render spec "")) ([spec os] (-service…
	v_cljg_DOT_os_service_unit.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(93), kw_column, int64(7), kw_end_line, int64(93), kw_end_column, int64(19), kw_arglists, lang.NewList(lang.NewVector(sym_spec), lang.NewVector(sym_spec, sym_os)), kw_doc, "Render the exact platform service definition text (systemd unit / launchd\n  plist) install would write for `spec`. Pure — good for review and tests.\n  Optional `os` (\"linux\"/\"darwin\"/\"windows\") cross-renders for a target\n  other than the host; Windows returns \"\" (its SCM is not file-based)."))
	tmp195 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			spec196 := args[0]
			_ = spec196
			tmp197 := v_cljg_DOT_os_X_service_render.Get()
			tmp198 := lang.Apply2(tmp197, spec196, "")
			return tmp198
		case 2:
			spec199 := args[0]
			_ = spec199
			os200 := args[1]
			_ = os200
			tmp201 := v_cljg_DOT_os_X_service_render.Get()
			tmp202 := lang.Apply2(tmp201, spec199, os200)
			return tmp202
		default:
			panic(lang.NewArityError(len(args), "cljg.os/service-unit", "1: [spec] or 2: [spec os]"))
		}
	})
	v_cljg_DOT_os_service_unit.BindRoot(tmp195)
	_ = v_cljg_DOT_os_service_unit
	// (def service-install (clojure.core/fn ([spec] (-service-install spec) nil)))
	v_cljg_DOT_os_service_install.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(101), kw_column, int64(7), kw_end_line, int64(101), kw_end_column, int64(22), kw_arglists, lang.NewList(lang.NewVector(sym_spec)), kw_doc, "Install `spec` as an OS service on the current platform (write the unit/\n  plist + enable via systemctl/launchctl, or sc.exe on Windows) and start it.\n  Returns nil. Needs the platform's privileges (:user scope avoids root on\n  Linux)."))
	tmp203 := lang.FnFunc1(func(spec204 any) any {
		tmp205 := v_cljg_DOT_os_X_service_install.Get()
		tmp206 := lang.Apply1(tmp205, spec204)
		_ = tmp206
		return nil
	})
	tmp207 := &lang.NamedFn1{Name: "cljg.os/service-install", Expects: "1: [spec]", F: tmp203}
	v_cljg_DOT_os_service_install.BindRoot(tmp207)
	fnD_cljg_DOT_os_service_install = tmp207.F
	v_cljg_DOT_os_service_install.SealDirect()
	_ = v_cljg_DOT_os_service_install
	// (def service-start (clojure.core/fn ([name] (-service-op "start" name) nil)))
	v_cljg_DOT_os_service_start.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(110), kw_column, int64(7), kw_end_line, int64(110), kw_end_column, int64(20), kw_arglists, lang.NewList(lang.NewVector(sym_name)), kw_doc, "Start an installed service by name."))
	tmp208 := lang.FnFunc1(func(name209 any) any {
		tmp210 := v_cljg_DOT_os_X_service_op.Get()
		tmp211 := lang.Apply2(tmp210, "start", name209)
		_ = tmp211
		return nil
	})
	tmp212 := &lang.NamedFn1{Name: "cljg.os/service-start", Expects: "1: [name]", F: tmp208}
	v_cljg_DOT_os_service_start.BindRoot(tmp212)
	fnD_cljg_DOT_os_service_start = tmp212.F
	v_cljg_DOT_os_service_start.SealDirect()
	_ = v_cljg_DOT_os_service_start
	// (def service-stop (clojure.core/fn ([name] (-service-op "stop" name) nil)))
	v_cljg_DOT_os_service_stop.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(111), kw_column, int64(7), kw_end_line, int64(111), kw_end_column, int64(19), kw_arglists, lang.NewList(lang.NewVector(sym_name)), kw_doc, "Stop a running service by name."))
	tmp213 := lang.FnFunc1(func(name214 any) any {
		tmp215 := v_cljg_DOT_os_X_service_op.Get()
		tmp216 := lang.Apply2(tmp215, "stop", name214)
		_ = tmp216
		return nil
	})
	tmp217 := &lang.NamedFn1{Name: "cljg.os/service-stop", Expects: "1: [name]", F: tmp213}
	v_cljg_DOT_os_service_stop.BindRoot(tmp217)
	fnD_cljg_DOT_os_service_stop = tmp217.F
	v_cljg_DOT_os_service_stop.SealDirect()
	_ = v_cljg_DOT_os_service_stop
	// (def service-uninstall (clojure.core/fn ([name] (-service-op "uninstall" name) nil)))
	v_cljg_DOT_os_service_uninstall.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(112), kw_column, int64(7), kw_end_line, int64(112), kw_end_column, int64(24), kw_arglists, lang.NewList(lang.NewVector(sym_name)), kw_doc, "Stop + remove a service by name."))
	tmp218 := lang.FnFunc1(func(name219 any) any {
		tmp220 := v_cljg_DOT_os_X_service_op.Get()
		tmp221 := lang.Apply2(tmp220, "uninstall", name219)
		_ = tmp221
		return nil
	})
	tmp222 := &lang.NamedFn1{Name: "cljg.os/service-uninstall", Expects: "1: [name]", F: tmp218}
	v_cljg_DOT_os_service_uninstall.BindRoot(tmp222)
	fnD_cljg_DOT_os_service_uninstall = tmp222.F
	v_cljg_DOT_os_service_uninstall.SealDirect()
	_ = v_cljg_DOT_os_service_uninstall
	// (def service-status (clojure.core/fn ([name] (-service-op "status" name))))
	v_cljg_DOT_os_service_status.SetMeta(lang.NewMap(kw_file, "cljg/os.cljg", kw_line, int64(114), kw_column, int64(7), kw_end_line, int64(114), kw_end_column, int64(21), kw_arglists, lang.NewList(lang.NewVector(sym_name)), kw_doc, "The platform status string for a service (e.g. \"active\"), or nil if it is\n  not installed / not running."))
	tmp223 := lang.FnFunc1(func(name224 any) any {
		tmp225 := v_cljg_DOT_os_X_service_op.Get()
		tmp226 := lang.Apply2(tmp225, "status", name224)
		return tmp226
	})
	tmp227 := &lang.NamedFn1{Name: "cljg.os/service-status", Expects: "1: [name]", F: tmp223}
	v_cljg_DOT_os_service_status.BindRoot(tmp227)
	fnD_cljg_DOT_os_service_status = tmp227.F
	v_cljg_DOT_os_service_status.SealDirect()
	_ = v_cljg_DOT_os_service_status
}
