;; Golden generator for the S8 syntax-quote conformance harness.
;;
;; For each corpus input, evaluates (pr-str (read-string INPUT)) so the reader's
;; syntax-quote expansion is printed UNEVALUATED (read-string performs the
;; expansion — a pure data->data transform — pr-str just prints the data).
;;
;; Emits RAW records to stdout (gensym numbers are per-JVM-run); the Go tool
;; cmd/mkgolden normalizes them into golden.txt. Record format:
;;
;;   IN: <input>
;;   OK: <pr-str of expansion>     ; or  ERR: <exception simple class name>
;;   <blank line>
;;
;; Run:  clojure -M gen_golden.clj corpus.txt > golden.raw.txt
;; NOTE: runs in ns `user` — unqualified symbols resolve to user/<sym>.

(require '[clojure.string :as str])

(let [path   (or (first *command-line-args*) "corpus.txt")
      inputs (->> (str/split-lines (slurp path))
                  (remove #(or (str/blank? %) (str/starts-with? % ";;"))))]
  (assert (= "user" (str *ns*)) "golden must be generated from ns user")
  (println (str ";; GENERATED by gen_golden.clj — Clojure " (clojure-version)
                " — ns " *ns* " — RAW (unnormalized gensym ids)"))
  (println)
  (doseq [in inputs]
    (let [res (try
                {:ok (pr-str (read-string in))}
                (catch Exception e
                  {:err (.getSimpleName (class e))}))]
      (println (str "IN: " in))
      (if (contains? res :ok)
        (println (str "OK: " (:ok res)))
        (println (str "ERR: " (:err res))))
      (println))))
