// Code generated by cljgo build. DO NOT EDIT.

package cljgnethttp

import (
	rt "github.com/muthuishere/cljgo/pkg/emit/rt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_arglists                               = lang.InternKeywordString("arglists")
	kw_as                                     = lang.InternKeywordString("as")
	kw_body                                   = lang.InternKeywordString("body")
	kw_column                                 = lang.InternKeywordString("column")
	kw_delete_                                = lang.InternKeywordString("delete")
	kw_doc                                    = lang.InternKeywordString("doc")
	kw_edn                                    = lang.InternKeywordString("edn")
	kw_else_                                  = lang.InternKeywordString("else")
	kw_end_column                             = lang.InternKeywordString("end-column")
	kw_end_line                               = lang.InternKeywordString("end-line")
	kw_err                                    = lang.InternKeywordString("err")
	kw_exclude                                = lang.InternKeywordString("exclude")
	kw_file                                   = lang.InternKeywordString("file")
	kw_form                                   = lang.InternKeywordString("form")
	kw_get                                    = lang.InternKeywordString("get")
	kw_head                                   = lang.InternKeywordString("head")
	kw_headers                                = lang.InternKeywordString("headers")
	kw_json                                   = lang.InternKeywordString("json")
	kw_line                                   = lang.InternKeywordString("line")
	kw_method                                 = lang.InternKeywordString("method")
	kw_ok_QMARK_                              = lang.InternKeywordString("ok?")
	kw_patch                                  = lang.InternKeywordString("patch")
	kw_post                                   = lang.InternKeywordString("post")
	kw_private                                = lang.InternKeywordString("private")
	kw_put                                    = lang.InternKeywordString("put")
	kw_query                                  = lang.InternKeywordString("query")
	kw_retry                                  = lang.InternKeywordString("retry")
	kw_status                                 = lang.InternKeywordString("status")
	kw_stream                                 = lang.InternKeywordString("stream")
	kw_timeout                                = lang.InternKeywordString("timeout")
	kw_timeout_ms                             = lang.InternKeywordString("timeout-ms")
	kw_url                                    = lang.InternKeywordString("url")
	kw_v                                      = lang.InternKeywordString("v")
	sym_as                                    = lang.NewSymbol("as")
	sym_body                                  = lang.NewSymbol("body")
	sym_cljg_DOT_net_DOT_http                 = lang.NewSymbol("cljg.net.http")
	sym_clojure_DOT_core                      = lang.NewSymbol("clojure.core")
	sym_clojure_DOT_string                    = lang.NewSymbol("clojure.string")
	sym_ctype                                 = lang.NewSymbol("ctype")
	sym_get                                   = lang.NewSymbol("get")
	sym_headers                               = lang.NewSymbol("headers")
	sym_m                                     = lang.NewSymbol("m")
	sym_method                                = lang.NewSymbol("method")
	sym_opts                                  = lang.NewSymbol("opts")
	sym_resp                                  = lang.NewSymbol("resp")
	sym_str                                   = lang.NewSymbol("str")
	sym_timeout                               = lang.NewSymbol("timeout")
	sym_url                                   = lang.NewSymbol("url")
	v_cljg_DOT_net_DOT_http_X_http_do         = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("-http-do")).SetPrivate()
	v_cljg_DOT_net_DOT_http_X_http_stream     = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("-http-stream")).SetPrivate()
	v_cljg_DOT_net_DOT_http_X_json_decode     = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("-json-decode")).SetPrivate()
	v_cljg_DOT_net_DOT_http_X_json_encode     = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("-json-encode")).SetPrivate()
	v_cljg_DOT_net_DOT_http_X_url_encode      = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("-url-encode")).SetPrivate()
	v_cljg_DOT_net_DOT_http_body_PLUS_type    = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("body+type")).SetPrivate()
	v_cljg_DOT_net_DOT_http_default_timeout   = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("default-timeout")).SetPrivate()
	v_cljg_DOT_net_DOT_http_delete_           = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("delete"))
	v_cljg_DOT_net_DOT_http_do_once           = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("do-once")).SetPrivate()
	v_cljg_DOT_net_DOT_http_edn_body          = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("edn-body"))
	v_cljg_DOT_net_DOT_http_encode_query      = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("encode-query")).SetPrivate()
	v_cljg_DOT_net_DOT_http_get               = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("get"))
	v_cljg_DOT_net_DOT_http_head              = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("head"))
	v_cljg_DOT_net_DOT_http_json_body         = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("json-body"))
	v_cljg_DOT_net_DOT_http_patch             = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("patch"))
	v_cljg_DOT_net_DOT_http_post              = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("post"))
	v_cljg_DOT_net_DOT_http_put               = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("put"))
	v_cljg_DOT_net_DOT_http_request           = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("request"))
	v_cljg_DOT_net_DOT_http_verb              = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("verb")).SetPrivate()
	v_cljg_DOT_net_DOT_http_with_content_type = lang.InternVarName(lang.NewSymbol("cljg.net.http"), lang.NewSymbol("with-content-type")).SetPrivate()
	v_clojure_DOT_core_X_EQ_                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("="))
	v_clojure_DOT_core_X_GT_                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol(">"))
	v_clojure_DOT_core_X_GT__EQ_              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol(">="))
	v_clojure_DOT_core_X_LT__EQ_              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("<="))
	v_clojure_DOT_core_assoc                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("assoc"))
	v_clojure_DOT_core_contains_QMARK_        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("contains?"))
	v_clojure_DOT_core_dec                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("dec"))
	v_clojure_DOT_core_in_ns                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_inc                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("inc"))
	v_clojure_DOT_core_map_                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("map"))
	v_clojure_DOT_core_name                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("name"))
	v_clojure_DOT_core_not                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("not"))
	v_clojure_DOT_core_not_EQ_                = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("not="))
	v_clojure_DOT_core_nth                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("nth"))
	v_clojure_DOT_core_pr_str                 = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("pr-str"))
	v_clojure_DOT_core_refer                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
	v_clojure_DOT_core_require                = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("require"))
	v_clojure_DOT_core_seq                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("seq"))
	v_clojure_DOT_core_some                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("some"))
	v_clojure_DOT_core_str                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("str"))
	v_clojure_DOT_edn_read_string             = lang.InternVarName(lang.NewSymbol("clojure.edn"), lang.NewSymbol("read-string"))
	v_clojure_DOT_string_join                 = lang.InternVarName(lang.NewSymbol("clojure.string"), lang.NewSymbol("join"))
	v_clojure_DOT_string_lower_case           = lang.InternVarName(lang.NewSymbol("clojure.string"), lang.NewSymbol("lower-case"))
	v_clojure_DOT_string_upper_case           = lang.InternVarName(lang.NewSymbol("clojure.string"), lang.NewSymbol("upper-case"))
)

var (
	fnD_cljg_DOT_net_DOT_http_encode_query      lang.FnFunc1
	fnD_cljg_DOT_net_DOT_http_body_PLUS_type    lang.FnFunc1
	fnD_cljg_DOT_net_DOT_http_with_content_type lang.FnFunc2
	fnD_cljg_DOT_net_DOT_http_request           lang.FnFunc1
	fnD_cljg_DOT_net_DOT_http_verb              lang.FnFunc3
	fnD_cljg_DOT_net_DOT_http_json_body         lang.FnFunc1
	fnD_cljg_DOT_net_DOT_http_edn_body          lang.FnFunc1
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("cljg.net.http")), lang.VarFile, "cljg/net_http.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote cljg.net.http))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_cljg_DOT_net_DOT_http)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core) :exclude (quote [get]))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply3(tmp3, sym_clojure_DOT_core, kw_exclude, lang.NewVector(sym_get))
	_ = tmp4
	// (require (quote [clojure.string :as str]))
	tmp5 := v_clojure_DOT_core_require.Get()
	tmp6 := lang.Apply1(tmp5, lang.NewVector(sym_clojure_DOT_string, kw_as, sym_str))
	_ = tmp6
	// (def default-timeout 30000)
	v_cljg_DOT_net_DOT_http_default_timeout.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(28), kw_column, int64(6), kw_end_line, int64(28), kw_end_column, int64(31), kw_private, true))
	v_cljg_DOT_net_DOT_http_default_timeout.BindRoot(int64(30000))
	_ = v_cljg_DOT_net_DOT_http_default_timeout
	// (def encode-query (clojure.core/fn ([m] (if (seq m) (str "?" (str/join "&" (map (fn [[k v]…
	v_cljg_DOT_net_DOT_http_encode_query.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(32), kw_column, int64(8), kw_end_line, int64(32), kw_end_column, int64(20), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_m)), kw_doc, "Build a `?a=b&c=d` string from a map (values url-encoded), or \"\" if empty."))
	tmp7 := lang.FnFunc1(func(m8 any) any {
		tmp9 := v_clojure_DOT_core_seq.Get()
		tmp10 := lang.Apply1(tmp9, m8)
		var tmp11 any
		_ = tmp11
		if lang.IsTruthy(tmp10) {
			tmp12 := v_clojure_DOT_core_str.Get()
			tmp13 := v_clojure_DOT_string_join.Get()
			tmp14 := v_clojure_DOT_core_map_.Get()
			tmp15 := lang.FnFunc1(func(p__14716 any) any {
				var tmp17 any
				_ = tmp17
				{
					var vec__14818 any = p__14716
					_ = vec__14818
					tmp19 := v_clojure_DOT_core_nth.Get()
					tmp20 := lang.Apply3(tmp19, vec__14818, int64(0), nil)
					var k21 any = tmp20
					_ = k21
					tmp22 := v_clojure_DOT_core_nth.Get()
					tmp23 := lang.Apply3(tmp22, vec__14818, int64(1), nil)
					var v24 any = tmp23
					_ = v24
					tmp25 := v_clojure_DOT_core_str.Get()
					tmp26 := v_cljg_DOT_net_DOT_http_X_url_encode.Get()
					tmp27 := v_clojure_DOT_core_name.Get()
					tmp28 := lang.Apply1(tmp27, k21)
					tmp29 := lang.Apply1(tmp26, tmp28)
					tmp30 := v_cljg_DOT_net_DOT_http_X_url_encode.Get()
					tmp31 := v_clojure_DOT_core_str.Get()
					tmp32 := lang.Apply1(tmp31, v24)
					tmp33 := lang.Apply1(tmp30, tmp32)
					tmp34 := lang.Apply3(tmp25, tmp29, "=", tmp33)
					tmp17 = tmp34
				}
				return tmp17
			})
			tmp35 := &lang.NamedFn1{Name: "fn", Expects: "1: [p__147]", F: tmp15}
			tmp36 := lang.Apply2(tmp14, tmp35, m8)
			tmp37 := lang.Apply2(tmp13, "&", tmp36)
			tmp38 := lang.Apply2(tmp12, "?", tmp37)
			tmp11 = tmp38
		} else {
			tmp11 = ""
		}
		return tmp11
	})
	tmp39 := &lang.NamedFn1{Name: "cljg.net.http/encode-query", Expects: "1: [m]", F: tmp7}
	v_cljg_DOT_net_DOT_http_encode_query.BindRoot(tmp39)
	fnD_cljg_DOT_net_DOT_http_encode_query = tmp39.F
	v_cljg_DOT_net_DOT_http_encode_query.SealDirect()
	_ = v_cljg_DOT_net_DOT_http_encode_query
	// (def body+type (clojure.core/fn ([opts] (cond (contains? opts :body) [(str (:body opts)) n…
	v_cljg_DOT_net_DOT_http_body_PLUS_type.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(41), kw_column, int64(8), kw_end_line, int64(41), kw_end_column, int64(17), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_opts)), kw_doc, "From the request opts, return [body-string content-type-or-nil]. Exactly one\n  of :body/:json/:edn/:form is honored (in that precedence)."))
	tmp40 := lang.FnFunc1(func(opts41 any) any {
		tmp42 := v_clojure_DOT_core_contains_QMARK_.Get()
		tmp43 := lang.Apply2(tmp42, opts41, kw_body)
		var tmp44 any
		_ = tmp44
		if lang.IsTruthy(tmp43) {
			tmp45 := v_clojure_DOT_core_str.Get()
			tmp46 := lang.Apply1(kw_body, opts41)
			tmp47 := lang.Apply1(tmp45, tmp46)
			tmp48 := lang.NewVector(tmp47, nil)
			tmp44 = tmp48
		} else {
			tmp49 := v_clojure_DOT_core_contains_QMARK_.Get()
			tmp50 := lang.Apply2(tmp49, opts41, kw_json)
			var tmp51 any
			_ = tmp51
			if lang.IsTruthy(tmp50) {
				tmp52 := v_cljg_DOT_net_DOT_http_X_json_encode.Get()
				tmp53 := lang.Apply1(kw_json, opts41)
				tmp54 := lang.Apply1(tmp52, tmp53)
				tmp55 := lang.NewVector(tmp54, "application/json")
				tmp51 = tmp55
			} else {
				tmp56 := v_clojure_DOT_core_contains_QMARK_.Get()
				tmp57 := lang.Apply2(tmp56, opts41, kw_edn)
				var tmp58 any
				_ = tmp58
				if lang.IsTruthy(tmp57) {
					tmp59 := v_clojure_DOT_core_pr_str.Get()
					tmp60 := lang.Apply1(kw_edn, opts41)
					tmp61 := lang.Apply1(tmp59, tmp60)
					tmp62 := lang.NewVector(tmp61, "application/edn")
					tmp58 = tmp62
				} else {
					tmp63 := v_clojure_DOT_core_contains_QMARK_.Get()
					tmp64 := lang.Apply2(tmp63, opts41, kw_form)
					var tmp65 any
					_ = tmp65
					if lang.IsTruthy(tmp64) {
						tmp66 := v_clojure_DOT_string_join.Get()
						tmp67 := v_clojure_DOT_core_map_.Get()
						tmp68 := lang.FnFunc1(func(p__15169 any) any {
							var tmp70 any
							_ = tmp70
							{
								var vec__15271 any = p__15169
								_ = vec__15271
								tmp72 := v_clojure_DOT_core_nth.Get()
								tmp73 := lang.Apply3(tmp72, vec__15271, int64(0), nil)
								var k74 any = tmp73
								_ = k74
								tmp75 := v_clojure_DOT_core_nth.Get()
								tmp76 := lang.Apply3(tmp75, vec__15271, int64(1), nil)
								var v77 any = tmp76
								_ = v77
								tmp78 := v_clojure_DOT_core_str.Get()
								tmp79 := v_cljg_DOT_net_DOT_http_X_url_encode.Get()
								tmp80 := v_clojure_DOT_core_name.Get()
								tmp81 := lang.Apply1(tmp80, k74)
								tmp82 := lang.Apply1(tmp79, tmp81)
								tmp83 := v_cljg_DOT_net_DOT_http_X_url_encode.Get()
								tmp84 := v_clojure_DOT_core_str.Get()
								tmp85 := lang.Apply1(tmp84, v77)
								tmp86 := lang.Apply1(tmp83, tmp85)
								tmp87 := lang.Apply3(tmp78, tmp82, "=", tmp86)
								tmp70 = tmp87
							}
							return tmp70
						})
						tmp88 := &lang.NamedFn1{Name: "fn", Expects: "1: [p__151]", F: tmp68}
						tmp89 := lang.Apply1(kw_form, opts41)
						tmp90 := lang.Apply2(tmp67, tmp88, tmp89)
						tmp91 := lang.Apply2(tmp66, "&", tmp90)
						tmp92 := lang.NewVector(tmp91, "application/x-www-form-urlencoded")
						tmp65 = tmp92
					} else {
						var tmp93 any
						_ = tmp93
						if lang.IsTruthy(kw_else_) {
							tmp94 := lang.NewVector(nil, nil)
							tmp93 = tmp94
						} else {
							tmp93 = nil
						}
						tmp65 = tmp93
					}
					tmp58 = tmp65
				}
				tmp51 = tmp58
			}
			tmp44 = tmp51
		}
		return tmp44
	})
	tmp95 := &lang.NamedFn1{Name: "cljg.net.http/body+type", Expects: "1: [opts]", F: tmp40}
	v_cljg_DOT_net_DOT_http_body_PLUS_type.BindRoot(tmp95)
	fnD_cljg_DOT_net_DOT_http_body_PLUS_type = tmp95.F
	v_cljg_DOT_net_DOT_http_body_PLUS_type.SealDirect()
	_ = v_cljg_DOT_net_DOT_http_body_PLUS_type
	// (def with-content-type (clojure.core/fn ([headers ctype] (if (and ctype (not (some (fn [[k…
	v_cljg_DOT_net_DOT_http_with_content_type.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(55), kw_column, int64(8), kw_end_line, int64(55), kw_end_column, int64(25), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_headers, sym_ctype))))
	tmp96 := lang.FnFunc2(func(headers97, ctype98 any) any {
		var tmp99 any
		_ = tmp99
		{
			var and__1__auto__100 any = ctype98
			_ = and__1__auto__100
			var tmp101 any
			_ = tmp101
			if lang.IsTruthy(and__1__auto__100) {
				tmp102 := v_clojure_DOT_core_not.Get()
				tmp103 := v_clojure_DOT_core_some.Get()
				tmp104 := lang.FnFunc1(func(p__155105 any) any {
					var tmp106 any
					_ = tmp106
					{
						var vec__156107 any = p__155105
						_ = vec__156107
						tmp108 := v_clojure_DOT_core_nth.Get()
						tmp109 := lang.Apply3(tmp108, vec__156107, int64(0), nil)
						var k110 any = tmp109
						_ = k110
						tmp111 := v_clojure_DOT_core_nth.Get()
						tmp112 := lang.Apply3(tmp111, vec__156107, int64(1), nil)
						var X_113 any = tmp112
						_ = X_113
						tmp114 := v_clojure_DOT_string_lower_case.Get()
						tmp115 := v_clojure_DOT_core_name.Get()
						tmp116 := lang.Apply1(tmp115, k110)
						tmp117 := lang.Apply1(tmp114, tmp116)
						tmp118 := rt.EQ2(v_clojure_DOT_core_X_EQ_, "content-type", tmp117)
						tmp106 = tmp118
					}
					return tmp106
				})
				tmp119 := &lang.NamedFn1{Name: "fn", Expects: "1: [p__155]", F: tmp104}
				tmp120 := lang.Apply2(tmp103, tmp119, headers97)
				tmp121 := lang.Apply1(tmp102, tmp120)
				tmp101 = tmp121
			} else {
				tmp101 = and__1__auto__100
			}
			tmp99 = tmp101
		}
		var tmp122 any
		_ = tmp122
		if lang.IsTruthy(tmp99) {
			tmp123 := v_clojure_DOT_core_assoc.Get()
			tmp124 := lang.Apply3(tmp123, headers97, "Content-Type", ctype98)
			tmp122 = tmp124
		} else {
			tmp122 = headers97
		}
		return tmp122
	})
	tmp125 := &lang.NamedFn2{Name: "cljg.net.http/with-content-type", Expects: "2: [headers ctype]", F: tmp96}
	v_cljg_DOT_net_DOT_http_with_content_type.BindRoot(tmp125)
	fnD_cljg_DOT_net_DOT_http_with_content_type = tmp125.F
	v_cljg_DOT_net_DOT_http_with_content_type.SealDirect()
	_ = v_cljg_DOT_net_DOT_http_with_content_type
	// (def do-once (clojure.core/fn ([method url headers body timeout as] (let [shim (if (= as :…
	v_cljg_DOT_net_DOT_http_do_once.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(62), kw_column, int64(8), kw_end_line, int64(62), kw_end_column, int64(15), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_method, sym_url, sym_headers, sym_body, sym_timeout, sym_as)), kw_doc, "One request → a response map with :ok? added. With `as` = :stream the :body is\n  a cljg.stream READABLE handle over the LIVE response body (constant-memory\n  streaming; the caller closes it) instead of a fully-buffered string; any other\n  `as` keeps the default buffered-string body."))
	tmp126 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 6:
			method127 := args[0]
			_ = method127
			url128 := args[1]
			_ = url128
			headers129 := args[2]
			_ = headers129
			body130 := args[3]
			_ = body130
			timeout131 := args[4]
			_ = timeout131
			as132 := args[5]
			_ = as132
			var tmp133 any
			_ = tmp133
			{
				tmp134 := rt.EQBool(v_clojure_DOT_core_X_EQ_, as132, kw_stream)
				var tmp135 any
				_ = tmp135
				if tmp134 {
					tmp136 := v_cljg_DOT_net_DOT_http_X_http_stream.Get()
					tmp135 = tmp136
				} else {
					tmp137 := v_cljg_DOT_net_DOT_http_X_http_do.Get()
					tmp135 = tmp137
				}
				var shim138 any = tmp135
				_ = shim138
				tmp139 := v_clojure_DOT_string_upper_case.Get()
				tmp140 := v_clojure_DOT_core_name.Get()
				tmp141 := lang.Apply1(tmp140, method127)
				tmp142 := lang.Apply1(tmp139, tmp141)
				var tmp143 any
				_ = tmp143
				{
					var or__2__auto__144 any = headers129
					_ = or__2__auto__144
					var tmp145 any
					_ = tmp145
					if lang.IsTruthy(or__2__auto__144) {
						tmp145 = or__2__auto__144
					} else {
						tmp146 := lang.NewMap()
						tmp145 = tmp146
					}
					tmp143 = tmp145
				}
				tmp147 := lang.Apply(shim138, []any{tmp142, url128, tmp143, body130, timeout131})
				var resp148 any = tmp147
				_ = resp148
				tmp149 := v_clojure_DOT_core_assoc.Get()
				tmp150 := v_clojure_DOT_core_X_LT__EQ_.Get()
				tmp151 := lang.Apply1(kw_status, resp148)
				tmp152 := lang.Apply3(tmp150, int64(200), tmp151, int64(299))
				tmp153 := lang.Apply3(tmp149, resp148, kw_ok_QMARK_, tmp152)
				tmp133 = tmp153
			}
			return tmp133
		default:
			panic(lang.NewArityError(len(args), "cljg.net.http/do-once", "6: [method url headers body timeout as]"))
		}
	})
	v_cljg_DOT_net_DOT_http_do_once.BindRoot(tmp126)
	_ = v_cljg_DOT_net_DOT_http_do_once
	// (def request (clojure.core/fn ([opts] (let [method (:method opts :get) url (str (:url opts…
	v_cljg_DOT_net_DOT_http_request.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(72), kw_column, int64(7), kw_end_line, int64(72), kw_end_column, int64(14), kw_arglists, lang.NewList(lang.NewVector(sym_opts)), kw_doc, "Perform an HTTP request. opts:\n    :method  keyword/string (default :get)   :url  the URL (or pass as 1st arg via the verbs)\n    :headers map {name value}                :query map → query string\n    :body    raw string | :json data | :edn data | :form map   (one; that precedence)\n    :timeout-ms ms (default 30000)           :retry n (default 0), backoff on transport error + 5xx\n                                             (:timeout is accepted as the older alias)\n    :as      :stream → :body is a cljg.stream readable handle over the live body\n             (opt-in; buffered string is the default)\n  Returns {:status :headers :body :ok?} — :body a string, or a cljg.stream\n  readable handle when :as :stream (the caller closes it). Retries re-raise the\n  last error / return the last 5xx after n attempts; a streaming response is not\n  retried on 5xx (its body handle is live), only on a transport error."))
	tmp154 := lang.FnFunc1(func(opts155 any) any {
		var tmp156 any
		_ = tmp156
		{
			tmp157 := lang.Apply2(kw_method, opts155, kw_get)
			var method158 any = tmp157
			_ = method158
			tmp159 := v_clojure_DOT_core_str.Get()
			tmp160 := lang.Apply1(kw_url, opts155)
			tmp161 := v_cljg_DOT_net_DOT_http_encode_query.Direct()
			var tmp162 any
			if !tmp161 {
				tmp162 = v_cljg_DOT_net_DOT_http_encode_query.Get()
			}
			tmp163 := lang.Apply1(kw_query, opts155)
			var tmp164 any
			if tmp161 {
				tmp164 = fnD_cljg_DOT_net_DOT_http_encode_query(tmp163)
			} else {
				tmp164 = lang.Apply1(tmp162, tmp163)
			}
			tmp165 := lang.Apply2(tmp159, tmp160, tmp164)
			var url166 any = tmp165
			_ = url166
			tmp167 := v_cljg_DOT_net_DOT_http_body_PLUS_type.Direct()
			var tmp168 any
			if !tmp167 {
				tmp168 = v_cljg_DOT_net_DOT_http_body_PLUS_type.Get()
			}
			var tmp169 any
			if tmp167 {
				tmp169 = fnD_cljg_DOT_net_DOT_http_body_PLUS_type(opts155)
			} else {
				tmp169 = lang.Apply1(tmp168, opts155)
			}
			var vec__159170 any = tmp169
			_ = vec__159170
			tmp171 := v_clojure_DOT_core_nth.Get()
			tmp172 := lang.Apply3(tmp171, vec__159170, int64(0), nil)
			var b173 any = tmp172
			_ = b173
			tmp174 := v_clojure_DOT_core_nth.Get()
			tmp175 := lang.Apply3(tmp174, vec__159170, int64(1), nil)
			var ct176 any = tmp175
			_ = ct176
			tmp177 := v_cljg_DOT_net_DOT_http_with_content_type.Direct()
			var tmp178 any
			if !tmp177 {
				tmp178 = v_cljg_DOT_net_DOT_http_with_content_type.Get()
			}
			var tmp179 any
			_ = tmp179
			{
				tmp180 := lang.Apply1(kw_headers, opts155)
				var or__2__auto__181 any = tmp180
				_ = or__2__auto__181
				var tmp182 any
				_ = tmp182
				if lang.IsTruthy(or__2__auto__181) {
					tmp182 = or__2__auto__181
				} else {
					tmp183 := lang.NewMap()
					tmp182 = tmp183
				}
				tmp179 = tmp182
			}
			var tmp184 any
			if tmp177 {
				tmp184 = fnD_cljg_DOT_net_DOT_http_with_content_type(tmp179, ct176)
			} else {
				tmp184 = lang.Apply2(tmp178, tmp179, ct176)
			}
			var headers185 any = tmp184
			_ = headers185
			var tmp186 any
			_ = tmp186
			{
				tmp187 := lang.Apply1(kw_timeout_ms, opts155)
				var or__2__auto__188 any = tmp187
				_ = or__2__auto__188
				var tmp189 any
				_ = tmp189
				if lang.IsTruthy(or__2__auto__188) {
					tmp189 = or__2__auto__188
				} else {
					var tmp190 any
					_ = tmp190
					{
						tmp191 := lang.Apply1(kw_timeout, opts155)
						var or__2__auto__192 any = tmp191
						_ = or__2__auto__192
						var tmp193 any
						_ = tmp193
						if lang.IsTruthy(or__2__auto__192) {
							tmp193 = or__2__auto__192
						} else {
							tmp194 := v_cljg_DOT_net_DOT_http_default_timeout.Get()
							tmp193 = tmp194
						}
						tmp190 = tmp193
					}
					tmp189 = tmp190
				}
				tmp186 = tmp189
			}
			var timeout195 any = tmp186
			_ = timeout195
			tmp196 := lang.Apply1(kw_as, opts155)
			var as197 any = tmp196
			_ = as197
			tmp198 := v_clojure_DOT_core_inc.Get()
			tmp199 := lang.Apply2(kw_retry, opts155, int64(0))
			tmp200 := lang.Apply1(tmp198, tmp199)
			var tries201 any = tmp200
			_ = tries201
			var tmp202 any
			_ = tmp202
			{
				var n203 any = tries201
				_ = n203
			loop204:
				for {
					var tmp205 any
					_ = tmp205
					{
						var tmp206 any
						_ = tmp206
						func() {
							defer func() {
								if r := recover(); r != nil {
									thrown := rt.Recover(r)
									if rt.CatchMatches("Throwable", thrown) {
										var e207 any = thrown
										_ = e207
										tmp208 := lang.NewMap(kw_err, e207)
										tmp206 = tmp208
										return
									}
									panic(r)
								}
							}()
							tmp209 := v_cljg_DOT_net_DOT_http_do_once.Get()
							tmp210 := lang.Apply(tmp209, []any{method158, url166, headers185, b173, timeout195, as197})
							tmp211 := lang.NewMap(kw_v, tmp210)
							tmp206 = tmp211
						}()
						var res212 any = tmp206
						_ = res212
						tmp213 := lang.Apply1(kw_err, res212)
						var tmp214 any
						_ = tmp214
						if lang.IsTruthy(tmp213) {
							tmp215 := rt.GTBool(v_clojure_DOT_core_X_GT_, n203, int64(1))
							var tmp216 any
							_ = tmp216
							if tmp215 {
								tmp217 := v_clojure_DOT_core_dec.Get()
								tmp218 := lang.Apply1(tmp217, n203)
								var tmp219 any = tmp218
								n203 = tmp219
								continue loop204
							} else {
								tmp220 := lang.Apply1(kw_err, res212)
								panic(rt.Throw(tmp220))
							}
						} else {
							var tmp221 any
							_ = tmp221
							{
								tmp222 := v_clojure_DOT_core_not_EQ_.Get()
								tmp223 := lang.Apply2(tmp222, as197, kw_stream)
								var and__1__auto__224 any = tmp223
								_ = and__1__auto__224
								var tmp225 any
								_ = tmp225
								if lang.IsTruthy(and__1__auto__224) {
									var tmp226 any
									_ = tmp226
									{
										tmp227 := lang.Apply1(kw_v, res212)
										tmp228 := lang.Apply1(kw_status, tmp227)
										tmp229 := rt.GE2(v_clojure_DOT_core_X_GT__EQ_, tmp228, int64(500))
										var and__1__auto__230 any = tmp229
										_ = and__1__auto__230
										var tmp231 any
										_ = tmp231
										if lang.IsTruthy(and__1__auto__230) {
											tmp232 := rt.GT2(v_clojure_DOT_core_X_GT_, n203, int64(1))
											tmp231 = tmp232
										} else {
											tmp231 = and__1__auto__230
										}
										tmp226 = tmp231
									}
									tmp225 = tmp226
								} else {
									tmp225 = and__1__auto__224
								}
								tmp221 = tmp225
							}
							var tmp233 any
							_ = tmp233
							if lang.IsTruthy(tmp221) {
								tmp234 := v_clojure_DOT_core_dec.Get()
								tmp235 := lang.Apply1(tmp234, n203)
								var tmp236 any = tmp235
								n203 = tmp236
								continue loop204
							} else {
								var tmp237 any
								_ = tmp237
								if lang.IsTruthy(kw_else_) {
									tmp238 := lang.Apply1(kw_v, res212)
									tmp237 = tmp238
								} else {
									tmp237 = nil
								}
								tmp233 = tmp237
							}
							tmp214 = tmp233
						}
						tmp205 = tmp214
					}
					tmp202 = tmp205
					break loop204
				}
			}
			tmp156 = tmp202
		}
		return tmp156
	})
	tmp239 := &lang.NamedFn1{Name: "cljg.net.http/request", Expects: "1: [opts]", F: tmp154}
	v_cljg_DOT_net_DOT_http_request.BindRoot(tmp239)
	fnD_cljg_DOT_net_DOT_http_request = tmp239.F
	v_cljg_DOT_net_DOT_http_request.SealDirect()
	_ = v_cljg_DOT_net_DOT_http_request
	// (def verb (clojure.core/fn ([method url opts] (request (assoc opts :method method :url url…
	v_cljg_DOT_net_DOT_http_verb.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(110), kw_column, int64(8), kw_end_line, int64(110), kw_end_column, int64(12), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_method, sym_url, sym_opts))))
	tmp240 := lang.FnFunc3(func(method241, url242, opts243 any) any {
		tmp244 := v_cljg_DOT_net_DOT_http_request.Direct()
		var tmp245 any
		if !tmp244 {
			tmp245 = v_cljg_DOT_net_DOT_http_request.Get()
		}
		tmp246 := v_clojure_DOT_core_assoc.Get()
		tmp247 := lang.Apply(tmp246, []any{opts243, kw_method, method241, kw_url, url242})
		var tmp248 any
		if tmp244 {
			tmp248 = fnD_cljg_DOT_net_DOT_http_request(tmp247)
		} else {
			tmp248 = lang.Apply1(tmp245, tmp247)
		}
		return tmp248
	})
	tmp249 := &lang.NamedFn3{Name: "cljg.net.http/verb", Expects: "3: [method url opts]", F: tmp240}
	v_cljg_DOT_net_DOT_http_verb.BindRoot(tmp249)
	fnD_cljg_DOT_net_DOT_http_verb = tmp249.F
	v_cljg_DOT_net_DOT_http_verb.SealDirect()
	_ = v_cljg_DOT_net_DOT_http_verb
	// (def get (clojure.core/fn ([url] (get url {})) ([url opts] (verb :get url opts))))
	v_cljg_DOT_net_DOT_http_get.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(112), kw_column, int64(7), kw_end_line, int64(112), kw_end_column, int64(10), kw_arglists, lang.NewList(lang.NewVector(sym_url), lang.NewVector(sym_url, sym_opts))))
	tmp250 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			url251 := args[0]
			_ = url251
			tmp252 := v_cljg_DOT_net_DOT_http_get.Get()
			tmp253 := lang.NewMap()
			tmp254 := lang.Apply2(tmp252, url251, tmp253)
			return tmp254
		case 2:
			url255 := args[0]
			_ = url255
			opts256 := args[1]
			_ = opts256
			tmp257 := v_cljg_DOT_net_DOT_http_verb.Direct()
			var tmp258 any
			if !tmp257 {
				tmp258 = v_cljg_DOT_net_DOT_http_verb.Get()
			}
			var tmp259 any
			if tmp257 {
				tmp259 = fnD_cljg_DOT_net_DOT_http_verb(kw_get, url255, opts256)
			} else {
				tmp259 = lang.Apply3(tmp258, kw_get, url255, opts256)
			}
			return tmp259
		default:
			panic(lang.NewArityError(len(args), "cljg.net.http/get", "1: [url] or 2: [url opts]"))
		}
	})
	v_cljg_DOT_net_DOT_http_get.BindRoot(tmp250)
	_ = v_cljg_DOT_net_DOT_http_get
	// (def post (clojure.core/fn ([url] (post url {})) ([url opts] (verb :post url opts))))
	v_cljg_DOT_net_DOT_http_post.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(113), kw_column, int64(7), kw_end_line, int64(113), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector(sym_url), lang.NewVector(sym_url, sym_opts))))
	tmp260 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			url261 := args[0]
			_ = url261
			tmp262 := v_cljg_DOT_net_DOT_http_post.Get()
			tmp263 := lang.NewMap()
			tmp264 := lang.Apply2(tmp262, url261, tmp263)
			return tmp264
		case 2:
			url265 := args[0]
			_ = url265
			opts266 := args[1]
			_ = opts266
			tmp267 := v_cljg_DOT_net_DOT_http_verb.Direct()
			var tmp268 any
			if !tmp267 {
				tmp268 = v_cljg_DOT_net_DOT_http_verb.Get()
			}
			var tmp269 any
			if tmp267 {
				tmp269 = fnD_cljg_DOT_net_DOT_http_verb(kw_post, url265, opts266)
			} else {
				tmp269 = lang.Apply3(tmp268, kw_post, url265, opts266)
			}
			return tmp269
		default:
			panic(lang.NewArityError(len(args), "cljg.net.http/post", "1: [url] or 2: [url opts]"))
		}
	})
	v_cljg_DOT_net_DOT_http_post.BindRoot(tmp260)
	_ = v_cljg_DOT_net_DOT_http_post
	// (def put (clojure.core/fn ([url] (put url {})) ([url opts] (verb :put url opts))))
	v_cljg_DOT_net_DOT_http_put.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(114), kw_column, int64(7), kw_end_line, int64(114), kw_end_column, int64(10), kw_arglists, lang.NewList(lang.NewVector(sym_url), lang.NewVector(sym_url, sym_opts))))
	tmp270 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			url271 := args[0]
			_ = url271
			tmp272 := v_cljg_DOT_net_DOT_http_put.Get()
			tmp273 := lang.NewMap()
			tmp274 := lang.Apply2(tmp272, url271, tmp273)
			return tmp274
		case 2:
			url275 := args[0]
			_ = url275
			opts276 := args[1]
			_ = opts276
			tmp277 := v_cljg_DOT_net_DOT_http_verb.Direct()
			var tmp278 any
			if !tmp277 {
				tmp278 = v_cljg_DOT_net_DOT_http_verb.Get()
			}
			var tmp279 any
			if tmp277 {
				tmp279 = fnD_cljg_DOT_net_DOT_http_verb(kw_put, url275, opts276)
			} else {
				tmp279 = lang.Apply3(tmp278, kw_put, url275, opts276)
			}
			return tmp279
		default:
			panic(lang.NewArityError(len(args), "cljg.net.http/put", "1: [url] or 2: [url opts]"))
		}
	})
	v_cljg_DOT_net_DOT_http_put.BindRoot(tmp270)
	_ = v_cljg_DOT_net_DOT_http_put
	// (def delete (clojure.core/fn ([url] (delete url {})) ([url opts] (verb :delete url opts)))…
	v_cljg_DOT_net_DOT_http_delete_.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(115), kw_column, int64(7), kw_end_line, int64(115), kw_end_column, int64(13), kw_arglists, lang.NewList(lang.NewVector(sym_url), lang.NewVector(sym_url, sym_opts))))
	tmp280 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			url281 := args[0]
			_ = url281
			tmp282 := v_cljg_DOT_net_DOT_http_delete_.Get()
			tmp283 := lang.NewMap()
			tmp284 := lang.Apply2(tmp282, url281, tmp283)
			return tmp284
		case 2:
			url285 := args[0]
			_ = url285
			opts286 := args[1]
			_ = opts286
			tmp287 := v_cljg_DOT_net_DOT_http_verb.Direct()
			var tmp288 any
			if !tmp287 {
				tmp288 = v_cljg_DOT_net_DOT_http_verb.Get()
			}
			var tmp289 any
			if tmp287 {
				tmp289 = fnD_cljg_DOT_net_DOT_http_verb(kw_delete_, url285, opts286)
			} else {
				tmp289 = lang.Apply3(tmp288, kw_delete_, url285, opts286)
			}
			return tmp289
		default:
			panic(lang.NewArityError(len(args), "cljg.net.http/delete", "1: [url] or 2: [url opts]"))
		}
	})
	v_cljg_DOT_net_DOT_http_delete_.BindRoot(tmp280)
	_ = v_cljg_DOT_net_DOT_http_delete_
	// (def patch (clojure.core/fn ([url] (patch url {})) ([url opts] (verb :patch url opts))))
	v_cljg_DOT_net_DOT_http_patch.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(116), kw_column, int64(7), kw_end_line, int64(116), kw_end_column, int64(12), kw_arglists, lang.NewList(lang.NewVector(sym_url), lang.NewVector(sym_url, sym_opts))))
	tmp290 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			url291 := args[0]
			_ = url291
			tmp292 := v_cljg_DOT_net_DOT_http_patch.Get()
			tmp293 := lang.NewMap()
			tmp294 := lang.Apply2(tmp292, url291, tmp293)
			return tmp294
		case 2:
			url295 := args[0]
			_ = url295
			opts296 := args[1]
			_ = opts296
			tmp297 := v_cljg_DOT_net_DOT_http_verb.Direct()
			var tmp298 any
			if !tmp297 {
				tmp298 = v_cljg_DOT_net_DOT_http_verb.Get()
			}
			var tmp299 any
			if tmp297 {
				tmp299 = fnD_cljg_DOT_net_DOT_http_verb(kw_patch, url295, opts296)
			} else {
				tmp299 = lang.Apply3(tmp298, kw_patch, url295, opts296)
			}
			return tmp299
		default:
			panic(lang.NewArityError(len(args), "cljg.net.http/patch", "1: [url] or 2: [url opts]"))
		}
	})
	v_cljg_DOT_net_DOT_http_patch.BindRoot(tmp290)
	_ = v_cljg_DOT_net_DOT_http_patch
	// (def head (clojure.core/fn ([url] (head url {})) ([url opts] (verb :head url opts))))
	v_cljg_DOT_net_DOT_http_head.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(117), kw_column, int64(7), kw_end_line, int64(117), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector(sym_url), lang.NewVector(sym_url, sym_opts))))
	tmp300 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			url301 := args[0]
			_ = url301
			tmp302 := v_cljg_DOT_net_DOT_http_head.Get()
			tmp303 := lang.NewMap()
			tmp304 := lang.Apply2(tmp302, url301, tmp303)
			return tmp304
		case 2:
			url305 := args[0]
			_ = url305
			opts306 := args[1]
			_ = opts306
			tmp307 := v_cljg_DOT_net_DOT_http_verb.Direct()
			var tmp308 any
			if !tmp307 {
				tmp308 = v_cljg_DOT_net_DOT_http_verb.Get()
			}
			var tmp309 any
			if tmp307 {
				tmp309 = fnD_cljg_DOT_net_DOT_http_verb(kw_head, url305, opts306)
			} else {
				tmp309 = lang.Apply3(tmp308, kw_head, url305, opts306)
			}
			return tmp309
		default:
			panic(lang.NewArityError(len(args), "cljg.net.http/head", "1: [url] or 2: [url opts]"))
		}
	})
	v_cljg_DOT_net_DOT_http_head.BindRoot(tmp300)
	_ = v_cljg_DOT_net_DOT_http_head
	// (def json-body (clojure.core/fn ([resp] (-json-decode (:body resp)))))
	v_cljg_DOT_net_DOT_http_json_body.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(123), kw_column, int64(7), kw_end_line, int64(123), kw_end_column, int64(16), kw_arglists, lang.NewList(lang.NewVector(sym_resp)), kw_doc, "Parse a response's :body as JSON (object keys → keywords, ints → longs)."))
	tmp310 := lang.FnFunc1(func(resp311 any) any {
		tmp312 := v_cljg_DOT_net_DOT_http_X_json_decode.Get()
		tmp313 := lang.Apply1(kw_body, resp311)
		tmp314 := lang.Apply1(tmp312, tmp313)
		return tmp314
	})
	tmp315 := &lang.NamedFn1{Name: "cljg.net.http/json-body", Expects: "1: [resp]", F: tmp310}
	v_cljg_DOT_net_DOT_http_json_body.BindRoot(tmp315)
	fnD_cljg_DOT_net_DOT_http_json_body = tmp315.F
	v_cljg_DOT_net_DOT_http_json_body.SealDirect()
	_ = v_cljg_DOT_net_DOT_http_json_body
	// (def edn-body (clojure.core/fn ([resp] (clojure.edn/read-string (:body resp)))))
	v_cljg_DOT_net_DOT_http_edn_body.SetMeta(lang.NewMap(kw_file, "cljg/net_http.cljg", kw_line, int64(128), kw_column, int64(7), kw_end_line, int64(128), kw_end_column, int64(15), kw_arglists, lang.NewList(lang.NewVector(sym_resp)), kw_doc, "Parse a response's :body as EDN."))
	tmp316 := lang.FnFunc1(func(resp317 any) any {
		tmp318 := v_clojure_DOT_edn_read_string.Get()
		tmp319 := lang.Apply1(kw_body, resp317)
		tmp320 := lang.Apply1(tmp318, tmp319)
		return tmp320
	})
	tmp321 := &lang.NamedFn1{Name: "cljg.net.http/edn-body", Expects: "1: [resp]", F: tmp316}
	v_cljg_DOT_net_DOT_http_edn_body.BindRoot(tmp321)
	fnD_cljg_DOT_net_DOT_http_edn_body = tmp321.F
	v_cljg_DOT_net_DOT_http_edn_body.SealDirect()
	_ = v_cljg_DOT_net_DOT_http_edn_body
}
