// Code generated by cljgo build. DO NOT EDIT.

package hierarchies

import (
	rt "github.com/muthuishere/cljgo/pkg/emit/rt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_ancestors                        = lang.InternKeywordString("ancestors")
	kw_column                           = lang.InternKeywordString("column")
	kw_descendants                      = lang.InternKeywordString("descendants")
	kw_doc                              = lang.InternKeywordString("doc")
	kw_end_column                       = lang.InternKeywordString("end-column")
	kw_end_line                         = lang.InternKeywordString("end-line")
	kw_file                             = lang.InternKeywordString("file")
	kw_line                             = lang.InternKeywordString("line")
	kw_parents                          = lang.InternKeywordString("parents")
	kw_private                          = lang.InternKeywordString("private")
	sym_X_EQ_                           = lang.NewSymbol("=")
	sym_and                             = lang.NewSymbol("and")
	sym_class_QMARK_                    = lang.NewSymbol("class?")
	sym_clojure_DOT_core                = lang.NewSymbol("clojure.core")
	sym_keyword_QMARK_                  = lang.NewSymbol("keyword?")
	sym_namespace                       = lang.NewSymbol("namespace")
	sym_not                             = lang.NewSymbol("not")
	sym_or                              = lang.NewSymbol("or")
	sym_parent                          = lang.NewSymbol("parent")
	sym_symbol_QMARK_                   = lang.NewSymbol("symbol?")
	sym_tag                             = lang.NewSymbol("tag")
	v_clojure_DOT_core_X_EQ_            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("="))
	v_clojure_DOT_core_X_type_bases     = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("-type-bases"))
	v_clojure_DOT_core_X_type_supers    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("-type-supers"))
	v_clojure_DOT_core_alter_var_root   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("alter-var-root"))
	v_clojure_DOT_core_ancestors        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("ancestors"))
	v_clojure_DOT_core_apply            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("apply"))
	v_clojure_DOT_core_assoc            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("assoc"))
	v_clojure_DOT_core_boolean          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("boolean"))
	v_clojure_DOT_core_class_QMARK_     = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("class?"))
	v_clojure_DOT_core_conj             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("conj"))
	v_clojure_DOT_core_cons             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("cons"))
	v_clojure_DOT_core_contains_QMARK_  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("contains?"))
	v_clojure_DOT_core_count            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("count"))
	v_clojure_DOT_core_derive           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("derive"))
	v_clojure_DOT_core_descendants      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("descendants"))
	v_clojure_DOT_core_disj             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("disj"))
	v_clojure_DOT_core_dissoc           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("dissoc"))
	v_clojure_DOT_core_ex_info          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("ex-info"))
	v_clojure_DOT_core_get              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("get"))
	v_clojure_DOT_core_global_hierarchy = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("global-hierarchy")).SetPrivate()
	v_clojure_DOT_core_in_ns            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_inc              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("inc"))
	v_clojure_DOT_core_interpose        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("interpose"))
	v_clojure_DOT_core_isa_QMARK_       = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("isa?"))
	v_clojure_DOT_core_key              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("key"))
	v_clojure_DOT_core_keyword_QMARK_   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("keyword?"))
	v_clojure_DOT_core_make_hierarchy   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("make-hierarchy"))
	v_clojure_DOT_core_map_             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("map"))
	v_clojure_DOT_core_mapcat           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("mapcat"))
	v_clojure_DOT_core_namespace        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("namespace"))
	v_clojure_DOT_core_not              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("not"))
	v_clojure_DOT_core_not_empty        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("not-empty"))
	v_clojure_DOT_core_parents          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("parents"))
	v_clojure_DOT_core_partition        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("partition"))
	v_clojure_DOT_core_pr_str           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("pr-str"))
	v_clojure_DOT_core_reduce           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("reduce"))
	v_clojure_DOT_core_seq              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("seq"))
	v_clojure_DOT_core_some             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("some"))
	v_clojure_DOT_core_str              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("str"))
	v_clojure_DOT_core_symbol_QMARK_    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("symbol?"))
	v_clojure_DOT_core_underive         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("underive"))
	v_clojure_DOT_core_val              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("val"))
	v_clojure_DOT_core_vector_QMARK_    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("vector?"))
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("clojure.core")), lang.VarFile, "hierarchies.cljg"))
	defer lang.PopThreadBindings()
	// (in-ns (quote clojure.core))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_clojure_DOT_core)
	_ = tmp2
	// (def make-hierarchy "Creates a hierarchy object for use with derive, isa? etc." (clojure.c…
	v_clojure_DOT_core_make_hierarchy.SetMeta(lang.NewMap(kw_file, "hierarchies.cljg", kw_line, int64(29), kw_column, int64(7), kw_end_line, int64(29), kw_end_column, int64(21), kw_doc, "Creates a hierarchy object for use with derive, isa? etc."))
	tmp3 := lang.FnFunc0(func() any {
		tmp4 := lang.NewMap()
		tmp5 := lang.NewMap()
		tmp6 := lang.NewMap()
		tmp7 := lang.NewMap(kw_parents, tmp4, kw_descendants, tmp5, kw_ancestors, tmp6)
		return tmp7
	})
	tmp8 := &lang.NamedFn0{Name: "clojure.core/make-hierarchy", Expects: "0: []", F: tmp3}
	v_clojure_DOT_core_make_hierarchy.BindRoot(tmp8)
	_ = v_clojure_DOT_core_make_hierarchy
	// (def global-hierarchy (make-hierarchy))
	v_clojure_DOT_core_global_hierarchy.SetMeta(lang.NewMap(kw_file, "hierarchies.cljg", kw_line, int64(33), kw_column, int64(6), kw_end_line, int64(33), kw_end_column, int64(32), kw_private, true))
	tmp9 := v_clojure_DOT_core_make_hierarchy.Get()
	tmp10 := lang.Apply0(tmp9)
	v_clojure_DOT_core_global_hierarchy.BindRoot(tmp10)
	_ = v_clojure_DOT_core_global_hierarchy
	// (def isa? "Returns true if (= child parent), or child is directly or indirectly\n  derived…
	v_clojure_DOT_core_isa_QMARK_.SetMeta(lang.NewMap(kw_file, "hierarchies.cljg", kw_line, int64(40), kw_column, int64(7), kw_end_line, int64(40), kw_end_column, int64(11), kw_doc, "Returns true if (= child parent), or child is directly or indirectly\n  derived from parent via a relationship established with derive. h must\n  be a hierarchy obtained from make-hierarchy; if not supplied defaults to\n  the global hierarchy. cljgo note (ADR 0039): a class child's REAL supers\n  (a record/type's declared protocols and implemented interfaces; Object\n  for concrete well-known classes) count, as the JVM's isAssignableFrom\n  branch does — but no JVM class graph is fabricated beyond that."))
	tmp11 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 2:
			child12 := args[0]
			_ = child12
			parent13 := args[1]
			_ = parent13
			tmp14 := v_clojure_DOT_core_isa_QMARK_.Get()
			tmp15 := v_clojure_DOT_core_global_hierarchy.Get()
			tmp16 := lang.Apply3(tmp14, tmp15, child12, parent13)
			return tmp16
		case 3:
			h17 := args[0]
			_ = h17
			child18 := args[1]
			_ = child18
			parent19 := args[2]
			_ = parent19
			var tmp20 any
			_ = tmp20
			{
				tmp21 := rt.EQ2(v_clojure_DOT_core_X_EQ_, child18, parent19)
				var or__2__auto__22 any = tmp21
				_ = or__2__auto__22
				var tmp23 any
				_ = tmp23
				if lang.IsTruthy(or__2__auto__22) {
					tmp23 = or__2__auto__22
				} else {
					var tmp24 any
					_ = tmp24
					{
						tmp25 := v_clojure_DOT_core_contains_QMARK_.Get()
						tmp26 := lang.Apply1(kw_ancestors, h17)
						tmp27 := lang.Apply1(tmp26, child18)
						tmp28 := lang.Apply2(tmp25, tmp27, parent19)
						var or__2__auto__29 any = tmp28
						_ = or__2__auto__29
						var tmp30 any
						_ = tmp30
						if lang.IsTruthy(or__2__auto__29) {
							tmp30 = or__2__auto__29
						} else {
							var tmp31 any
							_ = tmp31
							{
								var tmp32 any
								_ = tmp32
								{
									tmp33 := v_clojure_DOT_core_class_QMARK_.Get()
									tmp34 := lang.Apply1(tmp33, child18)
									var and__1__auto__35 any = tmp34
									_ = and__1__auto__35
									var tmp36 any
									_ = tmp36
									if lang.IsTruthy(and__1__auto__35) {
										var tmp37 any
										_ = tmp37
										{
											tmp38 := v_clojure_DOT_core_X_type_supers.Get()
											tmp39 := lang.Apply1(tmp38, child18)
											var ss40 any = tmp39
											_ = ss40
											tmp41 := v_clojure_DOT_core_boolean.Get()
											var tmp42 any
											_ = tmp42
											{
												tmp43 := v_clojure_DOT_core_contains_QMARK_.Get()
												tmp44 := lang.Apply2(tmp43, ss40, parent19)
												var or__2__auto__45 any = tmp44
												_ = or__2__auto__45
												var tmp46 any
												_ = tmp46
												if lang.IsTruthy(or__2__auto__45) {
													tmp46 = or__2__auto__45
												} else {
													tmp47 := v_clojure_DOT_core_some.Get()
													tmp48 := lang.FnFunc1(func(s49 any) any {
														tmp50 := v_clojure_DOT_core_contains_QMARK_.Get()
														tmp51 := lang.Apply1(kw_ancestors, h17)
														tmp52 := lang.Apply1(tmp51, s49)
														tmp53 := lang.Apply2(tmp50, tmp52, parent19)
														return tmp53
													})
													tmp54 := &lang.NamedFn1{Name: "fn", Expects: "1: [s]", F: tmp48}
													tmp55 := lang.Apply2(tmp47, tmp54, ss40)
													tmp46 = tmp55
												}
												tmp42 = tmp46
											}
											tmp56 := lang.Apply1(tmp41, tmp42)
											tmp37 = tmp56
										}
										tmp36 = tmp37
									} else {
										tmp36 = and__1__auto__35
									}
									tmp32 = tmp36
								}
								var or__2__auto__57 any = tmp32
								_ = or__2__auto__57
								var tmp58 any
								_ = tmp58
								if lang.IsTruthy(or__2__auto__57) {
									tmp58 = or__2__auto__57
								} else {
									var tmp59 any
									_ = tmp59
									{
										tmp60 := v_clojure_DOT_core_vector_QMARK_.Get()
										tmp61 := lang.Apply1(tmp60, parent19)
										var and__1__auto__62 any = tmp61
										_ = and__1__auto__62
										var tmp63 any
										_ = tmp63
										if lang.IsTruthy(and__1__auto__62) {
											var tmp64 any
											_ = tmp64
											{
												tmp65 := v_clojure_DOT_core_vector_QMARK_.Get()
												tmp66 := lang.Apply1(tmp65, child18)
												var and__1__auto__67 any = tmp66
												_ = and__1__auto__67
												var tmp68 any
												_ = tmp68
												if lang.IsTruthy(and__1__auto__67) {
													var tmp69 any
													_ = tmp69
													{
														tmp70 := v_clojure_DOT_core_count.Get()
														tmp71 := lang.Apply1(tmp70, parent19)
														tmp72 := v_clojure_DOT_core_count.Get()
														tmp73 := lang.Apply1(tmp72, child18)
														tmp74 := rt.EQ2(v_clojure_DOT_core_X_EQ_, tmp71, tmp73)
														var and__1__auto__75 any = tmp74
														_ = and__1__auto__75
														var tmp76 any
														_ = tmp76
														if lang.IsTruthy(and__1__auto__75) {
															var tmp77 any
															_ = tmp77
															if !rt.CoreDirty() {
																var tmp78 any
																_ = tmp78
																{
																	var ret79 any = true
																	_ = ret79
																	var i80 int64 = int64(0)
																	_ = i80
																loop81:
																	for {
																		var tmp82 any
																		_ = tmp82
																		{
																			tmp83 := v_clojure_DOT_core_not.Get()
																			tmp84 := lang.Apply1(tmp83, ret79)
																			var or__2__auto__85 any = tmp84
																			_ = or__2__auto__85
																			var tmp86 any
																			_ = tmp86
																			if lang.IsTruthy(or__2__auto__85) {
																				tmp86 = or__2__auto__85
																			} else {
																				tmp87 := v_clojure_DOT_core_count.Get()
																				tmp88 := lang.Apply1(tmp87, parent19)
																				tmp89 := rt.EQ2(v_clojure_DOT_core_X_EQ_, i80, tmp88)
																				tmp86 = tmp89
																			}
																			tmp82 = tmp86
																		}
																		var tmp90 any
																		_ = tmp90
																		if lang.IsTruthy(tmp82) {
																			tmp90 = ret79
																		} else {
																			tmp91 := v_clojure_DOT_core_isa_QMARK_.Get()
																			tmp92 := lang.Apply1(child18, i80)
																			tmp93 := lang.Apply1(parent19, i80)
																			tmp94 := lang.Apply3(tmp91, h17, tmp92, tmp93)
																			var tmp95 any = tmp94
																			var tmp96 int64 = rt.IInc(i80)
																			var tmp97 int64 = tmp96
																			ret79 = tmp95
																			i80 = tmp97
																			continue loop81
																		}
																		tmp78 = tmp90
																		break loop81
																	}
																}
																tmp77 = tmp78
															} else {
																var tmp98 any
																_ = tmp98
																{
																	var ret99 any = true
																	_ = ret99
																	var i100 any = int64(0)
																	_ = i100
																loop101:
																	for {
																		var tmp102 any
																		_ = tmp102
																		{
																			tmp103 := v_clojure_DOT_core_not.Get()
																			tmp104 := lang.Apply1(tmp103, ret99)
																			var or__2__auto__105 any = tmp104
																			_ = or__2__auto__105
																			var tmp106 any
																			_ = tmp106
																			if lang.IsTruthy(or__2__auto__105) {
																				tmp106 = or__2__auto__105
																			} else {
																				tmp107 := v_clojure_DOT_core_count.Get()
																				tmp108 := lang.Apply1(tmp107, parent19)
																				tmp109 := rt.EQ2(v_clojure_DOT_core_X_EQ_, i100, tmp108)
																				tmp106 = tmp109
																			}
																			tmp102 = tmp106
																		}
																		var tmp110 any
																		_ = tmp110
																		if lang.IsTruthy(tmp102) {
																			tmp110 = ret99
																		} else {
																			tmp111 := v_clojure_DOT_core_isa_QMARK_.Get()
																			tmp112 := lang.Apply1(child18, i100)
																			tmp113 := lang.Apply1(parent19, i100)
																			tmp114 := lang.Apply3(tmp111, h17, tmp112, tmp113)
																			var tmp115 any = tmp114
																			tmp116 := v_clojure_DOT_core_inc.Get()
																			tmp117 := lang.Apply1(tmp116, i100)
																			var tmp118 any = tmp117
																			ret99 = tmp115
																			i100 = tmp118
																			continue loop101
																		}
																		tmp98 = tmp110
																		break loop101
																	}
																}
																tmp77 = tmp98
															}
															tmp76 = tmp77
														} else {
															tmp76 = and__1__auto__75
														}
														tmp69 = tmp76
													}
													tmp68 = tmp69
												} else {
													tmp68 = and__1__auto__67
												}
												tmp64 = tmp68
											}
											tmp63 = tmp64
										} else {
											tmp63 = and__1__auto__62
										}
										tmp59 = tmp63
									}
									tmp58 = tmp59
								}
								tmp31 = tmp58
							}
							tmp30 = tmp31
						}
						tmp24 = tmp30
					}
					tmp23 = tmp24
				}
				tmp20 = tmp23
			}
			return tmp20
		default:
			panic(lang.NewArityError(len(args), "clojure.core/isa?", "2: [child parent] or 3: [h child parent]"))
		}
	})
	v_clojure_DOT_core_isa_QMARK_.BindRoot(tmp11)
	_ = v_clojure_DOT_core_isa_QMARK_
	// (def parents "Returns the immediate parents of tag, both via a relationship\n  established…
	v_clojure_DOT_core_parents.SetMeta(lang.NewMap(kw_file, "hierarchies.cljg", kw_line, int64(66), kw_column, int64(7), kw_end_line, int64(66), kw_end_column, int64(14), kw_doc, "Returns the immediate parents of tag, both via a relationship\n  established with derive and, for a class tag, its real direct supers\n  (ADR 0039). h must be a hierarchy obtained from make-hierarchy; if not\n  supplied defaults to the global hierarchy."))
	tmp119 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			tag120 := args[0]
			_ = tag120
			tmp121 := v_clojure_DOT_core_parents.Get()
			tmp122 := v_clojure_DOT_core_global_hierarchy.Get()
			tmp123 := lang.Apply2(tmp121, tmp122, tag120)
			return tmp123
		case 2:
			h124 := args[0]
			_ = h124
			tag125 := args[1]
			_ = tag125
			tmp126 := v_clojure_DOT_core_not_empty.Get()
			var tmp127 any
			_ = tmp127
			{
				tmp128 := v_clojure_DOT_core_get.Get()
				tmp129 := lang.Apply1(kw_parents, h124)
				tmp130 := lang.Apply2(tmp128, tmp129, tag125)
				var tp131 any = tmp130
				_ = tp131
				tmp132 := v_clojure_DOT_core_class_QMARK_.Get()
				tmp133 := lang.Apply1(tmp132, tag125)
				var tmp134 any
				_ = tmp134
				if lang.IsTruthy(tmp133) {
					tmp135 := v_clojure_DOT_core_reduce.Get()
					tmp136 := v_clojure_DOT_core_conj.Get()
					var tmp137 any
					_ = tmp137
					{
						tmp138 := v_clojure_DOT_core_X_type_bases.Get()
						tmp139 := lang.Apply1(tmp138, tag125)
						var or__2__auto__140 any = tmp139
						_ = or__2__auto__140
						var tmp141 any
						_ = tmp141
						if lang.IsTruthy(or__2__auto__140) {
							tmp141 = or__2__auto__140
						} else {
							tmp142 := lang.NewSet()
							tmp141 = tmp142
						}
						tmp137 = tmp141
					}
					tmp143 := lang.Apply3(tmp135, tmp136, tmp137, tp131)
					tmp134 = tmp143
				} else {
					tmp134 = tp131
				}
				tmp127 = tmp134
			}
			tmp144 := lang.Apply1(tmp126, tmp127)
			return tmp144
		default:
			panic(lang.NewArityError(len(args), "clojure.core/parents", "1: [tag] or 2: [h tag]"))
		}
	})
	v_clojure_DOT_core_parents.BindRoot(tmp119)
	_ = v_clojure_DOT_core_parents
	// (def ancestors "Returns the immediate and indirect parents of tag, both via a\n  relations…
	v_clojure_DOT_core_ancestors.SetMeta(lang.NewMap(kw_file, "hierarchies.cljg", kw_line, int64(84), kw_column, int64(7), kw_end_line, int64(84), kw_end_column, int64(16), kw_doc, "Returns the immediate and indirect parents of tag, both via a\n  relationship established with derive and, for a class tag, its real\n  supers (ADR 0039). h must be a hierarchy obtained from make-hierarchy;\n  if not supplied defaults to the global hierarchy."))
	tmp145 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			tag146 := args[0]
			_ = tag146
			tmp147 := v_clojure_DOT_core_ancestors.Get()
			tmp148 := v_clojure_DOT_core_global_hierarchy.Get()
			tmp149 := lang.Apply2(tmp147, tmp148, tag146)
			return tmp149
		case 2:
			h150 := args[0]
			_ = h150
			tag151 := args[1]
			_ = tag151
			tmp152 := v_clojure_DOT_core_not_empty.Get()
			var tmp153 any
			_ = tmp153
			{
				tmp154 := v_clojure_DOT_core_get.Get()
				tmp155 := lang.Apply1(kw_ancestors, h150)
				tmp156 := lang.Apply2(tmp154, tmp155, tag151)
				var ta157 any = tmp156
				_ = ta157
				tmp158 := v_clojure_DOT_core_class_QMARK_.Get()
				tmp159 := lang.Apply1(tmp158, tag151)
				var tmp160 any
				_ = tmp160
				if lang.IsTruthy(tmp159) {
					var tmp161 any
					_ = tmp161
					{
						tmp162 := v_clojure_DOT_core_X_type_supers.Get()
						tmp163 := lang.Apply1(tmp162, tag151)
						var superclasses164 any = tmp163
						_ = superclasses164
						tmp165 := v_clojure_DOT_core_reduce.Get()
						tmp166 := lang.FnFunc2(func(acc167, xs168 any) any {
							tmp169 := v_clojure_DOT_core_reduce.Get()
							tmp170 := v_clojure_DOT_core_conj.Get()
							tmp171 := lang.Apply3(tmp169, tmp170, acc167, xs168)
							return tmp171
						})
						tmp172 := &lang.NamedFn2{Name: "fn", Expects: "2: [acc xs]", F: tmp166}
						var tmp173 any
						_ = tmp173
						{
							var or__2__auto__174 any = superclasses164
							_ = or__2__auto__174
							var tmp175 any
							_ = tmp175
							if lang.IsTruthy(or__2__auto__174) {
								tmp175 = or__2__auto__174
							} else {
								tmp176 := lang.NewSet()
								tmp175 = tmp176
							}
							tmp173 = tmp175
						}
						tmp177 := v_clojure_DOT_core_cons.Get()
						tmp178 := v_clojure_DOT_core_map_.Get()
						tmp179 := lang.FnFunc1(func(s180 any) any {
							tmp181 := v_clojure_DOT_core_get.Get()
							tmp182 := lang.Apply1(kw_ancestors, h150)
							tmp183 := lang.Apply2(tmp181, tmp182, s180)
							return tmp183
						})
						tmp184 := &lang.NamedFn1{Name: "fn", Expects: "1: [s]", F: tmp179}
						tmp185 := lang.Apply2(tmp178, tmp184, superclasses164)
						tmp186 := lang.Apply2(tmp177, ta157, tmp185)
						tmp187 := lang.Apply3(tmp165, tmp172, tmp173, tmp186)
						tmp161 = tmp187
					}
					tmp160 = tmp161
				} else {
					tmp160 = ta157
				}
				tmp153 = tmp160
			}
			tmp188 := lang.Apply1(tmp152, tmp153)
			return tmp188
		default:
			panic(lang.NewArityError(len(args), "clojure.core/ancestors", "1: [tag] or 2: [h tag]"))
		}
	})
	v_clojure_DOT_core_ancestors.BindRoot(tmp145)
	_ = v_clojure_DOT_core_ancestors
	// (def descendants "Returns the immediate and indirect children of tag, via a relationship\n…
	v_clojure_DOT_core_descendants.SetMeta(lang.NewMap(kw_file, "hierarchies.cljg", kw_line, int64(105), kw_column, int64(7), kw_end_line, int64(105), kw_end_column, int64(18), kw_doc, "Returns the immediate and indirect children of tag, via a relationship\n  established with derive. h must be a hierarchy obtained from\n  make-hierarchy; if not supplied defaults to, and modifies, the global\n  hierarchy. Note: cljgo has no class inheritance to walk (design/05)."))
	tmp189 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			tag190 := args[0]
			_ = tag190
			tmp191 := v_clojure_DOT_core_descendants.Get()
			tmp192 := v_clojure_DOT_core_global_hierarchy.Get()
			tmp193 := lang.Apply2(tmp191, tmp192, tag190)
			return tmp193
		case 2:
			h194 := args[0]
			_ = h194
			tag195 := args[1]
			_ = tag195
			tmp196 := v_clojure_DOT_core_class_QMARK_.Get()
			tmp197 := lang.Apply1(tmp196, tag195)
			var tmp198 any
			_ = tmp198
			if lang.IsTruthy(tmp197) {
				tmp199 := v_clojure_DOT_core_ex_info.Get()
				tmp200 := lang.NewMap()
				tmp201 := lang.Apply2(tmp199, "Can't get descendants of classes", tmp200)
				panic(rt.Throw(tmp201))
			} else {
				tmp202 := v_clojure_DOT_core_not_empty.Get()
				tmp203 := v_clojure_DOT_core_get.Get()
				tmp204 := lang.Apply1(kw_descendants, h194)
				tmp205 := lang.Apply2(tmp203, tmp204, tag195)
				tmp206 := lang.Apply1(tmp202, tmp205)
				tmp198 = tmp206
			}
			return tmp198
		default:
			panic(lang.NewArityError(len(args), "clojure.core/descendants", "1: [tag] or 2: [h tag]"))
		}
	})
	v_clojure_DOT_core_descendants.BindRoot(tmp189)
	_ = v_clojure_DOT_core_descendants
	// (def derive "Establishes a parent/child relationship between parent and tag. Parent\n  mus…
	v_clojure_DOT_core_derive.SetMeta(lang.NewMap(kw_file, "hierarchies.cljg", kw_line, int64(124), kw_column, int64(7), kw_end_line, int64(124), kw_end_column, int64(13), kw_doc, "Establishes a parent/child relationship between parent and tag. Parent\n  must be a namespace-qualified keyword or symbol; tag may also be a\n  class (ADR 0036: a ClassRef or deftype/defrecord type). h must be a\n  hierarchy obtained from make-hierarchy; if not supplied defaults to,\n  and modifies, the global hierarchy."))
	tmp207 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 2:
			tag208 := args[0]
			_ = tag208
			parent209 := args[1]
			_ = parent209
			tmp210 := v_clojure_DOT_core_namespace.Get()
			tmp211 := lang.Apply1(tmp210, parent209)
			var tmp212 any
			_ = tmp212
			if lang.IsTruthy(tmp211) {
				tmp212 = nil
			} else {
				tmp213 := v_clojure_DOT_core_ex_info.Get()
				tmp214 := v_clojure_DOT_core_str.Get()
				tmp215 := v_clojure_DOT_core_pr_str.Get()
				tmp216 := lang.Apply1(tmp215, lang.NewList(sym_namespace, sym_parent))
				tmp217 := lang.Apply2(tmp214, "Assert failed: ", tmp216)
				tmp218 := lang.NewMap()
				tmp219 := lang.Apply2(tmp213, tmp217, tmp218)
				panic(rt.Throw(tmp219))
			}
			_ = tmp212
			var tmp220 any
			_ = tmp220
			{
				tmp221 := v_clojure_DOT_core_class_QMARK_.Get()
				tmp222 := lang.Apply1(tmp221, tag208)
				var or__2__auto__223 any = tmp222
				_ = or__2__auto__223
				var tmp224 any
				_ = tmp224
				if lang.IsTruthy(or__2__auto__223) {
					tmp224 = or__2__auto__223
				} else {
					var tmp225 any
					_ = tmp225
					{
						var tmp226 any
						_ = tmp226
						{
							tmp227 := v_clojure_DOT_core_keyword_QMARK_.Get()
							tmp228 := lang.Apply1(tmp227, tag208)
							var or__2__auto__229 any = tmp228
							_ = or__2__auto__229
							var tmp230 any
							_ = tmp230
							if lang.IsTruthy(or__2__auto__229) {
								tmp230 = or__2__auto__229
							} else {
								tmp231 := v_clojure_DOT_core_symbol_QMARK_.Get()
								tmp232 := lang.Apply1(tmp231, tag208)
								tmp230 = tmp232
							}
							tmp226 = tmp230
						}
						var and__1__auto__233 any = tmp226
						_ = and__1__auto__233
						var tmp234 any
						_ = tmp234
						if lang.IsTruthy(and__1__auto__233) {
							tmp235 := v_clojure_DOT_core_namespace.Get()
							tmp236 := lang.Apply1(tmp235, tag208)
							tmp234 = tmp236
						} else {
							tmp234 = and__1__auto__233
						}
						tmp225 = tmp234
					}
					tmp224 = tmp225
				}
				tmp220 = tmp224
			}
			var tmp237 any
			_ = tmp237
			if lang.IsTruthy(tmp220) {
				tmp237 = nil
			} else {
				tmp238 := v_clojure_DOT_core_ex_info.Get()
				tmp239 := v_clojure_DOT_core_str.Get()
				tmp240 := v_clojure_DOT_core_pr_str.Get()
				tmp241 := lang.Apply1(tmp240, lang.NewList(sym_or, lang.NewList(sym_class_QMARK_, sym_tag), lang.NewList(sym_and, lang.NewList(sym_or, lang.NewList(sym_keyword_QMARK_, sym_tag), lang.NewList(sym_symbol_QMARK_, sym_tag)), lang.NewList(sym_namespace, sym_tag))))
				tmp242 := lang.Apply2(tmp239, "Assert failed: ", tmp241)
				tmp243 := lang.NewMap()
				tmp244 := lang.Apply2(tmp238, tmp242, tmp243)
				panic(rt.Throw(tmp244))
			}
			_ = tmp237
			tmp245 := v_clojure_DOT_core_alter_var_root.Get()
			tmp246 := v_clojure_DOT_core_derive.Get()
			tmp247 := lang.Apply4(tmp245, v_clojure_DOT_core_global_hierarchy, tmp246, tag208, parent209)
			_ = tmp247
			return nil
		case 3:
			h248 := args[0]
			_ = h248
			tag249 := args[1]
			_ = tag249
			parent250 := args[2]
			_ = parent250
			tmp251 := v_clojure_DOT_core_not.Get()
			tmp252 := rt.EQ2(v_clojure_DOT_core_X_EQ_, tag249, parent250)
			tmp253 := lang.Apply1(tmp251, tmp252)
			var tmp254 any
			_ = tmp254
			if lang.IsTruthy(tmp253) {
				tmp254 = nil
			} else {
				tmp255 := v_clojure_DOT_core_ex_info.Get()
				tmp256 := v_clojure_DOT_core_str.Get()
				tmp257 := v_clojure_DOT_core_pr_str.Get()
				tmp258 := lang.Apply1(tmp257, lang.NewList(sym_not, lang.NewList(sym_X_EQ_, sym_tag, sym_parent)))
				tmp259 := lang.Apply2(tmp256, "Assert failed: ", tmp258)
				tmp260 := lang.NewMap()
				tmp261 := lang.Apply2(tmp255, tmp259, tmp260)
				panic(rt.Throw(tmp261))
			}
			_ = tmp254
			var tmp262 any
			_ = tmp262
			{
				tmp263 := v_clojure_DOT_core_class_QMARK_.Get()
				tmp264 := lang.Apply1(tmp263, tag249)
				var or__2__auto__265 any = tmp264
				_ = or__2__auto__265
				var tmp266 any
				_ = tmp266
				if lang.IsTruthy(or__2__auto__265) {
					tmp266 = or__2__auto__265
				} else {
					var tmp267 any
					_ = tmp267
					{
						tmp268 := v_clojure_DOT_core_keyword_QMARK_.Get()
						tmp269 := lang.Apply1(tmp268, tag249)
						var or__2__auto__270 any = tmp269
						_ = or__2__auto__270
						var tmp271 any
						_ = tmp271
						if lang.IsTruthy(or__2__auto__270) {
							tmp271 = or__2__auto__270
						} else {
							tmp272 := v_clojure_DOT_core_symbol_QMARK_.Get()
							tmp273 := lang.Apply1(tmp272, tag249)
							tmp271 = tmp273
						}
						tmp267 = tmp271
					}
					tmp266 = tmp267
				}
				tmp262 = tmp266
			}
			var tmp274 any
			_ = tmp274
			if lang.IsTruthy(tmp262) {
				tmp274 = nil
			} else {
				tmp275 := v_clojure_DOT_core_ex_info.Get()
				tmp276 := v_clojure_DOT_core_str.Get()
				tmp277 := v_clojure_DOT_core_pr_str.Get()
				tmp278 := lang.Apply1(tmp277, lang.NewList(sym_or, lang.NewList(sym_class_QMARK_, sym_tag), lang.NewList(sym_keyword_QMARK_, sym_tag), lang.NewList(sym_symbol_QMARK_, sym_tag)))
				tmp279 := lang.Apply2(tmp276, "Assert failed: ", tmp278)
				tmp280 := lang.NewMap()
				tmp281 := lang.Apply2(tmp275, tmp279, tmp280)
				panic(rt.Throw(tmp281))
			}
			_ = tmp274
			var tmp282 any
			_ = tmp282
			{
				tmp283 := v_clojure_DOT_core_keyword_QMARK_.Get()
				tmp284 := lang.Apply1(tmp283, parent250)
				var or__2__auto__285 any = tmp284
				_ = or__2__auto__285
				var tmp286 any
				_ = tmp286
				if lang.IsTruthy(or__2__auto__285) {
					tmp286 = or__2__auto__285
				} else {
					tmp287 := v_clojure_DOT_core_symbol_QMARK_.Get()
					tmp288 := lang.Apply1(tmp287, parent250)
					tmp286 = tmp288
				}
				tmp282 = tmp286
			}
			var tmp289 any
			_ = tmp289
			if lang.IsTruthy(tmp282) {
				tmp289 = nil
			} else {
				tmp290 := v_clojure_DOT_core_ex_info.Get()
				tmp291 := v_clojure_DOT_core_str.Get()
				tmp292 := v_clojure_DOT_core_pr_str.Get()
				tmp293 := lang.Apply1(tmp292, lang.NewList(sym_or, lang.NewList(sym_keyword_QMARK_, sym_parent), lang.NewList(sym_symbol_QMARK_, sym_parent)))
				tmp294 := lang.Apply2(tmp291, "Assert failed: ", tmp293)
				tmp295 := lang.NewMap()
				tmp296 := lang.Apply2(tmp290, tmp294, tmp295)
				panic(rt.Throw(tmp296))
			}
			_ = tmp289
			var tmp297 any
			_ = tmp297
			{
				tmp298 := lang.Apply1(kw_parents, h248)
				var tp299 any = tmp298
				_ = tp299
				tmp300 := lang.Apply1(kw_descendants, h248)
				var td301 any = tmp300
				_ = td301
				tmp302 := lang.Apply1(kw_ancestors, h248)
				var ta303 any = tmp302
				_ = ta303
				tmp304 := lang.FnFunc(func(args ...any) any {
					switch len(args) {
					case 5:
						m305 := args[0]
						_ = m305
						source306 := args[1]
						_ = source306
						sources307 := args[2]
						_ = sources307
						target308 := args[3]
						_ = target308
						targets309 := args[4]
						_ = targets309
						tmp310 := v_clojure_DOT_core_reduce.Get()
						tmp311 := lang.FnFunc2(func(ret312, k313 any) any {
							tmp314 := v_clojure_DOT_core_assoc.Get()
							tmp315 := v_clojure_DOT_core_reduce.Get()
							tmp316 := v_clojure_DOT_core_conj.Get()
							tmp317 := v_clojure_DOT_core_get.Get()
							tmp318 := lang.NewSet()
							tmp319 := lang.Apply3(tmp317, targets309, k313, tmp318)
							tmp320 := v_clojure_DOT_core_cons.Get()
							tmp321 := lang.Apply1(targets309, target308)
							tmp322 := lang.Apply2(tmp320, target308, tmp321)
							tmp323 := lang.Apply3(tmp315, tmp316, tmp319, tmp322)
							tmp324 := lang.Apply3(tmp314, ret312, k313, tmp323)
							return tmp324
						})
						tmp325 := &lang.NamedFn2{Name: "fn", Expects: "2: [ret k]", F: tmp311}
						tmp326 := v_clojure_DOT_core_cons.Get()
						tmp327 := lang.Apply1(sources307, source306)
						tmp328 := lang.Apply2(tmp326, source306, tmp327)
						tmp329 := lang.Apply3(tmp310, tmp325, m305, tmp328)
						return tmp329
					default:
						panic(lang.NewArityError(len(args), "fn", "5: [m source sources target targets]"))
					}
				})
				var tf330 any = tmp304
				_ = tf330
				var tmp331 any
				_ = tmp331
				{
					tmp332 := v_clojure_DOT_core_contains_QMARK_.Get()
					tmp333 := lang.Apply1(tp299, tag249)
					tmp334 := lang.Apply2(tmp332, tmp333, parent250)
					var tmp335 any
					_ = tmp335
					if lang.IsTruthy(tmp334) {
						tmp335 = nil
					} else {
						tmp336 := v_clojure_DOT_core_contains_QMARK_.Get()
						tmp337 := lang.Apply1(ta303, tag249)
						tmp338 := lang.Apply2(tmp336, tmp337, parent250)
						var tmp339 any
						_ = tmp339
						if lang.IsTruthy(tmp338) {
							tmp340 := v_clojure_DOT_core_ex_info.Get()
							tmp341 := v_clojure_DOT_core_str.Get()
							tmp342 := lang.Apply4(tmp341, tag249, " already has ", parent250, " as ancestor")
							tmp343 := lang.NewMap()
							tmp344 := lang.Apply2(tmp340, tmp342, tmp343)
							panic(rt.Throw(tmp344))
						} else {
							tmp339 = nil
						}
						_ = tmp339
						tmp345 := v_clojure_DOT_core_contains_QMARK_.Get()
						tmp346 := lang.Apply1(ta303, parent250)
						tmp347 := lang.Apply2(tmp345, tmp346, tag249)
						var tmp348 any
						_ = tmp348
						if lang.IsTruthy(tmp347) {
							tmp349 := v_clojure_DOT_core_ex_info.Get()
							tmp350 := v_clojure_DOT_core_str.Get()
							tmp351 := lang.Apply(tmp350, []any{"Cyclic derivation: ", parent250, " has ", tag249, " as ancestor"})
							tmp352 := lang.NewMap()
							tmp353 := lang.Apply2(tmp349, tmp351, tmp352)
							panic(rt.Throw(tmp353))
						} else {
							tmp348 = nil
						}
						_ = tmp348
						tmp354 := v_clojure_DOT_core_assoc.Get()
						tmp355 := lang.Apply1(kw_parents, h248)
						tmp356 := v_clojure_DOT_core_conj.Get()
						tmp357 := v_clojure_DOT_core_get.Get()
						tmp358 := lang.NewSet()
						tmp359 := lang.Apply3(tmp357, tp299, tag249, tmp358)
						tmp360 := lang.Apply2(tmp356, tmp359, parent250)
						tmp361 := lang.Apply3(tmp354, tmp355, tag249, tmp360)
						tmp362 := lang.Apply1(kw_ancestors, h248)
						tmp363 := lang.Apply(tf330, []any{tmp362, tag249, td301, parent250, ta303})
						tmp364 := lang.Apply1(kw_descendants, h248)
						tmp365 := lang.Apply(tf330, []any{tmp364, parent250, ta303, tag249, td301})
						tmp366 := lang.NewMap(kw_parents, tmp361, kw_ancestors, tmp363, kw_descendants, tmp365)
						tmp335 = tmp366
					}
					var or__2__auto__367 any = tmp335
					_ = or__2__auto__367
					var tmp368 any
					_ = tmp368
					if lang.IsTruthy(or__2__auto__367) {
						tmp368 = or__2__auto__367
					} else {
						tmp368 = h248
					}
					tmp331 = tmp368
				}
				tmp297 = tmp331
			}
			return tmp297
		default:
			panic(lang.NewArityError(len(args), "clojure.core/derive", "2: [tag parent] or 3: [h tag parent]"))
		}
	})
	v_clojure_DOT_core_derive.BindRoot(tmp207)
	_ = v_clojure_DOT_core_derive
	// (def underive "Removes a parent/child relationship between parent and tag. h must be a\n  …
	v_clojure_DOT_core_underive.SetMeta(lang.NewMap(kw_file, "hierarchies.cljg", kw_line, int64(159), kw_column, int64(7), kw_end_line, int64(159), kw_end_column, int64(15), kw_doc, "Removes a parent/child relationship between parent and tag. h must be a\n  hierarchy obtained from make-hierarchy; if not supplied defaults to, and\n  modifies, the global hierarchy."))
	tmp369 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 2:
			tag370 := args[0]
			_ = tag370
			parent371 := args[1]
			_ = parent371
			tmp372 := v_clojure_DOT_core_alter_var_root.Get()
			tmp373 := v_clojure_DOT_core_underive.Get()
			tmp374 := lang.Apply4(tmp372, v_clojure_DOT_core_global_hierarchy, tmp373, tag370, parent371)
			_ = tmp374
			return nil
		case 3:
			h375 := args[0]
			_ = h375
			tag376 := args[1]
			_ = tag376
			parent377 := args[2]
			_ = parent377
			var tmp378 any
			_ = tmp378
			{
				tmp379 := lang.Apply1(kw_parents, h375)
				var parent_map380 any = tmp379
				_ = parent_map380
				tmp381 := lang.Apply1(parent_map380, tag376)
				var tmp382 any
				_ = tmp382
				if lang.IsTruthy(tmp381) {
					tmp383 := v_clojure_DOT_core_disj.Get()
					tmp384 := lang.Apply1(parent_map380, tag376)
					tmp385 := lang.Apply2(tmp383, tmp384, parent377)
					tmp382 = tmp385
				} else {
					tmp386 := lang.NewSet()
					tmp382 = tmp386
				}
				var childs_parents387 any = tmp382
				_ = childs_parents387
				tmp388 := v_clojure_DOT_core_not_empty.Get()
				tmp389 := lang.Apply1(tmp388, childs_parents387)
				var tmp390 any
				_ = tmp390
				if lang.IsTruthy(tmp389) {
					tmp391 := v_clojure_DOT_core_assoc.Get()
					tmp392 := lang.Apply3(tmp391, parent_map380, tag376, childs_parents387)
					tmp390 = tmp392
				} else {
					tmp393 := v_clojure_DOT_core_dissoc.Get()
					tmp394 := lang.Apply2(tmp393, parent_map380, tag376)
					tmp390 = tmp394
				}
				var new_parents395 any = tmp390
				_ = new_parents395
				tmp396 := v_clojure_DOT_core_mapcat.Get()
				tmp397 := lang.FnFunc1(func(entry398 any) any {
					tmp399 := v_clojure_DOT_core_cons.Get()
					tmp400 := v_clojure_DOT_core_key.Get()
					tmp401 := lang.Apply1(tmp400, entry398)
					tmp402 := v_clojure_DOT_core_interpose.Get()
					tmp403 := v_clojure_DOT_core_key.Get()
					tmp404 := lang.Apply1(tmp403, entry398)
					tmp405 := v_clojure_DOT_core_val.Get()
					tmp406 := lang.Apply1(tmp405, entry398)
					tmp407 := lang.Apply2(tmp402, tmp404, tmp406)
					tmp408 := lang.Apply2(tmp399, tmp401, tmp407)
					return tmp408
				})
				tmp409 := &lang.NamedFn1{Name: "fn", Expects: "1: [entry]", F: tmp397}
				tmp410 := v_clojure_DOT_core_seq.Get()
				tmp411 := lang.Apply1(tmp410, new_parents395)
				tmp412 := lang.Apply2(tmp396, tmp409, tmp411)
				var deriv_seq413 any = tmp412
				_ = deriv_seq413
				tmp414 := v_clojure_DOT_core_contains_QMARK_.Get()
				tmp415 := lang.Apply1(parent_map380, tag376)
				tmp416 := lang.Apply2(tmp414, tmp415, parent377)
				var tmp417 any
				_ = tmp417
				if lang.IsTruthy(tmp416) {
					tmp418 := v_clojure_DOT_core_reduce.Get()
					tmp419 := lang.FnFunc2(func(hh420, pair421 any) any {
						tmp422 := v_clojure_DOT_core_apply.Get()
						tmp423 := v_clojure_DOT_core_derive.Get()
						tmp424 := lang.Apply3(tmp422, tmp423, hh420, pair421)
						return tmp424
					})
					tmp425 := &lang.NamedFn2{Name: "fn", Expects: "2: [hh pair]", F: tmp419}
					tmp426 := v_clojure_DOT_core_make_hierarchy.Get()
					tmp427 := lang.Apply0(tmp426)
					tmp428 := v_clojure_DOT_core_partition.Get()
					tmp429 := lang.Apply2(tmp428, int64(2), deriv_seq413)
					tmp430 := lang.Apply3(tmp418, tmp425, tmp427, tmp429)
					tmp417 = tmp430
				} else {
					tmp417 = h375
				}
				tmp378 = tmp417
			}
			return tmp378
		default:
			panic(lang.NewArityError(len(args), "clojure.core/underive", "2: [tag parent] or 3: [h tag parent]"))
		}
	})
	v_clojure_DOT_core_underive.BindRoot(tmp369)
	_ = v_clojure_DOT_core_underive
}
