package reader

// S8 golden conformance for syntax-quote (design/01-reader.md §2, §5 v1).
//
// testdata/syntax_quote_golden.txt is a verbatim copy of
// spikes/s8-syntax-quote-harness/golden.txt: 58 cases generated by
// real JVM Clojure 1.12.5 (gen_golden.clj, ns user, pr-str of the
// unevaluated read-string expansion), gensym ids normalized per case.
// The normalizer (normalizeGensyms) and golden parser below are
// copied from that spike's normalize/ and harness/ packages
// (trimmed); the spike directory itself is left untouched.

import (
	"bufio"
	"errors"
	"os"
	"regexp"
	"strconv"
	"strings"
	"testing"

	"github.com/muthuishere/cljgo/pkg/lang"
)

// gensymRe matches the numeric id of Clojure-style generated symbols:
// name__NNN__auto__ (auto-gensym x#) and pN__NNN# (#() arg hygiene).
// Copied from spikes/s8-syntax-quote-harness/normalize/normalize.go.
var gensymRe = regexp.MustCompile(`__([0-9]+)(__auto__|#)`)

// normalizeGensyms rewrites every gensym id in s to a stable id
// numbered by order of first appearance, starting at 1. Identical ids
// map to identical replacements and distinct ids stay distinct, so
// hygiene properties survive normalization. Applied to BOTH the
// golden output and our reader's output before comparing.
func normalizeGensyms(s string) string {
	seen := map[string]int{}
	next := 1
	return gensymRe.ReplaceAllStringFunc(s, func(m string) string {
		sub := gensymRe.FindStringSubmatch(m)
		id, ok := seen[sub[1]]
		if !ok {
			id = next
			seen[sub[1]] = id
			next++
		}
		return "__" + strconv.Itoa(id) + sub[2]
	})
}

// sqGoldenCase is one record of the golden file.
type sqGoldenCase struct {
	input   string // reader input, e.g. "`(a ~b)"
	golden  string // normalized pr-str of the JVM expansion; "" when wantErr
	wantErr bool   // JVM Clojure's reader threw on this input
	errKind string // JVM exception simple class name (informational only)
}

// loadSQGolden parses blank-line-separated "IN: ..." / "OK: ..."-or-
// "ERR: ..." records; ";;" lines are comments. Trimmed copy of
// spikes/s8-syntax-quote-harness/harness.ParseGolden.
func loadSQGolden(t *testing.T, path string) []sqGoldenCase {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer f.Close()

	var cases []sqGoldenCase
	var cur *sqGoldenCase
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	lineNo := 0
	for sc.Scan() {
		lineNo++
		line := sc.Text()
		switch {
		case strings.HasPrefix(line, ";;"), strings.TrimSpace(line) == "":
			// comment / record separator
		case strings.HasPrefix(line, "IN: "):
			if cur != nil {
				t.Fatalf("golden line %d: record %q has IN: but no OK:/ERR:", lineNo, cur.input)
			}
			cur = &sqGoldenCase{input: line[len("IN: "):]}
		case strings.HasPrefix(line, "OK: "):
			if cur == nil {
				t.Fatalf("golden line %d: OK: without preceding IN:", lineNo)
			}
			cur.golden = normalizeGensyms(line[len("OK: "):])
			cases = append(cases, *cur)
			cur = nil
		case strings.HasPrefix(line, "ERR: "):
			if cur == nil {
				t.Fatalf("golden line %d: ERR: without preceding IN:", lineNo)
			}
			cur.wantErr = true
			cur.errKind = line[len("ERR: "):]
			cases = append(cases, *cur)
			cur = nil
		default:
			t.Fatalf("golden line %d: unrecognized line %q", lineNo, line)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("scan golden: %v", err)
	}
	if cur != nil {
		t.Fatalf("golden truncated: record %q has IN: but no OK:/ERR:", cur.input)
	}
	return cases
}

// jvmUserResolver mimics the environment the goldens were generated
// in: JVM Clojure ns `user`, which refers all clojure.core publics
// and has no aliases and no relevant classes. ResolveVar therefore
// resolves exactly the clojure.core names the corpus uses; everything
// else qualifies to user/.
type jvmUserResolver struct{}

func (jvmUserResolver) CurrentNS() *lang.Symbol                  { return lang.NewSymbol("user") }
func (jvmUserResolver) ResolveAlias(s *lang.Symbol) *lang.Symbol { return nil }
func (jvmUserResolver) ResolveType(s *lang.Symbol) *lang.Symbol  { return nil }
func (jvmUserResolver) ResolveVar(s *lang.Symbol) *lang.Symbol {
	// Subset of clojure.core vars sufficient for the S8 corpus (the
	// JVM refers all of core; only these names appear unqualified).
	coreVars := map[string]bool{
		"fn?": true, "list": true, "let": true, "when": true,
		"map": true, "vector": true, "concat": true, "seq": true,
		"apply": true, "hash-map": true, "hash-set": true,
		"with-meta": true, "first": true, "str": true, "inc": true,
	}
	if coreVars[s.Name()] {
		return lang.InternSymbol("clojure.core", s.Name())
	}
	return nil
}

// TestSyntaxQuoteGoldenConformance runs all 58 S8 goldens: our
// ReadString (which performs syntax-quote expansion at read time) +
// a pr-str-compatible printer vs the JVM's pr-str, both sides
// gensym-normalized. lang.PrintString matched Clojure pr-str
// byte-for-byte on every golden form; printForm (syntaxquote_test.go)
// is used anyway because it fixes lang.PrintString's one divergence —
// the empty list prints "(nil)" — which #() bodies can hit.
func TestSyntaxQuoteGoldenConformance(t *testing.T) {
	cases := loadSQGolden(t, "testdata/syntax_quote_golden.txt")
	if len(cases) != 58 {
		t.Fatalf("expected 58 golden cases, loaded %d", len(cases))
	}
	for _, c := range cases {
		t.Run(c.input, func(t *testing.T) {
			form, err := ReadString(c.input, WithResolver(jvmUserResolver{}))
			if c.wantErr {
				// The harness contract requires only that we error;
				// exception class names are informational.
				if err == nil {
					t.Fatalf("want error (JVM threw %s), got %s",
						c.errKind, lang.PrintString(form))
				}
				if errors.Is(err, ErrEOF) {
					t.Fatalf("malformed input must not surface as clean ErrEOF")
				}
				return
			}
			if err != nil {
				t.Fatalf("read error: %v", err)
			}
			got := normalizeGensyms(printForm(form))
			if got != c.golden {
				t.Errorf("expansion mismatch\n want: %s\n  got: %s", c.golden, got)
			}
		})
	}
}
