// Code generated by cljgo build. DO NOT EDIT.

package bricliauth

import (
	rt "github.com/muthuishere/cljgo/pkg/emit/rt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_account                                  = lang.InternKeywordString("account")
	kw_as                                       = lang.InternKeywordString("as")
	kw_bri_DOT_cli_DOT_auth_SLASH_no_credential = lang.InternKeywordString("bri.cli.auth/no-credential")
	kw_bri_SLASH_error                          = lang.InternKeywordString("bri/error")
	kw_column                                   = lang.InternKeywordString("column")
	kw_doc                                      = lang.InternKeywordString("doc")
	kw_end_column                               = lang.InternKeywordString("end-column")
	kw_end_line                                 = lang.InternKeywordString("end-line")
	kw_file                                     = lang.InternKeywordString("file")
	kw_key                                      = lang.InternKeywordString("key")
	kw_label                                    = lang.InternKeywordString("label")
	kw_line                                     = lang.InternKeywordString("line")
	kw_private                                  = lang.InternKeywordString("private")
	kw_scheme                                   = lang.InternKeywordString("scheme")
	kw_service                                  = lang.InternKeywordString("service")
	sym_bri_DOT_cli                             = lang.NewSymbol("bri.cli")
	sym_bri_DOT_cli_DOT_auth                    = lang.NewSymbol("bri.cli.auth")
	sym_cli                                     = lang.NewSymbol("cli")
	sym_cljg_DOT_secrets                        = lang.NewSymbol("cljg.secrets")
	sym_clojure_DOT_core                        = lang.NewSymbol("clojure.core")
	sym_clojure_DOT_string                      = lang.NewSymbol("clojure.string")
	sym_secrets                                 = lang.NewSymbol("secrets")
	sym_str                                     = lang.NewSymbol("str")
	v_bri_DOT_cli_DOT_auth_account              = lang.InternVarName(lang.NewSymbol("bri.cli.auth"), lang.NewSymbol("account")).SetPrivate()
	v_bri_DOT_cli_DOT_auth_auth_header          = lang.InternVarName(lang.NewSymbol("bri.cli.auth"), lang.NewSymbol("auth-header"))
	v_bri_DOT_cli_DOT_auth_authed_QMARK_        = lang.InternVarName(lang.NewSymbol("bri.cli.auth"), lang.NewSymbol("authed?"))
	v_bri_DOT_cli_DOT_auth_default_account      = lang.InternVarName(lang.NewSymbol("bri.cli.auth"), lang.NewSymbol("default-account")).SetPrivate()
	v_bri_DOT_cli_DOT_auth_login                = lang.InternVarName(lang.NewSymbol("bri.cli.auth"), lang.NewSymbol("login"))
	v_bri_DOT_cli_DOT_auth_logout               = lang.InternVarName(lang.NewSymbol("bri.cli.auth"), lang.NewSymbol("logout"))
	v_bri_DOT_cli_DOT_auth_token                = lang.InternVarName(lang.NewSymbol("bri.cli.auth"), lang.NewSymbol("token"))
	v_bri_DOT_cli_ask_secret                    = lang.InternVarName(lang.NewSymbol("bri.cli"), lang.NewSymbol("ask-secret"))
	v_cljg_DOT_secrets_delete_                  = lang.InternVarName(lang.NewSymbol("cljg.secrets"), lang.NewSymbol("delete"))
	v_cljg_DOT_secrets_get                      = lang.InternVarName(lang.NewSymbol("cljg.secrets"), lang.NewSymbol("get"))
	v_cljg_DOT_secrets_reveal                   = lang.InternVarName(lang.NewSymbol("cljg.secrets"), lang.NewSymbol("reveal"))
	v_cljg_DOT_secrets_set                      = lang.InternVarName(lang.NewSymbol("cljg.secrets"), lang.NewSymbol("set"))
	v_clojure_DOT_core_boolean                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("boolean"))
	v_clojure_DOT_core_ex_info                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("ex-info"))
	v_clojure_DOT_core_in_ns                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_refer                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
	v_clojure_DOT_core_require                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("require"))
	v_clojure_DOT_core_str                      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("str"))
	v_clojure_DOT_string_blank_QMARK_           = lang.InternVarName(lang.NewSymbol("clojure.string"), lang.NewSymbol("blank?"))
)

var (
	fnD_bri_DOT_cli_DOT_auth_account lang.FnFunc1
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("bri.cli.auth")), lang.VarFile, "bri/cli_auth.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote bri.cli.auth))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_bri_DOT_cli_DOT_auth)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply1(tmp3, sym_clojure_DOT_core)
	_ = tmp4
	// (require (quote [clojure.string :as str]))
	tmp5 := v_clojure_DOT_core_require.Get()
	tmp6 := lang.Apply1(tmp5, lang.NewVector(sym_clojure_DOT_string, kw_as, sym_str))
	_ = tmp6
	// (require (quote [bri.cli :as cli]))
	tmp7 := v_clojure_DOT_core_require.Get()
	tmp8 := lang.Apply1(tmp7, lang.NewVector(sym_bri_DOT_cli, kw_as, sym_cli))
	_ = tmp8
	// (require (quote [cljg.secrets :as secrets]))
	tmp9 := v_clojure_DOT_core_require.Get()
	tmp10 := lang.Apply1(tmp9, lang.NewVector(sym_cljg_DOT_secrets, kw_as, sym_secrets))
	_ = tmp10
	// (def default-account "token")
	v_bri_DOT_cli_DOT_auth_default_account.SetMeta(lang.NewMap(kw_file, "bri/cli_auth.cljg", kw_line, int64(34), kw_column, int64(6), kw_end_line, int64(34), kw_end_column, int64(31), kw_private, true))
	v_bri_DOT_cli_DOT_auth_default_account.BindRoot("token")
	_ = v_bri_DOT_cli_DOT_auth_default_account
	// (def account (clojure.core/fn [opts] (:account opts default-account)))
	v_bri_DOT_cli_DOT_auth_account.SetMeta(lang.NewMap(kw_file, "bri/cli_auth.cljg", kw_line, int64(36), kw_column, int64(8), kw_end_line, int64(36), kw_end_column, int64(15), kw_private, true))
	tmp11 := lang.FnFunc1(func(opts12 any) any {
		tmp13 := v_bri_DOT_cli_DOT_auth_default_account.Get()
		tmp14 := lang.Apply2(kw_account, opts12, tmp13)
		return tmp14
	})
	tmp15 := &lang.NamedFn1{Name: "bri.cli.auth/account", Expects: "1: [opts]", F: tmp11}
	v_bri_DOT_cli_DOT_auth_account.BindRoot(tmp15)
	fnD_bri_DOT_cli_DOT_auth_account = tmp15.F
	v_bri_DOT_cli_DOT_auth_account.SealDirect()
	_ = v_bri_DOT_cli_DOT_auth_account
	// (def login "Obtain and store a credential for `service` in the OS keychain. With no\n  :ke…
	v_bri_DOT_cli_DOT_auth_login.SetMeta(lang.NewMap(kw_file, "bri/cli_auth.cljg", kw_line, int64(38), kw_column, int64(7), kw_end_line, int64(38), kw_end_column, int64(12), kw_doc, "Obtain and store a credential for `service` in the OS keychain. With no\n  :key, prompts for it with terminal echo off (bri.cli/ask-secret). Returns\n  `service`. opts: :key (skip the prompt), :account (default \"token\"),\n  :label (prompt text). Throws bri.cli.auth/no-credential on an empty value."))
	tmp16 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			service17 := args[0]
			_ = service17
			tmp18 := v_bri_DOT_cli_DOT_auth_login.Get()
			tmp19 := lang.NewMap()
			tmp20 := lang.Apply2(tmp18, service17, tmp19)
			return tmp20
		case 2:
			service21 := args[0]
			_ = service21
			opts22 := args[1]
			_ = opts22
			var tmp23 any
			_ = tmp23
			{
				var tmp24 any
				_ = tmp24
				{
					tmp25 := lang.Apply1(kw_key, opts22)
					var or__2__auto__26 any = tmp25
					_ = or__2__auto__26
					var tmp27 any
					_ = tmp27
					if lang.IsTruthy(or__2__auto__26) {
						tmp27 = or__2__auto__26
					} else {
						tmp28 := v_bri_DOT_cli_ask_secret.Get()
						var tmp29 any
						_ = tmp29
						{
							tmp30 := lang.Apply1(kw_label, opts22)
							var or__2__auto__31 any = tmp30
							_ = or__2__auto__31
							var tmp32 any
							_ = tmp32
							if lang.IsTruthy(or__2__auto__31) {
								tmp32 = or__2__auto__31
							} else {
								tmp33 := v_clojure_DOT_core_str.Get()
								tmp34 := lang.Apply2(tmp33, "API key for ", service21)
								tmp32 = tmp34
							}
							tmp29 = tmp32
						}
						tmp35 := lang.Apply1(tmp28, tmp29)
						tmp27 = tmp35
					}
					tmp24 = tmp27
				}
				var key36 any = tmp24
				_ = key36
				tmp37 := v_clojure_DOT_string_blank_QMARK_.Get()
				tmp38 := v_clojure_DOT_core_str.Get()
				tmp39 := lang.Apply1(tmp38, key36)
				tmp40 := lang.Apply1(tmp37, tmp39)
				var tmp41 any
				_ = tmp41
				if lang.IsTruthy(tmp40) {
					tmp42 := v_clojure_DOT_core_ex_info.Get()
					tmp43 := v_clojure_DOT_core_str.Get()
					tmp44 := lang.Apply2(tmp43, "bri.cli.auth/login: no credential provided for ", service21)
					tmp45 := lang.NewMap(kw_bri_SLASH_error, kw_bri_DOT_cli_DOT_auth_SLASH_no_credential, kw_service, service21)
					tmp46 := lang.Apply2(tmp42, tmp44, tmp45)
					panic(rt.Throw(tmp46))
				} else {
					tmp41 = nil
				}
				_ = tmp41
				tmp47 := v_cljg_DOT_secrets_set.Get()
				tmp48 := v_bri_DOT_cli_DOT_auth_account.Direct()
				var tmp49 any
				if !tmp48 {
					tmp49 = v_bri_DOT_cli_DOT_auth_account.Get()
				}
				var tmp50 any
				if tmp48 {
					tmp50 = fnD_bri_DOT_cli_DOT_auth_account(opts22)
				} else {
					tmp50 = lang.Apply1(tmp49, opts22)
				}
				tmp51 := v_clojure_DOT_core_str.Get()
				tmp52 := lang.Apply1(tmp51, key36)
				tmp53 := lang.Apply3(tmp47, service21, tmp50, tmp52)
				_ = tmp53
				tmp23 = service21
			}
			return tmp23
		default:
			panic(lang.NewArityError(len(args), "bri.cli.auth/login", "1: [service] or 2: [service opts]"))
		}
	})
	v_bri_DOT_cli_DOT_auth_login.BindRoot(tmp16)
	_ = v_bri_DOT_cli_DOT_auth_login
	// (def token "The stored credential for `service` as a MASKED secret (use\n  cljg.secrets/re…
	v_bri_DOT_cli_DOT_auth_token.SetMeta(lang.NewMap(kw_file, "bri/cli_auth.cljg", kw_line, int64(53), kw_column, int64(7), kw_end_line, int64(53), kw_end_column, int64(12), kw_doc, "The stored credential for `service` as a MASKED secret (use\n  cljg.secrets/reveal for the plaintext), or nil if not logged in."))
	tmp54 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			service55 := args[0]
			_ = service55
			tmp56 := v_bri_DOT_cli_DOT_auth_token.Get()
			tmp57 := lang.NewMap()
			tmp58 := lang.Apply2(tmp56, service55, tmp57)
			return tmp58
		case 2:
			service59 := args[0]
			_ = service59
			opts60 := args[1]
			_ = opts60
			tmp61 := v_cljg_DOT_secrets_get.Get()
			tmp62 := v_bri_DOT_cli_DOT_auth_account.Direct()
			var tmp63 any
			if !tmp62 {
				tmp63 = v_bri_DOT_cli_DOT_auth_account.Get()
			}
			var tmp64 any
			if tmp62 {
				tmp64 = fnD_bri_DOT_cli_DOT_auth_account(opts60)
			} else {
				tmp64 = lang.Apply1(tmp63, opts60)
			}
			tmp65 := lang.Apply2(tmp61, service59, tmp64)
			return tmp65
		default:
			panic(lang.NewArityError(len(args), "bri.cli.auth/token", "1: [service] or 2: [service opts]"))
		}
	})
	v_bri_DOT_cli_DOT_auth_token.BindRoot(tmp54)
	_ = v_bri_DOT_cli_DOT_auth_token
	// (def authed? "Is there a stored credential for `service`?" (clojure.core/fn ([service] (au…
	v_bri_DOT_cli_DOT_auth_authed_QMARK_.SetMeta(lang.NewMap(kw_file, "bri/cli_auth.cljg", kw_line, int64(59), kw_column, int64(7), kw_end_line, int64(59), kw_end_column, int64(14), kw_doc, "Is there a stored credential for `service`?"))
	tmp66 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			service67 := args[0]
			_ = service67
			tmp68 := v_bri_DOT_cli_DOT_auth_authed_QMARK_.Get()
			tmp69 := lang.NewMap()
			tmp70 := lang.Apply2(tmp68, service67, tmp69)
			return tmp70
		case 2:
			service71 := args[0]
			_ = service71
			opts72 := args[1]
			_ = opts72
			tmp73 := v_clojure_DOT_core_boolean.Get()
			tmp74 := v_bri_DOT_cli_DOT_auth_token.Get()
			tmp75 := lang.Apply2(tmp74, service71, opts72)
			tmp76 := lang.Apply1(tmp73, tmp75)
			return tmp76
		default:
			panic(lang.NewArityError(len(args), "bri.cli.auth/authed?", "1: [service] or 2: [service opts]"))
		}
	})
	v_bri_DOT_cli_DOT_auth_authed_QMARK_.BindRoot(tmp66)
	_ = v_bri_DOT_cli_DOT_auth_authed_QMARK_
	// (def logout "Remove the stored credential for `service`. Returns `service`." (clojure.core…
	v_bri_DOT_cli_DOT_auth_logout.SetMeta(lang.NewMap(kw_file, "bri/cli_auth.cljg", kw_line, int64(64), kw_column, int64(7), kw_end_line, int64(64), kw_end_column, int64(13), kw_doc, "Remove the stored credential for `service`. Returns `service`."))
	tmp77 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			service78 := args[0]
			_ = service78
			tmp79 := v_bri_DOT_cli_DOT_auth_logout.Get()
			tmp80 := lang.NewMap()
			tmp81 := lang.Apply2(tmp79, service78, tmp80)
			return tmp81
		case 2:
			service82 := args[0]
			_ = service82
			opts83 := args[1]
			_ = opts83
			tmp84 := v_cljg_DOT_secrets_delete_.Get()
			tmp85 := v_bri_DOT_cli_DOT_auth_account.Direct()
			var tmp86 any
			if !tmp85 {
				tmp86 = v_bri_DOT_cli_DOT_auth_account.Get()
			}
			var tmp87 any
			if tmp85 {
				tmp87 = fnD_bri_DOT_cli_DOT_auth_account(opts83)
			} else {
				tmp87 = lang.Apply1(tmp86, opts83)
			}
			tmp88 := lang.Apply2(tmp84, service82, tmp87)
			_ = tmp88
			return service82
		default:
			panic(lang.NewArityError(len(args), "bri.cli.auth/logout", "1: [service] or 2: [service opts]"))
		}
	})
	v_bri_DOT_cli_DOT_auth_logout.BindRoot(tmp77)
	_ = v_bri_DOT_cli_DOT_auth_logout
	// (def auth-header "Build an Authorization header map from the stored credential, or nil if …
	v_bri_DOT_cli_DOT_auth_auth_header.SetMeta(lang.NewMap(kw_file, "bri/cli_auth.cljg", kw_line, int64(69), kw_column, int64(7), kw_end_line, int64(69), kw_end_column, int64(18), kw_doc, "Build an Authorization header map from the stored credential, or nil if not\n  logged in. This is an explicit UNMASK point — the plaintext credential enters\n  the returned map so you can attach it to a request. opts: :scheme (default\n  \"Bearer\"; use \"\" for a bare token, e.g. an API-key header value)."))
	tmp89 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			service90 := args[0]
			_ = service90
			tmp91 := v_bri_DOT_cli_DOT_auth_auth_header.Get()
			tmp92 := lang.NewMap()
			tmp93 := lang.Apply2(tmp91, service90, tmp92)
			return tmp93
		case 2:
			service94 := args[0]
			_ = service94
			opts95 := args[1]
			_ = opts95
			var tmp96 any
			_ = tmp96
			{
				tmp97 := v_bri_DOT_cli_DOT_auth_token.Get()
				tmp98 := lang.Apply2(tmp97, service94, opts95)
				var temp__5__auto__99 any = tmp98
				_ = temp__5__auto__99
				var tmp100 any
				_ = tmp100
				if lang.IsTruthy(temp__5__auto__99) {
					var tmp101 any
					_ = tmp101
					{
						var t102 any = temp__5__auto__99
						_ = t102
						var tmp103 any
						_ = tmp103
						{
							tmp104 := lang.Apply2(kw_scheme, opts95, "Bearer")
							var scheme105 any = tmp104
							_ = scheme105
							tmp106 := v_cljg_DOT_secrets_reveal.Get()
							tmp107 := lang.Apply1(tmp106, t102)
							var raw108 any = tmp107
							_ = raw108
							tmp109 := v_clojure_DOT_string_blank_QMARK_.Get()
							tmp110 := lang.Apply1(tmp109, scheme105)
							var tmp111 any
							_ = tmp111
							if lang.IsTruthy(tmp110) {
								tmp111 = raw108
							} else {
								tmp112 := v_clojure_DOT_core_str.Get()
								tmp113 := lang.Apply3(tmp112, scheme105, " ", raw108)
								tmp111 = tmp113
							}
							tmp114 := lang.NewMap("Authorization", tmp111)
							tmp103 = tmp114
						}
						tmp101 = tmp103
					}
					tmp100 = tmp101
				} else {
					tmp100 = nil
				}
				tmp96 = tmp100
			}
			return tmp96
		default:
			panic(lang.NewArityError(len(args), "bri.cli.auth/auth-header", "1: [service] or 2: [service opts]"))
		}
	})
	v_bri_DOT_cli_DOT_auth_auth_header.BindRoot(tmp89)
	_ = v_bri_DOT_cli_DOT_auth_auth_header
}
