// Code generated by cljgo build. DO NOT EDIT.

package cljwalk

import (
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_column                           = lang.InternKeywordString("column")
	kw_doc                              = lang.InternKeywordString("doc")
	kw_else_                            = lang.InternKeywordString("else")
	kw_end_column                       = lang.InternKeywordString("end-column")
	kw_end_line                         = lang.InternKeywordString("end-line")
	kw_file                             = lang.InternKeywordString("file")
	kw_line                             = lang.InternKeywordString("line")
	sym_clojure_DOT_core                = lang.NewSymbol("clojure.core")
	sym_clojure_DOT_walk                = lang.NewSymbol("clojure.walk")
	v_clojure_DOT_core_apply            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("apply"))
	v_clojure_DOT_core_coll_QMARK_      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("coll?"))
	v_clojure_DOT_core_conj             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("conj"))
	v_clojure_DOT_core_contains_QMARK_  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("contains?"))
	v_clojure_DOT_core_doall            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("doall"))
	v_clojure_DOT_core_empty            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("empty"))
	v_clojure_DOT_core_identity         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("identity"))
	v_clojure_DOT_core_in_ns            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_into             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("into"))
	v_clojure_DOT_core_key              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("key"))
	v_clojure_DOT_core_keyword          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("keyword"))
	v_clojure_DOT_core_keyword_QMARK_   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("keyword?"))
	v_clojure_DOT_core_list             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("list"))
	v_clojure_DOT_core_list_QMARK_      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("list?"))
	v_clojure_DOT_core_macroexpand      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("macroexpand"))
	v_clojure_DOT_core_map_             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("map"))
	v_clojure_DOT_core_map_QMARK_       = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("map?"))
	v_clojure_DOT_core_map_entry_QMARK_ = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("map-entry?"))
	v_clojure_DOT_core_name             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("name"))
	v_clojure_DOT_core_nth              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("nth"))
	v_clojure_DOT_core_partial          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("partial"))
	v_clojure_DOT_core_print_           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("print"))
	v_clojure_DOT_core_prn              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("prn"))
	v_clojure_DOT_core_record_QMARK_    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("record?"))
	v_clojure_DOT_core_reduce           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("reduce"))
	v_clojure_DOT_core_refer            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
	v_clojure_DOT_core_seq_QMARK_       = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("seq?"))
	v_clojure_DOT_core_string_QMARK_    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("string?"))
	v_clojure_DOT_core_val              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("val"))
	v_clojure_DOT_walk_keywordize_keys  = lang.InternVarName(lang.NewSymbol("clojure.walk"), lang.NewSymbol("keywordize-keys"))
	v_clojure_DOT_walk_macroexpand_all  = lang.InternVarName(lang.NewSymbol("clojure.walk"), lang.NewSymbol("macroexpand-all"))
	v_clojure_DOT_walk_postwalk         = lang.InternVarName(lang.NewSymbol("clojure.walk"), lang.NewSymbol("postwalk"))
	v_clojure_DOT_walk_postwalk_demo    = lang.InternVarName(lang.NewSymbol("clojure.walk"), lang.NewSymbol("postwalk-demo"))
	v_clojure_DOT_walk_postwalk_replace = lang.InternVarName(lang.NewSymbol("clojure.walk"), lang.NewSymbol("postwalk-replace"))
	v_clojure_DOT_walk_prewalk          = lang.InternVarName(lang.NewSymbol("clojure.walk"), lang.NewSymbol("prewalk"))
	v_clojure_DOT_walk_prewalk_demo     = lang.InternVarName(lang.NewSymbol("clojure.walk"), lang.NewSymbol("prewalk-demo"))
	v_clojure_DOT_walk_prewalk_replace  = lang.InternVarName(lang.NewSymbol("clojure.walk"), lang.NewSymbol("prewalk-replace"))
	v_clojure_DOT_walk_stringify_keys   = lang.InternVarName(lang.NewSymbol("clojure.walk"), lang.NewSymbol("stringify-keys"))
	v_clojure_DOT_walk_walk             = lang.InternVarName(lang.NewSymbol("clojure.walk"), lang.NewSymbol("walk"))
)

func fnL_fn(x84 int64) int64 {
	_ = x84
	tmp85 := v_clojure_DOT_core_print_.Get()
	tmp86 := lang.Apply1(tmp85, "Walked: ")
	_ = tmp86
	tmp87 := v_clojure_DOT_core_prn.Get()
	tmp88 := lang.Apply1(tmp87, x84)
	_ = tmp88
	return x84
}

func fnL_fn_2(x100 int64) int64 {
	_ = x100
	tmp101 := v_clojure_DOT_core_print_.Get()
	tmp102 := lang.Apply1(tmp101, "Walked: ")
	_ = tmp102
	tmp103 := v_clojure_DOT_core_prn.Get()
	tmp104 := lang.Apply1(tmp103, x100)
	_ = tmp104
	return x100
}

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("clojure.walk")), lang.VarFile, "walk.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote clojure.walk))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_clojure_DOT_walk)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply1(tmp3, sym_clojure_DOT_core)
	_ = tmp4
	// (def walk "Traverses form, an arbitrary data structure.  inner and outer are\n  functions.…
	v_clojure_DOT_walk_walk.SetMeta(lang.NewMap(kw_file, "walk.cljg", kw_line, int64(31), kw_column, int64(7), kw_end_line, int64(31), kw_end_column, int64(11), kw_doc, "Traverses form, an arbitrary data structure.  inner and outer are\n  functions.  Applies inner to each element of form, building up a\n  data structure of the same type, then applies outer to the result.\n  Recognizes all Clojure data structures. Consumes seqs as with doall."))
	tmp5 := lang.FnFunc3(func(inner6, outer7, form8 any) any {
		tmp9 := v_clojure_DOT_core_list_QMARK_.Get()
		tmp10 := lang.Apply1(tmp9, form8)
		var tmp11 any
		_ = tmp11
		if lang.IsTruthy(tmp10) {
			tmp12 := v_clojure_DOT_core_apply.Get()
			tmp13 := v_clojure_DOT_core_list.Get()
			tmp14 := v_clojure_DOT_core_map_.Get()
			tmp15 := lang.Apply2(tmp14, inner6, form8)
			tmp16 := lang.Apply2(tmp12, tmp13, tmp15)
			tmp17 := lang.Apply1(outer7, tmp16)
			tmp11 = tmp17
		} else {
			tmp18 := v_clojure_DOT_core_map_entry_QMARK_.Get()
			tmp19 := lang.Apply1(tmp18, form8)
			var tmp20 any
			_ = tmp20
			if lang.IsTruthy(tmp19) {
				tmp21 := v_clojure_DOT_core_key.Get()
				tmp22 := lang.Apply1(tmp21, form8)
				tmp23 := lang.Apply1(inner6, tmp22)
				tmp24 := v_clojure_DOT_core_val.Get()
				tmp25 := lang.Apply1(tmp24, form8)
				tmp26 := lang.Apply1(inner6, tmp25)
				tmp27 := lang.NewVector(tmp23, tmp26)
				tmp28 := lang.Apply1(outer7, tmp27)
				tmp20 = tmp28
			} else {
				tmp29 := v_clojure_DOT_core_seq_QMARK_.Get()
				tmp30 := lang.Apply1(tmp29, form8)
				var tmp31 any
				_ = tmp31
				if lang.IsTruthy(tmp30) {
					tmp32 := v_clojure_DOT_core_doall.Get()
					tmp33 := v_clojure_DOT_core_map_.Get()
					tmp34 := lang.Apply2(tmp33, inner6, form8)
					tmp35 := lang.Apply1(tmp32, tmp34)
					tmp36 := lang.Apply1(outer7, tmp35)
					tmp31 = tmp36
				} else {
					tmp37 := v_clojure_DOT_core_record_QMARK_.Get()
					tmp38 := lang.Apply1(tmp37, form8)
					var tmp39 any
					_ = tmp39
					if lang.IsTruthy(tmp38) {
						tmp40 := v_clojure_DOT_core_reduce.Get()
						tmp41 := lang.FnFunc2(func(r42, x43 any) any {
							tmp44 := v_clojure_DOT_core_conj.Get()
							tmp45 := lang.Apply1(inner6, x43)
							tmp46 := lang.Apply2(tmp44, r42, tmp45)
							return tmp46
						})
						tmp47 := lang.Apply3(tmp40, tmp41, form8, form8)
						tmp48 := lang.Apply1(outer7, tmp47)
						tmp39 = tmp48
					} else {
						tmp49 := v_clojure_DOT_core_coll_QMARK_.Get()
						tmp50 := lang.Apply1(tmp49, form8)
						var tmp51 any
						_ = tmp51
						if lang.IsTruthy(tmp50) {
							tmp52 := v_clojure_DOT_core_into.Get()
							tmp53 := v_clojure_DOT_core_empty.Get()
							tmp54 := lang.Apply1(tmp53, form8)
							tmp55 := v_clojure_DOT_core_map_.Get()
							tmp56 := lang.Apply2(tmp55, inner6, form8)
							tmp57 := lang.Apply2(tmp52, tmp54, tmp56)
							tmp58 := lang.Apply1(outer7, tmp57)
							tmp51 = tmp58
						} else {
							var tmp59 any
							_ = tmp59
							if lang.IsTruthy(kw_else_) {
								tmp60 := lang.Apply1(outer7, form8)
								tmp59 = tmp60
							} else {
								tmp59 = nil
							}
							tmp51 = tmp59
						}
						tmp39 = tmp51
					}
					tmp31 = tmp39
				}
				tmp20 = tmp31
			}
			tmp11 = tmp20
		}
		return tmp11
	})
	v_clojure_DOT_walk_walk.BindRoot(tmp5)
	_ = v_clojure_DOT_walk_walk
	// (def postwalk "Performs a depth-first, post-order traversal of form.  Calls f on\n  each s…
	v_clojure_DOT_walk_postwalk.SetMeta(lang.NewMap(kw_file, "walk.cljg", kw_line, int64(47), kw_column, int64(7), kw_end_line, int64(47), kw_end_column, int64(15), kw_doc, "Performs a depth-first, post-order traversal of form.  Calls f on\n  each sub-form, uses f's return value in place of the original.\n  Recognizes all Clojure data structures. Consumes seqs as with doall."))
	tmp61 := lang.FnFunc2(func(f62, form63 any) any {
		tmp64 := v_clojure_DOT_walk_walk.Get()
		tmp65 := v_clojure_DOT_core_partial.Get()
		tmp66 := v_clojure_DOT_walk_postwalk.Get()
		tmp67 := lang.Apply2(tmp65, tmp66, f62)
		tmp68 := lang.Apply3(tmp64, tmp67, f62, form63)
		return tmp68
	})
	v_clojure_DOT_walk_postwalk.BindRoot(tmp61)
	_ = v_clojure_DOT_walk_postwalk
	// (def prewalk "Like postwalk, but does pre-order traversal." (clojure.core/fn [f form] (wal…
	v_clojure_DOT_walk_prewalk.SetMeta(lang.NewMap(kw_file, "walk.cljg", kw_line, int64(55), kw_column, int64(7), kw_end_line, int64(55), kw_end_column, int64(14), kw_doc, "Like postwalk, but does pre-order traversal."))
	tmp69 := lang.FnFunc2(func(f70, form71 any) any {
		tmp72 := v_clojure_DOT_walk_walk.Get()
		tmp73 := v_clojure_DOT_core_partial.Get()
		tmp74 := v_clojure_DOT_walk_prewalk.Get()
		tmp75 := lang.Apply2(tmp73, tmp74, f70)
		tmp76 := v_clojure_DOT_core_identity.Get()
		tmp77 := lang.Apply1(f70, form71)
		tmp78 := lang.Apply3(tmp72, tmp75, tmp76, tmp77)
		return tmp78
	})
	v_clojure_DOT_walk_prewalk.BindRoot(tmp69)
	_ = v_clojure_DOT_walk_prewalk
	// (def postwalk-demo "Demonstrates the behavior of postwalk by printing each form as it is\n…
	v_clojure_DOT_walk_postwalk_demo.SetMeta(lang.NewMap(kw_file, "walk.cljg", kw_line, int64(62), kw_column, int64(7), kw_end_line, int64(62), kw_end_column, int64(20), kw_doc, "Demonstrates the behavior of postwalk by printing each form as it is\n  walked.  Returns form."))
	tmp79 := lang.FnFunc1(func(form80 any) any {
		tmp81 := v_clojure_DOT_walk_postwalk.Get()
		tmp82 := lang.FnFunc1(func(x83 any) any {
			if a0_89, ok := x83.(int64); ok {
				return fnL_fn(a0_89)
			}
			tmp90 := v_clojure_DOT_core_print_.Get()
			tmp91 := lang.Apply1(tmp90, "Walked: ")
			_ = tmp91
			tmp92 := v_clojure_DOT_core_prn.Get()
			tmp93 := lang.Apply1(tmp92, x83)
			_ = tmp93
			return x83
		})
		tmp94 := lang.Apply2(tmp81, tmp82, form80)
		return tmp94
	})
	v_clojure_DOT_walk_postwalk_demo.BindRoot(tmp79)
	_ = v_clojure_DOT_walk_postwalk_demo
	// (def prewalk-demo "Demonstrates the behavior of prewalk by printing each form as it is\n  …
	v_clojure_DOT_walk_prewalk_demo.SetMeta(lang.NewMap(kw_file, "walk.cljg", kw_line, int64(68), kw_column, int64(7), kw_end_line, int64(68), kw_end_column, int64(19), kw_doc, "Demonstrates the behavior of prewalk by printing each form as it is\n  walked.  Returns form."))
	tmp95 := lang.FnFunc1(func(form96 any) any {
		tmp97 := v_clojure_DOT_walk_prewalk.Get()
		tmp98 := lang.FnFunc1(func(x99 any) any {
			if a0_105, ok := x99.(int64); ok {
				return fnL_fn_2(a0_105)
			}
			tmp106 := v_clojure_DOT_core_print_.Get()
			tmp107 := lang.Apply1(tmp106, "Walked: ")
			_ = tmp107
			tmp108 := v_clojure_DOT_core_prn.Get()
			tmp109 := lang.Apply1(tmp108, x99)
			_ = tmp109
			return x99
		})
		tmp110 := lang.Apply2(tmp97, tmp98, form96)
		return tmp110
	})
	v_clojure_DOT_walk_prewalk_demo.BindRoot(tmp95)
	_ = v_clojure_DOT_walk_prewalk_demo
	// (def keywordize-keys "Recursively transforms all map keys from strings to keywords." (cloj…
	v_clojure_DOT_walk_keywordize_keys.SetMeta(lang.NewMap(kw_file, "walk.cljg", kw_line, int64(76), kw_column, int64(7), kw_end_line, int64(76), kw_end_column, int64(22), kw_doc, "Recursively transforms all map keys from strings to keywords."))
	tmp111 := lang.FnFunc1(func(m112 any) any {
		var tmp113 any
		_ = tmp113
		{
			tmp114 := lang.FnFunc1(func(p__82115 any) any {
				var tmp116 any
				_ = tmp116
				{
					var vec__83117 any = p__82115
					_ = vec__83117
					tmp118 := v_clojure_DOT_core_nth.Get()
					tmp119 := lang.Apply3(tmp118, vec__83117, int64(0), nil)
					var k120 any = tmp119
					_ = k120
					tmp121 := v_clojure_DOT_core_nth.Get()
					tmp122 := lang.Apply3(tmp121, vec__83117, int64(1), nil)
					var v123 any = tmp122
					_ = v123
					tmp124 := v_clojure_DOT_core_string_QMARK_.Get()
					tmp125 := lang.Apply1(tmp124, k120)
					var tmp126 any
					_ = tmp126
					if lang.IsTruthy(tmp125) {
						tmp127 := v_clojure_DOT_core_keyword.Get()
						tmp128 := lang.Apply1(tmp127, k120)
						tmp129 := lang.NewVector(tmp128, v123)
						tmp126 = tmp129
					} else {
						tmp130 := lang.NewVector(k120, v123)
						tmp126 = tmp130
					}
					tmp116 = tmp126
				}
				return tmp116
			})
			var f131 any = tmp114
			_ = f131
			tmp132 := v_clojure_DOT_walk_postwalk.Get()
			tmp133 := lang.FnFunc1(func(x134 any) any {
				tmp135 := v_clojure_DOT_core_map_QMARK_.Get()
				tmp136 := lang.Apply1(tmp135, x134)
				var tmp137 any
				_ = tmp137
				if lang.IsTruthy(tmp136) {
					tmp138 := v_clojure_DOT_core_into.Get()
					tmp139 := lang.NewMap()
					tmp140 := v_clojure_DOT_core_map_.Get()
					tmp141 := lang.Apply2(tmp140, f131, x134)
					tmp142 := lang.Apply2(tmp138, tmp139, tmp141)
					tmp137 = tmp142
				} else {
					tmp137 = x134
				}
				return tmp137
			})
			tmp143 := lang.Apply2(tmp132, tmp133, m112)
			tmp113 = tmp143
		}
		return tmp113
	})
	v_clojure_DOT_walk_keywordize_keys.BindRoot(tmp111)
	_ = v_clojure_DOT_walk_keywordize_keys
	// (def stringify-keys "Recursively transforms all map keys from keywords to strings." (cloju…
	v_clojure_DOT_walk_stringify_keys.SetMeta(lang.NewMap(kw_file, "walk.cljg", kw_line, int64(84), kw_column, int64(7), kw_end_line, int64(84), kw_end_column, int64(21), kw_doc, "Recursively transforms all map keys from keywords to strings."))
	tmp144 := lang.FnFunc1(func(m145 any) any {
		var tmp146 any
		_ = tmp146
		{
			tmp147 := lang.FnFunc1(func(p__86148 any) any {
				var tmp149 any
				_ = tmp149
				{
					var vec__87150 any = p__86148
					_ = vec__87150
					tmp151 := v_clojure_DOT_core_nth.Get()
					tmp152 := lang.Apply3(tmp151, vec__87150, int64(0), nil)
					var k153 any = tmp152
					_ = k153
					tmp154 := v_clojure_DOT_core_nth.Get()
					tmp155 := lang.Apply3(tmp154, vec__87150, int64(1), nil)
					var v156 any = tmp155
					_ = v156
					tmp157 := v_clojure_DOT_core_keyword_QMARK_.Get()
					tmp158 := lang.Apply1(tmp157, k153)
					var tmp159 any
					_ = tmp159
					if lang.IsTruthy(tmp158) {
						tmp160 := v_clojure_DOT_core_name.Get()
						tmp161 := lang.Apply1(tmp160, k153)
						tmp162 := lang.NewVector(tmp161, v156)
						tmp159 = tmp162
					} else {
						tmp163 := lang.NewVector(k153, v156)
						tmp159 = tmp163
					}
					tmp149 = tmp159
				}
				return tmp149
			})
			var f164 any = tmp147
			_ = f164
			tmp165 := v_clojure_DOT_walk_postwalk.Get()
			tmp166 := lang.FnFunc1(func(x167 any) any {
				tmp168 := v_clojure_DOT_core_map_QMARK_.Get()
				tmp169 := lang.Apply1(tmp168, x167)
				var tmp170 any
				_ = tmp170
				if lang.IsTruthy(tmp169) {
					tmp171 := v_clojure_DOT_core_into.Get()
					tmp172 := lang.NewMap()
					tmp173 := v_clojure_DOT_core_map_.Get()
					tmp174 := lang.Apply2(tmp173, f164, x167)
					tmp175 := lang.Apply2(tmp171, tmp172, tmp174)
					tmp170 = tmp175
				} else {
					tmp170 = x167
				}
				return tmp170
			})
			tmp176 := lang.Apply2(tmp165, tmp166, m145)
			tmp146 = tmp176
		}
		return tmp146
	})
	v_clojure_DOT_walk_stringify_keys.BindRoot(tmp144)
	_ = v_clojure_DOT_walk_stringify_keys
	// (def prewalk-replace "Recursively transforms form by replacing keys in smap with their\n  …
	v_clojure_DOT_walk_prewalk_replace.SetMeta(lang.NewMap(kw_file, "walk.cljg", kw_line, int64(92), kw_column, int64(7), kw_end_line, int64(92), kw_end_column, int64(22), kw_doc, "Recursively transforms form by replacing keys in smap with their\n  values.  Like clojure/replace but works on any data structure.  Does\n  replacement at the root of the tree first."))
	tmp177 := lang.FnFunc2(func(smap178, form179 any) any {
		tmp180 := v_clojure_DOT_walk_prewalk.Get()
		tmp181 := lang.FnFunc1(func(x182 any) any {
			tmp183 := v_clojure_DOT_core_contains_QMARK_.Get()
			tmp184 := lang.Apply2(tmp183, smap178, x182)
			var tmp185 any
			_ = tmp185
			if lang.IsTruthy(tmp184) {
				tmp186 := lang.Apply1(smap178, x182)
				tmp185 = tmp186
			} else {
				tmp185 = x182
			}
			return tmp185
		})
		tmp187 := lang.Apply2(tmp180, tmp181, form179)
		return tmp187
	})
	v_clojure_DOT_walk_prewalk_replace.BindRoot(tmp177)
	_ = v_clojure_DOT_walk_prewalk_replace
	// (def postwalk-replace "Recursively transforms form by replacing keys in smap with their\n …
	v_clojure_DOT_walk_postwalk_replace.SetMeta(lang.NewMap(kw_file, "walk.cljg", kw_line, int64(100), kw_column, int64(7), kw_end_line, int64(100), kw_end_column, int64(23), kw_doc, "Recursively transforms form by replacing keys in smap with their\n  values.  Like clojure/replace but works on any data structure.  Does\n  replacement at the leaves of the tree first."))
	tmp188 := lang.FnFunc2(func(smap189, form190 any) any {
		tmp191 := v_clojure_DOT_walk_postwalk.Get()
		tmp192 := lang.FnFunc1(func(x193 any) any {
			tmp194 := v_clojure_DOT_core_contains_QMARK_.Get()
			tmp195 := lang.Apply2(tmp194, smap189, x193)
			var tmp196 any
			_ = tmp196
			if lang.IsTruthy(tmp195) {
				tmp197 := lang.Apply1(smap189, x193)
				tmp196 = tmp197
			} else {
				tmp196 = x193
			}
			return tmp196
		})
		tmp198 := lang.Apply2(tmp191, tmp192, form190)
		return tmp198
	})
	v_clojure_DOT_walk_postwalk_replace.BindRoot(tmp188)
	_ = v_clojure_DOT_walk_postwalk_replace
	// (def macroexpand-all "Recursively performs all possible macroexpansions in form." (clojure…
	v_clojure_DOT_walk_macroexpand_all.SetMeta(lang.NewMap(kw_file, "walk.cljg", kw_line, int64(109), kw_column, int64(7), kw_end_line, int64(109), kw_end_column, int64(22), kw_doc, "Recursively performs all possible macroexpansions in form."))
	tmp199 := lang.FnFunc1(func(form200 any) any {
		tmp201 := v_clojure_DOT_walk_prewalk.Get()
		tmp202 := lang.FnFunc1(func(x203 any) any {
			tmp204 := v_clojure_DOT_core_seq_QMARK_.Get()
			tmp205 := lang.Apply1(tmp204, x203)
			var tmp206 any
			_ = tmp206
			if lang.IsTruthy(tmp205) {
				tmp207 := v_clojure_DOT_core_macroexpand.Get()
				tmp208 := lang.Apply1(tmp207, x203)
				tmp206 = tmp208
			} else {
				tmp206 = x203
			}
			return tmp206
		})
		tmp209 := lang.Apply2(tmp201, tmp202, form200)
		return tmp209
	})
	v_clojure_DOT_walk_macroexpand_all.BindRoot(tmp199)
	_ = v_clojure_DOT_walk_macroexpand_all
}
