// auth_test.go — the T-security behavior suite for bri.auth + the
// bri.http router/observability surface (ADR 0069). Like bri_test.go,
// these have NO JVM oracle (bri does not exist in Clojure 1.12.5), so
// they run as Go tests against the real interpreter — deterministic
// (injected clock, fixed secret, captured sinks), no wall-clock in the
// assertions. The AOT dual-harness lands with the bri-AOT tier; until
// then the interpreter is the single source of truth here.
package bri_test

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"strings"
	"testing"
	"time"
)

// --- JWT: sign / verify / alg-pin -------------------------------------------

func TestJWTSignVerifyRoundTrip(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `(require '[bri.auth :as auth])`)
	// Fixed secret + clock → deterministic.
	tok := evalString(t, d, `(def t (auth/sign {:sub "u1" :role "admin"} {:secret "k" :now 1000 :exp-seconds 100})) t`)
	if strings.Count(tok, ".") != 2 {
		t.Fatalf("token is not a 3-part JWS: %q", tok)
	}
	if v := eval(t, d, `(:sub (auth/verify t {:secret "k" :now 1050}))`); v != "u1" {
		t.Fatalf("verify sub = %v, want u1", v)
	}
	if v := eval(t, d, `(:role (auth/verify t {:secret "k" :now 1050}))`); v != "admin" {
		t.Fatalf("verify role = %v", v)
	}
	// Expired.
	if v := eval(t, d, `(nil? (auth/verify t {:secret "k" :now 2000}))`); v != true {
		t.Fatalf("expired token verified")
	}
	// Wrong secret.
	if v := eval(t, d, `(nil? (auth/verify t {:secret "WRONG" :now 1050}))`); v != true {
		t.Fatalf("token verified under wrong secret")
	}
}

// The token is a REAL HS256 JWS — an independent stdlib check (a second
// implementation) agrees with bri's Go shim on header, payload, and MAC.
func TestJWTIsRealHS256(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `(require '[bri.auth :as auth])`)
	tok := evalString(t, d, `(auth/sign {:sub "x"} {:secret "topsecret" :now 0 :exp-seconds 60})`)
	parts := strings.Split(tok, ".")
	if len(parts) != 3 {
		t.Fatalf("not 3 parts: %q", tok)
	}
	hdr, _ := base64.RawURLEncoding.DecodeString(parts[0])
	if string(hdr) != `{"alg":"HS256","typ":"JWT"}` {
		t.Fatalf("header = %s", hdr)
	}
	mac := hmac.New(sha256.New, []byte("topsecret"))
	mac.Write([]byte(parts[0] + "." + parts[1]))
	want := base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
	if parts[2] != want {
		t.Fatalf("signature mismatch: independent stdlib HMAC disagrees")
	}
	var claims map[string]any
	pl, _ := base64.RawURLEncoding.DecodeString(parts[1])
	if err := json.Unmarshal(pl, &claims); err != nil {
		t.Fatal(err)
	}
	if claims["sub"] != "x" || claims["exp"] == nil || claims["iat"] == nil {
		t.Fatalf("claims wrong: %v", claims)
	}
}

// alg-confusion: a token whose header says alg:none is rejected even if
// the payload is well-formed (the Go verifier pins the header).
func TestJWTRejectsAlgNone(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `(require '[bri.auth :as auth])`)
	forged := "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ1MSJ9."
	got := eval(t, d, fmt.Sprintf(`(nil? (auth/verify %q {:secret "k"}))`, forged))
	if got != true {
		t.Fatalf("alg:none token was accepted — confusion vuln")
	}
}

func TestVerifyBangThrows401(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `(require '[bri.auth :as auth])`)
	if _, err := d.EvalString(`(auth/verify! "garbage" {:secret "k"})`, "auth_test"); err == nil {
		t.Fatal("verify! on garbage did not throw")
	}
}

// --- passwords: argon2id + bcrypt compat ------------------------------------

func TestPasswordHashArgon2(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `(require '[bri.auth :as auth]) (def h (auth/hash-password "hunter2"))`)
	if enc := evalString(t, d, `h`); !strings.HasPrefix(enc, "$argon2id$") {
		t.Fatalf("hash is not argon2id PHC: %q", enc)
	}
	if v := eval(t, d, `(auth/check-password "hunter2" h)`); v != true {
		t.Fatal("correct password rejected")
	}
	if v := eval(t, d, `(auth/check-password "wrong" h)`); v != false {
		t.Fatal("wrong password accepted")
	}
}

func TestPasswordBcryptCompat(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `(require '[bri.auth :as auth])`)
	// A bcrypt hash of "password" (cost 10), generated by golang.org/x/crypto/bcrypt.
	const h = "$2a$10$LSKxLVoNsF5kvysnWgjbuOv.Bstz724wJYpYqL1R/OorwoUO2n.Ka"
	if v := eval(t, d, fmt.Sprintf(`(auth/check-password "password" %q)`, h)); v != true {
		t.Fatal("bcrypt-compat verify failed for a known-good hash")
	}
	if v := eval(t, d, fmt.Sprintf(`(auth/check-password "nope" %q)`, h)); v != false {
		t.Fatal("bcrypt-compat accepted a wrong password")
	}
}

// --- guards: 401 / 403 / claims threading -----------------------------------

const guardPrelude = `
(require '[bri.http :as http] '[bri.auth :as auth])
(defn who [req] {:status 200 :body {:sub (get-in req [:auth/claims :sub])}})
(def rts (http/routes
           (http/GET "/me"    (auth/logged-in-only) #'who)
           (http/GET "/admin" (auth/admin-only)     #'who)))
(def utok (auth/sign {:sub "u" :role "user"}  {:secret "k"}))
(def atok (auth/sign {:sub "a" :role "admin"} {:secret "k"}))
(defn hit [path tok]
  (http/request rts {:method "GET" :path path
                     :headers (if tok {"authorization" (str "Bearer " tok)} {})}
                {:middleware [http/negotiate] :ops false}))
`

func TestGuardDecisions(t *testing.T) {
	d := newDriver(t)
	// Fix the auth secret so tokens verify under the guards' default secret.
	t.Setenv("APP_AUTH__SECRET", "k")
	eval(t, d, guardPrelude)
	cases := []struct {
		path, tok string
		want      int64
	}{
		{"/me", "", 401},
		{"/me", "utok", 200},
		{"/admin", "utok", 403},
		{"/admin", "atok", 200},
	}
	for _, c := range cases {
		tokExpr := "nil"
		if c.tok != "" {
			tokExpr = c.tok
		}
		st := eval(t, d, fmt.Sprintf(`(:status (hit %q %s))`, c.path, tokExpr))
		if st != c.want {
			t.Errorf("%s tok=%s → %v, want %d", c.path, c.tok, st, c.want)
		}
	}
	// claims threaded into the handler.
	if v := eval(t, d, `(:body (http/request rts {:method "GET" :path "/me" :headers {"authorization" (str "Bearer " atok)}} {:middleware [] :ops false}))`); v == nil {
		t.Fatal("no body")
	}
}

// A custom auth/guard predicate produces the SAME 401/403 path as the
// built-in admin-only (which is itself a guard specialization).
func TestCustomGuardMatchesBuiltin(t *testing.T) {
	d := newDriver(t)
	t.Setenv("APP_AUTH__SECRET", "k")
	eval(t, d, `
(require '[bri.http :as http] '[bri.auth :as auth])
(defn h [_] {:status 200 :body "ok"})
;; custom guard: same effect as admin-only, expressed by the user
(def custom (auth/guard (fn [req] (= "admin" (get-in req [:auth/claims :role])))))
(def rts (http/routes (http/GET "/c" custom #'h) (http/GET "/b" (auth/admin-only) #'h)))
(def utok (auth/sign {:sub "u" :role "user"}  {:secret "k"}))
(def atok (auth/sign {:sub "a" :role "admin"} {:secret "k"}))
(defn st [p tok] (:status (http/request rts {:method "GET" :path p :headers {"authorization" (str "Bearer " tok)}} {:middleware [] :ops false})))
`)
	for _, p := range []string{"/c", "/b"} {
		if u, a := eval(t, d, fmt.Sprintf(`(st %q utok)`, p)), eval(t, d, fmt.Sprintf(`(st %q atok)`, p)); u != int64(403) || a != int64(200) {
			t.Errorf("route %s: user=%v admin=%v (want 403/200)", p, u, a)
		}
	}
}

// --- composition equivalence: literal == wrap/context/generated -------------

func TestCompositionEquivalence(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `
(require '[bri.http :as http] '[bri.auth :as auth])
(defn h [_] {:status 200 :body "x"})
`)
	// data-generated == literal (byte-identical routes value).
	if v := eval(t, d, `
(= (http/routes (for [p ["/a" "/b"]] (http/GET p #'h)))
   (http/routes (http/GET "/a" #'h) (http/GET "/b" #'h)))`); v != true {
		t.Fatal("generated route table != literal")
	}
	// context prefix == hand-written prefixed patterns (no mw → structural =).
	if v := eval(t, d, `
(= (mapv first (http/context "/api" [] (http/GET "/x" #'h) (http/GET "/y" #'h)))
   ["GET /api/x" "GET /api/y"])`); v != true {
		t.Fatal("context prefixing wrong")
	}
	// add then remove returns to the original effective table.
	if v := eval(t, d, `
(let [base (http/routes (http/GET "/one" #'h))
      grown (http/add-route base (http/GET "/two" {:name :two} #'h))
      shrunk (http/remove-route grown :two)]
  (= base shrunk))`); v != true {
		t.Fatal("add then remove-by-name did not round-trip")
	}
}

// --- reverse routing: path-for / url-for ------------------------------------

func TestReverseRouting(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `
(require '[bri.http :as http])
(defn h [_] {:status 200})
(def rts (http/routes (http/GET "/items/{id}" {:name :item} #'h)))`)
	if v := evalString(t, d, `(http/path-for rts :item {:id 5})`); v != "/items/5" {
		t.Fatalf("path-for = %q, want /items/5", v)
	}
	if v := evalString(t, d, `(http/path-for rts :item {:id "a b"})`); v != "/items/a%20b" {
		t.Fatalf("path-for encoding = %q", v)
	}
	// url-for resolves against the served table (register on serve/request).
	eval(t, d, `(http/request rts {:method "GET" :path "/items/1"} {:ops false})`)
	if v := evalString(t, d, `(http/url-for :item {:id 5} {:q "x y"})`); v != "/items/5?q=x+y" {
		t.Fatalf("url-for = %q", v)
	}
	// unknown name errors loudly.
	if _, err := d.EvalString(`(http/path-for rts :nope {})`, "auth_test"); err == nil {
		t.Fatal("path-for on unknown name did not throw")
	}
	// missing param errors loudly.
	if _, err := d.EvalString(`(http/path-for rts :item {})`, "auth_test"); err == nil {
		t.Fatal("path-for with missing param did not throw")
	}
}

// --- dynamic path patterns: catch-all + param! coercion ---------------------

func TestCatchAllAndParamCoercion(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `
(require '[bri.http :as http])
(defn files [req] {:status 200 :body (get-in req [:path-params :path])})
(defn item  [req] {:status 200 :body (str "item " (http/param! req :id :int))})
(def rts (http/routes
           (http/GET "/files/{path...}" #'files)
           (http/GET "/items/{id}" #'item)))`)
	if v := evalString(t, d, `(:body (http/request rts {:method "GET" :path "/files/a/b/c.txt"} {:ops false}))`); v != "a/b/c.txt" {
		t.Fatalf("catch-all bound %q, want a/b/c.txt", v)
	}
	if v := evalString(t, d, `(:body (http/request rts {:method "GET" :path "/items/42"} {:ops false}))`); v != "item 42" {
		t.Fatalf("param! :int = %q", v)
	}
	if v := eval(t, d, `(:status (http/request rts {:method "GET" :path "/items/abc"} {:middleware [(http/recover)] :ops false}))`); v != int64(400) {
		t.Fatalf("bad :int param → %v, want 400", v)
	}
}

// --- runtime add / remove reflected live through the served table -----------

func TestRuntimeAddRemoveLive(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `
(require '[bri.http :as http])
(defn h [_] {:status 200 :body "y"})
(def app (http/routes (http/GET "/one" #'h)))
(defn st [p] (:status (http/request #'app {:method "GET" :path p} {:middleware [] :ops false})))`)
	if v := eval(t, d, `(st "/two")`); v != int64(404) {
		t.Fatalf("pre-add /two = %v, want 404", v)
	}
	eval(t, d, `(def app (http/add-route app (http/GET "/two" #'h)))`)
	if v := eval(t, d, `(st "/two")`); v != int64(200) {
		t.Fatalf("post-add /two = %v, want 200 (live re-def of routes var not reflected)", v)
	}
	eval(t, d, `(def app (http/remove-route app "/two"))`)
	if v := eval(t, d, `(st "/two")`); v != int64(404) {
		t.Fatalf("post-remove /two = %v, want 404", v)
	}
}

// --- custom middleware: first-class + short-circuit -------------------------

func TestCustomMiddlewareShortCircuit(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `
(require '[bri.http :as http])
(defn h [_] {:status 200 :body "paid"})
;; a user middleware in ~2 lines that returns a 402 early
(def paywall (http/wrap-request (fn [req] (if (= "yes" (get (:headers req) "x-paid")) req {:status 402 :body "pay"}))))
(def rts (http/routes (http/GET "/x" paywall #'h)))
(defn st [paid] (:status (http/request rts {:method "GET" :path "/x" :headers (if paid {"x-paid" "yes"} {})} {:middleware [] :ops false})))`)
	if v := eval(t, d, `(st false)`); v != int64(402) {
		t.Fatalf("paywall did not short-circuit: %v", v)
	}
	if v := eval(t, d, `(st true)`); v != int64(200) {
		t.Fatalf("paywall blocked a paid request: %v", v)
	}
}

// --- observability: request-id propagation + log shape ----------------------

func TestRequestIDPropagation(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `
(require '[bri.http :as http])
(defn h [_] {:status 200 :body "ok"})
(def rts (http/routes (http/GET "/x" #'h)))`)
	// incoming id honored + echoed
	if v := evalString(t, d, `(get (:headers (http/request rts {:method "GET" :path "/x" :headers {"x-request-id" "abc123"}} {:middleware [http/request-id] :ops false})) "x-request-id")`); v != "abc123" {
		t.Fatalf("request-id not propagated: %q", v)
	}
	// minted when absent
	if v := evalString(t, d, `(get (:headers (http/request rts {:method "GET" :path "/x"} {:middleware [http/request-id] :ops false})) "x-request-id")`); v == "" {
		t.Fatal("request-id not minted when absent")
	}
}

func TestAccessLogShape(t *testing.T) {
	d := newDriver(t)
	t.Setenv("APP_AUTH__SECRET", "k")
	eval(t, d, `
(require '[bri.http :as http] '[bri.auth :as auth])
(def cap (atom nil))
(http/set-log-sink! (fn [ev] (reset! cap ev)))
(defn h [_] {:status 200 :body "ok"})
(def rts (http/routes (http/GET "/x" (auth/logged-in-only) #'h)))
(def tok (auth/sign {:sub "user-7" :role "user"} {:secret "k"}))
(http/request rts {:method "GET" :path "/x" :headers {"authorization" (str "Bearer " tok)}}
              {:middleware [http/request-id http/logging] :ops false})`)
	// Freeze STRUCTURE (keys + subject), not the timestamp/ms/id.
	for _, expr := range []string{
		`(= 200 (:status @cap))`,
		`(= "GET" (:method @cap))`,
		`(= "/x" (:path @cap))`,
		`(= "user-7" (:subject @cap))`,
		`(contains? @cap :request/id)`,
	} {
		if v := eval(t, d, expr); v != true {
			t.Errorf("log shape %s = %v", expr, v)
		}
	}
}

// --- ops endpoints: healthz / readyz / metrics ------------------------------

func TestOpsEndpoints(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `
(require '[bri.http :as http])
(defn h [_] {:status 200 :body "ok"})
(def rts (http/routes (http/GET "/x" #'h)))
;; drive a request so metrics have data
(http/request rts {:method "GET" :path "/x"} {:middleware [http/metrics]})`)
	if v := eval(t, d, `(:status (http/request rts {:method "GET" :path "/healthz"} {}))`); v != int64(200) {
		t.Fatalf("/healthz = %v", v)
	}
	if v := eval(t, d, `(:status (http/request rts {:method "GET" :path "/readyz"} {}))`); v != int64(200) {
		t.Fatalf("/readyz = %v", v)
	}
	// readyz with a failing check → 503
	if v := eval(t, d, `(:status (http/request rts {:method "GET" :path "/readyz"} {:ready-checks [(fn [] false)]}))`); v != int64(503) {
		t.Fatalf("/readyz failing check = %v, want 503", v)
	}
	body := evalString(t, d, `(:body (http/request rts {:method "GET" :path "/metrics"} {}))`)
	if !strings.Contains(body, "bri_http_requests_total") || !strings.Contains(body, "bri_http_request_duration_ms_bucket") {
		t.Fatalf("metrics body missing Prometheus series:\n%s", body)
	}
	// metrics guardable: a guard yields 401 without a token.
	if v := eval(t, d, `(:status (http/request rts {:method "GET" :path "/metrics"}
                          {:metrics-guard (do (require '[bri.auth :as auth]) (auth/admin-only))}))`); v != int64(401) {
		t.Fatalf("guarded /metrics without token = %v, want 401", v)
	}
}

// --- client-ip: trusted-proxy posture ---------------------------------------

func TestClientIPTrustedProxy(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `(require '[bri.http :as http])`)
	// No trusted proxies configured → XFF ignored, socket peer wins.
	if v := evalString(t, d, `(http/client-ip {:remote-addr "203.0.113.9:5000" :headers {"x-forwarded-for" "1.2.3.4"}})`); v != "203.0.113.9" {
		t.Fatalf("untrusted XFF honored: %q (spoof bypass)", v)
	}
	// Peer inside a trusted CIDR → right-most untrusted XFF hop wins.
	t.Setenv("APP_HTTP__TRUSTED_PROXIES", "10.0.0.0/8")
	if v := evalString(t, d, `(http/client-ip {:remote-addr "10.1.2.3:5000" :headers {"x-forwarded-for" "1.2.3.4, 10.9.9.9"}})`); v != "1.2.3.4" {
		t.Fatalf("trusted-proxy XFF resolution = %q, want 1.2.3.4", v)
	}
	// Peer NOT in the trusted CIDR even though CIDRs are set → still peer.
	if v := evalString(t, d, `(http/client-ip {:remote-addr "203.0.113.9:5000" :headers {"x-forwarded-for" "1.2.3.4"}})`); v != "203.0.113.9" {
		t.Fatalf("XFF from untrusted peer honored: %q", v)
	}
}

// --- rate-limit: per-IP independence ----------------------------------------

func TestRateLimitPerIP(t *testing.T) {
	d := newDriver(t)
	eval(t, d, `
(require '[bri.http :as http])
(defn h [_] {:status 200 :body "ok"})
(def st (atom {}))
(def rl (http/rate-limit 2 {:store st :window-ms 100000}))
(def rts (http/routes (http/GET "/x" #'h)))
(defn hit [ip] (:status (http/request rts {:method "GET" :path "/x" :remote-addr (str ip ":1")} {:middleware [rl] :ops false})))`)
	// Two IPs have independent counters.
	got := []int64{
		eval(t, d, `(hit "1.1.1.1")`).(int64),
		eval(t, d, `(hit "1.1.1.1")`).(int64),
		eval(t, d, `(hit "1.1.1.1")`).(int64), // 3rd → over limit
		eval(t, d, `(hit "2.2.2.2")`).(int64), // different IP, fresh
	}
	if got[0] != 200 || got[1] != 200 || got[2] != 429 || got[3] != 200 {
		t.Fatalf("per-IP rate limiting wrong: %v (want 200 200 429 200)", got)
	}
}

// --- auto-ban: deterministic clock, threshold, cooldown, audit --------------

func TestAutoBan(t *testing.T) {
	d := newDriver(t)
	t.Setenv("APP_AUTH__SECRET", "k")
	eval(t, d, `
(require '[bri.http :as http] '[bri.auth :as auth] '[bri.audit :as audit])
(def clk (atom 0))
(def store (atom {}))
(def evs (atom []))
(audit/set-sink! (fn [e] (swap! evs conj e)))
(def ab (auth/auto-ban {:threshold 2 :window-ms 1000 :cooldown-ms 5000
                        :store store :clock (fn [] @clk)}))
;; a route that always denies (401), wrapped by auto-ban globally
(defn denyh [_] {:status 401 :body "no"})
(def rts (http/routes (http/GET "/x" #'denyh)))
(defn hit [] (:status (http/request rts {:method "GET" :path "/x" :remote-addr "9.9.9.9:1"} {:middleware [ab] :ops false})))`)
	// Under threshold: the underlying 401 passes through.
	if v := eval(t, d, `(hit)`); v != int64(401) {
		t.Fatalf("1st denial = %v, want 401", v)
	}
	// Second denial hits the threshold → client banned; NEXT request is 429.
	eval(t, d, `(hit)`) // this is the 2nd denial → triggers ban
	if v := eval(t, d, `(:status (http/request rts {:method "GET" :path "/x" :remote-addr "9.9.9.9:1"} {:middleware [ab] :ops false}))`); v != int64(429) {
		t.Fatalf("after threshold = %v, want 429 (banned)", v)
	}
	// Retry-After present.
	if v := evalString(t, d, `(get (:headers (http/request rts {:method "GET" :path "/x" :remote-addr "9.9.9.9:1"} {:middleware [ab] :ops false})) "retry-after")`); v == "" {
		t.Fatal("429 lacks Retry-After")
	}
	// Cooldown expiry → allowed again (the 401 passes through once more).
	eval(t, d, `(reset! clk 10000)`) // past the 5000ms cooldown
	if v := eval(t, d, `(hit)`); v != int64(401) {
		t.Fatalf("after cooldown = %v, want 401 (unbanned)", v)
	}
	// A ban was audited.
	if v := eval(t, d, `(some #(= :auth/auto-banned (:action %)) @evs)`); v != true {
		t.Fatal("no :auth/auto-banned audit event recorded")
	}
}

// --- perf budget (ADR 0024): a reflection-heavy JWT regression can't sneak in.
// s44 proved the Go path at ~1.1µs (sign+verify); THROUGH the interpreter the
// tree-walk overhead dominates, so the ceiling is generous and host-tunable
// (CLJGO_AUTH_PERF_MAX in µs). The gate catches a 10×+ blowup (e.g. someone
// swaps the hand-rolled HS256 for a reflection-driven lib), not micro-jitter.
func TestAuthPerfBudget(t *testing.T) {
	if testing.Short() {
		t.Skip("perf seam skipped under -short")
	}
	maxUS := 1500.0 // µs per sign+verify pair through the interpreter
	if s := os.Getenv("CLJGO_AUTH_PERF_MAX"); s != "" {
		if _, err := fmt.Sscanf(s, "%f", &maxUS); err != nil {
			t.Fatalf("CLJGO_AUTH_PERF_MAX=%q is not a number", s)
		}
	}
	d := newDriver(t)
	eval(t, d, `
(require '[bri.auth :as auth])
(defn roundtrip [] (auth/verify (auth/sign {:sub "u" :role "admin"} {:secret "k" :now 1000}) {:secret "k" :now 1000}))
(dotimes [_ 200] (roundtrip))`) // warm up
	const n = 2000
	start := time.Now()
	eval(t, d, fmt.Sprintf(`(dotimes [_ %d] (roundtrip))`, n))
	perUS := float64(time.Since(start).Microseconds()) / float64(n)
	t.Logf("sign+verify = %.1f µs/pair through the interpreter (ceiling %.0f µs; Go-native path is ~1.1 µs — s44)", perUS, maxUS)
	if perUS > maxUS {
		t.Fatalf("sign+verify %.1f µs exceeds the %.0f µs ceiling (CLJGO_AUTH_PERF_MAX)", perUS, maxUS)
	}
}

// Metrics stays off the hot path: the metrics middleware (atomic-add
// observe) must add only a small constant per request over the bare stack.
// The registry is proven O(atomic-adds) by s44's guard-overhead class; this
// gate catches a lock-contention / per-observe-alloc regression that would
// show up as the metrics stack costing multiples of the bare one.
func TestMetricsStackOverhead(t *testing.T) {
	if testing.Short() {
		t.Skip("perf seam skipped under -short")
	}
	d := newDriver(t)
	eval(t, d, `
(require '[bri.http :as http])
(defn h [_] {:status 200 :body "ok"})
(def rts (http/routes (http/GET "/x" #'h)))
(defn bare  [] (http/request rts {:method "GET" :path "/x"} {:middleware [] :ops false}))
(defn timed [] (http/request rts {:method "GET" :path "/x"} {:middleware [http/metrics] :ops false}))
(dotimes [_ 300] (bare) (timed))`) // warm
	const n = 3000
	bench := func(fn string) time.Duration {
		start := time.Now()
		eval(t, d, fmt.Sprintf(`(dotimes [_ %d] (%s))`, n, fn))
		return time.Since(start)
	}
	// The wall-clock ratio of two tiny measurements jitters badly on shared
	// runners: a single scheduler hiccup in the `bare` (denominator) sample
	// alone can spike the ratio past the ceiling on a green build (it tripped
	// macOS CI on a docs-only PR). A one-off hiccup inflates the ratio but can
	// never deflate a REAL regression below it, so take the MIN ratio over a
	// few samples — regression-faithful, immune to isolated jitter.
	const samples = 5
	ratio := math.Inf(1)
	var lastBare, lastTimed time.Duration
	for i := 0; i < samples; i++ {
		bare := bench("bare")
		timed := bench("timed")
		if r := float64(timed) / float64(bare); r < ratio {
			ratio, lastBare, lastTimed = r, bare, timed
		}
	}
	t.Logf("best of %d: bare %v/req vs +metrics %v/req = %.2fx", samples, lastBare/n, lastTimed/n, ratio)
	// A real regression is 5x+ (the middleware is a thin wrapper); the 3x
	// ceiling flags that with margin now that isolated jitter is sampled out.
	max := 3.0
	if s := os.Getenv("CLJGO_METRICS_PERF_MAX"); s != "" {
		fmt.Sscanf(s, "%f", &max)
	}
	if ratio > max {
		t.Fatalf("metrics middleware overhead %.2fx exceeds the %.1fx ceiling", ratio, max)
	}
}
