// Code generated by cljgo build. DO NOT EDIT.

package cljgdate

import (
	rt "github.com/muthuishere/cljgo/pkg/emit/rt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_arglists                      = lang.InternKeywordString("arglists")
	kw_column                        = lang.InternKeywordString("column")
	kw_doc                           = lang.InternKeywordString("doc")
	kw_end_column                    = lang.InternKeywordString("end-column")
	kw_end_line                      = lang.InternKeywordString("end-line")
	kw_exclude                       = lang.InternKeywordString("exclude")
	kw_file                          = lang.InternKeywordString("file")
	kw_line                          = lang.InternKeywordString("line")
	sym_cljg_DOT_date                = lang.NewSymbol("cljg.date")
	sym_clojure_DOT_core             = lang.NewSymbol("clojure.core")
	sym_format                       = lang.NewSymbol("format")
	sym_layout                       = lang.NewSymbol("layout")
	sym_millis                       = lang.NewSymbol("millis")
	sym_pattern                      = lang.NewSymbol("pattern")
	sym_s                            = lang.NewSymbol("s")
	sym_t0                           = lang.NewSymbol("t0")
	sym_t1                           = lang.NewSymbol("t1")
	v_cljg_DOT_date_X_format_iso     = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("-format-iso")).SetPrivate()
	v_cljg_DOT_date_X_format_layout  = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("-format-layout")).SetPrivate()
	v_cljg_DOT_date_X_format_pattern = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("-format-pattern")).SetPrivate()
	v_cljg_DOT_date_X_nano_time      = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("-nano-time")).SetPrivate()
	v_cljg_DOT_date_X_now_millis     = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("-now-millis")).SetPrivate()
	v_cljg_DOT_date_X_parse_iso      = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("-parse-iso")).SetPrivate()
	v_cljg_DOT_date_X_parse_layout   = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("-parse-layout")).SetPrivate()
	v_cljg_DOT_date_X_parse_pattern  = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("-parse-pattern")).SetPrivate()
	v_cljg_DOT_date_format           = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("format"))
	v_cljg_DOT_date_format_iso       = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("format-iso"))
	v_cljg_DOT_date_format_pattern   = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("format-pattern"))
	v_cljg_DOT_date_nano_time        = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("nano-time"))
	v_cljg_DOT_date_now              = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("now"))
	v_cljg_DOT_date_parse            = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("parse"))
	v_cljg_DOT_date_parse_iso        = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("parse-iso"))
	v_cljg_DOT_date_parse_pattern    = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("parse-pattern"))
	v_cljg_DOT_date_since            = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("since"))
	v_cljg_DOT_date_since_ms         = lang.InternVarName(lang.NewSymbol("cljg.date"), lang.NewSymbol("since-ms"))
	v_clojure_DOT_core_X_            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("-"))
	v_clojure_DOT_core_X_SLASH_      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("/"))
	v_clojure_DOT_core_double        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("double"))
	v_clojure_DOT_core_in_ns         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_refer         = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
)

var (
	fnD_cljg_DOT_date_nano_time      lang.FnFunc0
	fnD_cljg_DOT_date_now            lang.FnFunc0
	fnD_cljg_DOT_date_parse_iso      lang.FnFunc1
	fnD_cljg_DOT_date_format         lang.FnFunc2
	fnD_cljg_DOT_date_parse          lang.FnFunc2
	fnD_cljg_DOT_date_format_pattern lang.FnFunc2
	fnD_cljg_DOT_date_parse_pattern  lang.FnFunc2
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("cljg.date")), lang.VarFile, "cljg/date.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote cljg.date))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_cljg_DOT_date)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core) :exclude (quote [format]))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply3(tmp3, sym_clojure_DOT_core, kw_exclude, lang.NewVector(sym_format))
	_ = tmp4
	// (def nano-time (clojure.core/fn ([] (-nano-time))))
	v_cljg_DOT_date_nano_time.SetMeta(lang.NewMap(kw_file, "cljg/date.cljg", kw_line, int64(35), kw_column, int64(7), kw_end_line, int64(35), kw_end_column, int64(16), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "Monotonic nanoseconds since process start (the System/nanoTime analog).\n  Only the difference of two readings is meaningful — pair with `since`."))
	tmp5 := lang.FnFunc0(func() any {
		tmp6 := v_cljg_DOT_date_X_nano_time.Get()
		tmp7 := lang.Apply0(tmp6)
		return tmp7
	})
	tmp8 := &lang.NamedFn0{Name: "cljg.date/nano-time", Expects: "0: []", F: tmp5}
	v_cljg_DOT_date_nano_time.BindRoot(tmp8)
	fnD_cljg_DOT_date_nano_time = tmp8.F
	v_cljg_DOT_date_nano_time.SealDirect()
	_ = v_cljg_DOT_date_nano_time
	// (def now (clojure.core/fn ([] (-now-millis))))
	v_cljg_DOT_date_now.SetMeta(lang.NewMap(kw_file, "cljg/date.cljg", kw_line, int64(41), kw_column, int64(7), kw_end_line, int64(41), kw_end_column, int64(10), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "The current wall-clock time as epoch milliseconds (the System/currentTimeMillis\n  analog)."))
	tmp9 := lang.FnFunc0(func() any {
		tmp10 := v_cljg_DOT_date_X_now_millis.Get()
		tmp11 := lang.Apply0(tmp10)
		return tmp11
	})
	tmp12 := &lang.NamedFn0{Name: "cljg.date/now", Expects: "0: []", F: tmp9}
	v_cljg_DOT_date_now.BindRoot(tmp12)
	fnD_cljg_DOT_date_now = tmp12.F
	v_cljg_DOT_date_now.SealDirect()
	_ = v_cljg_DOT_date_now
	// (def since (clojure.core/fn ([t0] (- (nano-time) t0)) ([t0 t1] (- t1 t0))))
	v_cljg_DOT_date_since.SetMeta(lang.NewMap(kw_file, "cljg/date.cljg", kw_line, int64(47), kw_column, int64(7), kw_end_line, int64(47), kw_end_column, int64(12), kw_arglists, lang.NewList(lang.NewVector(sym_t0), lang.NewVector(sym_t0, sym_t1)), kw_doc, "Elapsed nanoseconds. With one reading `t0` (from `nano-time`), the elapsed\n  nanos from `t0` until now. With two readings, `t1` - `t0`."))
	tmp13 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			t014 := args[0]
			_ = t014
			tmp15 := v_cljg_DOT_date_nano_time.Direct()
			var tmp16 any
			if !tmp15 {
				tmp16 = v_cljg_DOT_date_nano_time.Get()
			}
			var tmp17 any
			if tmp15 {
				tmp17 = fnD_cljg_DOT_date_nano_time()
			} else {
				tmp17 = lang.Apply0(tmp16)
			}
			tmp18 := rt.Sub2(v_clojure_DOT_core_X_, tmp17, t014)
			return tmp18
		case 2:
			t019 := args[0]
			_ = t019
			t120 := args[1]
			_ = t120
			tmp21 := rt.Sub2(v_clojure_DOT_core_X_, t120, t019)
			return tmp21
		default:
			panic(lang.NewArityError(len(args), "cljg.date/since", "1: [t0] or 2: [t0 t1]"))
		}
	})
	v_cljg_DOT_date_since.BindRoot(tmp13)
	_ = v_cljg_DOT_date_since
	// (def since-ms (clojure.core/fn ([t0] (/ (double (since t0)) 1000000.0)) ([t0 t1] (/ (doubl…
	v_cljg_DOT_date_since_ms.SetMeta(lang.NewMap(kw_file, "cljg/date.cljg", kw_line, int64(53), kw_column, int64(7), kw_end_line, int64(53), kw_end_column, int64(15), kw_arglists, lang.NewList(lang.NewVector(sym_t0), lang.NewVector(sym_t0, sym_t1)), kw_doc, "Elapsed milliseconds (a double) — `since` divided by 1e6. One reading\n  measures until now; two measure the interval between them."))
	tmp22 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			t023 := args[0]
			_ = t023
			tmp24 := v_clojure_DOT_core_double.Get()
			tmp25 := v_cljg_DOT_date_since.Get()
			tmp26 := lang.Apply1(tmp25, t023)
			tmp27 := lang.Apply1(tmp24, tmp26)
			tmp28 := rt.Div2(v_clojure_DOT_core_X_SLASH_, tmp27, float64(1e+06))
			return tmp28
		case 2:
			t029 := args[0]
			_ = t029
			t130 := args[1]
			_ = t130
			tmp31 := v_clojure_DOT_core_double.Get()
			tmp32 := v_cljg_DOT_date_since.Get()
			tmp33 := lang.Apply2(tmp32, t029, t130)
			tmp34 := lang.Apply1(tmp31, tmp33)
			tmp35 := rt.Div2(v_clojure_DOT_core_X_SLASH_, tmp34, float64(1e+06))
			return tmp35
		default:
			panic(lang.NewArityError(len(args), "cljg.date/since-ms", "1: [t0] or 2: [t0 t1]"))
		}
	})
	v_cljg_DOT_date_since_ms.BindRoot(tmp22)
	_ = v_cljg_DOT_date_since_ms
	// (def format-iso (clojure.core/fn ([] (format-iso (now))) ([millis] (-format-iso millis))))
	v_cljg_DOT_date_format_iso.SetMeta(lang.NewMap(kw_file, "cljg/date.cljg", kw_line, int64(65), kw_column, int64(7), kw_end_line, int64(65), kw_end_column, int64(17), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_millis)), kw_doc, "Render an instant (epoch milliseconds; defaults to `now`) as an ISO-8601 /\n  RFC 3339 UTC string. Matches java.time.Instant.toString() at millisecond\n  precision: no fractional part on a whole second, exactly three digits\n  otherwise — (format-iso 0) => \"1970-01-01T00:00:00Z\",\n  (format-iso 1500) => \"1970-01-01T00:00:01.500Z\"."))
	tmp36 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 0:
			tmp37 := v_cljg_DOT_date_format_iso.Get()
			tmp38 := v_cljg_DOT_date_now.Direct()
			var tmp39 any
			if !tmp38 {
				tmp39 = v_cljg_DOT_date_now.Get()
			}
			var tmp40 any
			if tmp38 {
				tmp40 = fnD_cljg_DOT_date_now()
			} else {
				tmp40 = lang.Apply0(tmp39)
			}
			tmp41 := lang.Apply1(tmp37, tmp40)
			return tmp41
		case 1:
			millis42 := args[0]
			_ = millis42
			tmp43 := v_cljg_DOT_date_X_format_iso.Get()
			tmp44 := lang.Apply1(tmp43, millis42)
			return tmp44
		default:
			panic(lang.NewArityError(len(args), "cljg.date/format-iso", "0: [] or 1: [millis]"))
		}
	})
	v_cljg_DOT_date_format_iso.BindRoot(tmp36)
	_ = v_cljg_DOT_date_format_iso
	// (def parse-iso (clojure.core/fn ([s] (-parse-iso s))))
	v_cljg_DOT_date_parse_iso.SetMeta(lang.NewMap(kw_file, "cljg/date.cljg", kw_line, int64(74), kw_column, int64(7), kw_end_line, int64(74), kw_end_column, int64(16), kw_arglists, lang.NewList(lang.NewVector(sym_s)), kw_doc, "Parse an ISO-8601 / RFC 3339 timestamp into epoch milliseconds. A fractional\n  part is optional and any offset is honoured, not dropped —\n  (parse-iso \"2026-07-30T12:00:00+05:30\") equals\n  (parse-iso \"2026-07-30T06:30:00Z\"). Throws, naming the input, if the string\n  is not an instant."))
	tmp45 := lang.FnFunc1(func(s46 any) any {
		tmp47 := v_cljg_DOT_date_X_parse_iso.Get()
		tmp48 := lang.Apply1(tmp47, s46)
		return tmp48
	})
	tmp49 := &lang.NamedFn1{Name: "cljg.date/parse-iso", Expects: "1: [s]", F: tmp45}
	v_cljg_DOT_date_parse_iso.BindRoot(tmp49)
	fnD_cljg_DOT_date_parse_iso = tmp49.F
	v_cljg_DOT_date_parse_iso.SealDirect()
	_ = v_cljg_DOT_date_parse_iso
	// (def format (clojure.core/fn ([millis layout] (-format-layout millis layout))))
	v_cljg_DOT_date_format.SetMeta(lang.NewMap(kw_file, "cljg/date.cljg", kw_line, int64(83), kw_column, int64(7), kw_end_line, int64(83), kw_end_column, int64(13), kw_arglists, lang.NewList(lang.NewVector(sym_millis, sym_layout)), kw_doc, "Render an instant (epoch milliseconds) in UTC with `layout`.\n\n  NOTE — no JVM equivalent: `layout` is a GO reference-time layout, spelled by\n  writing the reference instant Mon Jan 2 15:04:05 MST 2006 the way you want\n  the output (\"2006-01-02\", \"15:04:05\", \"Jan 2 2006\"). It is NOT a\n  java.time DateTimeFormatter pattern (\"yyyy-MM-dd\"), and cljgo does not\n  translate one into the other — this is a Go host, and pretending otherwise\n  would silently mis-format. For a java.time pattern use `format-pattern`; for\n  the zero-decision portable case use `format-iso`.\n\n  Does NOT shadow clojure.core/format, which is untouched (see the ns header)."))
	tmp50 := lang.FnFunc2(func(millis51, layout52 any) any {
		tmp53 := v_cljg_DOT_date_X_format_layout.Get()
		tmp54 := lang.Apply2(tmp53, millis51, layout52)
		return tmp54
	})
	tmp55 := &lang.NamedFn2{Name: "cljg.date/format", Expects: "2: [millis layout]", F: tmp50}
	v_cljg_DOT_date_format.BindRoot(tmp55)
	fnD_cljg_DOT_date_format = tmp55.F
	v_cljg_DOT_date_format.SealDirect()
	_ = v_cljg_DOT_date_format
	// (def parse (clojure.core/fn ([s layout] (-parse-layout s layout))))
	v_cljg_DOT_date_parse.SetMeta(lang.NewMap(kw_file, "cljg/date.cljg", kw_line, int64(98), kw_column, int64(7), kw_end_line, int64(98), kw_end_column, int64(12), kw_arglists, lang.NewList(lang.NewVector(sym_s, sym_layout)), kw_doc, "Parse `s` with `layout` into epoch milliseconds — the inverse of `format`,\n  and likewise a GO reference-time layout, not a java.time pattern. A layout\n  carrying no zone is read as UTC. Throws, naming input and layout, on a\n  mismatch. For a java.time pattern use `parse-pattern`."))
	tmp56 := lang.FnFunc2(func(s57, layout58 any) any {
		tmp59 := v_cljg_DOT_date_X_parse_layout.Get()
		tmp60 := lang.Apply2(tmp59, s57, layout58)
		return tmp60
	})
	tmp61 := &lang.NamedFn2{Name: "cljg.date/parse", Expects: "2: [s layout]", F: tmp56}
	v_cljg_DOT_date_parse.BindRoot(tmp61)
	fnD_cljg_DOT_date_parse = tmp61.F
	v_cljg_DOT_date_parse.SealDirect()
	_ = v_cljg_DOT_date_parse
	// (def format-pattern (clojure.core/fn ([millis pattern] (-format-pattern millis pattern))))
	v_cljg_DOT_date_format_pattern.SetMeta(lang.NewMap(kw_file, "cljg/date.cljg", kw_line, int64(113), kw_column, int64(7), kw_end_line, int64(113), kw_end_column, int64(21), kw_arglists, lang.NewList(lang.NewVector(sym_millis, sym_pattern)), kw_doc, "Render an instant (epoch milliseconds) in UTC with a java.time\n  DateTimeFormatter `pattern` — the portable spelling.\n\n    (format-pattern 0 \"yyyy-MM-dd HH:mm:ss\")  ;=> \"1970-01-01 00:00:00\"\n    (format-pattern 0 \"EEE, d MMM yyyy\")      ;=> \"Thu, 1 Jan 1970\"\n\n  Supported: y M d E H h m s S a X Z, plus 'quoted literals'. Tokens with no\n  exact cljgo equivalent (G Q D w W F k K Y u z V) are REFUSED by name when the\n  pattern is compiled — never approximated, and never part-way through a render,\n  so a program cannot emit half a timestamp. Compiled patterns are memoised.\n\n  LOCALE — text tokens (MMM MMMM EEE EEEE) render ENGLISH names. A .cljc library\n  that must agree across hosts has to pass java.util.Locale/ENGLISH on the :clj\n  side. NOT Locale/ROOT: ROOT has no distinct full forms and yields \"Jul\" for\n  MMMM and \"Fri\" for EEEE, diverging silently on exactly the tokens the advice\n  exists to protect.\n\n  `format` remains a GO reference-time layout and is unchanged."))
	tmp62 := lang.FnFunc2(func(millis63, pattern64 any) any {
		tmp65 := v_cljg_DOT_date_X_format_pattern.Get()
		tmp66 := lang.Apply2(tmp65, millis63, pattern64)
		return tmp66
	})
	tmp67 := &lang.NamedFn2{Name: "cljg.date/format-pattern", Expects: "2: [millis pattern]", F: tmp62}
	v_cljg_DOT_date_format_pattern.BindRoot(tmp67)
	fnD_cljg_DOT_date_format_pattern = tmp67.F
	v_cljg_DOT_date_format_pattern.SealDirect()
	_ = v_cljg_DOT_date_format_pattern
	// (def parse-pattern (clojure.core/fn ([s pattern] (-parse-pattern s pattern))))
	v_cljg_DOT_date_parse_pattern.SetMeta(lang.NewMap(kw_file, "cljg/date.cljg", kw_line, int64(135), kw_column, int64(7), kw_end_line, int64(135), kw_end_column, int64(20), kw_arglists, lang.NewList(lang.NewVector(sym_s, sym_pattern)), kw_doc, "Parse `s` with a java.time DateTimeFormatter `pattern` into epoch\n  milliseconds — the inverse of `format-pattern`.\n\n    (parse-pattern \"1970-01-01 00:00:00\" \"yyyy-MM-dd HH:mm:ss\")  ;=> 0\n\n  A pattern carrying no offset is read as UTC. Parsing is deliberately stricter\n  than formatting: a pattern that cannot name a WHOLE instant is refused rather\n  than defaulted — no year, month or day, or a 12-hour clock (h) with no AM/PM\n  (a). A parsed weekday that contradicts the parsed date is an error too, as it\n  is on the JVM. Throws, naming input and pattern, on a mismatch."))
	tmp68 := lang.FnFunc2(func(s69, pattern70 any) any {
		tmp71 := v_cljg_DOT_date_X_parse_pattern.Get()
		tmp72 := lang.Apply2(tmp71, s69, pattern70)
		return tmp72
	})
	tmp73 := &lang.NamedFn2{Name: "cljg.date/parse-pattern", Expects: "2: [s pattern]", F: tmp68}
	v_cljg_DOT_date_parse_pattern.BindRoot(tmp73)
	fnD_cljg_DOT_date_parse_pattern = tmp73.F
	v_cljg_DOT_date_parse_pattern.SealDirect()
	_ = v_cljg_DOT_date_parse_pattern
}
