// Command genbri AOT-compiles the bri application framework's Clojure
// half — core/bri/*.cljg (bri.web.http/config/audit/html/auth) — into the Go
// packages under pkg/briaot (ADR 0071, mirroring cmd/gencore / ADR 0046).
// It is the generator behind `go generate ./pkg/briaot`; its output is
// checked in, and pkg/briaot's drift test re-runs it into a temp dir and
// fails on any divergence, so the committed packages can never disagree
// with the sources they were generated from.
//
// The compile is the interpreter's own bri load, captured: one full
// evaluator (eval.New — clojure.core booted), then bri.Specs() in
// dependency order, each with its Go shims interned (bri.InstallShimsInto)
// and its source read+analyzed+evaluated under the frame the interpreter's
// loader pushes (*ns* = the namespace, *file* = its source file) while
// pkg/emit captures the analyzed nodes. Compile time = eval time (ADR
// 0002): each namespace's vars are live for a later namespace's top-level
// require, exactly as at runtime — which is why the order matters.
//
// Usage: go run ./cmd/genbri [-o pkg/briaot]
package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/muthuishere/cljgo/pkg/ast"
	"github.com/muthuishere/cljgo/pkg/bri"
	// Blank-import every OptIn namespace's isolated shim package so its
	// init() registers the shim installer (bri.RegisterInstaller) before
	// compileSpec interns the private vars (ADR 0074). genbri is a build
	// tool — linking the OpenTelemetry SDK here is free of the user-binary
	// zero-cost constraint.
	_ "github.com/muthuishere/cljgo/pkg/bri/otel"
	"github.com/muthuishere/cljgo/pkg/emit"
	"github.com/muthuishere/cljgo/pkg/eval"
	"github.com/muthuishere/cljgo/pkg/lang"
)

// loaderName is the unexported loader-fn identifier for a bri subpackage:
// "brihttp" → "loadBrihttp".
func loaderName(pkg string) string {
	return "load" + strings.ToUpper(pkg[:1]) + pkg[1:]
}

func main() {
	out := flag.String("o", "pkg/briaot", "output directory for the generated packages")
	flag.Parse()
	if err := Generate(*out); err != nil {
		log.Fatalf("genbri: %v", err)
	}
}

// Generate compiles every bri namespace into dir/<pkg>/<pkg>.go and writes
// dir/briaot.go — the init() that registers a lib provider per namespace.
// Exported so the drift test can call it without shelling out.
func Generate(dir string) error {
	ev := eval.New()
	// A bri source that reaches for a file-backed require is a bug in the
	// source, not a silent gap in the binary: every require must resolve to
	// a boot namespace (clojure.*) or an already-compiled sibling bri
	// namespace (dependency order guarantees existence). Mirror gencore.
	ev.LibLoader = func(_ *eval.Evaluator, lib *lang.Symbol, path string) {
		panic(fmt.Errorf("bri source required namespace %s from file %s — bri's sources must resolve to core or an earlier bri namespace (bri.Specs order)", lib.FullName(), path))
	}

	for _, s := range bri.Specs() {
		forms, err := compileSpec(ev, s)
		if err != nil {
			return fmt.Errorf("compiling %s: %w", s.File, err)
		}
		formatted, raw, err := emit.EmitBootPackage(forms, s.Pkg, s.Name, s.File, emit.Options{})
		if err != nil {
			if len(raw) > 0 {
				return fmt.Errorf("emitting %s: %w\n--- unformatted ---\n%s", s.File, err, raw)
			}
			return fmt.Errorf("emitting %s: %w", s.File, err)
		}
		pkgDir := filepath.Join(dir, s.Pkg)
		if err := os.MkdirAll(pkgDir, 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(pkgDir, s.Pkg+".go"), formatted, 0o644); err != nil {
			return err
		}
		// An OptIn namespace (ADR 0074) is EXCLUDED from the umbrella
		// briaot.go — it must not link unless required — so its sub-package
		// self-registers its lib provider (and blank-imports its isolated
		// shim package so the installer is present). The emitter imports this
		// sub-package only when the app requires the namespace.
		if s.OptIn {
			if err := writeOptInProvider(pkgDir, s); err != nil {
				return err
			}
		}
	}
	return writeLoader(dir)
}

// writeOptInProvider emits pkg/briaot/<pkg>/provider.go for an OptIn
// namespace: an init() that registers the lib provider, a load() that
// installs the shims then runs the compiled Load, and a blank import of the
// namespace's isolated Go-shim package (ShimImport) so its init() registers
// the installer with pkg/bri before load() runs (ADR 0074).
func writeOptInProvider(pkgDir string, s bri.Spec) error {
	const mod = "github.com/muthuishere/cljgo"
	src := fmt.Sprintf(`// Code generated by cmd/genbri. DO NOT EDIT.

// This file makes %s an OPT-IN, separately-linked namespace (ADR 0074):
// blank-importing THIS sub-package (which the emitter does only when the
// app requires %s) links its isolated shim package and registers its lib
// provider — so the heavy dependency stays out of every other bri binary.
package %s

import (
	bri %q
	_ %q
	rt %q
)

func init() { rt.RegisterLib(%q, load) }

func load() { installShims(%q); Load() }

// installShims interns %s's Go shims (pkg/bri.InstallShimsInto, resolving
// the installer its isolated shim package registered via RegisterInstaller).
func installShims(name string) {
	for _, sp := range bri.Specs() {
		if sp.Name == name {
			bri.InstallShimsInto(sp)
			return
		}
	}
}
`, s.Name, s.Name, s.Pkg, mod+"/pkg/bri", s.ShimImport, mod+"/pkg/emit/rt", s.Name, s.Name, s.Name)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return fmt.Errorf("formatting %s/provider.go: %w\n%s", s.Pkg, err, src)
	}
	return os.WriteFile(filepath.Join(pkgDir, "provider.go"), formatted, 0o644)
}

// compileSpec interns s's Go shims, then reads+analyzes+evaluates its
// embedded source through ev, capturing the analyzed top-level forms under
// the *ns*/*file* frame the interpreter's bri loader pushes. Evaluating as
// it compiles is what makes each namespace's vars exist for the next one's
// analysis (ADR 0002).
func compileSpec(ev *eval.Evaluator, s bri.Spec) ([]*ast.Node, error) {
	bri.InstallShimsInto(s)
	ns := lang.FindOrCreateNamespace(lang.NewSymbol(s.Name))
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, ns, lang.VarFile, s.File))
	defer lang.PopThreadBindings()
	return emit.CompileSource(ev, strings.NewReader(*s.Source), s.File)
}

// writeLoader emits pkg/briaot/briaot.go: the init() that registers a lib
// provider per bri namespace (ADR 0042 §2). Each provider installs the
// namespace's Go shims (pkg/bri, the shim implementation both modes share)
// then runs the AOT-compiled forms (the sub-package's guarded Load), so a
// compiled binary's (require 'bri.web.http) resolves to real net/http + the
// framework fns with no interpreter linked (ADR 0071).
func writeLoader(dir string) error {
	const mod = "github.com/muthuishere/cljgo"
	var b strings.Builder
	b.WriteString(`// Code generated by cmd/genbri. DO NOT EDIT.

// Package briaot is the bri framework, AOT-compiled: one Go package per
// bri namespace (core/bri/*.cljg — bri.Specs()), each a Load() that runs
// that namespace's top-level forms, plus a lib provider per namespace that
// installs the Go shims before running it. Blank-importing this package
// into a compiled binary is what makes (require 'bri.web.http) resolve WITHOUT
// the tree-walk interpreter (ADR 0071, mirroring pkg/coreaot / ADR 0046).
// The emitter blank-imports it into a bri app's main package when the app
// uses bri (pkg/emit UsesBri). OPT-IN namespaces (ADR 0074, e.g. bri.core.telemetry)
// are EXCLUDED here — they self-register from their own sub-package and are
// blank-imported by the emitter only when the app requires them, so their
// heavy dependency never links into this umbrella.
package briaot

//go:generate go run ../../cmd/genbri -o .

import (
	bri "` + mod + `/pkg/bri"
	rt "` + mod + `/pkg/emit/rt"
`)
	for _, s := range bri.Specs() {
		if s.OptIn {
			continue
		}
		fmt.Fprintf(&b, "\t%s %q\n", s.Pkg, mod+"/pkg/briaot/"+s.Pkg)
	}
	b.WriteString(`)

// init registers a lib provider per bri namespace: the replayed
// (require 'bri.web.http) in a compiled binary triggers the matching loader at
// its source position (the providers are guarded — each sub-package's Load
// is load-once, and InstallShimsInto is idempotent re-interning).
func init() {
`)
	for _, s := range bri.Specs() {
		if s.OptIn {
			continue
		}
		fmt.Fprintf(&b, "\trt.RegisterLib(%q, %s)\n", s.Name, loaderName(s.Pkg))
	}
	b.WriteString(`}

// installShims interns the named bri namespace's Go shims as :private vars
// (pkg/bri.InstallShimsInto), the same shims the interpreter installs — so
// the AOT-compiled forms below resolve -serve/-jwt-sign/… identically.
func installShims(name string) {
	for _, s := range bri.Specs() {
		if s.Name == name {
			bri.InstallShimsInto(s)
			return
		}
	}
}

`)
	for _, s := range bri.Specs() {
		if s.OptIn {
			continue
		}
		fmt.Fprintf(&b, "func %s() { installShims(%q); %s.Load() }\n", loaderName(s.Pkg), s.Name, s.Pkg)
	}
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("formatting briaot.go: %w\n%s", err, b.String())
	}
	return os.WriteFile(filepath.Join(dir, "briaot.go"), formatted, 0o644)
}
