// Code generated by cljgo build. DO NOT EDIT.

package cljgio

import (
	rt "github.com/muthuishere/cljgo/pkg/emit/rt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_arglists                                     = lang.InternKeywordString("arglists")
	kw_as                                           = lang.InternKeywordString("as")
	kw_column                                       = lang.InternKeywordString("column")
	kw_command                                      = lang.InternKeywordString("command")
	kw_dir_QMARK_                                   = lang.InternKeywordString("dir?")
	kw_doc                                          = lang.InternKeywordString("doc")
	kw_end_column                                   = lang.InternKeywordString("end-column")
	kw_end_line                                     = lang.InternKeywordString("end-line")
	kw_err                                          = lang.InternKeywordString("err")
	kw_exit                                         = lang.InternKeywordString("exit")
	kw_file                                         = lang.InternKeywordString("file")
	kw_file_QMARK_                                  = lang.InternKeywordString("file?")
	kw_line                                         = lang.InternKeywordString("line")
	kw_modified                                     = lang.InternKeywordString("modified")
	kw_size                                         = lang.InternKeywordString("size")
	kw_timed_out_QMARK_                             = lang.InternKeywordString("timed-out?")
	sym_X_AMP_                                      = lang.NewSymbol("&")
	sym_cljg_DOT_io                                 = lang.NewSymbol("cljg.io")
	sym_clojure_DOT_core                            = lang.NewSymbol("clojure.core")
	sym_clojure_DOT_string                          = lang.NewSymbol("clojure.string")
	sym_command                                     = lang.NewSymbol("command")
	sym_data                                        = lang.NewSymbol("data")
	sym_dst                                         = lang.NewSymbol("dst")
	sym_opts                                        = lang.NewSymbol("opts")
	sym_path                                        = lang.NewSymbol("path")
	sym_pattern                                     = lang.NewSymbol("pattern")
	sym_prefix                                      = lang.NewSymbol("prefix")
	sym_root                                        = lang.NewSymbol("root")
	sym_segments                                    = lang.NewSymbol("segments")
	sym_src                                         = lang.NewSymbol("src")
	sym_str                                         = lang.NewSymbol("str")
	sym_suffix                                      = lang.NewSymbol("suffix")
	sym_w                                           = lang.NewSymbol("w")
	v_cljg_DOT_io_X_fs_copy                         = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-copy")).SetPrivate()
	v_cljg_DOT_io_X_fs_cwd                          = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-cwd")).SetPrivate()
	v_cljg_DOT_io_X_fs_delete                       = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-delete")).SetPrivate()
	v_cljg_DOT_io_X_fs_glob                         = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-glob")).SetPrivate()
	v_cljg_DOT_io_X_fs_home                         = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-home")).SetPrivate()
	v_cljg_DOT_io_X_fs_list                         = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-list")).SetPrivate()
	v_cljg_DOT_io_X_fs_mkdir                        = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-mkdir")).SetPrivate()
	v_cljg_DOT_io_X_fs_move                         = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-move")).SetPrivate()
	v_cljg_DOT_io_X_fs_read_bytes                   = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-read-bytes")).SetPrivate()
	v_cljg_DOT_io_X_fs_stat                         = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-stat")).SetPrivate()
	v_cljg_DOT_io_X_fs_temp_dir                     = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-temp-dir")).SetPrivate()
	v_cljg_DOT_io_X_fs_temp_file                    = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-temp-file")).SetPrivate()
	v_cljg_DOT_io_X_fs_walk                         = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-walk")).SetPrivate()
	v_cljg_DOT_io_X_fs_write_bytes                  = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-fs-write-bytes")).SetPrivate()
	v_cljg_DOT_io_X_path_abs                        = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-path-abs")).SetPrivate()
	v_cljg_DOT_io_X_path_base                       = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-path-base")).SetPrivate()
	v_cljg_DOT_io_X_path_dir                        = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-path-dir")).SetPrivate()
	v_cljg_DOT_io_X_path_ext                        = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-path-ext")).SetPrivate()
	v_cljg_DOT_io_X_path_join                       = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-path-join")).SetPrivate()
	v_cljg_DOT_io_X_path_real                       = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-path-real")).SetPrivate()
	v_cljg_DOT_io_X_proc_exec                       = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("-proc-exec")).SetPrivate()
	v_cljg_DOT_io_absolute                          = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("absolute"))
	v_cljg_DOT_io_copy_BANG_                        = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("copy!"))
	v_cljg_DOT_io_cwd                               = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("cwd"))
	v_cljg_DOT_io_delete_BANG_                      = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("delete!"))
	v_cljg_DOT_io_delete_tree_BANG_                 = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("delete-tree!"))
	v_cljg_DOT_io_directory_QMARK_                  = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("directory?"))
	v_cljg_DOT_io_exec                              = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("exec"))
	v_cljg_DOT_io_exists_QMARK_                     = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("exists?"))
	v_cljg_DOT_io_extension                         = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("extension"))
	v_cljg_DOT_io_file_QMARK_                       = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("file?"))
	v_cljg_DOT_io_filename                          = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("filename"))
	v_cljg_DOT_io_glob                              = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("glob"))
	v_cljg_DOT_io_home                              = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("home"))
	v_cljg_DOT_io_list_files                        = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("list-files"))
	v_cljg_DOT_io_mkdirs                            = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("mkdirs"))
	v_cljg_DOT_io_modified                          = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("modified"))
	v_cljg_DOT_io_move_BANG_                        = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("move!"))
	v_cljg_DOT_io_parent                            = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("parent"))
	v_cljg_DOT_io_path                              = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("path"))
	v_cljg_DOT_io_read_bytes                        = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("read-bytes"))
	v_cljg_DOT_io_real_path                         = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("real-path"))
	v_cljg_DOT_io_sh                                = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("sh"))
	v_cljg_DOT_io_sh_BANG_                          = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("sh!"))
	v_cljg_DOT_io_size                              = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("size"))
	v_cljg_DOT_io_stat                              = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("stat"))
	v_cljg_DOT_io_string_writer                     = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("string-writer"))
	v_cljg_DOT_io_temp_dir                          = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("temp-dir"))
	v_cljg_DOT_io_temp_file                         = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("temp-file"))
	v_cljg_DOT_io_walk                              = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("walk"))
	v_cljg_DOT_io_write_bytes                       = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("write-bytes"))
	v_cljg_DOT_io_writer_str                        = lang.InternVarName(lang.NewSymbol("cljg.io"), lang.NewSymbol("writer-str"))
	v_clojure_DOT_core_X_string_writer              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("-string-writer"))
	v_clojure_DOT_core_X_string_writer_str          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("-string-writer-str"))
	v_clojure_DOT_core_assoc                        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("assoc"))
	v_clojure_DOT_core_boolean                      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("boolean"))
	v_clojure_DOT_core_ex_info                      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("ex-info"))
	v_clojure_DOT_core_get                          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("get"))
	v_clojure_DOT_core_in_ns                        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_not_EQ_                      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("not="))
	v_clojure_DOT_core_refer                        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
	v_clojure_DOT_core_require                      = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("require"))
	v_clojure_DOT_core_seq                          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("seq"))
	v_clojure_DOT_core_seq_QMARK_                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("seq?"))
	v_clojure_DOT_core_seq_to_map_for_destructuring = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("seq-to-map-for-destructuring"))
	v_clojure_DOT_core_some_QMARK_                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("some?"))
	v_clojure_DOT_core_str                          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("str"))
	v_clojure_DOT_core_vec                          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("vec"))
	v_clojure_DOT_string_join                       = lang.InternVarName(lang.NewSymbol("clojure.string"), lang.NewSymbol("join"))
)

var (
	fnD_cljg_DOT_io_stat              lang.FnFunc1
	fnD_cljg_DOT_io_exists_QMARK_     lang.FnFunc1
	fnD_cljg_DOT_io_file_QMARK_       lang.FnFunc1
	fnD_cljg_DOT_io_directory_QMARK_  lang.FnFunc1
	fnD_cljg_DOT_io_size              lang.FnFunc1
	fnD_cljg_DOT_io_modified          lang.FnFunc1
	fnD_cljg_DOT_io_list_files        lang.FnFunc1
	fnD_cljg_DOT_io_mkdirs            lang.FnFunc1
	fnD_cljg_DOT_io_walk              lang.FnFunc1
	fnD_cljg_DOT_io_glob              lang.FnFunc1
	fnD_cljg_DOT_io_delete_BANG_      lang.FnFunc1
	fnD_cljg_DOT_io_delete_tree_BANG_ lang.FnFunc1
	fnD_cljg_DOT_io_copy_BANG_        lang.FnFunc2
	fnD_cljg_DOT_io_move_BANG_        lang.FnFunc2
	fnD_cljg_DOT_io_absolute          lang.FnFunc1
	fnD_cljg_DOT_io_real_path         lang.FnFunc1
	fnD_cljg_DOT_io_parent            lang.FnFunc1
	fnD_cljg_DOT_io_filename          lang.FnFunc1
	fnD_cljg_DOT_io_extension         lang.FnFunc1
	fnD_cljg_DOT_io_read_bytes        lang.FnFunc1
	fnD_cljg_DOT_io_home              lang.FnFunc0
	fnD_cljg_DOT_io_cwd               lang.FnFunc0
	fnD_cljg_DOT_io_string_writer     lang.FnFunc0
	fnD_cljg_DOT_io_writer_str        lang.FnFunc1
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("cljg.io")), lang.VarFile, "cljg/io.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote cljg.io))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_cljg_DOT_io)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply1(tmp3, sym_clojure_DOT_core)
	_ = tmp4
	// (require (quote [clojure.string :as str]))
	tmp5 := v_clojure_DOT_core_require.Get()
	tmp6 := lang.Apply1(tmp5, lang.NewVector(sym_clojure_DOT_string, kw_as, sym_str))
	_ = tmp6
	// (def stat (clojure.core/fn ([path] (-fs-stat path))))
	v_cljg_DOT_io_stat.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(34), kw_column, int64(7), kw_end_line, int64(34), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "The file's metadata as {:dir? :file? :size :modified(epoch ms)}, or nil when\n  the path does not exist (or is unreadable)."))
	tmp7 := lang.FnFunc1(func(path8 any) any {
		tmp9 := v_cljg_DOT_io_X_fs_stat.Get()
		tmp10 := lang.Apply1(tmp9, path8)
		return tmp10
	})
	tmp11 := &lang.NamedFn1{Name: "cljg.io/stat", Expects: "1: [path]", F: tmp7}
	v_cljg_DOT_io_stat.BindRoot(tmp11)
	fnD_cljg_DOT_io_stat = tmp11.F
	v_cljg_DOT_io_stat.SealDirect()
	_ = v_cljg_DOT_io_stat
	// (def exists? (clojure.core/fn ([path] (some? (stat path)))))
	v_cljg_DOT_io_exists_QMARK_.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(40), kw_column, int64(7), kw_end_line, int64(40), kw_end_column, int64(14), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "True if `path` exists."))
	tmp12 := lang.FnFunc1(func(path13 any) any {
		tmp14 := v_clojure_DOT_core_some_QMARK_.Get()
		tmp15 := v_cljg_DOT_io_stat.Direct()
		var tmp16 any
		if !tmp15 {
			tmp16 = v_cljg_DOT_io_stat.Get()
		}
		var tmp17 any
		if tmp15 {
			tmp17 = fnD_cljg_DOT_io_stat(path13)
		} else {
			tmp17 = lang.Apply1(tmp16, path13)
		}
		tmp18 := lang.Apply1(tmp14, tmp17)
		return tmp18
	})
	tmp19 := &lang.NamedFn1{Name: "cljg.io/exists?", Expects: "1: [path]", F: tmp12}
	v_cljg_DOT_io_exists_QMARK_.BindRoot(tmp19)
	fnD_cljg_DOT_io_exists_QMARK_ = tmp19.F
	v_cljg_DOT_io_exists_QMARK_.SealDirect()
	_ = v_cljg_DOT_io_exists_QMARK_
	// (def file? (clojure.core/fn ([path] (boolean (:file? (stat path))))))
	v_cljg_DOT_io_file_QMARK_.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(41), kw_column, int64(7), kw_end_line, int64(41), kw_end_column, int64(12), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "True if `path` exists and is a regular file."))
	tmp20 := lang.FnFunc1(func(path21 any) any {
		tmp22 := v_clojure_DOT_core_boolean.Get()
		tmp23 := v_cljg_DOT_io_stat.Direct()
		var tmp24 any
		if !tmp23 {
			tmp24 = v_cljg_DOT_io_stat.Get()
		}
		var tmp25 any
		if tmp23 {
			tmp25 = fnD_cljg_DOT_io_stat(path21)
		} else {
			tmp25 = lang.Apply1(tmp24, path21)
		}
		tmp26 := lang.Apply1(kw_file_QMARK_, tmp25)
		tmp27 := lang.Apply1(tmp22, tmp26)
		return tmp27
	})
	tmp28 := &lang.NamedFn1{Name: "cljg.io/file?", Expects: "1: [path]", F: tmp20}
	v_cljg_DOT_io_file_QMARK_.BindRoot(tmp28)
	fnD_cljg_DOT_io_file_QMARK_ = tmp28.F
	v_cljg_DOT_io_file_QMARK_.SealDirect()
	_ = v_cljg_DOT_io_file_QMARK_
	// (def directory? (clojure.core/fn ([path] (boolean (:dir? (stat path))))))
	v_cljg_DOT_io_directory_QMARK_.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(42), kw_column, int64(7), kw_end_line, int64(42), kw_end_column, int64(17), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "True if `path` exists and is a directory."))
	tmp29 := lang.FnFunc1(func(path30 any) any {
		tmp31 := v_clojure_DOT_core_boolean.Get()
		tmp32 := v_cljg_DOT_io_stat.Direct()
		var tmp33 any
		if !tmp32 {
			tmp33 = v_cljg_DOT_io_stat.Get()
		}
		var tmp34 any
		if tmp32 {
			tmp34 = fnD_cljg_DOT_io_stat(path30)
		} else {
			tmp34 = lang.Apply1(tmp33, path30)
		}
		tmp35 := lang.Apply1(kw_dir_QMARK_, tmp34)
		tmp36 := lang.Apply1(tmp31, tmp35)
		return tmp36
	})
	tmp37 := &lang.NamedFn1{Name: "cljg.io/directory?", Expects: "1: [path]", F: tmp29}
	v_cljg_DOT_io_directory_QMARK_.BindRoot(tmp37)
	fnD_cljg_DOT_io_directory_QMARK_ = tmp37.F
	v_cljg_DOT_io_directory_QMARK_.SealDirect()
	_ = v_cljg_DOT_io_directory_QMARK_
	// (def size (clojure.core/fn ([path] (:size (stat path)))))
	v_cljg_DOT_io_size.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(44), kw_column, int64(7), kw_end_line, int64(44), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "The file's size in bytes, or nil if `path` does not exist."))
	tmp38 := lang.FnFunc1(func(path39 any) any {
		tmp40 := v_cljg_DOT_io_stat.Direct()
		var tmp41 any
		if !tmp40 {
			tmp41 = v_cljg_DOT_io_stat.Get()
		}
		var tmp42 any
		if tmp40 {
			tmp42 = fnD_cljg_DOT_io_stat(path39)
		} else {
			tmp42 = lang.Apply1(tmp41, path39)
		}
		tmp43 := lang.Apply1(kw_size, tmp42)
		return tmp43
	})
	tmp44 := &lang.NamedFn1{Name: "cljg.io/size", Expects: "1: [path]", F: tmp38}
	v_cljg_DOT_io_size.BindRoot(tmp44)
	fnD_cljg_DOT_io_size = tmp44.F
	v_cljg_DOT_io_size.SealDirect()
	_ = v_cljg_DOT_io_size
	// (def modified (clojure.core/fn ([path] (:modified (stat path)))))
	v_cljg_DOT_io_modified.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(49), kw_column, int64(7), kw_end_line, int64(49), kw_end_column, int64(15), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "The file's last-modified time (epoch ms), or nil if `path` does not exist."))
	tmp45 := lang.FnFunc1(func(path46 any) any {
		tmp47 := v_cljg_DOT_io_stat.Direct()
		var tmp48 any
		if !tmp47 {
			tmp48 = v_cljg_DOT_io_stat.Get()
		}
		var tmp49 any
		if tmp47 {
			tmp49 = fnD_cljg_DOT_io_stat(path46)
		} else {
			tmp49 = lang.Apply1(tmp48, path46)
		}
		tmp50 := lang.Apply1(kw_modified, tmp49)
		return tmp50
	})
	tmp51 := &lang.NamedFn1{Name: "cljg.io/modified", Expects: "1: [path]", F: tmp45}
	v_cljg_DOT_io_modified.BindRoot(tmp51)
	fnD_cljg_DOT_io_modified = tmp51.F
	v_cljg_DOT_io_modified.SealDirect()
	_ = v_cljg_DOT_io_modified
	// (def list-files (clojure.core/fn ([path] (-fs-list path))))
	v_cljg_DOT_io_list_files.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(56), kw_column, int64(7), kw_end_line, int64(56), kw_end_column, int64(17), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "A vector of the entry NAMES (not full paths) directly under directory `path`,\n  sorted. Throws if `path` is not a readable directory."))
	tmp52 := lang.FnFunc1(func(path53 any) any {
		tmp54 := v_cljg_DOT_io_X_fs_list.Get()
		tmp55 := lang.Apply1(tmp54, path53)
		return tmp55
	})
	tmp56 := &lang.NamedFn1{Name: "cljg.io/list-files", Expects: "1: [path]", F: tmp52}
	v_cljg_DOT_io_list_files.BindRoot(tmp56)
	fnD_cljg_DOT_io_list_files = tmp56.F
	v_cljg_DOT_io_list_files.SealDirect()
	_ = v_cljg_DOT_io_list_files
	// (def mkdirs (clojure.core/fn ([path] (-fs-mkdir path) path)))
	v_cljg_DOT_io_mkdirs.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(62), kw_column, int64(7), kw_end_line, int64(62), kw_end_column, int64(13), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "Create directory `path` and any missing parents (mkdir -p). Returns `path`.\n  Not an error if it already exists."))
	tmp57 := lang.FnFunc1(func(path58 any) any {
		tmp59 := v_cljg_DOT_io_X_fs_mkdir.Get()
		tmp60 := lang.Apply1(tmp59, path58)
		_ = tmp60
		return path58
	})
	tmp61 := &lang.NamedFn1{Name: "cljg.io/mkdirs", Expects: "1: [path]", F: tmp57}
	v_cljg_DOT_io_mkdirs.BindRoot(tmp61)
	fnD_cljg_DOT_io_mkdirs = tmp61.F
	v_cljg_DOT_io_mkdirs.SealDirect()
	_ = v_cljg_DOT_io_mkdirs
	// (def walk (clojure.core/fn ([root] (-fs-walk root))))
	v_cljg_DOT_io_walk.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(69), kw_column, int64(7), kw_end_line, int64(69), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector(sym_root)), kw_doc, "A vector of every path under `root` (root included), depth-first. Throws if\n  `root` is unreadable."))
	tmp62 := lang.FnFunc1(func(root63 any) any {
		tmp64 := v_cljg_DOT_io_X_fs_walk.Get()
		tmp65 := lang.Apply1(tmp64, root63)
		return tmp65
	})
	tmp66 := &lang.NamedFn1{Name: "cljg.io/walk", Expects: "1: [root]", F: tmp62}
	v_cljg_DOT_io_walk.BindRoot(tmp66)
	fnD_cljg_DOT_io_walk = tmp66.F
	v_cljg_DOT_io_walk.SealDirect()
	_ = v_cljg_DOT_io_walk
	// (def glob (clojure.core/fn ([pattern] (-fs-glob pattern))))
	v_cljg_DOT_io_glob.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(75), kw_column, int64(7), kw_end_line, int64(75), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector(sym_pattern)), kw_doc, "A vector of paths matching the shell `pattern` (filepath.Glob semantics:\n  `*`, `?`, `[…]`), sorted. Empty when nothing matches."))
	tmp67 := lang.FnFunc1(func(pattern68 any) any {
		tmp69 := v_cljg_DOT_io_X_fs_glob.Get()
		tmp70 := lang.Apply1(tmp69, pattern68)
		return tmp70
	})
	tmp71 := &lang.NamedFn1{Name: "cljg.io/glob", Expects: "1: [pattern]", F: tmp67}
	v_cljg_DOT_io_glob.BindRoot(tmp71)
	fnD_cljg_DOT_io_glob = tmp71.F
	v_cljg_DOT_io_glob.SealDirect()
	_ = v_cljg_DOT_io_glob
	// (def delete! (clojure.core/fn ([path] (-fs-delete path false) nil)))
	v_cljg_DOT_io_delete_BANG_.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(83), kw_column, int64(7), kw_end_line, int64(83), kw_end_column, int64(14), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "Delete a single file or empty directory `path`. Not an error if it is\n  already absent. For a non-empty directory use `delete-tree!`."))
	tmp72 := lang.FnFunc1(func(path73 any) any {
		tmp74 := v_cljg_DOT_io_X_fs_delete.Get()
		tmp75 := lang.Apply2(tmp74, path73, false)
		_ = tmp75
		return nil
	})
	tmp76 := &lang.NamedFn1{Name: "cljg.io/delete!", Expects: "1: [path]", F: tmp72}
	v_cljg_DOT_io_delete_BANG_.BindRoot(tmp76)
	fnD_cljg_DOT_io_delete_BANG_ = tmp76.F
	v_cljg_DOT_io_delete_BANG_.SealDirect()
	_ = v_cljg_DOT_io_delete_BANG_
	// (def delete-tree! (clojure.core/fn ([path] (-fs-delete path true) nil)))
	v_cljg_DOT_io_delete_tree_BANG_.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(90), kw_column, int64(7), kw_end_line, int64(90), kw_end_column, int64(19), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "Recursively delete `path` and everything under it (rm -rf). Not an error if\n  it is already absent."))
	tmp77 := lang.FnFunc1(func(path78 any) any {
		tmp79 := v_cljg_DOT_io_X_fs_delete.Get()
		tmp80 := lang.Apply2(tmp79, path78, true)
		_ = tmp80
		return nil
	})
	tmp81 := &lang.NamedFn1{Name: "cljg.io/delete-tree!", Expects: "1: [path]", F: tmp77}
	v_cljg_DOT_io_delete_tree_BANG_.BindRoot(tmp81)
	fnD_cljg_DOT_io_delete_tree_BANG_ = tmp81.F
	v_cljg_DOT_io_delete_tree_BANG_.SealDirect()
	_ = v_cljg_DOT_io_delete_tree_BANG_
	// (def copy! (clojure.core/fn ([src dst] (-fs-copy src dst) dst)))
	v_cljg_DOT_io_copy_BANG_.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(97), kw_column, int64(7), kw_end_line, int64(97), kw_end_column, int64(12), kw_arglists, lang.NewList(lang.NewVector(sym_src, sym_dst)), kw_doc, "Copy file `src` to `dst` (contents + mode). `dst` is overwritten. Returns\n  `dst`. Single file — not a directory tree."))
	tmp82 := lang.FnFunc2(func(src83, dst84 any) any {
		tmp85 := v_cljg_DOT_io_X_fs_copy.Get()
		tmp86 := lang.Apply2(tmp85, src83, dst84)
		_ = tmp86
		return dst84
	})
	tmp87 := &lang.NamedFn2{Name: "cljg.io/copy!", Expects: "2: [src dst]", F: tmp82}
	v_cljg_DOT_io_copy_BANG_.BindRoot(tmp87)
	fnD_cljg_DOT_io_copy_BANG_ = tmp87.F
	v_cljg_DOT_io_copy_BANG_.SealDirect()
	_ = v_cljg_DOT_io_copy_BANG_
	// (def move! (clojure.core/fn ([src dst] (-fs-move src dst) dst)))
	v_cljg_DOT_io_move_BANG_.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(104), kw_column, int64(7), kw_end_line, int64(104), kw_end_column, int64(12), kw_arglists, lang.NewList(lang.NewVector(sym_src, sym_dst)), kw_doc, "Move/rename `src` to `dst` (falling back to copy+delete across filesystems).\n  Returns `dst`."))
	tmp88 := lang.FnFunc2(func(src89, dst90 any) any {
		tmp91 := v_cljg_DOT_io_X_fs_move.Get()
		tmp92 := lang.Apply2(tmp91, src89, dst90)
		_ = tmp92
		return dst90
	})
	tmp93 := &lang.NamedFn2{Name: "cljg.io/move!", Expects: "2: [src dst]", F: tmp88}
	v_cljg_DOT_io_move_BANG_.BindRoot(tmp93)
	fnD_cljg_DOT_io_move_BANG_ = tmp93.F
	v_cljg_DOT_io_move_BANG_.SealDirect()
	_ = v_cljg_DOT_io_move_BANG_
	// (def path (clojure.core/fn ([& segments] (-path-join (vec segments)))))
	v_cljg_DOT_io_path.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(113), kw_column, int64(7), kw_end_line, int64(113), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector(sym_X_AMP_, sym_segments)), kw_doc, "Join `segments` into one path with the host separator, cleaned\n  (e.g. (path \"a\" \"b\" \"c\") => \"a/b/c\")."))
	tmp94 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		default:
			if len(args) < 0 {
				panic(lang.NewArityError(len(args), "cljg.io/path", "0+: [segments & more]"))
			}
			var segments95 any
			if len(args) > 0 {
				segments95 = lang.NewList(args[0:]...)
			}
			_ = segments95
			tmp96 := v_cljg_DOT_io_X_path_join.Get()
			tmp97 := v_clojure_DOT_core_vec.Get()
			tmp98 := lang.Apply1(tmp97, segments95)
			tmp99 := lang.Apply1(tmp96, tmp98)
			return tmp99
		}
	})
	v_cljg_DOT_io_path.BindRoot(tmp94)
	_ = v_cljg_DOT_io_path
	// (def absolute (clojure.core/fn ([path] (-path-abs path))))
	v_cljg_DOT_io_absolute.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(119), kw_column, int64(7), kw_end_line, int64(119), kw_end_column, int64(15), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "`path` resolved against the current directory into an absolute, cleaned path."))
	tmp100 := lang.FnFunc1(func(path101 any) any {
		tmp102 := v_cljg_DOT_io_X_path_abs.Get()
		tmp103 := lang.Apply1(tmp102, path101)
		return tmp103
	})
	tmp104 := &lang.NamedFn1{Name: "cljg.io/absolute", Expects: "1: [path]", F: tmp100}
	v_cljg_DOT_io_absolute.BindRoot(tmp104)
	fnD_cljg_DOT_io_absolute = tmp104.F
	v_cljg_DOT_io_absolute.SealDirect()
	_ = v_cljg_DOT_io_absolute
	// (def real-path (clojure.core/fn ([path] (-path-real path))))
	v_cljg_DOT_io_real_path.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(124), kw_column, int64(7), kw_end_line, int64(124), kw_end_column, int64(16), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "`path` with every symlink resolved, as an absolute cleaned path. Unlike\n  `absolute`, this touches the filesystem — it throws (coded G5024) if `path`\n  does not exist, or on a symlink cycle (ELOOP) rather than looping forever.\n  Use it to canonicalise before comparing paths or guarding a directory walk\n  against symlink cycles."))
	tmp105 := lang.FnFunc1(func(path106 any) any {
		tmp107 := v_cljg_DOT_io_X_path_real.Get()
		tmp108 := lang.Apply1(tmp107, path106)
		return tmp108
	})
	tmp109 := &lang.NamedFn1{Name: "cljg.io/real-path", Expects: "1: [path]", F: tmp105}
	v_cljg_DOT_io_real_path.BindRoot(tmp109)
	fnD_cljg_DOT_io_real_path = tmp109.F
	v_cljg_DOT_io_real_path.SealDirect()
	_ = v_cljg_DOT_io_real_path
	// (def parent (clojure.core/fn ([path] (-path-dir path))))
	v_cljg_DOT_io_parent.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(133), kw_column, int64(7), kw_end_line, int64(133), kw_end_column, int64(13), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "The parent directory of `path` (everything but the final element)."))
	tmp110 := lang.FnFunc1(func(path111 any) any {
		tmp112 := v_cljg_DOT_io_X_path_dir.Get()
		tmp113 := lang.Apply1(tmp112, path111)
		return tmp113
	})
	tmp114 := &lang.NamedFn1{Name: "cljg.io/parent", Expects: "1: [path]", F: tmp110}
	v_cljg_DOT_io_parent.BindRoot(tmp114)
	fnD_cljg_DOT_io_parent = tmp114.F
	v_cljg_DOT_io_parent.SealDirect()
	_ = v_cljg_DOT_io_parent
	// (def filename (clojure.core/fn ([path] (-path-base path))))
	v_cljg_DOT_io_filename.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(138), kw_column, int64(7), kw_end_line, int64(138), kw_end_column, int64(15), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "The final element of `path` (the file or directory name)."))
	tmp115 := lang.FnFunc1(func(path116 any) any {
		tmp117 := v_cljg_DOT_io_X_path_base.Get()
		tmp118 := lang.Apply1(tmp117, path116)
		return tmp118
	})
	tmp119 := &lang.NamedFn1{Name: "cljg.io/filename", Expects: "1: [path]", F: tmp115}
	v_cljg_DOT_io_filename.BindRoot(tmp119)
	fnD_cljg_DOT_io_filename = tmp119.F
	v_cljg_DOT_io_filename.SealDirect()
	_ = v_cljg_DOT_io_filename
	// (def extension (clojure.core/fn ([path] (-path-ext path))))
	v_cljg_DOT_io_extension.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(143), kw_column, int64(7), kw_end_line, int64(143), kw_end_column, int64(16), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "The file extension of `path` including the leading dot (\"\" if none)."))
	tmp120 := lang.FnFunc1(func(path121 any) any {
		tmp122 := v_cljg_DOT_io_X_path_ext.Get()
		tmp123 := lang.Apply1(tmp122, path121)
		return tmp123
	})
	tmp124 := &lang.NamedFn1{Name: "cljg.io/extension", Expects: "1: [path]", F: tmp120}
	v_cljg_DOT_io_extension.BindRoot(tmp124)
	fnD_cljg_DOT_io_extension = tmp124.F
	v_cljg_DOT_io_extension.SealDirect()
	_ = v_cljg_DOT_io_extension
	// (def read-bytes (clojure.core/fn ([path] (-fs-read-bytes path))))
	v_cljg_DOT_io_read_bytes.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(156), kw_column, int64(7), kw_end_line, int64(156), kw_end_column, int64(17), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_doc, "Read the whole file at `path` and return its contents as a byte-array. Use\n  this, not `slurp`, for anything that is not text: a string round-trip\n  replaces every invalid UTF-8 sequence with U+FFFD and changes the length.\n  Throws if the file cannot be read.\n\n  The elements are SIGNED, exactly as the JVM's byte[] is and as\n  clojure.core/byte-array already builds: a 0xFF byte reads back as -1, not\n  255, so (vec (read-bytes p)) agrees with the JVM (oracle 1.12.5).\n\n  The JVM analog is (java.nio.file.Files/readAllBytes (java.nio.file.Path/of\n  path (into-array String []))); cljgo has no java.nio, so this is the route."))
	tmp125 := lang.FnFunc1(func(path126 any) any {
		tmp127 := v_cljg_DOT_io_X_fs_read_bytes.Get()
		tmp128 := lang.Apply1(tmp127, path126)
		return tmp128
	})
	tmp129 := &lang.NamedFn1{Name: "cljg.io/read-bytes", Expects: "1: [path]", F: tmp125}
	v_cljg_DOT_io_read_bytes.BindRoot(tmp129)
	fnD_cljg_DOT_io_read_bytes = tmp129.F
	v_cljg_DOT_io_read_bytes.SealDirect()
	_ = v_cljg_DOT_io_read_bytes
	// (def write-bytes (clojure.core/fn ([path data] (write-bytes path data nil)) ([path data op…
	v_cljg_DOT_io_write_bytes.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(171), kw_column, int64(7), kw_end_line, int64(171), kw_end_column, int64(18), kw_arglists, lang.NewList(lang.NewVector(sym_path, sym_data), lang.NewVector(sym_path, sym_data, sym_opts)), kw_doc, "Write `data` — a byte-array or a string — to the file at `path`, creating it\n  if needed, and return the number of bytes written. Truncates by default;\n  with {:append true} appends instead. `opts` must be a map (or nil) — a\n  non-map is rejected rather than quietly truncating. Throws if the file\n  cannot be written."))
	tmp130 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 2:
			path131 := args[0]
			_ = path131
			data132 := args[1]
			_ = data132
			tmp133 := v_cljg_DOT_io_write_bytes.Get()
			tmp134 := lang.Apply3(tmp133, path131, data132, nil)
			return tmp134
		case 3:
			path135 := args[0]
			_ = path135
			data136 := args[1]
			_ = data136
			opts137 := args[2]
			_ = opts137
			tmp138 := v_cljg_DOT_io_X_fs_write_bytes.Get()
			tmp139 := lang.Apply3(tmp138, path135, data136, opts137)
			return tmp139
		default:
			panic(lang.NewArityError(len(args), "cljg.io/write-bytes", "2: [path data] or 3: [path data opts]"))
		}
	})
	v_cljg_DOT_io_write_bytes.BindRoot(tmp130)
	_ = v_cljg_DOT_io_write_bytes
	// (def home (clojure.core/fn ([] (-fs-home))))
	v_cljg_DOT_io_home.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(182), kw_column, int64(7), kw_end_line, int64(182), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "The current user's home directory."))
	tmp140 := lang.FnFunc0(func() any {
		tmp141 := v_cljg_DOT_io_X_fs_home.Get()
		tmp142 := lang.Apply0(tmp141)
		return tmp142
	})
	tmp143 := &lang.NamedFn0{Name: "cljg.io/home", Expects: "0: []", F: tmp140}
	v_cljg_DOT_io_home.BindRoot(tmp143)
	fnD_cljg_DOT_io_home = tmp143.F
	v_cljg_DOT_io_home.SealDirect()
	_ = v_cljg_DOT_io_home
	// (def cwd (clojure.core/fn ([] (-fs-cwd))))
	v_cljg_DOT_io_cwd.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(183), kw_column, int64(7), kw_end_line, int64(183), kw_end_column, int64(10), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "The current working directory."))
	tmp144 := lang.FnFunc0(func() any {
		tmp145 := v_cljg_DOT_io_X_fs_cwd.Get()
		tmp146 := lang.Apply0(tmp145)
		return tmp146
	})
	tmp147 := &lang.NamedFn0{Name: "cljg.io/cwd", Expects: "0: []", F: tmp144}
	v_cljg_DOT_io_cwd.BindRoot(tmp147)
	fnD_cljg_DOT_io_cwd = tmp147.F
	v_cljg_DOT_io_cwd.SealDirect()
	_ = v_cljg_DOT_io_cwd
	// (def temp-file (clojure.core/fn ([] (temp-file "cljg" "")) ([prefix] (temp-file prefix "")…
	v_cljg_DOT_io_temp_file.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(185), kw_column, int64(7), kw_end_line, int64(185), kw_end_column, int64(16), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_prefix), lang.NewVector(sym_prefix, sym_suffix)), kw_doc, "Create a fresh temporary file and return its path. Optional `prefix`/`suffix`\n  shape the name (e.g. (temp-file \"build-\" \".log\"))."))
	tmp148 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 0:
			tmp149 := v_cljg_DOT_io_temp_file.Get()
			tmp150 := lang.Apply2(tmp149, "cljg", "")
			return tmp150
		case 1:
			prefix151 := args[0]
			_ = prefix151
			tmp152 := v_cljg_DOT_io_temp_file.Get()
			tmp153 := lang.Apply2(tmp152, prefix151, "")
			return tmp153
		case 2:
			prefix154 := args[0]
			_ = prefix154
			suffix155 := args[1]
			_ = suffix155
			tmp156 := v_cljg_DOT_io_X_fs_temp_file.Get()
			tmp157 := lang.Apply2(tmp156, prefix154, suffix155)
			return tmp157
		default:
			panic(lang.NewArityError(len(args), "cljg.io/temp-file", "0: [] or 1: [prefix] or 2: [prefix suffix]"))
		}
	})
	v_cljg_DOT_io_temp_file.BindRoot(tmp148)
	_ = v_cljg_DOT_io_temp_file
	// (def temp-dir (clojure.core/fn ([] (temp-dir "cljg")) ([prefix] (-fs-temp-dir prefix))))
	v_cljg_DOT_io_temp_dir.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(192), kw_column, int64(7), kw_end_line, int64(192), kw_end_column, int64(15), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_prefix)), kw_doc, "Create a fresh temporary directory and return its path. Optional `prefix`\n  shapes the name."))
	tmp158 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 0:
			tmp159 := v_cljg_DOT_io_temp_dir.Get()
			tmp160 := lang.Apply1(tmp159, "cljg")
			return tmp160
		case 1:
			prefix161 := args[0]
			_ = prefix161
			tmp162 := v_cljg_DOT_io_X_fs_temp_dir.Get()
			tmp163 := lang.Apply1(tmp162, prefix161)
			return tmp163
		default:
			panic(lang.NewArityError(len(args), "cljg.io/temp-dir", "0: [] or 1: [prefix]"))
		}
	})
	v_cljg_DOT_io_temp_dir.BindRoot(tmp158)
	_ = v_cljg_DOT_io_temp_dir
	// (def exec (clojure.core/fn ([command] (exec command {})) ([command opts] (-proc-exec (vec …
	v_cljg_DOT_io_exec.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(201), kw_column, int64(7), kw_end_line, int64(201), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector(sym_command), lang.NewVector(sym_command, sym_opts)), kw_doc, "Run a subprocess and return {:out :err :exit :timed-out?} — never throwing on\n  a non-zero exit (that's a normal result; use `sh!` to throw). `command` is a\n  vector [cmd arg…]. opts (optional):\n    :in         a string fed to the process's stdin\n    :env        {name value} merged onto the current environment\n    :dir        the working directory\n    :timeout-ms kill the process after n ms (:timed-out? true, :exit -1)\n  A missing/unrunnable binary throws (it never ran)."))
	tmp164 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			command165 := args[0]
			_ = command165
			tmp166 := v_cljg_DOT_io_exec.Get()
			tmp167 := lang.NewMap()
			tmp168 := lang.Apply2(tmp166, command165, tmp167)
			return tmp168
		case 2:
			command169 := args[0]
			_ = command169
			opts170 := args[1]
			_ = opts170
			tmp171 := v_cljg_DOT_io_X_proc_exec.Get()
			tmp172 := v_clojure_DOT_core_vec.Get()
			tmp173 := lang.Apply1(tmp172, command169)
			tmp174 := lang.Apply2(tmp171, tmp173, opts170)
			return tmp174
		default:
			panic(lang.NewArityError(len(args), "cljg.io/exec", "1: [command] or 2: [command opts]"))
		}
	})
	v_cljg_DOT_io_exec.BindRoot(tmp164)
	_ = v_cljg_DOT_io_exec
	// (def sh (clojure.core/fn ([& command] (exec (vec command)))))
	v_cljg_DOT_io_sh.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(213), kw_column, int64(7), kw_end_line, int64(213), kw_end_column, int64(9), kw_arglists, lang.NewList(lang.NewVector(sym_X_AMP_, sym_command)), kw_doc, "Convenience over `exec` for the common shape: pass the command + args as\n  varargs, get the same {:out :err :exit :timed-out?} map back.\n    (sh \"git\" \"rev-parse\" \"HEAD\")\n  For stdin/env/dir/timeout use `exec` with an opts map."))
	tmp175 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		default:
			if len(args) < 0 {
				panic(lang.NewArityError(len(args), "cljg.io/sh", "0+: [command & more]"))
			}
			var command176 any
			if len(args) > 0 {
				command176 = lang.NewList(args[0:]...)
			}
			_ = command176
			tmp177 := v_cljg_DOT_io_exec.Get()
			tmp178 := v_clojure_DOT_core_vec.Get()
			tmp179 := lang.Apply1(tmp178, command176)
			tmp180 := lang.Apply1(tmp177, tmp179)
			return tmp180
		}
	})
	v_cljg_DOT_io_sh.BindRoot(tmp175)
	_ = v_cljg_DOT_io_sh
	// (def sh! (clojure.core/fn ([command] (sh! command {})) ([command opts] (let [{:keys [exit …
	v_cljg_DOT_io_sh_BANG_.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(221), kw_column, int64(7), kw_end_line, int64(221), kw_end_column, int64(10), kw_arglists, lang.NewList(lang.NewVector(sym_command), lang.NewVector(sym_command, sym_opts)), kw_doc, "Like `sh`, but THROWS (ex-info) if the command exits non-zero or times out —\n  for the script style where a failed step should abort. Returns the same result\n  map on success. Takes a command vector + optional opts (like `exec`)."))
	tmp181 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			command182 := args[0]
			_ = command182
			tmp183 := v_cljg_DOT_io_sh_BANG_.Get()
			tmp184 := lang.NewMap()
			tmp185 := lang.Apply2(tmp183, command182, tmp184)
			return tmp185
		case 2:
			command186 := args[0]
			_ = command186
			opts187 := args[1]
			_ = opts187
			var tmp188 any
			_ = tmp188
			{
				tmp189 := v_cljg_DOT_io_exec.Get()
				tmp190 := lang.Apply2(tmp189, command186, opts187)
				var map__165191 any = tmp190
				_ = map__165191
				tmp192 := v_clojure_DOT_core_seq_QMARK_.Get()
				tmp193 := lang.Apply1(tmp192, map__165191)
				var tmp194 any
				_ = tmp194
				if lang.IsTruthy(tmp193) {
					tmp195 := v_clojure_DOT_core_seq_to_map_for_destructuring.Get()
					tmp196 := lang.Apply1(tmp195, map__165191)
					tmp194 = tmp196
				} else {
					tmp194 = map__165191
				}
				var map__165197 any = tmp194
				_ = map__165197
				var r198 any = map__165197
				_ = r198
				tmp199 := v_clojure_DOT_core_get.Get()
				tmp200 := lang.Apply2(tmp199, map__165197, kw_exit)
				var exit201 any = tmp200
				_ = exit201
				tmp202 := v_clojure_DOT_core_get.Get()
				tmp203 := lang.Apply2(tmp202, map__165197, kw_err)
				var err204 any = tmp203
				_ = err204
				tmp205 := v_clojure_DOT_core_get.Get()
				tmp206 := lang.Apply2(tmp205, map__165197, kw_timed_out_QMARK_)
				var timed_out_QMARK_207 any = tmp206
				_ = timed_out_QMARK_207
				tmp208 := v_clojure_DOT_core_not_EQ_.Get()
				tmp209 := lang.Apply2(tmp208, int64(0), exit201)
				var tmp210 any
				_ = tmp210
				if lang.IsTruthy(tmp209) {
					tmp211 := v_clojure_DOT_core_ex_info.Get()
					tmp212 := v_clojure_DOT_core_str.Get()
					var tmp213 any
					_ = tmp213
					if lang.IsTruthy(timed_out_QMARK_207) {
						tmp213 = " (timed out)"
					} else {
						tmp213 = nil
					}
					tmp214 := v_clojure_DOT_string_join.Get()
					tmp215 := lang.Apply2(tmp214, " ", command186)
					tmp216 := v_clojure_DOT_core_seq.Get()
					tmp217 := lang.Apply1(tmp216, err204)
					var tmp218 any
					_ = tmp218
					if lang.IsTruthy(tmp217) {
						tmp219 := v_clojure_DOT_core_str.Get()
						tmp220 := lang.Apply2(tmp219, "\n", err204)
						tmp218 = tmp220
					} else {
						tmp218 = nil
					}
					tmp221 := lang.Apply(tmp212, []any{"cljg.io: command failed", tmp213, " (exit ", exit201, "): ", tmp215, tmp218})
					tmp222 := v_clojure_DOT_core_assoc.Get()
					tmp223 := v_clojure_DOT_core_vec.Get()
					tmp224 := lang.Apply1(tmp223, command186)
					tmp225 := lang.Apply3(tmp222, r198, kw_command, tmp224)
					tmp226 := lang.Apply2(tmp211, tmp221, tmp225)
					panic(rt.Throw(tmp226))
				} else {
					tmp210 = nil
				}
				_ = tmp210
				tmp188 = r198
			}
			return tmp188
		default:
			panic(lang.NewArityError(len(args), "cljg.io/sh!", "1: [command] or 2: [command opts]"))
		}
	})
	v_cljg_DOT_io_sh_BANG_.BindRoot(tmp181)
	_ = v_cljg_DOT_io_sh_BANG_
	// (def string-writer (clojure.core/fn ([] (clojure.core/-string-writer))))
	v_cljg_DOT_io_string_writer.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(256), kw_column, int64(7), kw_end_line, int64(256), kw_end_column, int64(20), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "A fresh in-memory writer *out* can be bound to — the java.io.StringWriter\n  analog. Read what has been written to it with `writer-str`."))
	tmp227 := lang.FnFunc0(func() any {
		tmp228 := v_clojure_DOT_core_X_string_writer.Get()
		tmp229 := lang.Apply0(tmp228)
		return tmp229
	})
	tmp230 := &lang.NamedFn0{Name: "cljg.io/string-writer", Expects: "0: []", F: tmp227}
	v_cljg_DOT_io_string_writer.BindRoot(tmp230)
	fnD_cljg_DOT_io_string_writer = tmp230.F
	v_cljg_DOT_io_string_writer.SealDirect()
	_ = v_cljg_DOT_io_string_writer
	// (def writer-str (clojure.core/fn ([w] (clojure.core/-string-writer-str w))))
	v_cljg_DOT_io_writer_str.SetMeta(lang.NewMap(kw_file, "cljg/io.cljg", kw_line, int64(262), kw_column, int64(7), kw_end_line, int64(262), kw_end_column, int64(17), kw_arglists, lang.NewList(lang.NewVector(sym_w)), kw_doc, "Everything written to `w` (a `string-writer`) so far, as a String — the\n  (str a-StringWriter) analog. Non-destructive: the writer keeps accumulating."))
	tmp231 := lang.FnFunc1(func(w232 any) any {
		tmp233 := v_clojure_DOT_core_X_string_writer_str.Get()
		tmp234 := lang.Apply1(tmp233, w232)
		return tmp234
	})
	tmp235 := &lang.NamedFn1{Name: "cljg.io/writer-str", Expects: "1: [w]", F: tmp231}
	v_cljg_DOT_io_writer_str.BindRoot(tmp235)
	fnD_cljg_DOT_io_writer_str = tmp235.F
	v_cljg_DOT_io_writer_str.SealDirect()
	_ = v_cljg_DOT_io_writer_str
}
