// Code generated by cljgo build. DO NOT EDIT.

package cljgsecurity

import (
	rt "github.com/muthuishere/cljgo/pkg/emit/rt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_action                                 = lang.InternKeywordString("action")
	kw_actor                                  = lang.InternKeywordString("actor")
	kw_arglists                               = lang.InternKeywordString("arglists")
	kw_as                                     = lang.InternKeywordString("as")
	kw_auth_SLASH_auto_banned                 = lang.InternKeywordString("auth/auto-banned")
	kw_auth_SLASH_banned_request              = lang.InternKeywordString("auth/banned-request")
	kw_auth_SLASH_claims                      = lang.InternKeywordString("auth/claims")
	kw_auth_SLASH_denied                      = lang.InternKeywordString("auth/denied")
	kw_auth_SLASH_forbidden                   = lang.InternKeywordString("auth/forbidden")
	kw_auth_SLASH_token_issued                = lang.InternKeywordString("auth/token-issued")
	kw_auth_SLASH_unauthorized                = lang.InternKeywordString("auth/unauthorized")
	kw_auto                                   = lang.InternKeywordString("auto")
	kw_auto_ban                               = lang.InternKeywordString("auto-ban")
	kw_backend                                = lang.InternKeywordString("backend")
	kw_banned_until                           = lang.InternKeywordString("banned-until")
	kw_body                                   = lang.InternKeywordString("body")
	kw_bri_SLASH_error                        = lang.InternKeywordString("bri/error")
	kw_clock                                  = lang.InternKeywordString("clock")
	kw_column                                 = lang.InternKeywordString("column")
	kw_cooldown_ms                            = lang.InternKeywordString("cooldown-ms")
	kw_count                                  = lang.InternKeywordString("count")
	kw_denials                                = lang.InternKeywordString("denials")
	kw_doc                                    = lang.InternKeywordString("doc")
	kw_else_                                  = lang.InternKeywordString("else")
	kw_end_column                             = lang.InternKeywordString("end-column")
	kw_end_line                               = lang.InternKeywordString("end-line")
	kw_error_                                 = lang.InternKeywordString("error")
	kw_exp                                    = lang.InternKeywordString("exp")
	kw_exp_seconds                            = lang.InternKeywordString("exp-seconds")
	kw_file                                   = lang.InternKeywordString("file")
	kw_guard                                  = lang.InternKeywordString("guard")
	kw_headers                                = lang.InternKeywordString("headers")
	kw_iat                                    = lang.InternKeywordString("iat")
	kw_info                                   = lang.InternKeywordString("info")
	kw_ip                                     = lang.InternKeywordString("ip")
	kw_key                                    = lang.InternKeywordString("key")
	kw_line                                   = lang.InternKeywordString("line")
	kw_name                                   = lang.InternKeywordString("name")
	kw_not_authorized                         = lang.InternKeywordString("not-authorized")
	kw_now                                    = lang.InternKeywordString("now")
	kw_private                                = lang.InternKeywordString("private")
	kw_reason                                 = lang.InternKeywordString("reason")
	kw_request_SLASH_id                       = lang.InternKeywordString("request/id")
	kw_role                                   = lang.InternKeywordString("role")
	kw_secret                                 = lang.InternKeywordString("secret")
	kw_severity                               = lang.InternKeywordString("severity")
	kw_should_ban_QMARK_                      = lang.InternKeywordString("should-ban?")
	kw_status                                 = lang.InternKeywordString("status")
	kw_store                                  = lang.InternKeywordString("store")
	kw_sub                                    = lang.InternKeywordString("sub")
	kw_target                                 = lang.InternKeywordString("target")
	kw_threshold                              = lang.InternKeywordString("threshold")
	kw_unauthenticated                        = lang.InternKeywordString("unauthenticated")
	kw_uri                                    = lang.InternKeywordString("uri")
	kw_warning                                = lang.InternKeywordString("warning")
	kw_window_ms                              = lang.InternKeywordString("window-ms")
	kw_wrap                                   = lang.InternKeywordString("wrap")
	sym_account                               = lang.NewSymbol("account")
	sym_audit                                 = lang.NewSymbol("audit")
	sym_bri_DOT_core_DOT_audit                = lang.NewSymbol("bri.core.audit")
	sym_bri_DOT_web_DOT_http                  = lang.NewSymbol("bri.web.http")
	sym_claims                                = lang.NewSymbol("claims")
	sym_claims_pred                           = lang.NewSymbol("claims-pred")
	sym_cljg_DOT_security                     = lang.NewSymbol("cljg.security")
	sym_clojure_DOT_core                      = lang.NewSymbol("clojure.core")
	sym_clojure_DOT_string                    = lang.NewSymbol("clojure.string")
	sym_data                                  = lang.NewSymbol("data")
	sym_handler                               = lang.NewSymbol("handler")
	sym_hash                                  = lang.NewSymbol("hash")
	sym_http                                  = lang.NewSymbol("http")
	sym_key                                   = lang.NewSymbol("key")
	sym_message                               = lang.NewSymbol("message")
	sym_n                                     = lang.NewSymbol("n")
	sym_opts                                  = lang.NewSymbol("opts")
	sym_pw                                    = lang.NewSymbol("pw")
	sym_req                                   = lang.NewSymbol("req")
	sym_req_pred                              = lang.NewSymbol("req-pred")
	sym_role                                  = lang.NewSymbol("role")
	sym_s                                     = lang.NewSymbol("s")
	sym_service                               = lang.NewSymbol("service")
	sym_str                                   = lang.NewSymbol("str")
	sym_sub                                   = lang.NewSymbol("sub")
	sym_token                                 = lang.NewSymbol("token")
	sym_value                                 = lang.NewSymbol("value")
	v_bri_DOT_core_DOT_audit_record           = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("record"))
	v_bri_DOT_web_DOT_http_client_key         = lang.InternVarName(lang.NewSymbol("bri.web.http"), lang.NewSymbol("client-key"))
	v_bri_DOT_web_DOT_http_mark_subject_BANG_ = lang.InternVarName(lang.NewSymbol("bri.web.http"), lang.NewSymbol("mark-subject!"))
	v_cljg_DOT_security_X_argon2_hash         = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-argon2-hash")).SetPrivate()
	v_cljg_DOT_security_X_argon2_verify       = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-argon2-verify")).SetPrivate()
	v_cljg_DOT_security_X_b64_decode          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-b64-decode")).SetPrivate()
	v_cljg_DOT_security_X_b64_decode_bytes    = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-b64-decode-bytes")).SetPrivate()
	v_cljg_DOT_security_X_b64_encode          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-b64-encode")).SetPrivate()
	v_cljg_DOT_security_X_bcrypt_verify       = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-bcrypt-verify")).SetPrivate()
	v_cljg_DOT_security_X_getenv              = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-getenv")).SetPrivate()
	v_cljg_DOT_security_X_hex_decode          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-hex-decode")).SetPrivate()
	v_cljg_DOT_security_X_hex_encode          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-hex-encode")).SetPrivate()
	v_cljg_DOT_security_X_hmac_sha256         = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-hmac-sha256")).SetPrivate()
	v_cljg_DOT_security_X_jwt_sign            = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-jwt-sign")).SetPrivate()
	v_cljg_DOT_security_X_jwt_verify          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-jwt-verify")).SetPrivate()
	v_cljg_DOT_security_X_keychain_del        = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-keychain-del")).SetPrivate()
	v_cljg_DOT_security_X_keychain_get        = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-keychain-get")).SetPrivate()
	v_cljg_DOT_security_X_keychain_set        = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-keychain-set")).SetPrivate()
	v_cljg_DOT_security_X_now_millis          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-now-millis")).SetPrivate()
	v_cljg_DOT_security_X_rand_token          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-rand-token")).SetPrivate()
	v_cljg_DOT_security_X_secure_random       = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-secure-random")).SetPrivate()
	v_cljg_DOT_security_X_sha256              = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-sha256")).SetPrivate()
	v_cljg_DOT_security_X_uuid                = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("-uuid")).SetPrivate()
	v_cljg_DOT_security_admin_only            = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("admin-only"))
	v_cljg_DOT_security_authenticate          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("authenticate")).SetPrivate()
	v_cljg_DOT_security_auto_ban              = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("auto-ban"))
	v_cljg_DOT_security_backend_name          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("backend-name")).SetPrivate()
	v_cljg_DOT_security_ban_store             = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("ban-store")).SetPrivate()
	v_cljg_DOT_security_base64                = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("base64"))
	v_cljg_DOT_security_base64_decode         = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("base64-decode"))
	v_cljg_DOT_security_base64_decode_bytes   = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("base64-decode-bytes"))
	v_cljg_DOT_security_base64_encode         = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("base64-encode"))
	v_cljg_DOT_security_bearer                = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("bearer")).SetPrivate()
	v_cljg_DOT_security_check_password        = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("check-password"))
	v_cljg_DOT_security_delete_from_keychain  = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("delete-from-keychain"))
	v_cljg_DOT_security_deny_401              = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("deny-401")).SetPrivate()
	v_cljg_DOT_security_deny_403              = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("deny-403")).SetPrivate()
	v_cljg_DOT_security_get_from_keychain     = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("get-from-keychain"))
	v_cljg_DOT_security_guard                 = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("guard"))
	v_cljg_DOT_security_guard_claims          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("guard-claims"))
	v_cljg_DOT_security_hash_password         = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("hash-password"))
	v_cljg_DOT_security_hex                   = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("hex"))
	v_cljg_DOT_security_hex_decode            = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("hex-decode"))
	v_cljg_DOT_security_hmac                  = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("hmac"))
	v_cljg_DOT_security_issue                 = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("issue"))
	v_cljg_DOT_security_logged_in_only        = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("logged-in-only"))
	v_cljg_DOT_security_now_seconds           = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("now-seconds")).SetPrivate()
	v_cljg_DOT_security_process_secret        = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("process-secret")).SetPrivate()
	v_cljg_DOT_security_random                = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("random"))
	v_cljg_DOT_security_resolve_secret        = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("resolve-secret")).SetPrivate()
	v_cljg_DOT_security_role_only             = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("role-only"))
	v_cljg_DOT_security_save_to_keychain      = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("save-to-keychain"))
	v_cljg_DOT_security_sha256                = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("sha256"))
	v_cljg_DOT_security_sign                  = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("sign"))
	v_cljg_DOT_security_subject               = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("subject"))
	v_cljg_DOT_security_token                 = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("token"))
	v_cljg_DOT_security_user_only             = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("user-only"))
	v_cljg_DOT_security_uuid                  = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("uuid"))
	v_cljg_DOT_security_verify                = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("verify"))
	v_cljg_DOT_security_verify_BANG_          = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("verify!"))
	v_cljg_DOT_security_wrap_guard            = lang.InternVarName(lang.NewSymbol("cljg.security"), lang.NewSymbol("wrap-guard")).SetPrivate()
	v_clojure_DOT_core_X_                     = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("-"))
	v_clojure_DOT_core_X_EQ_                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("="))
	v_clojure_DOT_core_X_GT_                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol(">"))
	v_clojure_DOT_core_X_GT__EQ_              = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol(">="))
	v_clojure_DOT_core_X_LT_                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("<"))
	v_clojure_DOT_core_X_PLUS_                = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("+"))
	v_clojure_DOT_core_X_make_delay           = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("-make-delay")).SetPrivate()
	v_clojure_DOT_core_assoc                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("assoc"))
	v_clojure_DOT_core_atom                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("atom"))
	v_clojure_DOT_core_boolean                = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("boolean"))
	v_clojure_DOT_core_conj                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("conj"))
	v_clojure_DOT_core_contains_QMARK_        = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("contains?"))
	v_clojure_DOT_core_count                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("count"))
	v_clojure_DOT_core_deref                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("deref"))
	v_clojure_DOT_core_ex_info                = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("ex-info"))
	v_clojure_DOT_core_filterv                = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("filterv"))
	v_clojure_DOT_core_get                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("get"))
	v_clojure_DOT_core_in_ns                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_keyword                = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("keyword"))
	v_clojure_DOT_core_map_QMARK_             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("map?"))
	v_clojure_DOT_core_max_                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("max"))
	v_clojure_DOT_core_name                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("name"))
	v_clojure_DOT_core_nil_QMARK_             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("nil?"))
	v_clojure_DOT_core_not                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("not"))
	v_clojure_DOT_core_quot                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("quot"))
	v_clojure_DOT_core_refer                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
	v_clojure_DOT_core_require                = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("require"))
	v_clojure_DOT_core_reset_BANG_            = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("reset!"))
	v_clojure_DOT_core_str                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("str"))
	v_clojure_DOT_core_string_QMARK_          = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("string?"))
	v_clojure_DOT_core_subs                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("subs"))
	v_clojure_DOT_string_starts_with_QMARK_   = lang.InternVarName(lang.NewSymbol("clojure.string"), lang.NewSymbol("starts-with?"))
)

var (
	fnD_cljg_DOT_security_resolve_secret      lang.FnFunc1
	fnD_cljg_DOT_security_now_seconds         lang.FnFunc1
	fnD_cljg_DOT_security_subject             lang.FnFunc1
	fnD_cljg_DOT_security_hash_password       lang.FnFunc1
	fnD_cljg_DOT_security_check_password      lang.FnFunc2
	fnD_cljg_DOT_security_sha256              lang.FnFunc1
	fnD_cljg_DOT_security_hmac                lang.FnFunc2
	fnD_cljg_DOT_security_random              lang.FnFunc1
	fnD_cljg_DOT_security_token               lang.FnFunc0
	fnD_cljg_DOT_security_uuid                lang.FnFunc0
	fnD_cljg_DOT_security_base64              lang.FnFunc1
	fnD_cljg_DOT_security_base64_encode       lang.FnFunc1
	fnD_cljg_DOT_security_base64_decode       lang.FnFunc1
	fnD_cljg_DOT_security_base64_decode_bytes lang.FnFunc1
	fnD_cljg_DOT_security_hex                 lang.FnFunc1
	fnD_cljg_DOT_security_hex_decode          lang.FnFunc1
	fnD_cljg_DOT_security_backend_name        lang.FnFunc1
	fnD_cljg_DOT_security_bearer              lang.FnFunc1
	fnD_cljg_DOT_security_authenticate        lang.FnFunc1
	fnD_cljg_DOT_security_deny_401            lang.FnFunc1
	fnD_cljg_DOT_security_deny_403            lang.FnFunc2
	fnD_cljg_DOT_security_wrap_guard          lang.FnFunc2
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("cljg.security")), lang.VarFile, "cljg/security.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote cljg.security))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_cljg_DOT_security)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply1(tmp3, sym_clojure_DOT_core)
	_ = tmp4
	// (require (quote [clojure.string :as str]))
	tmp5 := v_clojure_DOT_core_require.Get()
	tmp6 := lang.Apply1(tmp5, lang.NewVector(sym_clojure_DOT_string, kw_as, sym_str))
	_ = tmp6
	// (require (quote [bri.core.audit :as audit]))
	tmp7 := v_clojure_DOT_core_require.Get()
	tmp8 := lang.Apply1(tmp7, lang.NewVector(sym_bri_DOT_core_DOT_audit, kw_as, sym_audit))
	_ = tmp8
	// (require (quote [bri.web.http :as http]))
	tmp9 := v_clojure_DOT_core_require.Get()
	tmp10 := lang.Apply1(tmp9, lang.NewVector(sym_bri_DOT_web_DOT_http, kw_as, sym_http))
	_ = tmp10
	// (def process-secret (delay (or (-getenv "APP_AUTH__SECRET") (-rand-token))))
	v_cljg_DOT_security_process_secret.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(38), kw_column, int64(6), kw_end_line, int64(38), kw_end_column, int64(30), kw_private, true))
	tmp11 := v_clojure_DOT_core_X_make_delay.Get()
	tmp12 := lang.FnFunc0(func() any {
		var tmp13 any
		_ = tmp13
		{
			tmp14 := v_cljg_DOT_security_X_getenv.Get()
			tmp15 := lang.Apply1(tmp14, "APP_AUTH__SECRET")
			var or__2__auto__16 any = tmp15
			_ = or__2__auto__16
			var tmp17 any
			_ = tmp17
			if lang.IsTruthy(or__2__auto__16) {
				tmp17 = or__2__auto__16
			} else {
				tmp18 := v_cljg_DOT_security_X_rand_token.Get()
				tmp19 := lang.Apply0(tmp18)
				tmp17 = tmp19
			}
			tmp13 = tmp17
		}
		return tmp13
	})
	tmp20 := &lang.NamedFn0{Name: "fn", Expects: "0: []", F: tmp12}
	tmp21 := lang.Apply1(tmp11, tmp20)
	v_cljg_DOT_security_process_secret.BindRoot(tmp21)
	_ = v_cljg_DOT_security_process_secret
	// (def resolve-secret (clojure.core/fn ([opts] (or (:secret opts) (clojure.core/deref proces…
	v_cljg_DOT_security_resolve_secret.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(40), kw_column, int64(7), kw_end_line, int64(40), kw_end_column, int64(31), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_opts))))
	tmp22 := lang.FnFunc1(func(opts23 any) any {
		var tmp24 any
		_ = tmp24
		{
			tmp25 := lang.Apply1(kw_secret, opts23)
			var or__2__auto__26 any = tmp25
			_ = or__2__auto__26
			var tmp27 any
			_ = tmp27
			if lang.IsTruthy(or__2__auto__26) {
				tmp27 = or__2__auto__26
			} else {
				tmp28 := v_clojure_DOT_core_deref.Get()
				tmp29 := v_cljg_DOT_security_process_secret.Get()
				tmp30 := lang.Apply1(tmp28, tmp29)
				tmp27 = tmp30
			}
			tmp24 = tmp27
		}
		return tmp24
	})
	tmp31 := &lang.NamedFn1{Name: "cljg.security/resolve-secret", Expects: "1: [opts]", F: tmp22}
	v_cljg_DOT_security_resolve_secret.BindRoot(tmp31)
	fnD_cljg_DOT_security_resolve_secret = tmp31.F
	v_cljg_DOT_security_resolve_secret.SealDirect()
	_ = v_cljg_DOT_security_resolve_secret
	// (def now-seconds (clojure.core/fn ([opts] (or (:now opts) (quot (-now-millis) 1000)))))
	v_cljg_DOT_security_now_seconds.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(43), kw_column, int64(7), kw_end_line, int64(43), kw_end_column, int64(28), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_opts))))
	tmp32 := lang.FnFunc1(func(opts33 any) any {
		var tmp34 any
		_ = tmp34
		{
			tmp35 := lang.Apply1(kw_now, opts33)
			var or__2__auto__36 any = tmp35
			_ = or__2__auto__36
			var tmp37 any
			_ = tmp37
			if lang.IsTruthy(or__2__auto__36) {
				tmp37 = or__2__auto__36
			} else {
				tmp38 := v_clojure_DOT_core_quot.Get()
				tmp39 := v_cljg_DOT_security_X_now_millis.Get()
				tmp40 := lang.Apply0(tmp39)
				tmp41 := lang.Apply2(tmp38, tmp40, int64(1000))
				tmp37 = tmp41
			}
			tmp34 = tmp37
		}
		return tmp34
	})
	tmp42 := &lang.NamedFn1{Name: "cljg.security/now-seconds", Expects: "1: [opts]", F: tmp32}
	v_cljg_DOT_security_now_seconds.BindRoot(tmp42)
	fnD_cljg_DOT_security_now_seconds = tmp42.F
	v_cljg_DOT_security_now_seconds.SealDirect()
	_ = v_cljg_DOT_security_now_seconds
	// (def sign (clojure.core/fn ([claims] (sign claims {})) ([claims opts] (let [now (now-secon…
	v_cljg_DOT_security_sign.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(47), kw_column, int64(7), kw_end_line, int64(47), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector(sym_claims), lang.NewVector(sym_claims, sym_opts)), kw_doc, "Sign claims into an HS256 token. iat and exp are injected (exp =\n  iat + :exp-seconds, default 3600). Options: :exp-seconds, :secret\n  (defaults from APP_AUTH__SECRET), :now (epoch seconds, for tests).\n  One call is the common case: (sign {:sub \"u\" :role \"admin\"})."))
	tmp43 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			claims44 := args[0]
			_ = claims44
			tmp45 := v_cljg_DOT_security_sign.Get()
			tmp46 := lang.NewMap()
			tmp47 := lang.Apply2(tmp45, claims44, tmp46)
			return tmp47
		case 2:
			claims48 := args[0]
			_ = claims48
			opts49 := args[1]
			_ = opts49
			var tmp50 any
			_ = tmp50
			{
				tmp51 := v_cljg_DOT_security_now_seconds.Direct()
				var tmp52 any
				if !tmp51 {
					tmp52 = v_cljg_DOT_security_now_seconds.Get()
				}
				var tmp53 any
				if tmp51 {
					tmp53 = fnD_cljg_DOT_security_now_seconds(opts49)
				} else {
					tmp53 = lang.Apply1(tmp52, opts49)
				}
				var now54 any = tmp53
				_ = now54
				tmp55 := v_clojure_DOT_core_assoc.Get()
				var tmp56 any
				_ = tmp56
				{
					tmp57 := lang.Apply1(kw_exp_seconds, opts49)
					var or__2__auto__58 any = tmp57
					_ = or__2__auto__58
					var tmp59 any
					_ = tmp59
					if lang.IsTruthy(or__2__auto__58) {
						tmp59 = or__2__auto__58
					} else {
						tmp59 = int64(3600)
					}
					tmp56 = tmp59
				}
				tmp60 := rt.Add2(v_clojure_DOT_core_X_PLUS_, now54, tmp56)
				tmp61 := lang.Apply(tmp55, []any{claims48, kw_iat, now54, kw_exp, tmp60})
				var body62 any = tmp61
				_ = body62
				tmp63 := v_cljg_DOT_security_X_jwt_sign.Get()
				tmp64 := v_cljg_DOT_security_resolve_secret.Direct()
				var tmp65 any
				if !tmp64 {
					tmp65 = v_cljg_DOT_security_resolve_secret.Get()
				}
				var tmp66 any
				if tmp64 {
					tmp66 = fnD_cljg_DOT_security_resolve_secret(opts49)
				} else {
					tmp66 = lang.Apply1(tmp65, opts49)
				}
				tmp67 := lang.Apply2(tmp63, tmp66, body62)
				tmp50 = tmp67
			}
			return tmp50
		default:
			panic(lang.NewArityError(len(args), "cljg.security/sign", "1: [claims] or 2: [claims opts]"))
		}
	})
	v_cljg_DOT_security_sign.BindRoot(tmp43)
	_ = v_cljg_DOT_security_sign
	// (def verify (clojure.core/fn ([token] (verify token {})) ([token opts] (let [claims (and (…
	v_cljg_DOT_security_verify.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(58), kw_column, int64(7), kw_end_line, int64(58), kw_end_column, int64(13), kw_arglists, lang.NewList(lang.NewVector(sym_token), lang.NewVector(sym_token, sym_opts)), kw_doc, "Verify an HS256 token: returns the claims map, or nil on a bad\n  signature, wrong algorithm, malformed token, or expiry. The algorithm\n  is pinned in the Go verifier; exp is checked here against :now (epoch\n  seconds, default wall-clock) so tests freeze the clock."))
	tmp68 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			token69 := args[0]
			_ = token69
			tmp70 := v_cljg_DOT_security_verify.Get()
			tmp71 := lang.NewMap()
			tmp72 := lang.Apply2(tmp70, token69, tmp71)
			return tmp72
		case 2:
			token73 := args[0]
			_ = token73
			opts74 := args[1]
			_ = opts74
			var tmp75 any
			_ = tmp75
			{
				var tmp76 any
				_ = tmp76
				{
					tmp77 := v_clojure_DOT_core_string_QMARK_.Get()
					tmp78 := lang.Apply1(tmp77, token73)
					var and__1__auto__79 any = tmp78
					_ = and__1__auto__79
					var tmp80 any
					_ = tmp80
					if lang.IsTruthy(and__1__auto__79) {
						tmp81 := v_cljg_DOT_security_X_jwt_verify.Get()
						tmp82 := v_cljg_DOT_security_resolve_secret.Direct()
						var tmp83 any
						if !tmp82 {
							tmp83 = v_cljg_DOT_security_resolve_secret.Get()
						}
						var tmp84 any
						if tmp82 {
							tmp84 = fnD_cljg_DOT_security_resolve_secret(opts74)
						} else {
							tmp84 = lang.Apply1(tmp83, opts74)
						}
						tmp85 := lang.Apply2(tmp81, tmp84, token73)
						tmp80 = tmp85
					} else {
						tmp80 = and__1__auto__79
					}
					tmp76 = tmp80
				}
				var claims86 any = tmp76
				_ = claims86
				tmp87 := v_clojure_DOT_core_map_QMARK_.Get()
				tmp88 := lang.Apply1(tmp87, claims86)
				var tmp89 any
				_ = tmp89
				if lang.IsTruthy(tmp88) {
					var tmp90 any
					_ = tmp90
					{
						tmp91 := lang.Apply1(kw_exp, claims86)
						var exp92 any = tmp91
						_ = exp92
						var tmp93 any
						_ = tmp93
						{
							tmp94 := v_clojure_DOT_core_nil_QMARK_.Get()
							tmp95 := lang.Apply1(tmp94, exp92)
							var or__2__auto__96 any = tmp95
							_ = or__2__auto__96
							var tmp97 any
							_ = tmp97
							if lang.IsTruthy(or__2__auto__96) {
								tmp97 = or__2__auto__96
							} else {
								tmp98 := v_cljg_DOT_security_now_seconds.Direct()
								var tmp99 any
								if !tmp98 {
									tmp99 = v_cljg_DOT_security_now_seconds.Get()
								}
								var tmp100 any
								if tmp98 {
									tmp100 = fnD_cljg_DOT_security_now_seconds(opts74)
								} else {
									tmp100 = lang.Apply1(tmp99, opts74)
								}
								tmp101 := rt.LT2(v_clojure_DOT_core_X_LT_, tmp100, exp92)
								tmp97 = tmp101
							}
							tmp93 = tmp97
						}
						var tmp102 any
						_ = tmp102
						if lang.IsTruthy(tmp93) {
							tmp102 = claims86
						} else {
							tmp102 = nil
						}
						tmp90 = tmp102
					}
					tmp89 = tmp90
				} else {
					tmp89 = nil
				}
				tmp75 = tmp89
			}
			return tmp75
		default:
			panic(lang.NewArityError(len(args), "cljg.security/verify", "1: [token] or 2: [token opts]"))
		}
	})
	v_cljg_DOT_security_verify.BindRoot(tmp68)
	_ = v_cljg_DOT_security_verify
	// (def verify! (clojure.core/fn ([token] (verify! token {})) ([token opts] (or (verify token…
	v_cljg_DOT_security_verify_BANG_.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(71), kw_column, int64(7), kw_end_line, int64(71), kw_end_column, int64(14), kw_arglists, lang.NewList(lang.NewVector(sym_token), lang.NewVector(sym_token, sym_opts)), kw_doc, "Like verify, but throws :auth/unauthorized (funnels to 401) instead of\n  returning nil (the ADR 0014 ! convention)."))
	tmp103 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			token104 := args[0]
			_ = token104
			tmp105 := v_cljg_DOT_security_verify_BANG_.Get()
			tmp106 := lang.NewMap()
			tmp107 := lang.Apply2(tmp105, token104, tmp106)
			return tmp107
		case 2:
			token108 := args[0]
			_ = token108
			opts109 := args[1]
			_ = opts109
			var tmp110 any
			_ = tmp110
			{
				tmp111 := v_cljg_DOT_security_verify.Get()
				tmp112 := lang.Apply2(tmp111, token108, opts109)
				var or__2__auto__113 any = tmp112
				_ = or__2__auto__113
				var tmp114 any
				_ = tmp114
				if lang.IsTruthy(or__2__auto__113) {
					tmp114 = or__2__auto__113
				} else {
					tmp115 := v_clojure_DOT_core_ex_info.Get()
					tmp116 := lang.NewMap(kw_bri_SLASH_error, kw_auth_SLASH_unauthorized)
					tmp117 := lang.Apply2(tmp115, "invalid or expired token", tmp116)
					panic(rt.Throw(tmp117))
				}
				tmp110 = tmp114
			}
			return tmp110
		default:
			panic(lang.NewArityError(len(args), "cljg.security/verify!", "1: [token] or 2: [token opts]"))
		}
	})
	v_cljg_DOT_security_verify_BANG_.BindRoot(tmp103)
	_ = v_cljg_DOT_security_verify_BANG_
	// (def subject (clojure.core/fn ([claims] (:sub claims))))
	v_cljg_DOT_security_subject.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(79), kw_column, int64(7), kw_end_line, int64(79), kw_end_column, int64(14), kw_arglists, lang.NewList(lang.NewVector(sym_claims)), kw_doc, "The token subject (:sub) — the audit actor."))
	tmp118 := lang.FnFunc1(func(claims119 any) any {
		tmp120 := lang.Apply1(kw_sub, claims119)
		return tmp120
	})
	tmp121 := &lang.NamedFn1{Name: "cljg.security/subject", Expects: "1: [claims]", F: tmp118}
	v_cljg_DOT_security_subject.BindRoot(tmp121)
	fnD_cljg_DOT_security_subject = tmp121.F
	v_cljg_DOT_security_subject.SealDirect()
	_ = v_cljg_DOT_security_subject
	// (def issue (clojure.core/fn ([sub] (issue sub {} {})) ([sub claims] (issue sub claims {}))…
	v_cljg_DOT_security_issue.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(84), kw_column, int64(7), kw_end_line, int64(84), kw_end_column, int64(12), kw_arglists, lang.NewList(lang.NewVector(sym_sub), lang.NewVector(sym_sub, sym_claims), lang.NewVector(sym_sub, sym_claims, sym_opts)), kw_doc, "Sign a token for a subject and AUDIT the issuance (login success).\n  (issue \"user-42\" {:role \"admin\"} {:exp-seconds 900})."))
	tmp122 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			sub123 := args[0]
			_ = sub123
			tmp124 := v_cljg_DOT_security_issue.Get()
			tmp125 := lang.NewMap()
			tmp126 := lang.NewMap()
			tmp127 := lang.Apply3(tmp124, sub123, tmp125, tmp126)
			return tmp127
		case 2:
			sub128 := args[0]
			_ = sub128
			claims129 := args[1]
			_ = claims129
			tmp130 := v_cljg_DOT_security_issue.Get()
			tmp131 := lang.NewMap()
			tmp132 := lang.Apply3(tmp130, sub128, claims129, tmp131)
			return tmp132
		case 3:
			sub133 := args[0]
			_ = sub133
			claims134 := args[1]
			_ = claims134
			opts135 := args[2]
			_ = opts135
			var tmp136 any
			_ = tmp136
			{
				tmp137 := v_cljg_DOT_security_sign.Get()
				tmp138 := v_clojure_DOT_core_assoc.Get()
				tmp139 := lang.Apply3(tmp138, claims134, kw_sub, sub133)
				tmp140 := lang.Apply2(tmp137, tmp139, opts135)
				var tok141 any = tmp140
				_ = tok141
				tmp142 := v_bri_DOT_core_DOT_audit_record.Get()
				tmp143 := lang.NewMap(kw_action, kw_auth_SLASH_token_issued, kw_actor, sub133, kw_severity, kw_info)
				tmp144 := lang.Apply1(tmp142, tmp143)
				_ = tmp144
				tmp136 = tok141
			}
			return tmp136
		default:
			panic(lang.NewArityError(len(args), "cljg.security/issue", "1: [sub] or 2: [sub claims] or 3: [sub claims opts]"))
		}
	})
	v_cljg_DOT_security_issue.BindRoot(tmp122)
	_ = v_cljg_DOT_security_issue
	// (def hash-password (clojure.core/fn ([pw] (-argon2-hash pw))))
	v_cljg_DOT_security_hash_password.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(95), kw_column, int64(7), kw_end_line, int64(95), kw_end_column, int64(20), kw_arglists, lang.NewList(lang.NewVector(sym_pw)), kw_doc, "argon2id hash (OWASP params) as a self-describing PHC string.\n  DELIBERATELY slow (~16 ms) — that is the anti-brute-force feature."))
	tmp145 := lang.FnFunc1(func(pw146 any) any {
		tmp147 := v_cljg_DOT_security_X_argon2_hash.Get()
		tmp148 := lang.Apply1(tmp147, pw146)
		return tmp148
	})
	tmp149 := &lang.NamedFn1{Name: "cljg.security/hash-password", Expects: "1: [pw]", F: tmp145}
	v_cljg_DOT_security_hash_password.BindRoot(tmp149)
	fnD_cljg_DOT_security_hash_password = tmp149.F
	v_cljg_DOT_security_hash_password.SealDirect()
	_ = v_cljg_DOT_security_hash_password
	// (def check-password (clojure.core/fn ([pw hash] (cond (not (string? hash)) false (str/star…
	v_cljg_DOT_security_check_password.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(101), kw_column, int64(7), kw_end_line, int64(101), kw_end_column, int64(21), kw_arglists, lang.NewList(lang.NewVector(sym_pw, sym_hash)), kw_doc, "Verify a password against an argon2id ($argon2id$…) or legacy bcrypt\n  ($2a$/$2b$…) hash. Constant-time; false on any mismatch or unknown\n  format."))
	tmp150 := lang.FnFunc2(func(pw151, hash152 any) any {
		tmp153 := v_clojure_DOT_core_not.Get()
		tmp154 := v_clojure_DOT_core_string_QMARK_.Get()
		tmp155 := lang.Apply1(tmp154, hash152)
		tmp156 := lang.Apply1(tmp153, tmp155)
		var tmp157 any
		_ = tmp157
		if lang.IsTruthy(tmp156) {
			tmp157 = false
		} else {
			tmp158 := v_clojure_DOT_string_starts_with_QMARK_.Get()
			tmp159 := lang.Apply2(tmp158, hash152, "$argon2")
			var tmp160 any
			_ = tmp160
			if lang.IsTruthy(tmp159) {
				tmp161 := v_cljg_DOT_security_X_argon2_verify.Get()
				tmp162 := lang.Apply2(tmp161, pw151, hash152)
				tmp160 = tmp162
			} else {
				tmp163 := v_clojure_DOT_string_starts_with_QMARK_.Get()
				tmp164 := lang.Apply2(tmp163, hash152, "$2")
				var tmp165 any
				_ = tmp165
				if lang.IsTruthy(tmp164) {
					tmp166 := v_cljg_DOT_security_X_bcrypt_verify.Get()
					tmp167 := lang.Apply2(tmp166, pw151, hash152)
					tmp165 = tmp167
				} else {
					var tmp168 any
					_ = tmp168
					if lang.IsTruthy(kw_else_) {
						tmp168 = false
					} else {
						tmp168 = nil
					}
					tmp165 = tmp168
				}
				tmp160 = tmp165
			}
			tmp157 = tmp160
		}
		return tmp157
	})
	tmp169 := &lang.NamedFn2{Name: "cljg.security/check-password", Expects: "2: [pw hash]", F: tmp150}
	v_cljg_DOT_security_check_password.BindRoot(tmp169)
	fnD_cljg_DOT_security_check_password = tmp169.F
	v_cljg_DOT_security_check_password.SealDirect()
	_ = v_cljg_DOT_security_check_password
	// (def sha256 (clojure.core/fn ([s] (-sha256 s))))
	v_cljg_DOT_security_sha256.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(113), kw_column, int64(7), kw_end_line, int64(113), kw_end_column, int64(13), kw_arglists, lang.NewList(lang.NewVector(sym_s)), kw_doc, "SHA-256 digest of a string OR a byte-array, as lowercase hex — so a blob\n  read with cljg.io/read-bytes or decoded with `base64-decode-bytes` hashes\n  directly, with no lossy detour through a string."))
	tmp170 := lang.FnFunc1(func(s171 any) any {
		tmp172 := v_cljg_DOT_security_X_sha256.Get()
		tmp173 := lang.Apply1(tmp172, s171)
		return tmp173
	})
	tmp174 := &lang.NamedFn1{Name: "cljg.security/sha256", Expects: "1: [s]", F: tmp170}
	v_cljg_DOT_security_sha256.BindRoot(tmp174)
	fnD_cljg_DOT_security_sha256 = tmp174.F
	v_cljg_DOT_security_sha256.SealDirect()
	_ = v_cljg_DOT_security_sha256
	// (def hmac (clojure.core/fn ([key message] (-hmac-sha256 key message))))
	v_cljg_DOT_security_hmac.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(120), kw_column, int64(7), kw_end_line, int64(120), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector(sym_key, sym_message)), kw_doc, "HMAC-SHA256 of message with key, as lowercase hex. Both may be a string or\n  a byte-array."))
	tmp175 := lang.FnFunc2(func(key176, message177 any) any {
		tmp178 := v_cljg_DOT_security_X_hmac_sha256.Get()
		tmp179 := lang.Apply2(tmp178, key176, message177)
		return tmp179
	})
	tmp180 := &lang.NamedFn2{Name: "cljg.security/hmac", Expects: "2: [key message]", F: tmp175}
	v_cljg_DOT_security_hmac.BindRoot(tmp180)
	fnD_cljg_DOT_security_hmac = tmp180.F
	v_cljg_DOT_security_hmac.SealDirect()
	_ = v_cljg_DOT_security_hmac
	// (def random (clojure.core/fn ([n] (-secure-random n))))
	v_cljg_DOT_security_random.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(126), kw_column, int64(7), kw_end_line, int64(126), kw_end_column, int64(13), kw_arglists, lang.NewList(lang.NewVector(sym_n)), kw_doc, "n cryptographically secure random bytes (crypto/rand), as lowercase\n  hex (a 2n-char string)."))
	tmp181 := lang.FnFunc1(func(n182 any) any {
		tmp183 := v_cljg_DOT_security_X_secure_random.Get()
		tmp184 := lang.Apply1(tmp183, n182)
		return tmp184
	})
	tmp185 := &lang.NamedFn1{Name: "cljg.security/random", Expects: "1: [n]", F: tmp181}
	v_cljg_DOT_security_random.BindRoot(tmp185)
	fnD_cljg_DOT_security_random = tmp185.F
	v_cljg_DOT_security_random.SealDirect()
	_ = v_cljg_DOT_security_random
	// (def token (clojure.core/fn ([] (-rand-token))))
	v_cljg_DOT_security_token.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(132), kw_column, int64(7), kw_end_line, int64(132), kw_end_column, int64(12), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "A 256-bit URL-safe random token (crypto/rand, base64url) — session\n  ids, API keys, CSRF tokens."))
	tmp186 := lang.FnFunc0(func() any {
		tmp187 := v_cljg_DOT_security_X_rand_token.Get()
		tmp188 := lang.Apply0(tmp187)
		return tmp188
	})
	tmp189 := &lang.NamedFn0{Name: "cljg.security/token", Expects: "0: []", F: tmp186}
	v_cljg_DOT_security_token.BindRoot(tmp189)
	fnD_cljg_DOT_security_token = tmp189.F
	v_cljg_DOT_security_token.SealDirect()
	_ = v_cljg_DOT_security_token
	// (def uuid (clojure.core/fn ([] (-uuid))))
	v_cljg_DOT_security_uuid.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(138), kw_column, int64(7), kw_end_line, int64(138), kw_end_column, int64(11), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "A random (v4) UUID string from crypto/rand."))
	tmp190 := lang.FnFunc0(func() any {
		tmp191 := v_cljg_DOT_security_X_uuid.Get()
		tmp192 := lang.Apply0(tmp191)
		return tmp192
	})
	tmp193 := &lang.NamedFn0{Name: "cljg.security/uuid", Expects: "0: []", F: tmp190}
	v_cljg_DOT_security_uuid.BindRoot(tmp193)
	fnD_cljg_DOT_security_uuid = tmp193.F
	v_cljg_DOT_security_uuid.SealDirect()
	_ = v_cljg_DOT_security_uuid
	// (def base64 (clojure.core/fn ([data] (-b64-encode data))))
	v_cljg_DOT_security_base64.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(143), kw_column, int64(7), kw_end_line, int64(143), kw_end_column, int64(13), kw_arglists, lang.NewList(lang.NewVector(sym_data)), kw_doc, "Standard base64 of a string or byte-array. `base64-encode` is the same fn\n  under the name the rest of the base64 family uses."))
	tmp194 := lang.FnFunc1(func(data195 any) any {
		tmp196 := v_cljg_DOT_security_X_b64_encode.Get()
		tmp197 := lang.Apply1(tmp196, data195)
		return tmp197
	})
	tmp198 := &lang.NamedFn1{Name: "cljg.security/base64", Expects: "1: [data]", F: tmp194}
	v_cljg_DOT_security_base64.BindRoot(tmp198)
	fnD_cljg_DOT_security_base64 = tmp198.F
	v_cljg_DOT_security_base64.SealDirect()
	_ = v_cljg_DOT_security_base64
	// (def base64-encode (clojure.core/fn ([data] (-b64-encode data))))
	v_cljg_DOT_security_base64_encode.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(149), kw_column, int64(7), kw_end_line, int64(149), kw_end_column, int64(20), kw_arglists, lang.NewList(lang.NewVector(sym_data)), kw_doc, "Standard (RFC 4648, padded) base64 of `data` — a string, whose UTF-8 bytes\n  are encoded, or a byte-array (e.g. from cljg.io/read-bytes or\n  cljg.compress/gzip). Matches java.util.Base64/getEncoder: (base64-encode\n  \"hello\") => \"aGVsbG8=\", (base64-encode \"\") => \"\" (oracle 1.12.5)."))
	tmp199 := lang.FnFunc1(func(data200 any) any {
		tmp201 := v_cljg_DOT_security_X_b64_encode.Get()
		tmp202 := lang.Apply1(tmp201, data200)
		return tmp202
	})
	tmp203 := &lang.NamedFn1{Name: "cljg.security/base64-encode", Expects: "1: [data]", F: tmp199}
	v_cljg_DOT_security_base64_encode.BindRoot(tmp203)
	fnD_cljg_DOT_security_base64_encode = tmp203.F
	v_cljg_DOT_security_base64_encode.SealDirect()
	_ = v_cljg_DOT_security_base64_encode
	// (def base64-decode (clojure.core/fn ([s] (-b64-decode s))))
	v_cljg_DOT_security_base64_decode.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(157), kw_column, int64(7), kw_end_line, int64(157), kw_end_column, int64(20), kw_arglists, lang.NewList(lang.NewVector(sym_s)), kw_doc, "Decode standard base64 back to a STRING, or nil on invalid input. Lossy for\n  a payload that is not valid UTF-8 — use `base64-decode-bytes` for binary."))
	tmp204 := lang.FnFunc1(func(s205 any) any {
		tmp206 := v_cljg_DOT_security_X_b64_decode.Get()
		tmp207 := lang.Apply1(tmp206, s205)
		return tmp207
	})
	tmp208 := &lang.NamedFn1{Name: "cljg.security/base64-decode", Expects: "1: [s]", F: tmp204}
	v_cljg_DOT_security_base64_decode.BindRoot(tmp208)
	fnD_cljg_DOT_security_base64_decode = tmp208.F
	v_cljg_DOT_security_base64_decode.SealDirect()
	_ = v_cljg_DOT_security_base64_decode
	// (def base64-decode-bytes (clojure.core/fn ([s] (-b64-decode-bytes s))))
	v_cljg_DOT_security_base64_decode_bytes.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(163), kw_column, int64(7), kw_end_line, int64(163), kw_end_column, int64(26), kw_arglists, lang.NewList(lang.NewVector(sym_s)), kw_doc, "Decode standard base64 to a BYTE-ARRAY, or nil on invalid input. This is the\n  half a string cannot carry: an image, a gzip blob, any non-UTF-8 payload.\n  Pairs with cljg.io/write-bytes. Elements are SIGNED like the JVM's byte[]:\n  (vec (base64-decode-bytes \"AAECgA==\")) => [0 1 2 -128] (oracle 1.12.5,\n  java.util.Base64/getDecoder)."))
	tmp209 := lang.FnFunc1(func(s210 any) any {
		tmp211 := v_cljg_DOT_security_X_b64_decode_bytes.Get()
		tmp212 := lang.Apply1(tmp211, s210)
		return tmp212
	})
	tmp213 := &lang.NamedFn1{Name: "cljg.security/base64-decode-bytes", Expects: "1: [s]", F: tmp209}
	v_cljg_DOT_security_base64_decode_bytes.BindRoot(tmp213)
	fnD_cljg_DOT_security_base64_decode_bytes = tmp213.F
	v_cljg_DOT_security_base64_decode_bytes.SealDirect()
	_ = v_cljg_DOT_security_base64_decode_bytes
	// (def hex (clojure.core/fn ([s] (-hex-encode s))))
	v_cljg_DOT_security_hex.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(172), kw_column, int64(7), kw_end_line, int64(172), kw_end_column, int64(10), kw_arglists, lang.NewList(lang.NewVector(sym_s)), kw_doc, "Lowercase hex of a string's bytes, or of a byte-array."))
	tmp214 := lang.FnFunc1(func(s215 any) any {
		tmp216 := v_cljg_DOT_security_X_hex_encode.Get()
		tmp217 := lang.Apply1(tmp216, s215)
		return tmp217
	})
	tmp218 := &lang.NamedFn1{Name: "cljg.security/hex", Expects: "1: [s]", F: tmp214}
	v_cljg_DOT_security_hex.BindRoot(tmp218)
	fnD_cljg_DOT_security_hex = tmp218.F
	v_cljg_DOT_security_hex.SealDirect()
	_ = v_cljg_DOT_security_hex
	// (def hex-decode (clojure.core/fn ([s] (-hex-decode s))))
	v_cljg_DOT_security_hex_decode.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(177), kw_column, int64(7), kw_end_line, int64(177), kw_end_column, int64(17), kw_arglists, lang.NewList(lang.NewVector(sym_s)), kw_doc, "Decode hex back to the string, or nil on invalid input."))
	tmp219 := lang.FnFunc1(func(s220 any) any {
		tmp221 := v_cljg_DOT_security_X_hex_decode.Get()
		tmp222 := lang.Apply1(tmp221, s220)
		return tmp222
	})
	tmp223 := &lang.NamedFn1{Name: "cljg.security/hex-decode", Expects: "1: [s]", F: tmp219}
	v_cljg_DOT_security_hex_decode.BindRoot(tmp223)
	fnD_cljg_DOT_security_hex_decode = tmp223.F
	v_cljg_DOT_security_hex_decode.SealDirect()
	_ = v_cljg_DOT_security_hex_decode
	// (def backend-name (clojure.core/fn ([opts] (name (or (:backend opts) :auto)))))
	v_cljg_DOT_security_backend_name.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(188), kw_column, int64(7), kw_end_line, int64(188), kw_end_column, int64(29), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_opts))))
	tmp224 := lang.FnFunc1(func(opts225 any) any {
		tmp226 := v_clojure_DOT_core_name.Get()
		var tmp227 any
		_ = tmp227
		{
			tmp228 := lang.Apply1(kw_backend, opts225)
			var or__2__auto__229 any = tmp228
			_ = or__2__auto__229
			var tmp230 any
			_ = tmp230
			if lang.IsTruthy(or__2__auto__229) {
				tmp230 = or__2__auto__229
			} else {
				tmp230 = kw_auto
			}
			tmp227 = tmp230
		}
		tmp231 := lang.Apply1(tmp226, tmp227)
		return tmp231
	})
	tmp232 := &lang.NamedFn1{Name: "cljg.security/backend-name", Expects: "1: [opts]", F: tmp224}
	v_cljg_DOT_security_backend_name.BindRoot(tmp232)
	fnD_cljg_DOT_security_backend_name = tmp232.F
	v_cljg_DOT_security_backend_name.SealDirect()
	_ = v_cljg_DOT_security_backend_name
	// (def save-to-keychain (clojure.core/fn ([service account value] (save-to-keychain service …
	v_cljg_DOT_security_save_to_keychain.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(191), kw_column, int64(7), kw_end_line, int64(191), kw_end_column, int64(23), kw_arglists, lang.NewList(lang.NewVector(sym_service, sym_account, sym_value), lang.NewVector(sym_service, sym_account, sym_value, sym_opts)), kw_doc, "Store secret value under (service, account). Returns the backend\n  keyword that stored it (:native or :file). The value is never printed\n  or logged."))
	tmp233 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 3:
			service234 := args[0]
			_ = service234
			account235 := args[1]
			_ = account235
			value236 := args[2]
			_ = value236
			tmp237 := v_cljg_DOT_security_save_to_keychain.Get()
			tmp238 := lang.NewMap()
			tmp239 := lang.Apply4(tmp237, service234, account235, value236, tmp238)
			return tmp239
		case 4:
			service240 := args[0]
			_ = service240
			account241 := args[1]
			_ = account241
			value242 := args[2]
			_ = value242
			opts243 := args[3]
			_ = opts243
			tmp244 := v_clojure_DOT_core_keyword.Get()
			tmp245 := v_cljg_DOT_security_X_keychain_set.Get()
			tmp246 := v_clojure_DOT_core_str.Get()
			tmp247 := lang.Apply1(tmp246, service240)
			tmp248 := v_clojure_DOT_core_str.Get()
			tmp249 := lang.Apply1(tmp248, account241)
			tmp250 := v_clojure_DOT_core_str.Get()
			tmp251 := lang.Apply1(tmp250, value242)
			tmp252 := v_cljg_DOT_security_backend_name.Direct()
			var tmp253 any
			if !tmp252 {
				tmp253 = v_cljg_DOT_security_backend_name.Get()
			}
			var tmp254 any
			if tmp252 {
				tmp254 = fnD_cljg_DOT_security_backend_name(opts243)
			} else {
				tmp254 = lang.Apply1(tmp253, opts243)
			}
			tmp255 := lang.Apply4(tmp245, tmp247, tmp249, tmp251, tmp254)
			tmp256 := lang.Apply1(tmp244, tmp255)
			return tmp256
		default:
			panic(lang.NewArityError(len(args), "cljg.security/save-to-keychain", "3: [service account value] or 4: [service account value opts]"))
		}
	})
	v_cljg_DOT_security_save_to_keychain.BindRoot(tmp233)
	_ = v_cljg_DOT_security_save_to_keychain
	// (def get-from-keychain (clojure.core/fn ([service account] (get-from-keychain service acco…
	v_cljg_DOT_security_get_from_keychain.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(199), kw_column, int64(7), kw_end_line, int64(199), kw_end_column, int64(24), kw_arglists, lang.NewList(lang.NewVector(sym_service, sym_account), lang.NewVector(sym_service, sym_account, sym_opts)), kw_doc, "The secret for (service, account), or nil when absent."))
	tmp257 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 2:
			service258 := args[0]
			_ = service258
			account259 := args[1]
			_ = account259
			tmp260 := v_cljg_DOT_security_get_from_keychain.Get()
			tmp261 := lang.NewMap()
			tmp262 := lang.Apply3(tmp260, service258, account259, tmp261)
			return tmp262
		case 3:
			service263 := args[0]
			_ = service263
			account264 := args[1]
			_ = account264
			opts265 := args[2]
			_ = opts265
			tmp266 := v_cljg_DOT_security_X_keychain_get.Get()
			tmp267 := v_clojure_DOT_core_str.Get()
			tmp268 := lang.Apply1(tmp267, service263)
			tmp269 := v_clojure_DOT_core_str.Get()
			tmp270 := lang.Apply1(tmp269, account264)
			tmp271 := v_cljg_DOT_security_backend_name.Direct()
			var tmp272 any
			if !tmp271 {
				tmp272 = v_cljg_DOT_security_backend_name.Get()
			}
			var tmp273 any
			if tmp271 {
				tmp273 = fnD_cljg_DOT_security_backend_name(opts265)
			} else {
				tmp273 = lang.Apply1(tmp272, opts265)
			}
			tmp274 := lang.Apply3(tmp266, tmp268, tmp270, tmp273)
			return tmp274
		default:
			panic(lang.NewArityError(len(args), "cljg.security/get-from-keychain", "2: [service account] or 3: [service account opts]"))
		}
	})
	v_cljg_DOT_security_get_from_keychain.BindRoot(tmp257)
	_ = v_cljg_DOT_security_get_from_keychain
	// (def delete-from-keychain (clojure.core/fn ([service account] (delete-from-keychain servic…
	v_cljg_DOT_security_delete_from_keychain.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(205), kw_column, int64(7), kw_end_line, int64(205), kw_end_column, int64(27), kw_arglists, lang.NewList(lang.NewVector(sym_service, sym_account), lang.NewVector(sym_service, sym_account, sym_opts)), kw_doc, "Delete (service, account); absent is a no-op. Returns the backend\n  keyword that handled it (:native or :file)."))
	tmp275 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 2:
			service276 := args[0]
			_ = service276
			account277 := args[1]
			_ = account277
			tmp278 := v_cljg_DOT_security_delete_from_keychain.Get()
			tmp279 := lang.NewMap()
			tmp280 := lang.Apply3(tmp278, service276, account277, tmp279)
			return tmp280
		case 3:
			service281 := args[0]
			_ = service281
			account282 := args[1]
			_ = account282
			opts283 := args[2]
			_ = opts283
			tmp284 := v_clojure_DOT_core_keyword.Get()
			tmp285 := v_cljg_DOT_security_X_keychain_del.Get()
			tmp286 := v_clojure_DOT_core_str.Get()
			tmp287 := lang.Apply1(tmp286, service281)
			tmp288 := v_clojure_DOT_core_str.Get()
			tmp289 := lang.Apply1(tmp288, account282)
			tmp290 := v_cljg_DOT_security_backend_name.Direct()
			var tmp291 any
			if !tmp290 {
				tmp291 = v_cljg_DOT_security_backend_name.Get()
			}
			var tmp292 any
			if tmp290 {
				tmp292 = fnD_cljg_DOT_security_backend_name(opts283)
			} else {
				tmp292 = lang.Apply1(tmp291, opts283)
			}
			tmp293 := lang.Apply3(tmp285, tmp287, tmp289, tmp292)
			tmp294 := lang.Apply1(tmp284, tmp293)
			return tmp294
		default:
			panic(lang.NewArityError(len(args), "cljg.security/delete-from-keychain", "2: [service account] or 3: [service account opts]"))
		}
	})
	v_cljg_DOT_security_delete_from_keychain.BindRoot(tmp275)
	_ = v_cljg_DOT_security_delete_from_keychain
	// (def bearer (clojure.core/fn ([req] (let [h (get (:headers req) "authorization")] (when (a…
	v_cljg_DOT_security_bearer.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(213), kw_column, int64(7), kw_end_line, int64(213), kw_end_column, int64(23), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_req))))
	tmp295 := lang.FnFunc1(func(req296 any) any {
		var tmp297 any
		_ = tmp297
		{
			tmp298 := v_clojure_DOT_core_get.Get()
			tmp299 := lang.Apply1(kw_headers, req296)
			tmp300 := lang.Apply2(tmp298, tmp299, "authorization")
			var h301 any = tmp300
			_ = h301
			var tmp302 any
			_ = tmp302
			{
				tmp303 := v_clojure_DOT_core_string_QMARK_.Get()
				tmp304 := lang.Apply1(tmp303, h301)
				var and__1__auto__305 any = tmp304
				_ = and__1__auto__305
				var tmp306 any
				_ = tmp306
				if lang.IsTruthy(and__1__auto__305) {
					tmp307 := v_clojure_DOT_string_starts_with_QMARK_.Get()
					tmp308 := lang.Apply2(tmp307, h301, "Bearer ")
					tmp306 = tmp308
				} else {
					tmp306 = and__1__auto__305
				}
				tmp302 = tmp306
			}
			var tmp309 any
			_ = tmp309
			if lang.IsTruthy(tmp302) {
				tmp310 := v_clojure_DOT_core_subs.Get()
				tmp311 := lang.Apply2(tmp310, h301, int64(7))
				tmp309 = tmp311
			} else {
				tmp309 = nil
			}
			tmp297 = tmp309
		}
		return tmp297
	})
	tmp312 := &lang.NamedFn1{Name: "cljg.security/bearer", Expects: "1: [req]", F: tmp295}
	v_cljg_DOT_security_bearer.BindRoot(tmp312)
	fnD_cljg_DOT_security_bearer = tmp312.F
	v_cljg_DOT_security_bearer.SealDirect()
	_ = v_cljg_DOT_security_bearer
	// (def authenticate (clojure.core/fn ([req] (or (:auth/claims req) (some-> (bearer req) veri…
	v_cljg_DOT_security_authenticate.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(218), kw_column, int64(7), kw_end_line, int64(218), kw_end_column, int64(29), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_req)), kw_doc, "Claims from the request: an already-populated :auth/claims, else the\n  Bearer token verified."))
	tmp313 := lang.FnFunc1(func(req314 any) any {
		var tmp315 any
		_ = tmp315
		{
			tmp316 := lang.Apply1(kw_auth_SLASH_claims, req314)
			var or__2__auto__317 any = tmp316
			_ = or__2__auto__317
			var tmp318 any
			_ = tmp318
			if lang.IsTruthy(or__2__auto__317) {
				tmp318 = or__2__auto__317
			} else {
				var tmp319 any
				_ = tmp319
				{
					tmp320 := v_cljg_DOT_security_bearer.Direct()
					var tmp321 any
					if !tmp320 {
						tmp321 = v_cljg_DOT_security_bearer.Get()
					}
					var tmp322 any
					if tmp320 {
						tmp322 = fnD_cljg_DOT_security_bearer(req314)
					} else {
						tmp322 = lang.Apply1(tmp321, req314)
					}
					var some__116323 any = tmp322
					_ = some__116323
					var tmp324 any
					_ = tmp324
					{
						tmp325 := v_clojure_DOT_core_nil_QMARK_.Get()
						tmp326 := lang.Apply1(tmp325, some__116323)
						var tmp327 any
						_ = tmp327
						if lang.IsTruthy(tmp326) {
							tmp327 = nil
						} else {
							tmp328 := v_cljg_DOT_security_verify.Get()
							tmp329 := lang.Apply1(tmp328, some__116323)
							tmp327 = tmp329
						}
						var some__117330 any = tmp327
						_ = some__117330
						tmp324 = some__117330
					}
					tmp319 = tmp324
				}
				tmp318 = tmp319
			}
			tmp315 = tmp318
		}
		return tmp315
	})
	tmp331 := &lang.NamedFn1{Name: "cljg.security/authenticate", Expects: "1: [req]", F: tmp313}
	v_cljg_DOT_security_authenticate.BindRoot(tmp331)
	fnD_cljg_DOT_security_authenticate = tmp331.F
	v_cljg_DOT_security_authenticate.SealDirect()
	_ = v_cljg_DOT_security_authenticate
	// (def deny-401 (clojure.core/fn ([req] (audit/record {:action :auth/denied, :severity :warn…
	v_cljg_DOT_security_deny_401.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(224), kw_column, int64(7), kw_end_line, int64(224), kw_end_column, int64(25), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_req))))
	tmp332 := lang.FnFunc1(func(req333 any) any {
		tmp334 := v_bri_DOT_core_DOT_audit_record.Get()
		tmp335 := lang.Apply1(kw_uri, req333)
		tmp336 := lang.Apply1(kw_request_SLASH_id, req333)
		tmp337 := lang.NewMap(kw_action, kw_auth_SLASH_denied, kw_severity, kw_warning, kw_reason, kw_unauthenticated, kw_target, tmp335, kw_request_SLASH_id, tmp336)
		tmp338 := lang.Apply1(tmp334, tmp337)
		_ = tmp338
		tmp339 := lang.NewMap(kw_error_, "unauthorized")
		tmp340 := lang.NewMap(kw_status, int64(401), kw_body, tmp339)
		return tmp340
	})
	tmp341 := &lang.NamedFn1{Name: "cljg.security/deny-401", Expects: "1: [req]", F: tmp332}
	v_cljg_DOT_security_deny_401.BindRoot(tmp341)
	fnD_cljg_DOT_security_deny_401 = tmp341.F
	v_cljg_DOT_security_deny_401.SealDirect()
	_ = v_cljg_DOT_security_deny_401
	// (def deny-403 (clojure.core/fn ([req claims] (audit/record {:action :auth/forbidden, :seve…
	v_cljg_DOT_security_deny_403.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(229), kw_column, int64(7), kw_end_line, int64(229), kw_end_column, int64(25), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_req, sym_claims))))
	tmp342 := lang.FnFunc2(func(req343, claims344 any) any {
		tmp345 := v_bri_DOT_core_DOT_audit_record.Get()
		tmp346 := v_cljg_DOT_security_subject.Direct()
		var tmp347 any
		if !tmp346 {
			tmp347 = v_cljg_DOT_security_subject.Get()
		}
		var tmp348 any
		if tmp346 {
			tmp348 = fnD_cljg_DOT_security_subject(claims344)
		} else {
			tmp348 = lang.Apply1(tmp347, claims344)
		}
		tmp349 := lang.Apply1(kw_uri, req343)
		tmp350 := lang.Apply1(kw_request_SLASH_id, req343)
		tmp351 := lang.NewMap(kw_action, kw_auth_SLASH_forbidden, kw_severity, kw_warning, kw_reason, kw_not_authorized, kw_actor, tmp348, kw_target, tmp349, kw_request_SLASH_id, tmp350)
		tmp352 := lang.Apply1(tmp345, tmp351)
		_ = tmp352
		tmp353 := lang.NewMap(kw_error_, "forbidden")
		tmp354 := lang.NewMap(kw_status, int64(403), kw_body, tmp353)
		return tmp354
	})
	tmp355 := &lang.NamedFn2{Name: "cljg.security/deny-403", Expects: "2: [req claims]", F: tmp342}
	v_cljg_DOT_security_deny_403.BindRoot(tmp355)
	fnD_cljg_DOT_security_deny_403 = tmp355.F
	v_cljg_DOT_security_deny_403.SealDirect()
	_ = v_cljg_DOT_security_deny_403
	// (def wrap-guard (clojure.core/fn ([req-pred handler] (fn [req] (let [claims (authenticate …
	v_cljg_DOT_security_wrap_guard.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(234), kw_column, int64(7), kw_end_line, int64(234), kw_end_column, int64(27), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_req_pred, sym_handler))))
	tmp356 := lang.FnFunc2(func(req_pred357, handler358 any) any {
		tmp359 := lang.FnFunc1(func(req360 any) any {
			var tmp361 any
			_ = tmp361
			{
				tmp362 := v_cljg_DOT_security_authenticate.Direct()
				var tmp363 any
				if !tmp362 {
					tmp363 = v_cljg_DOT_security_authenticate.Get()
				}
				var tmp364 any
				if tmp362 {
					tmp364 = fnD_cljg_DOT_security_authenticate(req360)
				} else {
					tmp364 = lang.Apply1(tmp363, req360)
				}
				var claims365 any = tmp364
				_ = claims365
				tmp366 := v_clojure_DOT_core_nil_QMARK_.Get()
				tmp367 := lang.Apply1(tmp366, claims365)
				var tmp368 any
				_ = tmp368
				if lang.IsTruthy(tmp367) {
					tmp369 := v_cljg_DOT_security_deny_401.Direct()
					var tmp370 any
					if !tmp369 {
						tmp370 = v_cljg_DOT_security_deny_401.Get()
					}
					var tmp371 any
					if tmp369 {
						tmp371 = fnD_cljg_DOT_security_deny_401(req360)
					} else {
						tmp371 = lang.Apply1(tmp370, req360)
					}
					tmp368 = tmp371
				} else {
					var tmp372 any
					_ = tmp372
					{
						tmp373 := v_clojure_DOT_core_assoc.Get()
						tmp374 := lang.Apply3(tmp373, req360, kw_auth_SLASH_claims, claims365)
						var req_SINGLEQUOTE_375 any = tmp374
						_ = req_SINGLEQUOTE_375
						tmp376 := v_bri_DOT_web_DOT_http_mark_subject_BANG_.Get()
						tmp377 := v_cljg_DOT_security_subject.Direct()
						var tmp378 any
						if !tmp377 {
							tmp378 = v_cljg_DOT_security_subject.Get()
						}
						var tmp379 any
						if tmp377 {
							tmp379 = fnD_cljg_DOT_security_subject(claims365)
						} else {
							tmp379 = lang.Apply1(tmp378, claims365)
						}
						tmp380 := lang.Apply2(tmp376, req_SINGLEQUOTE_375, tmp379)
						_ = tmp380
						var tmp381 any
						_ = tmp381
						func() {
							defer func() {
								if r := recover(); r != nil {
									thrown := rt.Recover(r)
									if rt.CatchMatches("Throwable", thrown) {
										var X_382 any = thrown
										_ = X_382
										tmp381 = false
										return
									}
									panic(r)
								}
							}()
							tmp383 := v_clojure_DOT_core_boolean.Get()
							tmp384 := lang.Apply1(req_pred357, req_SINGLEQUOTE_375)
							tmp385 := lang.Apply1(tmp383, tmp384)
							tmp381 = tmp385
						}()
						var tmp386 any
						_ = tmp386
						if lang.IsTruthy(tmp381) {
							tmp387 := lang.Apply1(handler358, req_SINGLEQUOTE_375)
							tmp386 = tmp387
						} else {
							tmp388 := v_cljg_DOT_security_deny_403.Direct()
							var tmp389 any
							if !tmp388 {
								tmp389 = v_cljg_DOT_security_deny_403.Get()
							}
							var tmp390 any
							if tmp388 {
								tmp390 = fnD_cljg_DOT_security_deny_403(req_SINGLEQUOTE_375, claims365)
							} else {
								tmp390 = lang.Apply2(tmp389, req_SINGLEQUOTE_375, claims365)
							}
							tmp386 = tmp390
						}
						tmp372 = tmp386
					}
					tmp368 = tmp372
				}
				tmp361 = tmp368
			}
			return tmp361
		})
		tmp391 := &lang.NamedFn1{Name: "fn", Expects: "1: [req]", F: tmp359}
		return tmp391
	})
	tmp392 := &lang.NamedFn2{Name: "cljg.security/wrap-guard", Expects: "2: [req-pred handler]", F: tmp356}
	v_cljg_DOT_security_wrap_guard.BindRoot(tmp392)
	fnD_cljg_DOT_security_wrap_guard = tmp392.F
	v_cljg_DOT_security_wrap_guard.SealDirect()
	_ = v_cljg_DOT_security_wrap_guard
	// (def guard (clojure.core/fn ([req-pred] {:name :guard, :wrap (fn [h] (wrap-guard req-pred …
	v_cljg_DOT_security_guard.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(245), kw_column, int64(7), kw_end_line, int64(245), kw_end_column, int64(12), kw_arglists, lang.NewList(lang.NewVector(sym_req_pred), lang.NewVector(sym_req_pred, sym_handler)), kw_doc, "The GENERAL authorization guard and the framework's authz seam:\n  (guard req-pred) → middleware; (guard req-pred handler) → wrapped\n  handler. req-pred is (req -> boolean) with :auth/claims populated. No/\n  invalid token → 401; authenticated but pred false → 403 (RFC 6750).\n  logged-in-only / role-only / user-only / admin-only are all thin\n  specializations of this. Tenant check in one line:\n  (guard #(= (get-in % [:auth/claims :org]) (get-in % [:path-params :org])))."))
	tmp393 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			req_pred394 := args[0]
			_ = req_pred394
			tmp395 := lang.FnFunc1(func(h396 any) any {
				tmp397 := v_cljg_DOT_security_wrap_guard.Direct()
				var tmp398 any
				if !tmp397 {
					tmp398 = v_cljg_DOT_security_wrap_guard.Get()
				}
				var tmp399 any
				if tmp397 {
					tmp399 = fnD_cljg_DOT_security_wrap_guard(req_pred394, h396)
				} else {
					tmp399 = lang.Apply2(tmp398, req_pred394, h396)
				}
				return tmp399
			})
			tmp400 := &lang.NamedFn1{Name: "fn", Expects: "1: [h]", F: tmp395}
			tmp401 := lang.NewMap(kw_name, kw_guard, kw_wrap, tmp400)
			return tmp401
		case 2:
			req_pred402 := args[0]
			_ = req_pred402
			handler403 := args[1]
			_ = handler403
			tmp404 := v_cljg_DOT_security_wrap_guard.Direct()
			var tmp405 any
			if !tmp404 {
				tmp405 = v_cljg_DOT_security_wrap_guard.Get()
			}
			var tmp406 any
			if tmp404 {
				tmp406 = fnD_cljg_DOT_security_wrap_guard(req_pred402, handler403)
			} else {
				tmp406 = lang.Apply2(tmp405, req_pred402, handler403)
			}
			return tmp406
		default:
			panic(lang.NewArityError(len(args), "cljg.security/guard", "1: [req-pred] or 2: [req-pred handler]"))
		}
	})
	v_cljg_DOT_security_guard.BindRoot(tmp393)
	_ = v_cljg_DOT_security_guard
	// (def guard-claims (clojure.core/fn ([claims-pred] (guard (fn [req] (claims-pred (:auth/cla…
	v_cljg_DOT_security_guard_claims.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(256), kw_column, int64(7), kw_end_line, int64(256), kw_end_column, int64(19), kw_arglists, lang.NewList(lang.NewVector(sym_claims_pred), lang.NewVector(sym_claims_pred, sym_handler)), kw_doc, "guard whose predicate sees the CLAIMS map directly (the common case)."))
	tmp407 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			claims_pred408 := args[0]
			_ = claims_pred408
			tmp409 := v_cljg_DOT_security_guard.Get()
			tmp410 := lang.FnFunc1(func(req411 any) any {
				tmp412 := lang.Apply1(kw_auth_SLASH_claims, req411)
				tmp413 := lang.Apply1(claims_pred408, tmp412)
				return tmp413
			})
			tmp414 := &lang.NamedFn1{Name: "fn", Expects: "1: [req]", F: tmp410}
			tmp415 := lang.Apply1(tmp409, tmp414)
			return tmp415
		case 2:
			claims_pred416 := args[0]
			_ = claims_pred416
			handler417 := args[1]
			_ = handler417
			tmp418 := v_cljg_DOT_security_guard.Get()
			tmp419 := lang.FnFunc1(func(req420 any) any {
				tmp421 := lang.Apply1(kw_auth_SLASH_claims, req420)
				tmp422 := lang.Apply1(claims_pred416, tmp421)
				return tmp422
			})
			tmp423 := &lang.NamedFn1{Name: "fn", Expects: "1: [req]", F: tmp419}
			tmp424 := lang.Apply2(tmp418, tmp423, handler417)
			return tmp424
		default:
			panic(lang.NewArityError(len(args), "cljg.security/guard-claims", "1: [claims-pred] or 2: [claims-pred handler]"))
		}
	})
	v_cljg_DOT_security_guard_claims.BindRoot(tmp407)
	_ = v_cljg_DOT_security_guard_claims
	// (def logged-in-only (clojure.core/fn ([] (guard (fn [_] true))) ([handler] (guard (fn [_] …
	v_cljg_DOT_security_logged_in_only.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(261), kw_column, int64(7), kw_end_line, int64(261), kw_end_column, int64(21), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_handler)), kw_doc, "Require a valid token (any claims). 401 otherwise."))
	tmp425 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 0:
			tmp426 := v_cljg_DOT_security_guard.Get()
			tmp427 := lang.FnFunc1(func(X_428 any) any {
				return true
			})
			tmp429 := &lang.NamedFn1{Name: "fn", Expects: "1: [_]", F: tmp427}
			tmp430 := lang.Apply1(tmp426, tmp429)
			return tmp430
		case 1:
			handler431 := args[0]
			_ = handler431
			tmp432 := v_cljg_DOT_security_guard.Get()
			tmp433 := lang.FnFunc1(func(X_434 any) any {
				return true
			})
			tmp435 := &lang.NamedFn1{Name: "fn", Expects: "1: [_]", F: tmp433}
			tmp436 := lang.Apply2(tmp432, tmp435, handler431)
			return tmp436
		default:
			panic(lang.NewArityError(len(args), "cljg.security/logged-in-only", "0: [] or 1: [handler]"))
		}
	})
	v_cljg_DOT_security_logged_in_only.BindRoot(tmp425)
	_ = v_cljg_DOT_security_logged_in_only
	// (def role-only (clojure.core/fn ([role] (guard-claims (fn [c] (= (name role) (str (:role c…
	v_cljg_DOT_security_role_only.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(266), kw_column, int64(7), kw_end_line, int64(266), kw_end_column, int64(16), kw_arglists, lang.NewList(lang.NewVector(sym_role), lang.NewVector(sym_role, sym_handler)), kw_doc, "Require the token's :role to equal role. 401 (no token) or 403 (wrong\n  role)."))
	tmp437 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 1:
			role438 := args[0]
			_ = role438
			tmp439 := v_cljg_DOT_security_guard_claims.Get()
			tmp440 := lang.FnFunc1(func(c441 any) any {
				tmp442 := v_clojure_DOT_core_name.Get()
				tmp443 := lang.Apply1(tmp442, role438)
				tmp444 := v_clojure_DOT_core_str.Get()
				tmp445 := lang.Apply1(kw_role, c441)
				tmp446 := lang.Apply1(tmp444, tmp445)
				tmp447 := rt.EQ2(v_clojure_DOT_core_X_EQ_, tmp443, tmp446)
				return tmp447
			})
			tmp448 := &lang.NamedFn1{Name: "fn", Expects: "1: [c]", F: tmp440}
			tmp449 := lang.Apply1(tmp439, tmp448)
			return tmp449
		case 2:
			role450 := args[0]
			_ = role450
			handler451 := args[1]
			_ = handler451
			tmp452 := v_cljg_DOT_security_guard_claims.Get()
			tmp453 := lang.FnFunc1(func(c454 any) any {
				tmp455 := v_clojure_DOT_core_name.Get()
				tmp456 := lang.Apply1(tmp455, role450)
				tmp457 := v_clojure_DOT_core_str.Get()
				tmp458 := lang.Apply1(kw_role, c454)
				tmp459 := lang.Apply1(tmp457, tmp458)
				tmp460 := rt.EQ2(v_clojure_DOT_core_X_EQ_, tmp456, tmp459)
				return tmp460
			})
			tmp461 := &lang.NamedFn1{Name: "fn", Expects: "1: [c]", F: tmp453}
			tmp462 := lang.Apply2(tmp452, tmp461, handler451)
			return tmp462
		default:
			panic(lang.NewArityError(len(args), "cljg.security/role-only", "1: [role] or 2: [role handler]"))
		}
	})
	v_cljg_DOT_security_role_only.BindRoot(tmp437)
	_ = v_cljg_DOT_security_role_only
	// (def user-only (clojure.core/fn ([] (role-only "user")) ([handler] (role-only "user" handl…
	v_cljg_DOT_security_user_only.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(272), kw_column, int64(7), kw_end_line, int64(272), kw_end_column, int64(16), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_handler)), kw_doc, "Sugar: (role-only :user)."))
	tmp463 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 0:
			tmp464 := v_cljg_DOT_security_role_only.Get()
			tmp465 := lang.Apply1(tmp464, "user")
			return tmp465
		case 1:
			handler466 := args[0]
			_ = handler466
			tmp467 := v_cljg_DOT_security_role_only.Get()
			tmp468 := lang.Apply2(tmp467, "user", handler466)
			return tmp468
		default:
			panic(lang.NewArityError(len(args), "cljg.security/user-only", "0: [] or 1: [handler]"))
		}
	})
	v_cljg_DOT_security_user_only.BindRoot(tmp463)
	_ = v_cljg_DOT_security_user_only
	// (def admin-only (clojure.core/fn ([] (role-only "admin")) ([handler] (role-only "admin" ha…
	v_cljg_DOT_security_admin_only.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(277), kw_column, int64(7), kw_end_line, int64(277), kw_end_column, int64(17), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_handler)), kw_doc, "Sugar: (role-only :admin)."))
	tmp469 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 0:
			tmp470 := v_cljg_DOT_security_role_only.Get()
			tmp471 := lang.Apply1(tmp470, "admin")
			return tmp471
		case 1:
			handler472 := args[0]
			_ = handler472
			tmp473 := v_cljg_DOT_security_role_only.Get()
			tmp474 := lang.Apply2(tmp473, "admin", handler472)
			return tmp474
		default:
			panic(lang.NewArityError(len(args), "cljg.security/admin-only", "0: [] or 1: [handler]"))
		}
	})
	v_cljg_DOT_security_admin_only.BindRoot(tmp469)
	_ = v_cljg_DOT_security_admin_only
	// (def ban-store (atom {}))
	v_cljg_DOT_security_ban_store.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(291), kw_column, int64(6), kw_end_line, int64(291), kw_end_column, int64(25), kw_private, true))
	tmp475 := v_clojure_DOT_core_atom.Get()
	tmp476 := lang.NewMap()
	tmp477 := lang.Apply1(tmp475, tmp476)
	v_cljg_DOT_security_ban_store.BindRoot(tmp477)
	_ = v_cljg_DOT_security_ban_store
	// (def auto-ban (clojure.core/fn ([] (auto-ban {})) ([opts] (let [threshold (or (:threshold …
	v_cljg_DOT_security_auto_ban.SetMeta(lang.NewMap(kw_file, "cljg/security.cljg", kw_line, int64(293), kw_column, int64(7), kw_end_line, int64(293), kw_end_column, int64(15), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_opts)), kw_doc, "Default-on abuse guard. Options: :threshold (5), :window-ms (60000),\n  :cooldown-ms (300000), :key (:ip | :subject | (fn [req] key)),\n  :should-ban? ((fn [denial-count req] boolean) — custom ban policy),\n  :clock ((fn [] millis), for tests), :store (atom, for test isolation)."))
	tmp478 := lang.FnFunc(func(args ...any) any {
		switch len(args) {
		case 0:
			tmp479 := v_cljg_DOT_security_auto_ban.Get()
			tmp480 := lang.NewMap()
			tmp481 := lang.Apply1(tmp479, tmp480)
			return tmp481
		case 1:
			opts482 := args[0]
			_ = opts482
			var tmp483 any
			_ = tmp483
			{
				var tmp484 any
				_ = tmp484
				{
					tmp485 := lang.Apply1(kw_threshold, opts482)
					var or__2__auto__486 any = tmp485
					_ = or__2__auto__486
					var tmp487 any
					_ = tmp487
					if lang.IsTruthy(or__2__auto__486) {
						tmp487 = or__2__auto__486
					} else {
						tmp487 = int64(5)
					}
					tmp484 = tmp487
				}
				var threshold488 any = tmp484
				_ = threshold488
				var tmp489 any
				_ = tmp489
				{
					tmp490 := lang.Apply1(kw_window_ms, opts482)
					var or__2__auto__491 any = tmp490
					_ = or__2__auto__491
					var tmp492 any
					_ = tmp492
					if lang.IsTruthy(or__2__auto__491) {
						tmp492 = or__2__auto__491
					} else {
						tmp492 = int64(60000)
					}
					tmp489 = tmp492
				}
				var window493 any = tmp489
				_ = window493
				var tmp494 any
				_ = tmp494
				{
					tmp495 := lang.Apply1(kw_cooldown_ms, opts482)
					var or__2__auto__496 any = tmp495
					_ = or__2__auto__496
					var tmp497 any
					_ = tmp497
					if lang.IsTruthy(or__2__auto__496) {
						tmp497 = or__2__auto__496
					} else {
						tmp497 = int64(300000)
					}
					tmp494 = tmp497
				}
				var cooldown498 any = tmp494
				_ = cooldown498
				var tmp499 any
				_ = tmp499
				{
					tmp500 := lang.Apply1(kw_clock, opts482)
					var or__2__auto__501 any = tmp500
					_ = or__2__auto__501
					var tmp502 any
					_ = tmp502
					if lang.IsTruthy(or__2__auto__501) {
						tmp502 = or__2__auto__501
					} else {
						tmp503 := lang.FnFunc0(func() any {
							tmp504 := v_cljg_DOT_security_X_now_millis.Get()
							tmp505 := lang.Apply0(tmp504)
							return tmp505
						})
						tmp506 := &lang.NamedFn0{Name: "fn", Expects: "0: []", F: tmp503}
						tmp502 = tmp506
					}
					tmp499 = tmp502
				}
				var clock507 any = tmp499
				_ = clock507
				var tmp508 any
				_ = tmp508
				{
					tmp509 := lang.Apply1(kw_store, opts482)
					var or__2__auto__510 any = tmp509
					_ = or__2__auto__510
					var tmp511 any
					_ = tmp511
					if lang.IsTruthy(or__2__auto__510) {
						tmp511 = or__2__auto__510
					} else {
						tmp512 := v_cljg_DOT_security_ban_store.Get()
						tmp511 = tmp512
					}
					tmp508 = tmp511
				}
				var store513 any = tmp508
				_ = store513
				var tmp514 any
				_ = tmp514
				{
					tmp515 := lang.Apply1(kw_key, opts482)
					var or__2__auto__516 any = tmp515
					_ = or__2__auto__516
					var tmp517 any
					_ = tmp517
					if lang.IsTruthy(or__2__auto__516) {
						tmp517 = or__2__auto__516
					} else {
						tmp517 = kw_ip
					}
					tmp514 = tmp517
				}
				tmp518 := lang.NewMap(kw_key, tmp514)
				var key_opts519 any = tmp518
				_ = key_opts519
				var tmp520 any
				_ = tmp520
				{
					tmp521 := lang.Apply1(kw_should_ban_QMARK_, opts482)
					var or__2__auto__522 any = tmp521
					_ = or__2__auto__522
					var tmp523 any
					_ = tmp523
					if lang.IsTruthy(or__2__auto__522) {
						tmp523 = or__2__auto__522
					} else {
						tmp524 := lang.FnFunc2(func(n525, X_req526 any) any {
							tmp527 := rt.GE2(v_clojure_DOT_core_X_GT__EQ_, n525, threshold488)
							return tmp527
						})
						tmp528 := &lang.NamedFn2{Name: "fn", Expects: "2: [n _req]", F: tmp524}
						tmp523 = tmp528
					}
					tmp520 = tmp523
				}
				var should_ban_QMARK_529 any = tmp520
				_ = should_ban_QMARK_529
				tmp530 := lang.FnFunc1(func(handler531 any) any {
					tmp532 := lang.FnFunc1(func(req533 any) any {
						var tmp534 any
						_ = tmp534
						{
							tmp535 := v_bri_DOT_web_DOT_http_client_key.Get()
							tmp536 := lang.Apply2(tmp535, req533, key_opts519)
							var ck537 any = tmp536
							_ = ck537
							tmp538 := lang.Apply0(clock507)
							var now539 any = tmp538
							_ = now539
							tmp540 := v_clojure_DOT_core_get.Get()
							tmp541 := v_clojure_DOT_core_deref.Get()
							tmp542 := lang.Apply1(tmp541, store513)
							tmp543 := lang.Apply2(tmp540, tmp542, ck537)
							var st544 any = tmp543
							_ = st544
							var tmp545 any
							_ = tmp545
							{
								var and__1__auto__546 any = st544
								_ = and__1__auto__546
								var tmp547 any
								_ = tmp547
								if lang.IsTruthy(and__1__auto__546) {
									var tmp548 any
									_ = tmp548
									{
										tmp549 := lang.Apply1(kw_banned_until, st544)
										var and__1__auto__550 any = tmp549
										_ = and__1__auto__550
										var tmp551 any
										_ = tmp551
										if lang.IsTruthy(and__1__auto__550) {
											tmp552 := lang.Apply1(kw_banned_until, st544)
											tmp553 := rt.LT2(v_clojure_DOT_core_X_LT_, now539, tmp552)
											tmp551 = tmp553
										} else {
											tmp551 = and__1__auto__550
										}
										tmp548 = tmp551
									}
									tmp547 = tmp548
								} else {
									tmp547 = and__1__auto__546
								}
								tmp545 = tmp547
							}
							var tmp554 any
							_ = tmp554
							if lang.IsTruthy(tmp545) {
								tmp555 := v_bri_DOT_core_DOT_audit_record.Get()
								tmp556 := lang.Apply1(kw_banned_until, st544)
								tmp557 := rt.Sub2(v_clojure_DOT_core_X_, tmp556, now539)
								tmp558 := lang.Apply1(kw_request_SLASH_id, req533)
								tmp559 := lang.NewMap(kw_action, kw_auth_SLASH_banned_request, kw_actor, ck537, kw_severity, kw_warning, kw_cooldown_ms, tmp557, kw_request_SLASH_id, tmp558)
								tmp560 := lang.Apply1(tmp555, tmp559)
								_ = tmp560
								tmp561 := v_clojure_DOT_core_str.Get()
								tmp562 := v_clojure_DOT_core_max_.Get()
								tmp563 := v_clojure_DOT_core_quot.Get()
								tmp564 := lang.Apply1(kw_banned_until, st544)
								tmp565 := rt.Sub2(v_clojure_DOT_core_X_, tmp564, now539)
								tmp566 := lang.Apply2(tmp563, tmp565, int64(1000))
								tmp567 := lang.Apply2(tmp562, int64(1), tmp566)
								tmp568 := lang.Apply1(tmp561, tmp567)
								tmp569 := lang.NewMap("retry-after", tmp568)
								tmp570 := lang.NewMap(kw_error_, "too many requests")
								tmp571 := lang.NewMap(kw_status, int64(429), kw_headers, tmp569, kw_body, tmp570)
								tmp554 = tmp571
							} else {
								var tmp572 any
								_ = tmp572
								{
									tmp573 := lang.Apply1(handler531, req533)
									var res574 any = tmp573
									_ = res574
									tmp575 := v_clojure_DOT_core_contains_QMARK_.Get()
									tmp576 := lang.NewSet(int64(401), int64(403))
									tmp577 := lang.Apply1(kw_status, res574)
									tmp578 := lang.Apply2(tmp575, tmp576, tmp577)
									var tmp579 any
									_ = tmp579
									if lang.IsTruthy(tmp578) {
										var tmp580 any
										_ = tmp580
										{
											tmp581 := v_clojure_DOT_core_conj.Get()
											tmp582 := v_clojure_DOT_core_filterv.Get()
											tmp583 := lang.FnFunc1(func(p1__43_SHARP_584 any) any {
												tmp585 := rt.Sub2(v_clojure_DOT_core_X_, now539, window493)
												tmp586 := rt.GT2(v_clojure_DOT_core_X_GT_, p1__43_SHARP_584, tmp585)
												return tmp586
											})
											tmp587 := &lang.NamedFn1{Name: "fn", Expects: "1: [p1__43#]", F: tmp583}
											tmp588 := lang.NewVector()
											tmp589 := lang.Apply2(kw_denials, st544, tmp588)
											tmp590 := lang.Apply2(tmp582, tmp587, tmp589)
											tmp591 := lang.Apply2(tmp581, tmp590, now539)
											var recent592 any = tmp591
											_ = recent592
											tmp593 := v_clojure_DOT_core_count.Get()
											tmp594 := lang.Apply1(tmp593, recent592)
											tmp595 := lang.Apply2(should_ban_QMARK_529, tmp594, req533)
											var tmp596 any
											_ = tmp596
											if lang.IsTruthy(tmp595) {
												tmp597 := v_clojure_DOT_core_reset_BANG_.Get()
												tmp598 := v_clojure_DOT_core_assoc.Get()
												tmp599 := v_clojure_DOT_core_deref.Get()
												tmp600 := lang.Apply1(tmp599, store513)
												tmp601 := lang.NewVector()
												tmp602 := rt.Add2(v_clojure_DOT_core_X_PLUS_, now539, cooldown498)
												tmp603 := lang.NewMap(kw_denials, tmp601, kw_banned_until, tmp602)
												tmp604 := lang.Apply3(tmp598, tmp600, ck537, tmp603)
												tmp605 := lang.Apply2(tmp597, store513, tmp604)
												_ = tmp605
												tmp606 := v_bri_DOT_core_DOT_audit_record.Get()
												tmp607 := v_clojure_DOT_core_count.Get()
												tmp608 := lang.Apply1(tmp607, recent592)
												tmp609 := lang.Apply1(kw_request_SLASH_id, req533)
												tmp610 := lang.NewMap(kw_action, kw_auth_SLASH_auto_banned, kw_actor, ck537, kw_count, tmp608, kw_cooldown_ms, cooldown498, kw_severity, kw_warning, kw_request_SLASH_id, tmp609)
												tmp611 := lang.Apply1(tmp606, tmp610)
												tmp596 = tmp611
											} else {
												tmp612 := v_clojure_DOT_core_reset_BANG_.Get()
												tmp613 := v_clojure_DOT_core_assoc.Get()
												tmp614 := v_clojure_DOT_core_deref.Get()
												tmp615 := lang.Apply1(tmp614, store513)
												tmp616 := v_clojure_DOT_core_assoc.Get()
												var tmp617 any
												_ = tmp617
												{
													var or__2__auto__618 any = st544
													_ = or__2__auto__618
													var tmp619 any
													_ = tmp619
													if lang.IsTruthy(or__2__auto__618) {
														tmp619 = or__2__auto__618
													} else {
														tmp620 := lang.NewMap()
														tmp619 = tmp620
													}
													tmp617 = tmp619
												}
												tmp621 := lang.Apply3(tmp616, tmp617, kw_denials, recent592)
												tmp622 := lang.Apply3(tmp613, tmp615, ck537, tmp621)
												tmp623 := lang.Apply2(tmp612, store513, tmp622)
												tmp596 = tmp623
											}
											tmp580 = tmp596
										}
										tmp579 = tmp580
									} else {
										tmp579 = nil
									}
									_ = tmp579
									tmp572 = res574
								}
								tmp554 = tmp572
							}
							tmp534 = tmp554
						}
						return tmp534
					})
					tmp624 := &lang.NamedFn1{Name: "fn", Expects: "1: [req]", F: tmp532}
					return tmp624
				})
				tmp625 := &lang.NamedFn1{Name: "fn", Expects: "1: [handler]", F: tmp530}
				tmp626 := lang.NewMap(kw_name, kw_auto_ban, kw_wrap, tmp625)
				tmp483 = tmp626
			}
			return tmp483
		default:
			panic(lang.NewArityError(len(args), "cljg.security/auto-ban", "0: [] or 1: [opts]"))
		}
	})
	v_cljg_DOT_security_auto_ban.BindRoot(tmp478)
	_ = v_cljg_DOT_security_auto_ban
}
