// keel.go — the keel framework's CLI surface (ADR 0041, openspec
// app-framework T0/T1):
//
//	cljgo new <name>   generate an app in the blessed layout
//	cljgo dev          run it: server + nREPL attached + the dev banner
//	cljgo test         load src/, run every test under test/
//	cljgo config       print the resolved config map, layer per key
//	cljgo routes       print the routes and the effective middleware stack
//
// `cljgo new` is a generator, not a container: it writes plain files
// the user owns; nothing scans them (the app calls keel, visibly).
// The generated main.cljg IS the golden page of ADR 0041, trimmed to
// the shipped tiers (T0/T1: config + routes + a styled page — no db
// verbs until T2 ships them).
package main

import (
	"flag"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/muthuishere/cljgo/pkg/lang"
	"github.com/muthuishere/cljgo/pkg/nrepl"
	"github.com/muthuishere/cljgo/pkg/repl"
)

const appMain = "src/app/main.cljg"

// --- cljgo new ---------------------------------------------------------------

func runNew(args []string) int {
	fs := flag.NewFlagSet("new", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	fs.Usage = func() {
		fmt.Fprintln(os.Stderr, "usage: cljgo new <name>")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if fs.NArg() != 1 {
		fs.Usage()
		return 2
	}
	name := fs.Arg(0)
	if !validAppName(name) {
		fmt.Fprintf(os.Stderr, "cljgo new: %q is not a valid app name (lowercase letters, digits, - _)\n", name)
		return 2
	}
	if entries, err := os.ReadDir(name); err == nil && len(entries) > 0 {
		fmt.Fprintf(os.Stderr, "cljgo new: directory %s already exists and is not empty\n", name)
		return 1
	}

	for path, body := range scaffold(name) {
		full := filepath.Join(name, path)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "cljgo new:", err)
			return 1
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "cljgo new:", err)
			return 1
		}
	}

	// Stable listing order (map iteration is random).
	paths := make([]string, 0, len(scaffold(name)))
	for p := range scaffold(name) {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	fmt.Printf("created %s/\n", name)
	for _, p := range paths {
		fmt.Printf("  %s\n", p)
	}
	fmt.Printf("\nnext:\n  cd %s\n  cljgo dev     # server + nREPL\n  cljgo test    # the generated test\n", name)
	return 0
}

func validAppName(name string) bool {
	if name == "" || name == "." || name == ".." {
		return false
	}
	for _, c := range name {
		if !(c >= 'a' && c <= 'z' || c >= '0' && c <= '9' || c == '-' || c == '_') {
			return false
		}
	}
	return true
}

// scaffold is the T0/T1 file manifest (openspec app-framework task 0.1):
// the golden page trimmed to shipped pillars, conf.edn + a minimal
// schema, a REAL stylesheet, one passing test, build.cljgo, .gitignore.
// Every generated verb has a same-tier implementation.
func scaffold(name string) map[string]string {
	return map[string]string{
		appMain: `;; app.main — generated by ` + "`cljgo new`" + `. This file is YOURS: keel is
;; called from here, visibly; nothing scans or loads it behind your back.
;; The top level constructs VALUES (no I/O); -main starts the world.
(ns app.main
  (:require [keel.http :as http]
            [keel.html :as html]
            [keel.config :as config]))

(def cfg (config/load!))   ; conf.edn (+ :profiles by APP_PROFILE) + APP_* env.

(defn home [_req]
  (http/ok
    (html/page {:title "` + name + `"}
      [:main
       [:h1 "It's alive."]
       [:p "This page is keel.html data, served by keel.http on Go's net/http."]
       [:p "Edit " [:code "src/app/main.cljg"] " — or connect to the nREPL port
           printed by " [:code "cljgo dev"] " and re-" [:code "def"] " " [:code "home"] ",
           then refresh: the route holds " [:code "#'home"] ", derefed per request."]
       [:p.hint "routes are data · middleware defaults are on · config is one map"]])))

(def routes
  [["GET /{$}"     #'home]
   ["GET /static/" (http/dir "public")]
   ["GET /health"  (http/health {})]])

(defn -main [& _args]
  ;; No :middleware given = (http/defaults): access-log, recover (the
  ;; documented error table), sessions, JSON negotiation, CSRF.
  (http/serve routes {:port (:port cfg)}))
`,
		"conf.edn": `{:port 3000
 :profiles
 {:dev  {}
  :test {}}}
`,
		"conf.schema.edn": `;; Optional — enforced because it exists: a violation aborts boot,
;; naming the key and the layer. Delete this file to go schemaless.
{[:port] {:type :int :required true :default 3000}}
`,
		"public/app.css": `/* ` + name + ` — a real stylesheet, served from disk by (http/dir "public").
   No pipeline, no build step: edit, refresh. */
:root {
  --bg: #f7f6f3;
  --fg: #1c1b1a;
  --muted: #6f6b66;
  --accent: #0f62fe;
  --card: #ffffff;
}
@media (prefers-color-scheme: dark) {
  :root { --bg: #171614; --fg: #eceae6; --muted: #98938c; --card: #211f1c; }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font: 17px/1.6 system-ui, -apple-system, "Segoe UI", sans-serif;
  display: grid;
  place-items: center;
  min-height: 100vh;
}
main {
  max-width: 34rem;
  padding: 2.5rem 3rem;
  background: var(--card);
  border-radius: 12px;
  box-shadow: 0 1px 3px rgb(0 0 0 / 0.12);
}
h1 { margin-top: 0; letter-spacing: -0.02em; }
code {
  font: 0.9em ui-monospace, "SF Mono", monospace;
  background: rgb(127 127 127 / 0.14);
  padding: 0.1em 0.35em;
  border-radius: 4px;
}
.hint { color: var(--muted); font-size: 0.85em; }
a { color: var(--accent); }
`,
		"test/app/main_test.cljg": `;; The generated test: keel's IN-PROCESS http test client (no socket)
;; against the app's own routes. Run it with ` + "`cljgo test`" + `.
(ns app.main-test
  (:require [clojure.test :refer [deftest is]]
            [clojure.string :as str]
            [keel.http :as http]
            [app.main :as main]))

(deftest home-page-renders
  (let [res (http/request main/routes {:method "GET" :path "/"})]
    (is (= 200 (:status res)))
    (is (str/includes? (:body res) "alive."))))
`,
		"build.cljgo": `;; build.cljgo — the project build plan (ADR 0021).
;; NOTE: AOT compilation of keel apps lands with a later tier of the
;; app-framework change; today the dev loop is ` + "`cljgo dev` / `cljgo test`" + `.
(defn build [b]
  (let [app (exe b {:name "` + name + `"
                    :main "src/app/main.cljg"})]
    (install b app)
    (run b app)))
`,
		".gitignore": `/` + name + `
.nrepl-port
.dev/
`,
	}
}

// --- cljgo dev ------------------------------------------------------------------

// runDev is the T0 dev loop (task 0.2): the app served through the
// interpreter with an nREPL attached — the REPL is the reload story
// (nothing is watched; re-def the var). KEEL_DEV=1 turns on keel's
// loud dev behaviors (plain-fn route warnings, bare-Result messages).
// Ctrl-C/SIGTERM = graceful drain (keel.http/serve owns shutdown).
func runDev(args []string) int {
	fs := flag.NewFlagSet("dev", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	nreplPort := fs.Int("nrepl-port", 0, "nREPL port (0 = an ephemeral port)")
	fs.Usage = func() {
		fmt.Fprintln(os.Stderr, "usage: cljgo dev [--nrepl-port N] (run from the app directory)")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if _, err := os.Stat(appMain); err != nil {
		fmt.Fprintf(os.Stderr, "cljgo dev: no %s here — run from an app directory (create one with `cljgo new <name>`)\n", appMain)
		return 1
	}

	os.Setenv("KEEL_DEV", "1")
	if os.Getenv("APP_PROFILE") == "" {
		os.Setenv("APP_PROFILE", "dev")
	}

	// nREPL first: editors connect while the server runs. Same process,
	// same global namespace/var registry — a re-def through this port
	// changes the NEXT request on the live server (the S20 claim).
	ln, err := net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", *nreplPort))
	if err != nil {
		fmt.Fprintln(os.Stderr, "cljgo dev:", err)
		return 1
	}
	defer ln.Close()
	actual := ln.Addr().(*net.TCPAddr).Port
	if err := os.WriteFile(portFileName, []byte(strconv.Itoa(actual)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not write %s: %v\n", portFileName, err)
	} else {
		defer os.Remove(portFileName)
	}
	go nrepl.NewServer().Serve(ln)

	appName := filepath.Base(mustGetwd())
	fmt.Printf(`keel dev — %s
  profile : %s
  nREPL   : nrepl://127.0.0.1:%d (.nrepl-port written)
  reload  : re-(def) a handler var at the REPL — routes hold #'vars

`, appName, os.Getenv("APP_PROFILE"), actual)

	d := repl.New(nil, os.Stdout, os.Stderr)
	if code := evalAppFile(d, appMain); code != 0 {
		return code
	}
	if _, err := d.EvalString("(app.main/-main)", "cljgo-dev"); err != nil {
		fmt.Fprintln(os.Stderr, "cljgo dev:", err)
		return 1
	}
	return 0
}

func mustGetwd() string {
	wd, err := os.Getwd()
	if err != nil {
		return "app"
	}
	return wd
}

// evalAppFile loads one source file through the driver (same load
// frame as `cljgo run`).
func evalAppFile(d *repl.Driver, path string) int {
	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	defer f.Close()
	if _, err := d.EvalReader(f, path); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	return 0
}

// --- cljgo test -------------------------------------------------------------------

// runTest loads every namespace under src/ (skipping ones a require
// already pulled in), then every *_test file under test/, then runs
// clojure.test over all of it. APP_PROFILE defaults to test — the
// no-I/O-at-load contract is what makes requiring app.main safe here.
func runTest(args []string) int {
	fs := flag.NewFlagSet("test", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	fs.Usage = func() {
		fmt.Fprintln(os.Stderr, "usage: cljgo test (run from the app directory)")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if _, err := os.Stat("test"); err != nil {
		fmt.Fprintln(os.Stderr, "cljgo test: no test/ directory here")
		return 1
	}
	if os.Getenv("APP_PROFILE") == "" {
		os.Setenv("APP_PROFILE", "test")
	}

	d := repl.New(nil, os.Stdout, os.Stderr)
	for _, root := range []string{"src", "test"} {
		files, err := sourceFiles(root)
		if err != nil {
			fmt.Fprintln(os.Stderr, "cljgo test:", err)
			return 1
		}
		for _, path := range files {
			if nsAlreadyLoaded(path, root) {
				continue
			}
			if code := evalAppFile(d, path); code != 0 {
				return code
			}
		}
	}
	res, err := d.EvalString("(clojure.test/successful? (clojure.test/run-all-tests))", "cljgo-test")
	if err != nil {
		fmt.Fprintln(os.Stderr, "cljgo test:", err)
		return 1
	}
	if res != true {
		return 1
	}
	return 0
}

// sourceFiles lists .clj/.cljg files under root, sorted.
func sourceFiles(root string) ([]string, error) {
	var files []string
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && (strings.HasSuffix(path, ".clj") || strings.HasSuffix(path, ".cljg")) {
			files = append(files, path)
		}
		return nil
	})
	sort.Strings(files)
	return files, err
}

// nsAlreadyLoaded reports whether path's conventional namespace (its
// path relative to root, _ → -, / → .) already exists — a require from
// an earlier file loaded it; evaluating the file again would re-run it.
func nsAlreadyLoaded(path, root string) bool {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return false
	}
	stem := strings.TrimSuffix(strings.TrimSuffix(rel, ".cljg"), ".clj")
	nsName := strings.ReplaceAll(strings.ReplaceAll(filepath.ToSlash(stem), "/", "."), "_", "-")
	return lang.FindNamespace(lang.NewSymbol(nsName)) != nil
}

// --- cljgo config -----------------------------------------------------------------

// runConfig prints the resolved config map with each key's winning
// layer (task 1.6 — "2 a.m. debugging").
func runConfig(args []string) int {
	if _, err := os.Stat("conf.edn"); err != nil {
		fmt.Fprintln(os.Stderr, "cljgo config: no conf.edn here — run from an app directory")
		return 1
	}
	d := repl.New(nil, os.Stdout, os.Stderr)
	out, err := d.EvalString("(do (require 'keel.config) (keel.config/explain))", "cljgo-config")
	if err != nil {
		fmt.Fprintln(os.Stderr, "cljgo config:", err)
		return 1
	}
	s, _ := out.(string)
	fmt.Print(s)
	return 0
}

// --- cljgo routes -----------------------------------------------------------------

// runRoutes prints every route and the effective middleware stack
// (task 1.3 — the defaults are inspectable DATA).
func runRoutes(args []string) int {
	if _, err := os.Stat(appMain); err != nil {
		fmt.Fprintf(os.Stderr, "cljgo routes: no %s here — run from an app directory\n", appMain)
		return 1
	}
	d := repl.New(nil, os.Stdout, os.Stderr)
	if code := evalAppFile(d, appMain); code != 0 {
		return code
	}
	out, err := d.EvalString("(keel.http/describe app.main/routes {})", "cljgo-routes")
	if err != nil {
		fmt.Fprintln(os.Stderr, "cljgo routes:", err)
		return 1
	}
	s, _ := out.(string)
	fmt.Print(s)
	return 0
}
