// Code generated by cljgo build. DO NOT EDIT.

package briaudit

import (
	rt "github.com/muthuishere/cljgo/pkg/emit/rt"
	lang "github.com/muthuishere/cljgo/pkg/lang"
)

var (
	kw_arglists                                = lang.InternKeywordString("arglists")
	kw_as                                      = lang.InternKeywordString("as")
	kw_audit                                   = lang.InternKeywordString("audit")
	kw_column                                  = lang.InternKeywordString("column")
	kw_doc                                     = lang.InternKeywordString("doc")
	kw_dynamic                                 = lang.InternKeywordString("dynamic")
	kw_end_column                              = lang.InternKeywordString("end-column")
	kw_end_line                                = lang.InternKeywordString("end-line")
	kw_file                                    = lang.InternKeywordString("file")
	kw_info                                    = lang.InternKeywordString("info")
	kw_kind                                    = lang.InternKeywordString("kind")
	kw_line                                    = lang.InternKeywordString("line")
	kw_private                                 = lang.InternKeywordString("private")
	kw_severity                                = lang.InternKeywordString("severity")
	kw_sub                                     = lang.InternKeywordString("sub")
	kw_ts                                      = lang.InternKeywordString("ts")
	sym_bri_DOT_core_DOT_audit                 = lang.NewSymbol("bri.core.audit")
	sym_claims                                 = lang.NewSymbol("claims")
	sym_clojure_DOT_core                       = lang.NewSymbol("clojure.core")
	sym_clojure_DOT_string                     = lang.NewSymbol("clojure.string")
	sym_ev                                     = lang.NewSymbol("ev")
	sym_f                                      = lang.NewSymbol("f")
	sym_str                                    = lang.NewSymbol("str")
	v_bri_DOT_core_DOT_audit_X_STAR_sink_STAR_ = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("*sink*")).SetDynamic()
	v_bri_DOT_core_DOT_audit_X_eprintln        = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("-eprintln")).SetPrivate()
	v_bri_DOT_core_DOT_audit_X_getenv          = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("-getenv")).SetPrivate()
	v_bri_DOT_core_DOT_audit_X_json_encode     = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("-json-encode")).SetPrivate()
	v_bri_DOT_core_DOT_audit_X_now_millis      = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("-now-millis")).SetPrivate()
	v_bri_DOT_core_DOT_audit_default_sink      = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("default-sink")).SetPrivate()
	v_bri_DOT_core_DOT_audit_dev_QMARK_        = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("dev?")).SetPrivate()
	v_bri_DOT_core_DOT_audit_process_sink      = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("process-sink")).SetPrivate()
	v_bri_DOT_core_DOT_audit_record            = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("record"))
	v_bri_DOT_core_DOT_audit_set_sink_BANG_    = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("set-sink!"))
	v_bri_DOT_core_DOT_audit_subject           = lang.InternVarName(lang.NewSymbol("bri.core.audit"), lang.NewSymbol("subject"))
	v_clojure_DOT_core_X_EQ_                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("="))
	v_clojure_DOT_core_atom                    = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("atom"))
	v_clojure_DOT_core_deref                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("deref"))
	v_clojure_DOT_core_in_ns                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("in-ns"))
	v_clojure_DOT_core_merge                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("merge"))
	v_clojure_DOT_core_pr_str                  = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("pr-str"))
	v_clojure_DOT_core_refer                   = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("refer"))
	v_clojure_DOT_core_require                 = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("require"))
	v_clojure_DOT_core_reset_BANG_             = lang.InternVarName(lang.NewSymbol("clojure.core"), lang.NewSymbol("reset!"))
)

var (
	fnD_bri_DOT_core_DOT_audit_dev_QMARK_     lang.FnFunc0
	fnD_bri_DOT_core_DOT_audit_set_sink_BANG_ lang.FnFunc1
	fnD_bri_DOT_core_DOT_audit_default_sink   lang.FnFunc1
	fnD_bri_DOT_core_DOT_audit_record         lang.FnFunc1
	fnD_bri_DOT_core_DOT_audit_subject        lang.FnFunc1
)

var loaded = false

// Load evaluates the namespace's top-level forms exactly once, in source order.
func Load() {
	if loaded {
		return
	}
	loaded = true
	lang.PushThreadBindings(lang.NewMap(lang.VarCurrentNS, lang.FindOrCreateNamespace(lang.NewSymbol("bri.core.audit")), lang.VarFile, "bri/audit.cljg"))
	defer lang.PopThreadBindings()
	// (clojure.core/in-ns (quote bri.core.audit))
	tmp1 := v_clojure_DOT_core_in_ns.Get()
	tmp2 := lang.Apply1(tmp1, sym_bri_DOT_core_DOT_audit)
	_ = tmp2
	// (clojure.core/refer (quote clojure.core))
	tmp3 := v_clojure_DOT_core_refer.Get()
	tmp4 := lang.Apply1(tmp3, sym_clojure_DOT_core)
	_ = tmp4
	// (require (quote [clojure.string :as str]))
	tmp5 := v_clojure_DOT_core_require.Get()
	tmp6 := lang.Apply1(tmp5, lang.NewVector(sym_clojure_DOT_string, kw_as, sym_str))
	_ = tmp6
	// (def dev? (clojure.core/fn ([] (= "1" (-getenv "BRI_DEV")))))
	v_bri_DOT_core_DOT_audit_dev_QMARK_.SetMeta(lang.NewMap(kw_file, "bri/audit.cljg", kw_line, int64(16), kw_column, int64(7), kw_end_line, int64(16), kw_end_column, int64(21), kw_private, true, kw_arglists, lang.NewList(lang.NewVector())))
	tmp7 := lang.FnFunc0(func() any {
		tmp8 := v_bri_DOT_core_DOT_audit_X_getenv.Get()
		tmp9 := lang.Apply1(tmp8, "BRI_DEV")
		tmp10 := rt.EQ2(v_clojure_DOT_core_X_EQ_, "1", tmp9)
		return tmp10
	})
	tmp11 := &lang.NamedFn0{Name: "bri.core.audit/dev?", Expects: "0: []", F: tmp7}
	v_bri_DOT_core_DOT_audit_dev_QMARK_.BindRoot(tmp11)
	fnD_bri_DOT_core_DOT_audit_dev_QMARK_ = tmp11.F
	v_bri_DOT_core_DOT_audit_dev_QMARK_.SealDirect()
	_ = v_bri_DOT_core_DOT_audit_dev_QMARK_
	// (def *sink* "When thread-bound, receives every event map (used by tests to capture\n  dete…
	v_bri_DOT_core_DOT_audit_X_STAR_sink_STAR_.SetMeta(lang.NewMap(kw_file, "bri/audit.cljg", kw_line, int64(19), kw_column, int64(6), kw_end_line, int64(19), kw_end_column, int64(22), kw_dynamic, true, kw_doc, "When thread-bound, receives every event map (used by tests to capture\n  deterministically). nil = fall through to the process sink."))
	v_bri_DOT_core_DOT_audit_X_STAR_sink_STAR_.BindRoot(nil)
	_ = v_bri_DOT_core_DOT_audit_X_STAR_sink_STAR_
	// (def process-sink (atom nil))
	v_bri_DOT_core_DOT_audit_process_sink.SetMeta(lang.NewMap(kw_file, "bri/audit.cljg", kw_line, int64(24), kw_column, int64(6), kw_end_line, int64(24), kw_end_column, int64(28), kw_private, true))
	tmp12 := v_clojure_DOT_core_atom.Get()
	tmp13 := lang.Apply1(tmp12, nil)
	v_bri_DOT_core_DOT_audit_process_sink.BindRoot(tmp13)
	_ = v_bri_DOT_core_DOT_audit_process_sink
	// (def set-sink! (clojure.core/fn ([f] (reset! process-sink f))))
	v_bri_DOT_core_DOT_audit_set_sink_BANG_.SetMeta(lang.NewMap(kw_file, "bri/audit.cljg", kw_line, int64(26), kw_column, int64(7), kw_end_line, int64(26), kw_end_column, int64(16), kw_arglists, lang.NewList(lang.NewVector(sym_f)), kw_doc, "Install the process-wide audit sink: a fn of the event map. The T2\n  seam — point it at cljg.data.cast + notify.Send. Passing nil restores the\n  default structured-stderr sink."))
	tmp14 := lang.FnFunc1(func(f15 any) any {
		tmp16 := v_clojure_DOT_core_reset_BANG_.Get()
		tmp17 := v_bri_DOT_core_DOT_audit_process_sink.Get()
		tmp18 := lang.Apply2(tmp16, tmp17, f15)
		return tmp18
	})
	tmp19 := &lang.NamedFn1{Name: "bri.core.audit/set-sink!", Expects: "1: [f]", F: tmp14}
	v_bri_DOT_core_DOT_audit_set_sink_BANG_.BindRoot(tmp19)
	fnD_bri_DOT_core_DOT_audit_set_sink_BANG_ = tmp19.F
	v_bri_DOT_core_DOT_audit_set_sink_BANG_.SealDirect()
	_ = v_bri_DOT_core_DOT_audit_set_sink_BANG_
	// (def default-sink (clojure.core/fn ([ev] (if (dev?) (-eprintln (pr-str ev)) (-eprintln (-j…
	v_bri_DOT_core_DOT_audit_default_sink.SetMeta(lang.NewMap(kw_file, "bri/audit.cljg", kw_line, int64(33), kw_column, int64(7), kw_end_line, int64(33), kw_end_column, int64(29), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_ev))))
	tmp20 := lang.FnFunc1(func(ev21 any) any {
		tmp22 := v_bri_DOT_core_DOT_audit_dev_QMARK_.Direct()
		var tmp23 any
		if !tmp22 {
			tmp23 = v_bri_DOT_core_DOT_audit_dev_QMARK_.Get()
		}
		var tmp24 any
		if tmp22 {
			tmp24 = fnD_bri_DOT_core_DOT_audit_dev_QMARK_()
		} else {
			tmp24 = lang.Apply0(tmp23)
		}
		var tmp25 any
		_ = tmp25
		if lang.IsTruthy(tmp24) {
			tmp26 := v_bri_DOT_core_DOT_audit_X_eprintln.Get()
			tmp27 := v_clojure_DOT_core_pr_str.Get()
			tmp28 := lang.Apply1(tmp27, ev21)
			tmp29 := lang.Apply1(tmp26, tmp28)
			tmp25 = tmp29
		} else {
			tmp30 := v_bri_DOT_core_DOT_audit_X_eprintln.Get()
			tmp31 := v_bri_DOT_core_DOT_audit_X_json_encode.Get()
			tmp32 := lang.Apply1(tmp31, ev21)
			tmp33 := lang.Apply1(tmp30, tmp32)
			tmp25 = tmp33
		}
		return tmp25
	})
	tmp34 := &lang.NamedFn1{Name: "bri.core.audit/default-sink", Expects: "1: [ev]", F: tmp20}
	v_bri_DOT_core_DOT_audit_default_sink.BindRoot(tmp34)
	fnD_bri_DOT_core_DOT_audit_default_sink = tmp34.F
	v_bri_DOT_core_DOT_audit_default_sink.SealDirect()
	_ = v_bri_DOT_core_DOT_audit_default_sink
	// (def record (clojure.core/fn ([ev] (let [event (merge {:ts (-now-millis), :kind :audit, :s…
	v_bri_DOT_core_DOT_audit_record.SetMeta(lang.NewMap(kw_file, "bri/audit.cljg", kw_line, int64(40), kw_column, int64(7), kw_end_line, int64(40), kw_end_column, int64(13), kw_arglists, lang.NewList(lang.NewVector(sym_ev)), kw_doc, "Record ONE audit event. Merges a :ts (epoch millis), :kind :audit and\n  a default :severity :info; the caller supplies :action (required by\n  convention), :actor (subject or client key), :target, and any extra\n  keys. Returns the completed event. Routing: a thread-bound *sink* wins\n  (tests), else the process sink, else structured stderr."))
	tmp35 := lang.FnFunc1(func(ev36 any) any {
		var tmp37 any
		_ = tmp37
		{
			tmp38 := v_clojure_DOT_core_merge.Get()
			tmp39 := v_bri_DOT_core_DOT_audit_X_now_millis.Get()
			tmp40 := lang.Apply0(tmp39)
			tmp41 := lang.NewMap(kw_ts, tmp40, kw_kind, kw_audit, kw_severity, kw_info)
			tmp42 := lang.Apply2(tmp38, tmp41, ev36)
			var event43 any = tmp42
			_ = event43
			var tmp44 any
			_ = tmp44
			{
				tmp45 := v_bri_DOT_core_DOT_audit_X_STAR_sink_STAR_.Get()
				var or__2__auto__46 any = tmp45
				_ = or__2__auto__46
				var tmp47 any
				_ = tmp47
				if lang.IsTruthy(or__2__auto__46) {
					tmp47 = or__2__auto__46
				} else {
					var tmp48 any
					_ = tmp48
					{
						tmp49 := v_clojure_DOT_core_deref.Get()
						tmp50 := v_bri_DOT_core_DOT_audit_process_sink.Get()
						tmp51 := lang.Apply1(tmp49, tmp50)
						var or__2__auto__52 any = tmp51
						_ = or__2__auto__52
						var tmp53 any
						_ = tmp53
						if lang.IsTruthy(or__2__auto__52) {
							tmp53 = or__2__auto__52
						} else {
							tmp54 := v_bri_DOT_core_DOT_audit_default_sink.Get()
							tmp53 = tmp54
						}
						tmp48 = tmp53
					}
					tmp47 = tmp48
				}
				tmp44 = tmp47
			}
			var sink55 any = tmp44
			_ = sink55
			tmp56 := lang.Apply1(sink55, event43)
			_ = tmp56
			tmp37 = event43
		}
		return tmp37
	})
	tmp57 := &lang.NamedFn1{Name: "bri.core.audit/record", Expects: "1: [ev]", F: tmp35}
	v_bri_DOT_core_DOT_audit_record.BindRoot(tmp57)
	fnD_bri_DOT_core_DOT_audit_record = tmp57.F
	v_bri_DOT_core_DOT_audit_record.SealDirect()
	_ = v_bri_DOT_core_DOT_audit_record
	// (def subject (clojure.core/fn ([claims] (:sub claims))))
	v_bri_DOT_core_DOT_audit_subject.SetMeta(lang.NewMap(kw_file, "bri/audit.cljg", kw_line, int64(52), kw_column, int64(7), kw_end_line, int64(52), kw_end_column, int64(14), kw_arglists, lang.NewList(lang.NewVector(sym_claims)), kw_doc, "The audit actor for a claims map — the JWT subject."))
	tmp58 := lang.FnFunc1(func(claims59 any) any {
		tmp60 := lang.Apply1(kw_sub, claims59)
		return tmp60
	})
	tmp61 := &lang.NamedFn1{Name: "bri.core.audit/subject", Expects: "1: [claims]", F: tmp58}
	v_bri_DOT_core_DOT_audit_subject.BindRoot(tmp61)
	fnD_bri_DOT_core_DOT_audit_subject = tmp61.F
	v_bri_DOT_core_DOT_audit_subject.SealDirect()
	_ = v_bri_DOT_core_DOT_audit_subject
}
